// Comes from sandbox.elastic.dev/test-books/apm/guide/transclusion/tab-widgets/install-agents/go.mdx

**1. Install the agent**

Install the {apm-agent} package using `go get`:

[source,go]
----
go get -u go.elastic.co/apm/v2
----

**2. Configure the agent**

To simplify development and testing,
the agent defaults to sending data to Elastic at `http://localhost:8200`.
To send data to an alternative location, you must configure `ELASTIC_APM_SERVER_URL`.

[source,go]
----
# The APM integration host and port
export ELASTIC_APM_SERVER_URL=

# If you do not specify `ELASTIC_APM_SERVICE_NAME`, the Go agent will use the
# executable name. For example, if your executable is called "my-app.exe", then your
# service will be identified as "my-app".
export ELASTIC_APM_SERVICE_NAME=

# Secret tokens are used to authorize requests to the APM integration
export ELASTIC_APM_SECRET_TOKEN=
----

**3. Instrument your application**

Instrumentation is the process of extending your application's code to report trace data to Elastic APM. Go applications must be instrumented manually at the source code level. To instrument your applications, use one of the following approaches:

* {apm-go-ref}/builtin-modules.html[Built-in instrumentation modules].
* {apm-go-ref}/custom-instrumentation.html[Custom instrumentation] and context propagation with the Go Agent API.

**Learn more in the {apm-agent} reference**

* {apm-go-ref}/supported-tech.html[Supported technologies]
* {apm-go-ref}/configuration.html[Advanced configuration]
* {apm-go-ref}/getting-started.html[Detailed guide to instrumenting Go source code]
