// Comes from sandbox.elastic.dev/test-books/apm/guide/transclusion/tab-widgets/install-agents/php.mdx

**1. Install the agent**

Install the PHP agent using one of the https://github.com/elastic/apm-agent-php/releases/latest[published packages].

To use the RPM Package (RHEL/CentOS and Fedora):

[source,php]
----
rpm -ivh <package-file>.rpm
----

To use the DEB package (Debian and Ubuntu):

[source,php]
----
dpkg -i <package-file>.deb
----

To use the APK package (Alpine):

[source,php]
----
apk add --allow-untrusted <package-file>.apk
----

If you can’t find your distribution, you can install the agent by building it from the source.
The following instructions will build the APM agent using the same docker environment that Elastic uses to build our official packages.

[NOTE]
====
The agent is currently only available for Linux operating system.
====

. Download the https://github.com/elastic/apm-agent-php/[agent source].
. Execute the following commands to build the agent and install it:

[source,bash]
----
cd apm-agent-php
# for linux glibc - libc distributions (Ubuntu, Redhat, etc)
export BUILD_ARCHITECTURE=linux-x86-64
# for linux with musl - libc distributions (Alpine)
export BUILD_ARCHITECTURE=linuxmusl-x86-64
# provide a path to php-config tool
export PHP_CONFIG=php-config

# build extensions
make -f .ci/Makefile build

# run extension tests
PHP_VERSION=`$PHP_CONFIG --version | cut -d'.' -f 1,2` make -f .ci/Makefile run-phpt-tests

# install agent extensions
sudo cp agent/native/_build/${BUILD_ARCHITECTURE}-release/ext/elastic_apm-*.so `$PHP_CONFIG --extension-dir`

# install automatic loader
sudo cp agent/native/_build/${BUILD_ARCHITECTURE}-release/loader/code/elastic_apm_loader.so `$PHP_CONFIG --extension-dir`
----

**2. Enable and configure the APM agent**

Enable and configure your agent inside of the `php.ini` file:

[source,ini]
----
extension=elastic_apm_loader.so
elastic_apm.bootstrap_php_part_file=<repo root>/agent/php/bootstrap_php_part.php
----

**Learn more in the {apm-agent} reference**

* {apm-php-ref}/supported-technologies.html[Supported technologies]
* {apm-py-ref}/configuration.html[Configuration]
