[[apm-configure-agent-config]]
= Configure APM agent configuration

status_badge::[cloud_serverless, unavailable]

++++
<titleabbrev>APM agent configuration</titleabbrev>
++++

****
image:./binary-yes-fm-yes.svg[supported deployment methods]

APM agent configuration is supported by all {apm-server} deployment methods.
****

APM agent configuration allows you to fine-tune your APM agents from within the Applications UI.
Changes are automatically propagated to your APM agents, so there's no need to redeploy your applications.

To learn more about this feature, see <<apm-agent-configuration,APM agent configuration>>.

Here's a sample configuration:

[source,yaml]
----
apm-server.agent.config.cache.expiration: 45s
apm-server.agent.config.elasticsearch.api_key: TiNAGG4BaaMdaH1tRfuU:KnR6yE41RrSowb0kQ0HWoA
----

[float]
== APM agent configuration options

The following options are only supported for {apm-server} binary users.
You can specify these options in the `apm-server.agent.config` section of the
+apm-server.yml+ config file:

[float]
[[apm-agent-config-cache]]
=== `apm-server.agent.config.cache.expiration`

When using APM agent configuration, information fetched from {es} will be cached in memory for some time.
Specify the cache expiration time via this setting. Defaults to `30s` (30 seconds).

[float]
[[apm-agent-config-elasticsearch]]
=== `apm-server.agent.config.elasticsearch`

Takes the same options as <<apm-elasticsearch-output,output.elasticsearch>>.

For {apm-server} binary users and Elastic Agent standalone-managed {apm-server},
APM agent configuration is automatically fetched from {es} using the `output.elasticsearch`
configuration. If `output.elasticsearch` isn't set or doesn't have sufficient privileges,
use these {es} options to provide {es} access.

[float]
=== Common problems

You may see either of the following HTTP 403 errors from {apm-server} when it attempts to fetch APM agent configuration:

APM agent log:

[source,log]
----
"Your Elasticsearch configuration does not support agent config queries. Check your configurations at `output.elasticsearch` or `apm-server.agent.config.elasticsearch`."
----

{apm-server} log:

[source,log]
----
rejecting fetch request: no valid elasticsearch config
----

This occurs because the user or API key set in either `apm-server.agent.config.elasticsearch` or `output.elasticsearch`
(if `apm-server.agent.config.elasticsearch` is not set) does not have adequate permissions to read source maps from {es}.

To fix this error, ensure that {apm-server} has all the required privileges. See <<apm-privileges-agent-central-config-server>> for more details.
