[[apm-configuration-process]]
= General configuration options

status_badge::[stack, ga]
status_badge::[serverless, unavailable]

****
image:./binary-yes-fm-yes.svg[supported deployment methods]

Most options on this page are supported by all {apm-server} deployment methods.
****

General {apm-server} configuration options.

include::./tab-widgets/general-config-widget.asciidoc[]

[float]
[[apm-configuration-apm-server]]
== Configuration options

[[apm-host]]
[float]
=== Host
Defines the host and port the server is listening on.
Use `"unix:/path/to.sock"` to listen on a Unix domain socket.
Defaults to 'localhost:8200'. (text)

|====
| {apm-server} binary | `apm-server.host`
| Fleet-managed     | `Host`
|====

[float]
=== URL
The publicly reachable server URL. For deployments on Elastic Cloud or ECK, the default is unchangeable.

|====
| {apm-server} binary | N/A
| Fleet-managed     | `URL`
|====

[[apm-max_header_size]]
[float]
=== Max header size
Maximum permitted size of a request's header accepted by the server to be processed (in Bytes).
Defaults to 1048576 Bytes (1 MB). (int)

|====
| {apm-server} binary | `apm-server.max_header_size`
| Fleet-managed     | `Maximum size of a request's header`
|====

[[apm-idle_timeout]]
[float]
=== Idle timeout
Maximum amount of time to wait for the next incoming request before underlying connection is closed.
Defaults to `45s` (45 seconds). (text)

|====
| {apm-server} binary | `apm-server.idle_timeout`
| Fleet-managed     | `Idle time before underlying connection is closed`
|====

[[apm-read_timeout]]
[float]
=== Read timeout
Maximum permitted duration for reading an entire request.
Defaults to `3600s` (3600 seconds). (text)

|====
| {apm-server} binary | `apm-server.read_timeout`
| Fleet-managed     | `Maximum duration for reading an entire request`
|====

[[apm-write_timeout]]
[float]
=== Write timeout
Maximum permitted duration for writing a response.
Defaults to `30s` (30 seconds). (text)

|====
| {apm-server} binary | `apm-server.write_timeout`
| Fleet-managed     | `Maximum duration for writing a response`
|====

[[apm-shutdown_timeout]]
[float]
==== Shutdown timeout
Maximum duration in seconds before releasing resources when shutting down the server.
Defaults to `30s` (30 seconds). (text)

|====
| {apm-server} binary | `apm-server.shutdown_timeout`
| Fleet-managed     | `Maximum duration before releasing resources when shutting down`
|====

[[apm-max_event_size]]
[float]
=== Max event size
Maximum permitted size of an event accepted by the server to be processed (in Bytes).
Defaults to `307200` Bytes. (int)

|====
| {apm-server} binary | `apm-server.max_event_size`
| Fleet-managed     | `Maximum size per event`
|====

[[apm-max_connections]]
[float]
=== Max connections
Maximum number of TCP connections to accept simultaneously.
Default value is 0, which means _unlimited_. (int)

|====
| {apm-server} binary | `apm-server.max_connections`
| Fleet-managed     | `Simultaneously accepted connections`
|====

[[apm-custom_http_headers]]
[float]
=== Custom HTTP response headers
Custom HTTP headers to add to HTTP responses. Useful for security policy compliance. (text)

|====
| {apm-server} binary | `apm-server.response_headers`
| Fleet-managed     | `Custom HTTP response headers`
|====

[[apm-capture_personal_data]]
[float]
=== Capture personal data
If true,
{apm-server} captures the IP of the instrumented service and its User Agent if any.
Enabled by default. (bool)

|====
| {apm-server} binary | `apm-server.capture_personal_data`
| Fleet-managed     | `Capture personal data`
|====


[[apm-default_service_environment]]
[float]
=== Default service environment
Sets the default service environment to associate with data and requests received from agents which have no service environment defined. Default: none. (text)

|====
| {apm-server} binary | `apm-server.default_service_environment`
| Fleet-managed     | `Default Service Environment`
|====

[[apm-expvar.enabled]]
[float]
=== expvar support
When set to true {apm-server} exposes https://golang.org/pkg/expvar/[golang expvar] under `/debug/vars`.
Disabled by default.

|====
| {apm-server} binary | `apm-server.expvar.enabled`
| Fleet-managed     | `Enable {apm-server} Golang expvar support`
|====

[[apm-expvar.url]]
[float]
=== expvar URL
Configure the URL to expose expvar.
Defaults to `debug/vars`.

|====
| {apm-server} binary | `apm-server.expvar.url`
| Fleet-managed     | N/A
|====

[[apm-data_streams.namespace]]
[float]
=== Data stream namespace

Change the default namespace.
This setting changes the name of the data stream.

For {fleet}-managed users, the namespace is inherited from the selected {agent} policy.

|====
| {apm-server} binary | `apm-server.data_streams.namespace`
| Fleet-managed     | `Namespace` (Integration settings > Advanced options)
|====
