[[apm-configuration-path]]
= Configure project paths

status_badge::[cloud_serverless, unavailable]

++++
<titleabbrev>Project paths</titleabbrev>
++++

****
image:./binary-yes-fm-no.svg[supported deployment methods]

This documentation is only relevant for {apm-server} binary users.
Fleet-managed paths are defined in <<apm-directory-layout>>.
****

The `path` section of the +apm-server.yml+ config file contains configuration
options that define where {apm-server} looks for its files. For example, {apm-server}
looks for the {es} template file in the configuration path and writes
log files in the logs path.
ifdef::has_registry[]
{apm-server} looks for its registry files in the data path.
endif::[]

Please see the <<apm-directory-layout>> section for more details.

Here is an example configuration:

[source,yaml]
------------------------------------------------------------------------------
path.home: /usr/share/beat
path.config: /etc/beat
path.data: /var/lib/beat
path.logs: /var/log/
------------------------------------------------------------------------------

Note that it is possible to override these options by using command line flags.

[float]
== Configuration options

You can specify the following options in the `path` section of the +apm-server.yml+ config file:

[float]
=== `home`

The home path for the {apm-server} installation. This is the default base path for all
other path settings and for miscellaneous files that come with the distribution (for example, the
sample dashboards). If not set by a CLI flag or in the configuration file, the default
for the home path is the location of the {apm-server} binary.

Example:

[source,yaml]
------------------------------------------------------------------------------
path.home: /usr/share/beats
------------------------------------------------------------------------------

[float]
=== `config`

The configuration path for the {apm-server} installation. This is the default base path
for configuration files, including the main YAML configuration file and the
{es} template file. If not set by a CLI flag or in the configuration file, the default for the
configuration path is the home path.

Example:

[source,yaml]
------------------------------------------------------------------------------
path.config: /usr/share/beats/config
------------------------------------------------------------------------------

[float]
=== `data`

The data path for the {apm-server} installation. This is the default base path for all
the files in which {apm-server} needs to store its data. If not set by a CLI
flag or in the configuration file, the default for the data path is a `data`
subdirectory inside the home path.


Example:

[source,yaml]
------------------------------------------------------------------------------
path.data: /var/lib/beats
------------------------------------------------------------------------------

TIP: When running multiple {apm-server} instances on the same host, make sure they
each have a distinct `path.data` value.

[float]
=== `logs`

The logs path for a {apm-server} installation. This is the default location for {apm-server}'s
log files. If not set by a CLI flag or in the configuration file, the default
for the logs path is a `logs` subdirectory inside the home path.

Example:

[source,yaml]
------------------------------------------------------------------------------
path.logs: /var/log/beats
------------------------------------------------------------------------------

[float]
=== `system.hostfs`

Specifies the mount point of the host's file system for use in monitoring a host.
This can either be set in the config, or with the `--system.hostfs` CLI flag. This is used for cgroup self-monitoring.
ifeval::["apm-server"=="metricbeat"]
This is also used by the system module to read files from `/proc` and `/sys`.
endif::[]


Example:

[source,yaml]
------------------------------------------------------------------------------
system.hostfs: /mount/rootfs
------------------------------------------------------------------------------
