[[configuration-rum]]
= Configure Real User Monitoring (RUM)

++++
<titleabbrev>Real User Monitoring (RUM)</titleabbrev>
++++

****
image:./binary-yes-fm-yes.svg[supported deployment methods]

Most options in this section are supported by all APM Server deployment methods.
****

The {apm-rum-ref-v}/index.html[Real User Monitoring (RUM) agent] captures user interactions with clients such as web browsers.
These interactions are sent as events to the APM Server.
Because the RUM agent runs on the client side, the connection between agent and server is unauthenticated.
As a security precaution, RUM is therefore disabled by default.

include::./tab-widgets/rum-config-widget.asciidoc[]

In addition, if APM Server is deployed in an origin different than the page’s origin,
you will need to configure {apm-rum-ref-v}/configuring-cors.html[Cross-Origin Resource Sharing (CORS)] in the Agent.

[float]
[[enable-rum-support]]
= Configuration reference

[[rum-enable]]
[float]
== Enable RUM
To enable RUM support, set to `true`.
By default this is disabled. (bool)

|====
| APM Server binary | `apm-server.rum.enabled`
| Fleet-managed     | `Enable RUM`
|====

[NOTE]
====
If an <<api-key,API key>> or <<secret-token,secret token>> is configured,
enabling RUM support will automatically enable <<configuration-anonymous>>.
Anonymous authentication is required as the RUM agent runs in the browser.
====

[float]
[[rum-allow-origins]]
== Allowed Origins
A list of permitted origins for RUM support.
User-agents send an Origin header that will be validated against this list.
This is done automatically by modern browsers as part of the https://www.w3.org/TR/cors/[CORS specification].
An origin is made of a protocol scheme, host and port, without the URL path.

Default: `['*']` (allows everything). (text)

|====
| APM Server binary | `apm-server.rum.allow_origins`
| Fleet-managed     | `Allowed Origins`
|====

[float]
[[rum-allow-headers]]
== Access-Control-Allow-Headers
HTTP requests made from the RUM agent to the APM Server are limited in the HTTP headers they are allowed to have.
If any other headers are added, the request will be rejected by the browser due to Cross-Origin Resource Sharing (CORS) restrictions.
Use this setting to allow additional headers.
The default list of allowed headers includes "Content-Type", "Content-Encoding", and "Accept";
custom values configured here are appended to the default list and used as the value for the `Access-Control-Allow-Headers` header.

Default: `[]`. (text)

|====
| APM Server binary | `apm-server.rum.allow_headers`
| Fleet-managed     | `Access-Control-Allow-Headers`
|====

[float]
[[rum-response-headers]]
== Custom HTTP response headers
Custom HTTP headers to add to RUM responses.
This can be useful for security policy compliance.

Values set for the same key will be concatenated.

Default: none. (text)

|====
| APM Server binary | `apm-server.rum.response_headers`
| Fleet-managed     | `Custom HTTP response headers`
|====

[float]
[[rum-library-pattern]]
== Library Frame Pattern
RegExp to be matched against a stack trace frame's `file_name` and `abs_path` attributes.
If the RegExp matches, the stack trace frame is considered to be a library frame.
When source mapping is applied, the `error.culprit` is set to reflect the _function_ and the _filename_
of the first non library frame.
This aims to provide an entry point for identifying issues.

Default: `"node_modules|bower_components|~"`. (text)

|====
| APM Server binary | `apm-server.rum.library_pattern`
| Fleet-managed     | `Library Frame Pattern`
|====

[float]
== Exclude from grouping
RegExp to be matched against a stack trace frame's `file_name`.
If the RegExp matches, the stack trace frame is excluded from being used for calculating error groups.

Default: `"^/webpack"` (excludes stack trace frames that have a filename starting with `/webpack`). (text)

|====
| APM Server binary | `apm-server.rum.exclude_from_grouping`
| Fleet-managed     | `Exclude from grouping`
|====


[float]
[[rum-source-map]]
= Source map configuration options

****
image:./binary-yes-fm-no.svg[supported deployment methods]

Source maps are supported by all APM Server deployment methods, however,
the options in this section are only supported by the APM Server binary.
****

[[config-sourcemapping-enabled]]
[float]
== `source_mapping.enabled`
Used to enable/disable <<source-map-how-to,source mapping>> for RUM events.
When enabled, the APM Server needs additional privileges to read source maps.
See <<privileges-rum-source-mapping>> for more details.

Default: `true`

[[config-sourcemapping-elasticsearch]]
[float]
== `source_mapping.elasticsearch`
Configure the {es} source map retrieval location, taking the same options as <<elasticsearch-output,output.elasticsearch>>.
This must be set when using an output other than {es}, and that output is writing to {es}.
Otherwise leave this section empty.

[[rum-sourcemap-cache]]
[float]
== `source_mapping.cache.expiration`
If a source map has been uploaded to the APM Server,
<<source-map-how-to,source mapping>> is automatically applied to documents sent to the RUM endpoint.
Source maps are fetched from {es} and then kept in an in-memory cache for the configured time.
Values configured without a time unit are treated as seconds.

Default: `5m` (5 minutes)

[float]
== `source_mapping.index_pattern`
Previous versions of APM Server stored source maps in `apm-%{[observer.version]}-sourcemap` indices.
Search source maps stored in an older version with this setting.

Default: `"apm-*-sourcemap*"`

[float]
= Ingest pipelines

The default APM Server pipeline includes processors that enrich RUM data prior to indexing in {es}.
See <<ingest-pipelines>> for details on how to locate, edit, or disable this preprocessing.
