[[apm-data-streams]]
=== Data streams

****
{agent} uses data streams to store append-only time series data across multiple indices.
Data streams are well-suited for logs, metrics, traces, and other continuously generated data,
and offer a host of benefits over other indexing strategies:

* Reduced number of fields per index
* More granular data control
* Flexible naming scheme
* Fewer ingest permissions required

See the {fleet-guide}/data-streams.html[{fleet} and {agent} Guide] to learn more.
****

[discrete]
[[apm-data-streams-naming-scheme]]
=== Data stream naming scheme

// tag::data-streams[]
APM data follows the `<type>-<dataset>-<namespace>` naming scheme.
The `type` and `dataset` are predefined by the APM integration,
but the `namespace` is your opportunity to customize how different types of data are stored in {es}.
There is no recommendation for what to use as your namespace--it is intentionally flexible.
For example, you might create namespaces for each of your environments,
like `dev`, `prod`, `production`, etc.
Or, you might create namespaces that correspond to strategic business units within your organization.
// end::data-streams[]

[discrete]
[[apm-data-streams-list]]
=== APM data streams

By type, the APM data streams are:

Traces::
Traces are comprised of {observability-guide}/apm-data-model.html[spans and transactions].
Traces are stored in the following data streams:
+
// tag::traces-data-streams[]
- Application traces: `traces-apm-<namespace>`
- RUM and iOS agent application traces: `traces-apm.rum-<namespace>`
// end::traces-data-streams[]


Metrics::
Metrics include application-based metrics, aggregation metrics, and basic system metrics.
Metrics are stored in the following data streams:
+
// tag::metrics-data-streams[]
- APM internal metrics: `metrics-apm.internal-<namespace>`
- APM transaction metrics: `metrics-apm.transaction.<metricset.interval>-<namespace>`
- APM service destination metrics: `metrics-apm.service_destination.<metricset.interval>-<namespace>`
- APM service transaction metrics: `metrics-apm.service_transaction.<metricset.interval>-<namespace>`
- APM service summary metrics: `metrics-apm.service_summary.<metricset.interval>-<namespace>`
- Application metrics: `metrics-apm.app.<service.name>-<namespace>`
// end::metrics-data-streams[]
+
Application metrics include the instrumented service's name--defined in each {apm-agent}'s
configuration--in the data stream name.
Service names therefore must follow certain index naming rules.
+
[%collapsible]
.Service name rules
====
* Service names are case-insensitive and must be unique.
For example, you cannot have a service named `Foo` and another named `foo`.
* Special characters will be removed from service names and replaced with underscores (`_`).
Special characters include:
+
[source,text]
----
'\\', '/', '*', '?', '"', '<', '>', '|', ' ', ',', '#', ':', '-'
----
====


Logs::
Logs include application error events and application logs.
Logs are stored in the following data streams:
+
// tag::logs-data-streams[]
- APM error/exception logging: `logs-apm.error-<namespace>`
- APM app logging: `logs-apm.app.<service.name>-<namespace>`
// end::logs-data-streams[]

[discrete]
[[apm-data-stream-rerouting]]
=== APM data stream rerouting

APM supports rerouting APM data to user-defined APM data stream names other than the defaults.
This can be achieved by using a {ref}/reroute-processor.html[`reroute` processor] in ingest pipelines to set the data stream dataset or namespace.
The benefit of separating APM data streams is that custom retention and security policies can be used.

For example, consider traces that would originally be indexed to `traces-apm-default`. To set the data stream namespace from the trace's `service.environment` and fallback to a static string `"default"`, create an ingest pipeline named `traces-apm@custom` which will be used automatically:

[source, json]
----
[
  {
    "reroute": {
      "namespace": [
        "{{service.environment}}",
        "default"
      ]
    }
  }
]
----

For more about other ingest pipelines called by default, e.g. `traces-apm@custom`, see {fleet-guide}/data-streams.html#data-streams-pipelines[integration data streams ingest pipelines].

For more custom APM ingest pipeline guides, see <<apm-ingest-pipelines,parse data using ingest pipelines>>.

[discrete]
[[apm-data-streams-next]]
=== What's next?

* Data streams define not only how data is stored in {es}, but also how data is retained over time.
See <<apm-ilm-how-to>> to learn how to create your own data retention policies.

* See <<apm-manage-storage>> for information on APM storage and processing costs,
processing and performance, and other index management features.
