[[apm-upgrading-to-8.x]]
=== Upgrade to version {version}

status_badge::[stack, ga]
status_badge::[serverless, unavailable]

This guide explains the upgrade process for version {version}.
For a detailed look at what's new, see:

* {observability-guide}/whats-new.html[What's new in {observability}]
* {kibana-ref}/whats-new.html[What's new in {kib}]
* {ref}/release-highlights.html[{es} release highlights]

[float]
=== Notable APM changes

* All index management has been removed from {apm-server};
the built-in {es} apm-data plugin is entirely responsible for setting up index templates, index lifecycle polices,
and index pipelines.
* {apm-server} now only writes to well-defined data streams;
writing to classic indices is no longer supported.
* {apm-server} has a new {es} output implementation with defaults that should be sufficient for
most use cases.

// Temporarily remove for status-badge test
// As a result of the above changes,
// a number of index management and index tuning configuration variables have been removed.
// See the APM <<apm-release-notes,release notes>>, <<apm-breaking,breaking changes>> for full details.

[float]
=== Find your upgrade guide

Starting in version 7.14, there are two ways to run Elastic APM.
Determine which method you're using, then use the links below to find the correct upgrading guide.

* **Standalone**: Users in this mode run and configure the {apm-server} binary.
* **{fleet} and the APM integration**: Users in this mode run and configure {fleet} and the Elastic APM integration.

**Self-installation (non-{ecloud} users) upgrade guides**

* <<apm-upgrade-8.0-self-standalone>>
* <<apm-upgrade-8.0-self-integration>>

**{ecloud} upgrade guides**

* <<apm-upgrade-8.0-cloud-standalone>>
* <<apm-upgrade-8.0-cloud-integration>>

// ********************************************************

[[apm-upgrade-8.0-self-standalone]]
==== Upgrade a self-installation of {apm-server} standalone to {version}

++++
<titleabbrev>Self-installation standalone</titleabbrev>
++++

This upgrade guide is for the standalone method of running {apm-server}.
Only use this guide if both of the following are true:

* You have a self-installation of the {stack}, i.e. you're not using {ecloud}.
* You're running the {apm-server} binary, i.e. you haven't switched to the Elastic APM integration.

[float]
==== Prerequisites

. Prior to upgrading to version {version}, {es}, {kib},
and {apm-server} must be upgraded to version 7.17.
** To upgrade {es} and {kib},
see the https://www.elastic.co/guide/en/elastic-stack/7.17/upgrading-elastic-stack.html[{stack} Installation and Upgrade Guide]
** To upgrade {apm-server} to version 7.17, see
{apm-guide-7x}/upgrading-to-717.html[upgrade to version 7.17].

// Temporarily remove for status-badge test
// . Review the APM <<apm-release-notes,release notes>>, <<apm-breaking,breaking changes>>,
// and {observability} {observability-guide}/whats-new.html[What's new] content.

[float]
==== Upgrade steps

. **Upgrade the {stack} to version {version}**
+
The {stack} ({es} and {kib}) must be upgraded before {apm-server}.
See the {stack-ref}/upgrading-elastic-stack.html[{stack} Installation and Upgrade Guide] for guidance.

. **Install the {version} {apm-server} release**
+
See <<apm-installing,install>> to find the command that works with your system.

. **Review your configuration file**
+
Some settings have been removed or changed. You may need to update your `apm-server.yml` configuration
file prior to starting the {apm-server}.
See <<apm-directory-layout>> for help in locating this file,
and <<apm-configuring-howto-apm-server>> for a list of all available configuration options.

. **Start the {apm-server}**
+
To start the {apm-server}, run:
+
[source,bash]
----
./apm-server -e
----
+
Additional details are available in <<apm-server-starting,start the {apm-server}>>.

. **(Optional) Upgrade to the APM integration**
+
Got time for one more upgrade?
See <<apm-upgrade-to-apm-integration>>.

// ********************************************************

[[apm-upgrade-8.0-self-integration]]
==== Upgrade a self-installation of the APM integration to {version}

++++
<titleabbrev>Self-installation APM integration</titleabbrev>
++++

This upgrade guide is for the Elastic APM integration.
Only use this guide if both of the following are true:

* You have a self-installation of the {stack}, i.e. you're not using {ecloud}.
* You have already switched to and are running {fleet} and the Elastic APM integration.

[float]
==== Prerequisites

. Prior to upgrading to version {version}, {es}, and {kib}
must be upgraded to version 7.17. To upgrade {es} and {kib},
see the https://www.elastic.co/guide/en/elastic-stack/7.17/upgrading-elastic-stack.html[{stack} Installation and Upgrade Guide]

// Temporarily remove for status-badge test
// . Review the APM <<apm-release-notes,release notes>>, <<apm-breaking,breaking changes>>,
// and {observability} {observability-guide}/whats-new.html[What's new] content.

[float]
==== Upgrade steps

. Upgrade the {stack} to version {version}.
+
The {stack} ({es} and {kib}) must be upgraded before {agent}.
See the {stack-ref}/upgrading-elastic-stack.html[{stack} Installation and Upgrade Guide] for guidance.

. Upgrade {agent} to version {version}.
As a part of this process, the APM integration will automatically upgrade to version {version}.
+
--
. In {fleet}, select **Agents**.

. Under **Agents**, click **Upgrade available** to see a list of agents that you can upgrade.

. Choose **Upgrade agent** from the **Actions** menu next to the agent you want to upgrade.
The **Upgrade agent** option is grayed out when an upgrade is unavailable, or
the {kib} version is lower than the agent version.
--
+
For more details, or for bulk upgrade instructions, see
{fleet-guide}/upgrade-elastic-agent.html[Upgrade {agent}]

// ********************************************************

[[apm-upgrade-8.0-cloud-standalone]]
==== Upgrade {ecloud} {apm-server} standalone to {version}

++++
<titleabbrev>{ecloud} standalone</titleabbrev>
++++

This upgrade guide is for the standalone method of running {apm-server}.
Only use this guide if both of the following are true:

* You're using {ecloud}.
* You're using the {apm-server} binary, i.e. you haven't switched to the Elastic APM integration.

Follow these steps to upgrade:

// Temporarily remove for status-badge test
// . Review the APM <<apm-release-notes,release notes>>, <<apm-breaking,breaking changes>>,
// and {observability} {observability-guide}/whats-new.html[What's new] content.

. Upgrade {ecloud} to {version},
See {cloud}/ec-upgrade-deployment.html[Upgrade versions] for instructions.

. (Optional) Upgrade to the APM integration.
Got time for one more upgrade?
See <<apm-upgrade-to-apm-integration>>.

// ********************************************************

[[apm-upgrade-8.0-cloud-integration]]
==== Upgrade {ecloud} with the APM integration to 8.0

++++
<titleabbrev>{ecloud} APM integration</titleabbrev>
++++

This upgrade guide is for the Elastic APM integration.
Only use this guide if both of the following are true:

* You're using {ecloud}.
* You have already switched to and are running {fleet} and the Elastic APM integration.

Follow these steps to upgrade:

// Temporarily remove for status-badge test
// . Review the APM <<apm-release-notes,release notes>>, <<apm-breaking,breaking changes>>,
// and {observability} {observability-guide}/whats-new.html[What's new] content.

. Upgrade your {ecloud} instance to {version}.
See {cloud}/ec-upgrade-deployment.html[Upgrade versions] for details.
The APM integration will automatically be upgraded to version {version} as a part of this process.


NOTE: {ece} users require additional TLS setup.
See {ece-ref}/ece-manage-apm-settings.html[Add APM user settings] for more information.
