  - name: backport patches to 9.0 branch
    conditions:
      - merged
      - base=main
      - label=backport-9.0
    actions:
      backport:
        assignees:
          - "{{ author }}"
        labels:
          - "backport"
        branches:
          - "9.0"
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
