  - name: backport patches to 8.18 branch
    conditions:
      - merged
      - base=main
      - label=backport-8.18
    actions:
      backport:
        assignees:
          - "{{ author }}"
        labels:
          - "backport"
        branches:
          - "8.18"
        title: "[{{ destination_branch }}](backport #{{ number }}) {{ title }}"
