policy:
  - template: ['elastic-request.yaml']
    section:
      - id: ['version']
        block-list: []
        label:
          - name: 'request'
            keys: ['N/A']
          - name: '8.11-request'
            keys: ['8.11']
          - name: '8.12-request'
            keys: ['8.12']
          - name: '8.13-request'
            keys: ['8.13']
          - name: '8.14-request'
            keys: ['8.14']
          - name: '8.15-request'
            keys: ['8.15']
          - name: '8.16-request'
            keys: ['8.16']
      - id: [doc-set]
        block-list: []
        label:
          - name: 'all-docs'
            keys: ['Stateful and Serverless']
          - name: 'serverless-docs'
            keys: ['Serverless only']
          - name: 'stateful-docs'
            keys: ['Stateful only']
          - name: 'integration-docs'
            keys: ['Integrations']
          - name: 'unknown-docs'
            keys: ['Unknown']
      - id: [collaboration]
        block-list: []
        label:
          - name: 'writer-led'
            keys: ['The documentation team']
          - name: 'product-led'
            keys: ['The product team']
          - name: 'eng-led'
            keys: ['The engineering team']
          - name: 'unknown-led'
            keys: ['Unknown', 'Other (please describe below)']