policy:
  - template: ['elastic-request.yaml']
    section:
      - id: ['version']
        block-list: []
        label:
          - name: 'Request'
            keys: ['N/A']
          - name: 'Request:8.11'
            keys: ['8.11']
          - name: 'Request:8.12'
            keys: ['8.12']
          - name: 'Request:8.13'
            keys: ['8.13']
          - name: 'Request:8.14'
            keys: ['8.14']
          - name: 'Request:8.15'
            keys: ['8.15']
          - name: 'Request:8.16'
            keys: ['8.16']
      - id: [doc-set]
        block-list: []
        label:
          - name: 'Docset:All'
            keys: ['Stateful and Serverless']
          - name: 'Docset:Serverless'
            keys: ['Serverless only']
          - name: 'Docset:Stateful'
            keys: ['Stateful only']
          - name: 'Docset:Integrations'
            keys: ['Integrations']
          - name: 'Docset:Unknown'
            keys: ['Unknown']
      - id: [collaboration]
        block-list: []
        label:
          - name: 'Lead:Writer'
            keys: ['The documentation team']
          - name: 'Lead:Product'
            keys: ['The product team']
          - name: 'Lead:Eng'
            keys: ['The engineering team']
          - name: 'Lead:Unknown'
            keys: ['Unknown', 'Other (please describe below)']