---
version: 2
updates:

  # GitHub actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    reviewers:
      - "elastic/observablt-ci"
    groups:
      github-actions:
        patterns:
          - "*"
