name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
change-template: '* $TITLE ({$URL[#$NUMBER])' 
exclude-labels:
  - 'release_note:skip'
  - 'Team:Docs'
  - 'reverted'
  - 'backport'
include-labels:
  - 'Feature:Uptime'
  - 'Feature:Logs UI'
  - 'Team:apm'
  - 'Team:APM'
  - 'Feature:Metrics UI'
  - 'Team:logs-metrics-ui'
  - 'Feature:Observability Home'
  - 'Team:obs-ux-management'
  - 'Team:Obs AI Assistant'
  - 'Feature:SLO'
categories:
  - title: 'Breaking changes'
    collapse-after: 5
    labels: ['release_note:breaking']
  - title: 'Features and enhancements'
    collapse-after: 5
    labels: ['release_note:feature', 'release_note:enhancement']
  - title: 'Bug fixes'
    collapse-after: 5
    labels: ['release_note:fix']
template: |
  == Elastic {observability}

  $CHANGES

 To view all changes, check https://github.com/$OWNER/$REPO/compare/$PREVIOUS_TAG...$CURRENT_TAG.