[[observability-billing]]
= {obs-serverless} billing dimensions

// :description: Learn about how Observability usage affects pricing.
// :keywords: serverless, observability, overview

{obs-serverless} projects provide you with all the capabilities of Elastic Observability to monitor critical applications.
Projects are provided using a Software as a Service (SaaS) model, and pricing is entirely consumption-based.

Your monthly bill is based on the capabilities you use.
When you use {obs-serverless}, your bill is calculated based on data volume, which has these components:

* **Ingest** — Measured by the number of GB of log/event/info data that you send to your Observability project over the course of a month.
* **Storage/Retention** — This is known as Search AI Lake.
* In addition to the core ingest and retention dimensions, there is an optional charge to execute synthetic monitors on our testing infrastructure.
Browser (journey) based tests are charged on a per-test-run basis,
and Ping (lightweight) tests have an all-you-can-use model per location used.

For more information, refer to <<general-serverless-billing>>.

For detailed {obs-serverless} project rates, check the https://www.elastic.co/pricing/serverless-observability[{obs-serverless} pricing page].
