// tag::helm[]

The OpenTelemetry Operator will:

* Deploy the EDOT collector to collect logs and infrastructure metrics from a set of locations specified in the configuration. 
* Auto-instrument applications that are annotated as described in the instructions.

// What instructions is the above referring to?

Add the OpenTelemetry Helm Repo:

[source,bash]
----
helm repo add open-telemetry 'https://open-telemetry.github.io/opentelemetry-helm-charts' --force-update
----

Replace the Endpoint and API Key copied above into the command below:

[source,bash]
----
kubectl create namespace opentelemetry-operator-system
kubectl create secret generic elastic-secret-otel \
  --namespace opentelemetry-operator-system \
  --from-literal=elastic_endpoint='<YOUR_INGEST_URL>' \
  --from-literal=elastic_api_key='<Api Key YOUR_BASE64_APIKEY>'
helm install opentelemetry-kube-stack open-telemetry/opentelemetry-kube-stack \
  --namespace opentelemetry-operator-system \
  --values 'https://raw.githubusercontent.com/elastic/elastic-agent/51942e903eb69bb295920763b10a1c8bec68d1e8/deploy/helm/edot-collector/kube-stack/values.yaml' \
  --version '0.3.9'
----

Finally, confirm that you have three OpenTelemetry collectors running with the following command:

[source,bash]
----
kubectl get opentelemetrycollectors -A
----
// end::helm[]

// tag::linux[]

The EDOT collector will:

* Collect logs from a set of locations specified in the configuration.
* Collect infrastructure metrics with the host metrics receiver.

Run the following command to download the EDOT collector:

[source,bash]
----
arch=$(if ([[ $(arch) == "arm" || $(arch) == "aarch64" ]]); then echo "arm64"; else echo $(arch); fi)

curl --output elastic-distro-8.18.0-SNAPSHOT-linux-$arch.tar.gz --url https://snapshots.elastic.co/8.18.0-72dd839e/downloads/beats/elastic-agent/elastic-agent-8.18.0-SNAPSHOT-linux-$arch.tar.gz --proto '=https' --tlsv1.2 -fOL && mkdir -p elastic-distro-8.18.0-SNAPSHOT-linux-$arch && tar -xvf elastic-distro-8.18.0-SNAPSHOT-linux-$arch.tar.gz -C "elastic-distro-8.18.0-SNAPSHOT-linux-$arch" --strip-components=1 && cd elastic-distro-8.18.0-SNAPSHOT-linux-$arch

rm ./otel.yml && curl https://raw.githubusercontent.com/elastic/elastic-agent/a4d698f501d625f8d6ebb21badbcecdce6bd32a0/internal/pkg/otel/samples/linux/platformlogs_hostmetrics.yml -o otel.yml && mkdir -p ./data/otelcol && sed -i 's#\${env:STORAGE_DIR}#'"$PWD"/data/otelcol'#g' ./otel.yml
----

Run the EDOT collector with your API endpoint and API Key:

[source,bash]
----
sudo ELASTIC_ENDPOINT='<YOUR_INGEST_URL>' ELASTIC_API_KEY='ApiKey <YOUR_BASE64_APIKEY>' ./otelcol --config otel.yml
----

// end::linux[]

// tag::mac[]

The EDOT collector will:

* Collect logs from a set of locations specified in the configuration.
* Collect infrastructure metrics with the host metrics receiver.

Run the following command to download the EDOT collector:

[source,bash]
----
arch=$(if ([[ $(arch) == "arm" || $(arch) == "arm64" ]]); then echo "aarch64"; else echo $(arch); fi)

curl --output elastic-distro-8.18.0-SNAPSHOT-darwin-$arch.tar.gz --url https://snapshots.elastic.co/8.18.0-72dd839e/downloads/beats/elastic-agent/elastic-agent-8.18.0-SNAPSHOT-darwin-$arch.tar.gz --proto '=https' --tlsv1.2 -fOL && mkdir -p elastic-distro-8.18.0-SNAPSHOT-darwin-$arch && tar -xvf elastic-distro-8.18.0-SNAPSHOT-darwin-$arch.tar.gz -C "elastic-distro-8.18.0-SNAPSHOT-darwin-$arch" --strip-components=1 && cd elastic-distro-8.18.0-SNAPSHOT-darwin-$arch

rm ./otel.yml && curl https://raw.githubusercontent.com/elastic/elastic-agent/a4d698f501d625f8d6ebb21badbcecdce6bd32a0/internal/pkg/otel/samples/darwin/platformlogs_hostmetrics.yml -o otel.yml && mkdir -p ./data/otelcol && sed -i '' 's#\${env:STORAGE_DIR}#'"$PWD"/data/otelcol'#g' ./otel.yml
----

Run the EDOT collector with your API endpoint and API Key:

[source,bash]
----
sudo ELASTIC_ENDPOINT='<YOUR_INGEST_URL>' ELASTIC_API_KEY='ApiKey <YOUR_BASE64_APIKEY>' ./otelcol --config otel.yml
----

// end::mac[]