[[observability-apm-alerts]]
= Create APM rules and alerts

++++
<titleabbrev>Create rules and alerts</titleabbrev>
++++

The Applications UI allows you to define *rules* to detect complex conditions within your APM data
and trigger built-in *actions* when those conditions are met.

[discrete]
== APM rules

The following APM rules are supported:

[cols="1,1"]
|===
| *APM Anomaly*
a| Alert when either the latency, throughput, or failed transaction rate of a service is anomalous.
Anomaly rules can be set at the environment level, service level, and/or transaction type level.

Read more in <<observability-create-anomaly-alert-rule,APM Anomaly rule →>>

| *Error count threshold*
a| Alert when the number of errors in a service exceeds a defined threshold. Error count rules can be set at the
environment level, service level, and error group level.

Read more in <<observability-create-error-count-threshold-alert-rule,Error count threshold rule →>>

| *Failed transaction rate threshold*
a| Alert when the rate of transaction errors in a service exceeds a defined threshold.

Read more in <<observability-create-failed-transaction-rate-threshold-alert-rule,Failed transaction rate threshold rule →>>

| *Latency threshold*
a| Alert when the latency or failed transaction rate is abnormal.
Threshold rules can be as broad or as granular as you'd like, enabling you to define exactly when you want to be alerted--whether that's at the environment level, service name level, transaction type level, and/or transaction name level.

Read more in <<observability-create-latency-threshold-alert-rule,Latency threshold rule →>>

|===

