[[add-observability-data]]
= Send data to {es}

To use Elastic Observability, you need {es} for storing and searching your
data, and {kib} for visualizing and managing it.

[float]
[[spin-up-stack]]
== Spin up the Elastic Stack

You can use our
https://www.elastic.co/cloud/elasticsearch-service[hosted {ess}]
on {ecloud} (recommended), or self-manage the {stack} on your own hardware.

include::{shared}/spin-up-the-stack/widget.asciidoc[]

[float]
[[send-data-deployment]]
== Get data into your deployment

Now that you have provisioned your first deployment of your {es} cluster,
you’re ready to ingest your logs, metrics, uptime data, and APM data.

To make full use of Elastic Observability, we recommend that you install the observability
products in the following order:

1. Install and configure {filebeat} on your servers to collect log events. For details, see
<<ingest-logs,Ingest logs>> or <<ingest-splunk,Ingest Splunk>>.

2. Install and configure {metricbeat} on your servers to collect and preprocess system
and service metrics, such as information about running processes, as well as CPU, memory,
disk, and network utilization numbers. For details, see <<ingest-metrics,Ingest metrics>>.

3. Install and configure {heartbeat} on your servers to periodically check the status of your
services. For details, see <<ingest-uptime,Ingest uptime data>>.

4. If you have added an APM Server as part of an {ess-trial}[{ess}] deployment, configure your
APM agents to send data to your {es} cluster. For details, see <<instrument-apps,Instrument applications>>.

// Add Javascript and CSS for tabbed panels
include::{shared}/tab-widget-code/code.asciidoc[]
