[[apm-failed-transaction-rate-threshold-rule]]
= Failed transaction rate threshold rule

Alert when the rate of transaction errors in a service exceeds a defined threshold.

[discrete]
== Filters and conditions

// TO DO: Write this section...
Filters:

* Service
* Type
* Environment
* Name

Conditions:

* is above XX%
* for the last X minutes

[discrete]
== Group

// TO DO: Write this section...
Create an alert for every unique value. For example: "transaction.name". By default, alert is created for every unique service.name, service.environment and transaction.type.

[discrete]
== Action types

Extend your rules by connecting them to actions that use the following supported built-in integrations.

include::../shared/alerting-connectors.asciidoc[]

[discrete]
=== Action variables

Use the default notification message or customize it. You can add more context to the message by clicking the icon above the message text box and selecting from a list of available variables.

// TO DO: add image?

The following variables are specific to this rule type.
You an also specify {kibana-ref}/rule-action-variables.html[variables common to all rules].

`context.alertDetailsUrl`::
Link to the alert troubleshooting view for further context and details. This will be an empty string if the server.publicBaseUrl is not configured.

`context.environment`::
The transaction type the alert is created for

`context.interval`::
The length and unit of the time period where the alert conditions were met

`context.reason`::
A concise description of the reason for the alert

`context.serviceName`::
The service the alert is created for

`context.threshold`::
Any trigger value above this value will cause the alert to fire

`context.transactionName`::
The transaction name the alert is created for

`context.transactionType`::
The transaction type the alert is created for

`context.triggerValue`::
The value that breached the threshold and triggered the alert

`context.viewInAppUrl`::
Link to the alert source