[[application-and-service-monitoring]]
= Application and service monitoring

++++
<titleabbrev>Applications and services</titleabbrev>
++++

Explore the topics in this section to learn how to observe and monitor software applications and services running in your environment.

[cols="1,1"]
|===
| *Application performance monitoring (APM)*
a| Monitor software services and applications in real time, by collecting detailed performance information on response time for incoming requests, database queries, calls to caches, external HTTP requests, and more.

Read more in <<apm>>.

a| *Synthetic monitoring* +
status_badge::[cloud_hosted, ga, 8.8.0] +
status_badge::[cloud_hosted, beta, 8.0.0]
a| Monitor the availability of network endpoints and services.

Read more in <<monitor-uptime-synthetics>>.

a| *Real user monitoring* +
status_badge::[cloud_serverless, unavailable]
a| Quantify and analyze the perceived performance of your web application using real-world user experiences.

Read more in <<user-experience>>.

a| *Uptime monitoring* +
status_badge::[cloud_hosted, deprecated, 8.15.0] +
status_badge::[cloud_serverless, unavailable]
a| Periodically check the status of your services and applications.

Read more in <<uptime-intro>>.

a| *Tutorial: Monitor a Java application* +
status_badge::[cloud_serverless, unavailable]
a| Monitor a Java application using Elastic Observability: Logs, Infrastructure metrics, APM, and Uptime.

Try it out in <<monitor-java-app>>.

|===