[[configure-settings]]
= Configure settings

By default, the {kibana-ref}/infrastructure-ui-settings-kb.html[configuration settings] for the 
{metrics-app} are enabled. The configuration uses the `metricbeat-*` and `metrics-*` index patterns
to query the data. The configuration also defines field settings for things like timestamps
and container names.

[[metrics-config-settings]]
== Override configuration settings

. In the side navigation, expand *Observability*, and then click *Metrics*.
+
. Click *Settings*.
+
You can override the following configuration settings.
+
|=== 

| *Name* | Name of the source configuration. 

| *Indices* | Index pattern or patterns in the {es} indices to read metrics data from.

| *Fields* | Configuring fields input has been deprecated. You should adjust your indexing using the
<<metrics-app-fields,Metrics app fields>>, which use the {ecs-ref}/index.html[Elastic Common Schema (ECS) specification].

|=== 
+
. When you have completed your changes, click *Apply*.
+
If the fields are greyed out and cannot be edited, you may not have sufficient privileges to change the source configuration.
For more information see {kibana-ref}/xpack-security-authorization.html[Granting access to Kibana].
+
[TIP]
===============================
If {kibana-ref}/xpack-spaces.html[Spaces] are enabled in your Kibana instance, any configuration changes you make here are specific to the current space.
You can make different subsets of data available by creating multiple spaces with different data source configurations.
===============================
