[[configure-data-sources]]
= Configure data sources

// QUESTION FOR MIKE: Should we say anything here about how these settings apply to the legacy logs app?
// Here's what the UI says: "These settings only apply to the legacy Logs Stream app, and we do not recommend configuring them. Instead, use Logs Explorer which makes viewing and inspecting your logs easier with more features, better performance, and more intuitive navigation."

Specify the source configuration for logs in the
{kibana-ref}/logs-ui-settings-kb.html[Logs settings] in the
{kibana-ref}/settings.html[{kib} configuration file].
By default, the configuration uses the index patterns stored in the {kib} log sources advanced setting to query the data.
The configuration also defines the default columns displayed in the logs stream.

If your logs have custom index patterns, use non-default field settings, or contain
parsed fields that you want to expose as individual columns, you can override the
default configuration settings.

[discrete]
[[edit-config-settings]]
== Edit configuration settings

. To open **Logs settings**, search for `logs settings` in the {kibana-ref}/introduction.html#kibana-navigation-search[global search field].
+
|===

| *Name* | Name of the source configuration.

| *{kib} log sources advanced setting* | Use index patterns stored in the {kib} *log sources* advanced setting, which provides a centralized place to store and query log index patterns.
To open **Advanced settings**, find **Stack Management** in the main menu or use the {kibana-ref}/introduction.html#kibana-navigation-search[global search field].

| *{data-source-cap} (deprecated)* | The Logs UI integrates with {data-sources} to
configure the used indices by clicking *Use {data-sources}*.

| *Log indices (deprecated)* | {kib} index patterns or index name patterns in the {es} indices
to read log data from.

| *Log columns* | Columns that are displayed in the logs *Stream* page.

|===
+
. When you have completed your changes, click *Apply*.

[discrete]
[[customize-stream-page]]
== Customize Stream page

[TIP]
===============================
If {kibana-ref}/xpack-spaces.html[Spaces] are enabled in your {kib} instance,
any configuration changes you make here are specific to the current space.
You can make different subsets of data available by creating multiple spaces
with other data source configurations.
===============================

By default, the *Stream* page within the {logs-app} displays the following columns.

|===

| *Timestamp* | The timestamp of the log entry from the `timestamp` field.

| *Message* | The message extracted from the document.
The content of this field depends on the type of log message.
If no special log message type is detected, the {ecs-ref}/ecs-base.html[Elastic Common Schema (ECS)]
base field, `message`, is used.

|===

1. To add a new column to the logs stream, select *Settings > Add column*.
2. In the list of available fields, select the field you want to add.
To filter the field list by that name, you can start typing a field name in the search box.
3. To remove an existing column, click the *Remove this column* icon.
4. When you have completed your changes, click *Apply*.

If the fields are grayed out and cannot be edited, you may not have sufficient privileges
to modify the source configuration. For more information, see {kibana-ref}/xpack-security-authorization.html[Granting access to {kib}].
