[[configure-metrics-sources]]
= Configure data sources

Specify the source configuration for metrics in the
{kibana-ref}/infrastructure-ui-settings-kb.html[{metrics-app} settings] in the
{kibana-ref}/settings.html[Kibana configuration file].
By default, the configuration uses the `metricbeat-*` index pattern to query the data.
The configuration also defines field settings for things like timestamps
and container names.

If your metrics have custom index patterns, use non-default field settings, or contain
parsed fields that you want to expose as individual columns, you can override the
default configuration settings.

[[metrics-config-settings]]
== Edit configuration settings

[NOTE]
===============================
These settings are shared with logs. Changes you make here may also affect the
settings used by the {metrics-guide}/configure-metrics-source.html[{logs-app}].
===============================

To change the configuration settings, select the *Settings* page, and modify the following values.

|=== 

| *Name* | Name of the source configuration. 

| *Indices* | Index pattern or patterns in the {es} indices to read metrics data from.

| *Fields* | Names of specific fields in the indices that are used to query and interpret the data correctly.

|=== 

When you have completed your changes, click *Apply*.

If the fields are greyed out and cannot be edited, you may not have sufficient privileges to change the source configuration.
For more information see {kibana-ref}/xpack-security-authorization.html[Granting access to Kibana].

[TIP]
===============================
If {kibana-ref}/xpack-spaces.html[Spaces] are enabled in your Kibana instance, any configuration changes you make here are specific to the current space.
You can make different subsets of data available by creating multiple spaces with different data source configurations.
===============================
