[[create-alerts]]
= Alerting

[IMPORTANT]
====
Make sure to set up alerting in {kib}. For details, see
{kibana-ref}/alerting-setup.html[Setup and prerequisites].
====

Within the Logs, Metrics, and Uptime apps, alerting enables you to detect
complex *conditions* defined by a *rule*. When a condition is met, the rule
tracks it as an *alert* and responds by triggering one or more *actions*.

Alerting can be centrally managed from the
{kibana-ref}/create-and-manage-rules.html[{kib} Management UI] and provides a
set of built-in {kibana-ref}/rule-types.html[rule types] and
{kibana-ref}/action-types.html[connectors] for you to use.

Extend your rules by connecting them to actions that use built-in *connectors* for email,
IBM Resilient, Index, JIRA, Microsoft Teams, PagerDuty, Server log, ServiceNow ITSM, and Slack.
Also supported is a powerful webhook output letting you tie into other third-party systems.
Connectors allow actions to talk to these services and integrations.

* <<logs-threshold-alert,Logs threshold rule>>
* <<infrastructure-threshold-alert,Infrastructure threshold rule>>
* <<metrics-threshold-alert,Metrics threshold rule>>
* <<monitor-status-alert,Monitor status rule>>
* <<tls-certificate-alert,TLS certificate rule>>
* <<duration-anomaly-alert,Uptime duration anomaly rule>>

include::logs-threshold-alert.asciidoc[leveloffset=+1]

include::infrastructure-threshold-alert.asciidoc[leveloffset=+1]

include::metrics-threshold-alert.asciidoc[leveloffset=+1]

include::monitor-status-alert.asciidoc[leveloffset=+1]

include::uptime-tls-alert.asciidoc[leveloffset=+1]

include::uptime-duration-anomaly-alert.asciidoc[leveloffset=+1]
