[[create-alerts]]
= Alerting

[IMPORTANT]
====
Ensure Alerting is already set up in {kib}. For details, see
{kibana-ref}/alerting-setup.html[Setup and prerequisites].
====

Alerting enables you to detect complex *conditions* defined by a rule
within the Logs, Metrics, Uptime, and APM apps. When a condition is met, the rule
tracks it as an *alert* and responds by triggering one or more *actions*.

Listed on the <<view-observability-alerts,Alerts>> page are all of your
observability alerts that have met a condition defined by a rule you created
using the Logs, Metrics, Uptime, or APM apps.

IMPORTANT: Not all of the predefined rules in Stack Management will generate and 
list an alert on the Alerts page. Only alerts generated by rules relating to Logs, Metrics, Uptime, and APM
can be viewed on the Alerts page.

Alerting can be centrally managed from the
{kibana-ref}/create-and-manage-rules.html[{kib} Management UI] and provides a
set of built-in {kibana-ref}/rule-types.html[rule types] and
{kibana-ref}/action-types.html[connectors] for you to use.

Extend your rules by connecting them to actions that use built-in *connectors* for email,
IBM Resilient, Index, JIRA, Microsoft Teams, PagerDuty, Server log, ServiceNow ITSM, and Slack.
Also supported is a powerful webhook output letting you tie into other third-party systems.
Connectors allow actions to talk to these services and integrations.

* <<logs-threshold-alert,Logs threshold rule>>
* <<infrastructure-threshold-alert,Infrastructure threshold rule>>
* <<metrics-threshold-alert,Metrics threshold rule>>
* <<monitor-status-alert,Monitor status rule>>
* <<tls-certificate-alert,TLS certificate rule>>
* <<duration-anomaly-alert,Uptime duration anomaly rule>>

[discrete]
[[create-alerts-configure]]
== Configure alerts

You may want to disable writing to specific {observability} alert indices or disable all alerts and remove the Alerts page altogether.
You can do this in {kib} settings.

If you are using our https://www.elastic.co/cloud/elasticsearch-service[hosted {ess}] on {ecloud},
you'll edit the {kib} user settings:

. Select your deployment on the home page, and from your deployment menu go to the *Edit* page.
. In the *{kib}* section, click *Edit user settings*, and add the desired settings (detailed below).
. Click *Back*, and then click *Save*. The changes are automatically appended to the `kibana.yml` configuration file for your instance.

If you have a self-managed {stack}, you'll edit the settings in your `kibana.yml` file.

[discrete]
[[create-alerts-disable-some]]
=== Disable writing to specific alert indices

To disable writing to specific {observability} alerts-as-data indices
while continuing to write to others, use `xpack.ruleRegistry.write.disabledRegistrationContexts`.

You can disable writing to alert indices for:

* Logs (`observability.logs`)
* Metrics (`observability.metrics`)
* APM (`observability.apm`)
* Uptime (`observability.uptime`)

NOTE: Disabling writing to the indices of one of the {observability} apps listed above will affect _all_ rule types of the corresponding app.
For example, disabling writing to uptime alert indices will affect _all_ uptime rule types including monitor status and TLS rule types.

For example, to disable writing to Logs alert indices, you would add the following to your {kib} settings:

[source,yml]
----
xpack.ruleRegistry.write.disabledRegistrationContexts : ['observability.logs']
----

To disable writing to both Logs and Uptime alert indices, you would use: 

[source,yml]
----
xpack.ruleRegistry.write.disabledRegistrationContexts : ['observability.logs', 'observability.uptime']
----

[discrete]
[[create-alerts-remove-page]]
=== Remove the Alerts page

To disable writing to all alert indices and remove the Alerts page from {kib} altogether, use the following settings:

[source,yml]
----
xpack.ruleRegistry.write.enabled: 'false'
xpack.observability.unsafe.alertingExperience.enabled: 'false'
----


include::logs-threshold-alert.asciidoc[leveloffset=+1]

include::infrastructure-threshold-alert.asciidoc[leveloffset=+1]

include::metrics-threshold-alert.asciidoc[leveloffset=+1]

include::monitor-status-alert.asciidoc[leveloffset=+1]

include::uptime-tls-alert.asciidoc[leveloffset=+1]

include::uptime-duration-anomaly-alert.asciidoc[leveloffset=+1]

include::view-observability-alerts.asciidoc[leveloffset=+1]
