[[deploy-beats-to-send-data]]
= Deploy {beats} to send data

{beats} are lightweight data shippers that send operational data to
{es}. Elastic provides separate {beats} for different types of data, such as
logs, metrics, and uptime. To send observability data, you must install multiple
shippers on a single host.

Prefer to use a single agent for your use case? Refer to
<<deploy-agent-to-send-data>>.

To get started with {beats}:

. Install and configure {filebeat} on your servers to collect log events. For details, refer to
<<ingest-logs,Ingest logs>>.

. Install and configure {metricbeat} on your servers to collect and preprocess system
and service metrics, such as information about running processes, as well as CPU, memory,
disk, and network utilization numbers. For details, refer to <<ingest-metrics,Ingest metrics>>.

. Install and configure {heartbeat} on your servers to periodically check the status of your
services. For details, refer to <<ingest-uptime,Ingest uptime data>>.

. If you have added an APM Server as part of an {ess-trial}[{ess}] deployment, configure your
APM agents to send data to your {es} cluster. For details, refer to <<instrument-apps,Instrument applications>>.


