[chapter, role="xpack"]
[[install-observability]]
= Get started

To use the Elastic Observability, you need {ess} for storing and searching your 
data, and {kib} for visualizing and managing it.

[float]
[[set-up-on-cloud]]
== Set up on Cloud

To get started quickly, you can spin up a deployment of our
https://www.elastic.co/cloud/elasticsearch-service[hosted {ess}]. The deployment includes
{es}, {kib}, and APM Server, and is available on AWS, GCP, and Azure.

include::{docs-root}/shared/cloud/ess-getting-started.asciidoc[]

[float]
[[self-manage]]
== Self manage

Alternatively, you can install and self manage {stack-gs}/get-started-elastic-stack.html#install-elasticsearch[Elasticsearch], 
{stack-gs}/get-started-elastic-stack.html#install-kibana[Kibana], and 
{apm-get-started-ref}/apm-server.html[APM server]. 
First see the https://www.elastic.co/support/matrix[Elastic Support Matrix] for information about 
supported operating systems and product compatibility. We recommend you use the same 
version of Elasticsearch, Kibana, and APM Server.





