[chapter, role="xpack"]
[[ingest-logs]]

:beatname_uc: Filebeat
:beatname_lc: filebeat
:beatname_pkg: {beatname_lc}
:beatname_url: {beats-ref-root}/{beatname_lc}/{branch}
:modulename: nginx
:has_modules_command:

[[ingest-logs]]
= Ingest logs with {filebeat}

++++
<titleabbrev>Ingest logs</titleabbrev>
++++

[NOTE]
=====
If you haven't already, you need to install {es} for storing and searching your data, and {kib} for visualizing and
managing it. For more information, see <<spin-up-stack>>.
=====

Install and configure {filebeat} on your servers to collect log events. {filebeat} allows you ship log data from sources that come
in the form of files. It monitors the log files or locations that you specify,
collects log events, and forwards them to {es}. To ease the collection and parsing of
log formats for common applications such as Apache, MySQL, and Kafka, a number of
{filebeat-ref}/filebeat-modules.html[modules] are available.

[discrete]
[[install-filebeat]]
== Step 1: Install {beatname_uc}

Install {beatname_uc} on all the servers you want to monitor.

To download and install {beatname_uc}, use the commands that work with your system:

include::{beats-repo-dir}/tab-widgets/install-widget.asciidoc[]

[discrete]
[[other-filebeat-installations]]
=== Other installation options

// TODO: include a ref to the new docs for running cloud on Kubernetes. Issue number https://github.com/elastic/beats/pull/19966
* {filebeat-ref}/running-on-kubernetes.html[Kubernetes]
* {filebeat-ref}/running-on-docker.html[Docker]
* {filebeat-ref}/running-on-cloudfoundry.html[Cloud Foundry]
* {filebeat-ref}/setup-repositories.html[APT or YUM]
* https://www.elastic.co/downloads/beats/filebeat[Download page]

[discrete]
[[logs-connect-to-stack]]
== Step 2: Connect to {es} and {kib}

Connections to {es} and {kib} are required to set up {beatname_uc}.

Set the connection information in `filebeat.yml`. To locate this configuration file,
see {filebeat-ref}/directory-layout.html[Directory layout].

include::{beats-repo-dir}/tab-widgets/set-connection-widget.asciidoc[]

To learn more about required roles and privileges, see {filebeat-ref}/feature-roles.html[Grant users access to secured resources].

[NOTE]
=====

You can send data to other {filebeat-ref}/configuring-output.html[outputs], such as {ls},
but that requires additional configuration and setup.

=====

[discrete]
[[enable-logs-modules]]
== Step 3: Enable and configure modules

{beatname_uc} uses modules to collect and parse log data.

. Identify the modules you need to enable. To see a list of available {filebeat-ref}/filebeat-modules.html[modules], run:
+
--
include::{beats-repo-dir}/tab-widgets/list-modules-widget.asciidoc[]
--
+
Can’t find a module for your file type? Skip this section and
{filebeat-ref}/configuration-filebeat-options.html[configure the input manually].

. From the installation directory, enable one or more modules. For example, the
following command enables the +{modulename}+ module config:
+
--
include::{beats-repo-dir}/tab-widgets/enable-modules-widget.asciidoc[]
--

. In the module config under `modules.d`, change the module settings to match
your environment.
+
For example, log locations are set based on the OS. If your logs aren't in
default locations, set the `paths` variable:
+
--
[source,yaml]
----
- module: nginx
  access:
    var.paths: ["/var/log/nginx/access.log*"] <1>
----
--

To see the full list of variables for a module, see the documentation under
{filebeat-ref}/filebeat-modules.html[Modules].

[TIP]
=====
To test your configuration file, change to the directory where the {beatname_uc} binary
is installed, and run {beatname_uc} in the foreground with the following options specified:
`./filebeat test config -e`. Make sure your config files are in the path expected by
{beatname_uc} (see {filebeat-ref}/directory-layout.html[Directory layout]),
or use the `-c` flag to specify the path to the config file.
=====

For more information about configuring {beatname_uc}, also see:

* {filebeat-ref}/configuring-howto-filebeat.html[Configure {beatname_uc}]
* {beats-ref}/config-file-format.html[Config file format]
* {filebeat-ref}/filebeat-reference-yml.html[`filebeat.reference.yml`]: This reference
configuration file shows all non-deprecated options. You’ll find it in the same location as `filebeat.yml`.

[discrete]
[[set-filebeat-assets]]
== Step 4: Set up assets
{beatname_uc} comes with predefined assets for parsing, indexing, and
visualizing your data. To load these assets:

. Make sure the user specified in `filebeat.yml` is
{filebeat-ref}/privileges-to-setup-beats.html[authorized to set up {beatname_uc}].

. From the installation directory, run:
+
--
include::{beats-repo-dir}/tab-widgets/setup-widget.asciidoc[]
--
+
`-e` is optional and sends output to standard error instead of the configured log output.

This step loads the recommended {ref}/indices-templates.html[index template] for writing to {es}
and deploys the sample dashboards for visualizing the data in {kib}.

This step does not load the ingest pipelines used to parse log lines. By
default, ingest pipelines are set up automatically the first time you run the
module and connect to {es}.

[TIP]
=====
A connection to {es} (or {ess}) is required to set up the initial
environment. If you're using a different output, such as {ls}, see:

* {filebeat-ref}/filebeat-template.html#load-template-manually[Load the index template manually]
* {filebeat-ref}/load-kibana-dashboards.html[Load {kib} dashboards]
* {filebeat-ref}/load-ingest-pipelines.html[Load ingest pipelines]
=====

[discrete]
[[start-filebeat]]
== Step 5: Start {beatname_uc}

Before starting {beatname_uc}, modify the user credentials in
`filebeat.yml` and specify a user who is
{filebeat-ref}/privileges-to-publish-events.html[authorized to publish events].

To start {beatname_uc}, run:

// tag::start-step[]
:requires-sudo:
include::{beats-repo-dir}/tab-widgets/start-widget.asciidoc[]
:requires-sudo!:
// end::start-step[]

{beatname_uc} should begin streaming events to {es}.

[discrete]
[[view-logs-kibana]]
== Step 6: Confirm logs are streaming

Let's confirm your data is correctly streaming to your cloud instance.

. Launch {kib}:
+
--
include::{beats-repo-dir}/tab-widgets/open-kibana-widget.asciidoc[]
--

. Open the main menu, then click *Discover*.
+
. Select `filebeat-*` as your {data-source}.
+
Each document in the index that matches the `filebeat-*` {data-source}
is displayed. By default, *Discover* shows data for the last 15 minutes.  If you have
a time-based index, and no data displays, you might need to increase the time range.
+
You can now search your log messages, filter your search results, add or remove fields,
examine the document contents in either table or JSON format, and view a document in context.

Now let's have a look at the <<monitor-logs,{logs-app}>>.

:!beatname_uc:
:!beatname_lc:
:!beatname_pkg:
:!modulename:
:!has_modules_command:
