[chapter, role="xpack"]
[[instrument-apps]]
= Instrument applications with APM

++++
<titleabbrev>Instrument applications</titleabbrev>
++++

Elastic APM monitors software services and applications in real time, collects unhandled
errors and exceptions, and automatically picks up basic host-level metrics and agent specific metrics.

[NOTE]
=====
If you haven’t already, you need to install {es} for storing and searching your data, {kib} for
visualizing and managing it, and APM Server. For more information, see <<spin-up-stack>>.
=====

[discrete]
[[install-apm-agents]]
== Step 1: Install APM agents

--
include::{apm-repo-dir}/legacy/tab-widgets/install-agents-widget.asciidoc[]
--

[discrete]
[[configuring-apm]]
== Step 2: Configure APM

[[configure-apm-data]]
Now that you're up and running with Elastic APM, you may want to adjust some configuration settings.
Luckily, there are many different ways to tweak and tune the Elastic ecosystem to adapt it to your needs.

[[configure-apm-agents]]
*Configure APM Agents*

--
include::{apm-repo-dir}/legacy/tab-widgets/configure-agent-widget.asciidoc[]
--

[[configure-elastic-cloud]]
*Configure APM Server*

--
include::{apm-repo-dir}/legacy/tab-widgets/configure-server-widget.asciidoc[]
--

[discrete]
[[view-apm-data]]
== Step 3: View your data in {kib}

To view the <<observability-ui,{observability} Overview>> page:

. Launch {kib}:
+
--
include::{beats-repo-dir}/tab-widgets/open-kibana-widget.asciidoc[]
--

. In the side navigation, select *{observability}*, and click *Overview*.

:!beatname_uc:
:!beatname_lc:
