[[logs-checklist]]
= Logs resource guide

++++
<titleabbrev>Resource guide</titleabbrev>
++++

In this guide, you'll find resources on sending log data to {es}, configuring your logs, and analyzing your logs.

[discrete]
[[logs-getting-started-checklist]]
== Get started with logs

If you're new to ingesting, viewing, and analyzing logs with Elastic, see <<logs-metrics-get-started, Get started with logs and metrics>> for an overview of adding integrations, installing and running an {agent}, and monitoring logs.

[discrete]
[[logs-send-data-checklist]]
== Send logs data to {es}

You can send logs data to {es} in different ways depending on your needs:

- {agent}
- {filebeat}

When choosing between {agent} and {beats}, consider the different features and functionalities between the two options.
See {fleet-guide}/beats-agent-comparison.html[{agent} and {beats} capabilities] for more information on which option best fits your situation.

[discrete]
[[agent-ref-guide]]
=== {agent}
{agent} uses https://www.elastic.co/integrations/data-integrations[integrations] to ingest logs from Kubernetes, MySQL, and many more data sources.
You have the following options when installing and managing an {agent}:

* *{fleet}-managed {agent}*
+
Install an {agent} and use {fleet} in {kib} to define, configure, and manage your agents in a central location.
+
See {fleet-guide}/install-fleet-managed-elastic-agent.html[install {fleet}-managed {agent}].

* *Standalone {agent}*
+
Install an {agent} and manually configure it locally on the system where it’s installed.
You are responsible for managing and upgrading the agents.
This approach is reserved for advanced users only.
+
See {fleet-guide}/install-standalone-elastic-agent.html[install standalone {agent}].

* *{agent} in a containerized environment*
+
Run an {agent} inside of a container -- either with {fleet-server} or standalone.
+
See {fleet-guide}/install-elastic-agents-in-containers.html[install {agent} in containers].

[discrete]
[[beats-ref-guide]]
=== {filebeat}
{filebeat} is a lightweight shipper for forwarding and centralizing log data.
Installed as a service on your servers, {filebeat} monitors the log files or locations that you specify, collects log events, and forwards them
either to https://www.elastic.co/products/elasticsearch[Elasticsearch] or
https://www.elastic.co/products/logstash[Logstash] for indexing.

- {filebeat-ref}/filebeat-overview.html[{filebeat} overview] – general information on {filebeat} and how it works.
- {filebeat-ref}/filebeat-installation-configuration.html[{filebeat} quick start] – basic installation instructions to get you started.
- {filebeat-ref}/setting-up-and-running.html[Set up and run {filebeat}] – information on how to install, set up, and run {filebeat}.

[discrete]
[[logs-configure-data-checklist]]
== Configure logs

The following resources provide information on configuring your logs:

- {ref}/data-streams.html[Data streams] – Efficiently store append-only time series data in multiple backing indices partitioned by time and size.
- {kibana-ref}/data-views.html[Data views] – Query log entries from the data streams of specific datasets or namespaces.
- {ref}/example-using-index-lifecycle-policy.html[Index lifecycle management] – Configure the built-in logs policy based on your application's performance, resilience, and retention requirements.
- {ref}/ingest.html[Ingest pipeline] – Parse and transform log entries into a suitable format before indexing.
- {ref}/mapping.html[Mapping] – define how data is stored and indexed.

[discrete]
[[logs-monitor-checklist]]
== View and monitor logs

With the {logs-app} in {kib} you can search, filter, and tail all your logs ingested into {es} in one place.

The following resources provide information on viewing and monitoring your logs:

- <<tail-logs>> – monitor all of the log events flowing in from your servers, virtual machines, and containers in a centralized view.
- <<inspect-log-anomalies>> use {ml} to detect log anomalies automatically.
- <<categorize-logs>> – use {ml} to categorize log messages to quickly identify patterns in your log events.
- <<configure-data-sources>> – Specify the source configuration for logs in the Logs app settings in the Kibana configuration file.

[discrete]
[[logs-app-checklist]]
== Application logs

Application logs provide valuable insight into events that have occurred within your services and applications.
See <<logs-stream-application>>.

[discrete]
[[logs-alerts-checklist]]
== Create a logs threshold alert

You can create a rule to send an alert when the log aggregation exceeds a threshold.
See <<logs-threshold-alert>>.