[[logs-observability-overview]]
= Logs overview

++++
<titleabbrev>Logs</titleabbrev>
++++

Elastic Observability allows you to deploy and manage logs at a petabyte scale, giving you insights into your logs in minutes. You can also search across your logs in one place, troubleshoot in real-time, and detect patterns and outliers with categorization and anomaly detection. For more information, refer to the following links:

- <<logs-checklist, Logs resource guide>> – See an overview on sending log data, configuring logs, and analyzing logs.
- <<logs-stream>> – Send log files to {es} using a standalone {agent}.
- <<logs-parse>> – Parse your log data and extract structured fields then use those structured fields to filter and analyze your logs.
- <<logs-filter>> – Filter and aggregate your log data to find specific information, gain insight, and monitor your systems more efficiently.
- <<monitor-logs>> – Find information on visualizing and analyzing logs in {kib}.
- <<logs-troubleshooting>> – Find solutions for errors you might encounter while onboarding your logs.