[[logs-troubleshooting]]
= Troubleshoot your logs

This section provides solutions to errors you might encounter while onboarding your logs.

[discrete]
[[logs-troubleshooting-insufficient-priv]]
== User does not have permissions to create API key

If you don't have the required privileges to create an API key, you'll see the following error message:

[source, plaintext]
----
User does not have permissions to create API key.

Required cluster privileges are [`monitor`, `manage_own_api_key`] and 
required index privileges are [`auto_configure`, `create_doc`] for 
indices [`logs-*-*`, `metrics-*-*`], please add all required privileges 
to the role of the authenticated user.
----

[discrete]
[[logs-troubleshooting-insufficient-priv-solution]]
=== Solution

You need to either:

* Get the necessary privileges listed in the error messages from an administrator, and restart the onboarding flow.
* Get an API key from an administrator and manually add the API to the {agent} configuration. See <<logs-stream-agent-config, Configure the {agent}>> for more on manually updating the configuration and adding the API.

[discrete]
[[logs-troubleshooting-API-key-failed]]
== Failed to create API key

If you don't have the privileges to create `savedObjects` in {kib}, you'll see the following error message:

[source, plaintext]
----
Failed to create API key

Something went wrong: Unable to create observability-onboarding-state
----

[discrete]
[[logs-troubleshooting-API-key-failed-solution]]
=== Solution

You need an administrator to give you privileges to create `savedObjects` in {kib} to generate the required `observabilityOnboarding` flow state.
Once you have necessary privileges, restart the onboarding flow.

[discrete]
[[logs-troubleshooting-kib-not-accessible]]
== {kib} not accessible from host

If {kib} is not accessible from the host, you'll see the following error message after pasting the *Install the {agent}* instructions into your host:

[source, plaintext]
----
New integrated terminal

To set your external terminal as the default, change your preferences.
----

[discrete]
[[logs-troubleshooting-kib-not-accessible-solution]]
=== Solution

The host needs access to {Kib}. If that's not possible, you can manually download and configure the {agent}. See the <<logs-stream, Stream a log file>> documentation for more information.

[discrete]
[[logs-troubleshooting-download-agent]]
== Download {agent} failed

If the host was able to download the installation script but cannot connect to the public artifactory repository, you'll see the following error message:

[source, plaintext]
----
Download Elastic Agent

Failed to download Elastic Agent, see script for error.
----

[discrete]
[[logs-troubleshooting-download-agent-solution]]
=== Solutions

* Agent version and OS architecture is not available:
+
The combination of {agent} version and OS architecture is not available. If this is the case you'll see the following error message on your host:
+
[source, plaintext]
----
New integrated terminal

To set your external terminal as the default, change your preferences.
----
+
To fix this, modify the {agent} version in the installation instructions to a known version of the {agent}.
* You're an Elastic Cloud Enterprise user without access to the Elastic downloads page.
* The {agent} was fully downloaded previously. In this case, delete previous downloads and restart the onboarding.

[discrete]
[[logs-troubleshooting-install-agent]]
== Install {agent} failed

If an {agent} already exists on your host, you'll see the following error message:

[source, plaintext]
----
Install Elastic Agent

Failed to install Elastic Agent, see script for error.
----

[discrete]
[[logs-troubleshooting-install-agent-solution]]
=== Solution
You can uninstall the current {agent} using the `elastic-agent uninstall` command, and run the script again.

WARNING: Uninstalling the current {agent} removes the entire current setup including the existing configuration. 

[discrete]
[[logs-troubleshooting-wait-for-logs]]
== Waiting for Logs to be shipped... step never completes

If the *Waiting for Logs to be shipped...* step never completes, logs are not being shipped to {es}, and there is most likely an issue with your {agent} configuration. 

[discrete]
[[logs-troubleshooting-wait-for-logs-solution]]
=== Solution

See the {fleet-guide}/debug-standalone-agents.html#inspect-standalone-agent-logs[Debug standalone {agent}s] documentation for information on checking {agent} logs to look for errors.