[[manage-cases]]
= Open and manage new cases

[discrete]
[[new-case-observability]]
== Open a new case

Open a new case to keep track of issues and share the details with colleagues.

. Go to *Cases* -> *Create new case*.
. Give the case a name, add any identifying tags, and enter a description.
+
TIP: In the `Description` area, you can use
https://www.markdownguide.org/cheat-sheet[Markdown] syntax to create formatted text.

. Under External incident management system, select a <<cases-external-connectors,connector>>. If
you’ve previously added one, that connector displays as the default selection. Otherwise, the
default setting is `No connector selected`.
. After you’ve completed all of the required fields, click *Create case*.

[discrete]
[[manage-case-observability]]
== Manage existing cases

You can search existing cases and filter them by tags, reporter, and status: *open*, *in-progress*, or *closed*.

To view a case, click on its name. You can then:

* Add a new comment.
* Edit existing comments and the description.
* Add a <<cases-external-connectors,connector>> (if you did not select one while creating the case).
* Send updates to external systems (if external connections are configured).
* Close the case.
* Reopen a closed case.
* Edit tags.
* Refresh the case to retrieve the latest updates.