[[manage-cases]]
= Open and manage new cases

[discrete]
[[new-case-observability]]
== Open a new case

Open a new case to keep track of issues and share the details with colleagues.

. Go to *Cases* -> *Create new case*.
. Give the case a name, severity, and description.
+
TIP: In the `Description` area, you can use
https://www.markdownguide.org/cheat-sheet[Markdown] syntax to create formatted text.

. Optionally, add assignees and tags. You can add users only if they meet the
necessary <<grant-cases-access,prerequisites>>.

. Under External incident management system, select a <<cases-external-connectors,connector>>. If
you've previously added one, that connector displays as the default selection. Otherwise, the
default setting is `No connector selected`.
. After you've completed all of the required fields, click *Create case*.

[discrete]
[[manage-case-observability]]
== Manage existing cases

You can search existing cases and filter them by attributes such as assignees,
severity, status, and tags. You can also select multiple cases and use bulk
actions to delete cases or change their attributes.

To view a case, click on its name. You can then:

* Add a new comment.
* Edit existing comments and the description.
* Add or remove assignees.
* Add a <<cases-external-connectors,connector>> (if you did not select one while creating the case).
* Send updates to external systems (if external connections are configured).
* Edit tags.
* Change the status.
* Change the severity.
* Remove an alert.
* Refresh the case to retrieve the latest updates.
* Close the case.
* Reopen a closed case.
