[[monitor-docker]]
= Monitor Docker containers

[NOTE]
=====
If you haven't already, you need to install {metricbeat} and enable the
{metricbeat-ref}/metricbeat-module-docker.html[Docker module] to ingest metrics
from your running Docker containers. For more information,
see <<enable-metrics-modules,Enable modules>>.
=====

To help you analyze the Docker container metrics listed on the *Inventory* page, you can select
view filters based on the following predefined metrics or you can add <<custom-metrics,custom metrics>>.

|=== 

| *CPU Usage* | Average of `docker.cpu.total.pct`. 

| *Memory Usage* | Average of `docker.memory.usage.pct`.

| *Inbound Traffic* | Derivative of the maximum of `docker.network.in.bytes` scaled to a 1 second rate.

| *Outbound Traffic* | Derivative of the maximum of `docker.network.out.bytes` scaled to a 1 second rate.

|=== 

For information about which required fields the {metrics-app} uses to display Docker container metrics, see the
<<metrics-app-fields,Metrics field reference>>.