[[kubernetes-pod-metrics]]
= Kubernetes pod metrics

[NOTE]
=====
If you haven't already, please install and configure {metricbeat} to populate
the {metrics-app} with data. For more information, see <<ingest-metrics,Ingest metrics>>.
=====

To ingest metrics from running Kubernetes pods, {metricbeat} needs to run as a
DaemonSet to monitor multiple pods. For more information,
see {metricbeat-ref}/running-on-kubernetes.html[Running {metricbeat} on Kubernetes].

When monitoring Kubernetes pods, use autodiscovery to automatically change the configuration settings in response to changes in your pods.
Autodiscovery ensures that even when your pod configuration changes, metrics are still collected.
To learn how to do this, see {metricbeat-ref}/configuration-autodiscover.html[{metricbeat} autodiscover configuration].

To help you analyze the Kubernetes pod metrics listed on the *Inventory* page, you can select view filters based on the following
predefined metrics or you can add <<custom-metrics,custom metrics>>.

|=== 

| *CPU Usage* | Average of `kubernetes.pod.cpu.usage.node.pct`. 

| *Memory Usage* | Average of `kubernetes.pod.memory.usage.node.pct`.

| *Inbound Traffic* | Derivative of the maximum of `kubernetes.pod.network.rx.bytes` scaled to a 1 second rate.

| *Outbound Traffic* | Derivative of the maximum of `kubernetes.pod.network.tx.bytes` scaled to a 1 second rate.

|=== 

For information about which required fields the {metrics-app} uses to display Kubernetes pods metrics, see the
<<metrics-app-fields,Metrics field reference>>.
