[[monitor-servers]]
= Monitor servers

Host metrics are ingested using the {metricbeat} {metricbeat-ref}/metricbeat-module-system.html[system module],
which is enabled by default, and become available for analysis in the {metrics-app}.

To help you analyze the host metrics listed on the *Inventory* page, you can select view filters based on the following
predefined metrics or you can add <<custom-metrics,custom metrics>>.

|=== 

| *CPU Usage* | Average of `system.cpu.user.pct` added to the average of `system.cpu.system.pct` divided by `system.cpu.cores`. 

| *Memory Usage* | Average of `system.memory.actual.used.pct`.

| *Load* | Average of `system.load.5`.

| *Inbound Traffic* | Derivative of the maximum of `system.network.in.bytes` scaled to a 1 second rate.

| *Outbound Traffic* | Derivative of the maximum of `system.network.out.bytes` scaled to a 1 second rate.

| *Log Rate* | Derivative of the cumulative sum of the document count scaled to a 1 second rate.
This metric relies on the same indices as the logs.

|=== 

For information about which required fields the {metrics-app} uses to display host metrics, see the
<<metrics-app-fields,Metrics field reference>>.
