[[observability-get-started]]
= Get started with Elastic Observability

++++
<titleabbrev>Get started</titleabbrev>
++++

Learn how to spin up a deployment of our hosted {ess} and use Elastic
Observability to gain deeper insight into the behavior of your applications and
systems.

The guides in this section describe how to:

image::images/get-started.svg[]

1. **Choose your source.** Elastic integrates with hundreds of data sources for
unified visibility across all your applications and systems.

2. **Ingest your data.** Turn-key integrations provide a repeatable workflow to
ingest data from all your sources: you install an integration, configure it, and
deploy an agent to collect your data.

3. **View your data.** Navigate seamlessly between Observabilty UIs and
dashboards to identify and resolve problems quickly.

4. **Customize.** Expand your deployment and add features like alerting and anomaly
detection.

[discrete]
== Get started now

Follow the steps in these guides to get started:

* <<logs-metrics-get-started,Get started with logs and metrics>>
* <<traces-get-started,Get started with application traces and APM>>
* <<splunk-get-started,Get started with data from Splunk>>

[discrete]
== Additional guides

Ready to dig into more features of Elastic Observability? See these guides:

* <<monitor-uptime-synthetics,Get started with synthetic monitoring>>
* <<profiling-get-started,Get started with Universal Profiling>>
* <<create-alerts,Create an alert>>
* <<slo-create,Create a service-level objective (SLO)>>

[discrete]
== Related content

* {estc-welcome}/index.html[Starting with the {es} Platform and its Solutions] for new users
* {cloud}/ec-cloud-ingest-data.html[Adding data to {es}] for other ways to
ingest data
* <<observability-tutorials>> for hands-on steps
