[[observability-get-started]]
= Get started with Elastic Observability

++++
<titleabbrev>Get started</titleabbrev>
++++

New to Elastic {observability}? Discover more about our observability features and how to get started.

[discrete]
== Learn about Elastic {observability}

Learn about key features available to help you get value from your observability data:

* <<observability-introduction>>
* <<whats-new>>

[discrete]
[[get-started-with-use-case]]
== Get started with your use case

Learn how to spin up a deployment of our hosted {ess} and use Elastic
Observability to gain deeper insight into the behavior of your applications and
systems.

image::images/get-started.svg[]

1. **Choose your source.** Elastic integrates with hundreds of data sources for
unified visibility across all your applications and systems.

2. **Ingest your data.** Turn-key integrations provide a repeatable workflow to
ingest data from all your sources: you install an integration, configure it, and
deploy an agent to collect your data.

3. **View your data.** Navigate seamlessly between Observabilty UIs and
dashboards to identify and resolve problems quickly.

4. **Customize.** Expand your deployment and add features like alerting and anomaly
detection.

[discrete]
[[quickstarts-overview]]
=== Quickstarts

Our quickstarts dramatically reduce your time-to-value by offering a fast path to ingest and visualize your Observability data.
Each quickstart provides:

* A highly opinionated, fast path to data ingestion
* Sensible configuration defaults with minimal configuration required
* Auto-detection of logs and metrics for monitoring hosts
* Quick access to related dashboards and visualizations

Follow the steps in these guides to get started quickly:

* <<quickstart-monitor-hosts-with-elastic-agent>>
* <<monitor-k8s-logs-metrics-with-elastic-agent>>
* <<monitor-k8s-otel-edot>>
* <<collect-data-with-aws-firehose>>

[discrete]
=== Get started with other features

Want to use {fleet} or some other feature not covered in the quickstarts?
Follow the steps in these guides to get started:

* <<logs-metrics-get-started,Get started with system metrics>>
* <<get-started-with-fleet-apm-server,Get started with application traces and APM>>
* <<monitor-uptime-synthetics,Get started with synthetic monitoring>>
* <<profiling-get-started,Get started with Universal Profiling>>

[discrete]
== Additional guides

Ready to dig into more features of Elastic Observability? See these guides:

* <<create-alerts,Create an alert>>
* <<slo-create,Create a service-level objective (SLO)>>

[discrete]
== Related content

* {estc-welcome}/index.html[Starting with the {es} Platform and its Solutions] for new users
* {cloud}/ec-cloud-ingest-data.html[Adding data to {es}] for other ways to
ingest data
