[[profiling-upgrade]]
= Upgrade Universal Profiling

++++
<titleabbrev>Upgrade</titleabbrev>
++++

beta::[]

Universal Profiling is a beta program, and we are developing and iterating over it frequently upon receiving feedback.
For this reason, you have to erase *all existing profiling data* from your deployment when upgrading between minor releases in the {stack}.
When the product hits general availability, we will remove this requirement.

[discrete]
[[profiling-upgrade-process]]
== Upgrade process

To upgrade Universal Profiling, you need to:

. Perform a stack upgrade in {ecloud}
. Stop profiling data ingestion
. Delete existing profiling data
. Setup Universal Profiling from scratch
. Start profiling data ingestion

[discrete]
[[profiling-upgrade-in-cloud]]
=== Perform a stack upgrade in the {ecloud} console

To perform a stack upgrade in {ecloud}:

. Locate the deployment you wish to upgrade in https://cloud.elastic.co[{ecloud}].
. Click the *Manage deployment* icon next to your deployment to open the deployment settings.
. Find *Deployment version* on the right side of the page.
. Click *Upgrade*, and choose the desired version.
. Verify the upgrade was successful under **Your deployment → Activity** in the navigation menu.

[discrete]
[[profiling-stop-ingestion]]
=== Stop profiling data ingestion

During the Universal Profiling upgrade, you must stop data ingestion.

If you have an automated host-agent setup and control of the *full* fleet of machines where the host-agent is installed, deleting
all host-agent deployments stops ingestion.

If you do not have direct control of all host-agent deployments, you can stop data ingestion by stopping incoming requests to the
Integrations Server. To do this:

. From the deployment settings, scroll down to the *Instances* section and locate all Integrations Server instances.
. Click the three vertical dots in the upper-right corner of the Integrations Server card.
. Select *Stop routing requests*.
. Repeat this process for all Integrations Server instances.

NOTE: When stopping incoming requests, host-agent replicas back off and retry connecting to the {ecloud} endpoint at increasing time intervals.

[discrete]
[[profiling-delete-data]]
=== Delete existing profiling data

You can delete existing profiling data in Kibana:

. From the navigation menu, go to *Stack Management → Index Management*.
. Make sure you're in the *Indices* tab, and search for `profiling-` in the search bar.
. Select all resulting indices, click the *Manage indices* button, and select Delete indices* from the drop-down menu.
. Switch to the *Data Streams* tab, and  search for `profiling-` in the search bar.
. Select all resulting data streams, and click the *Delete data streams* button.

Verify that no ingestion is happening by reloading the *Indices* and *Data Streams* pages and ensuring that there are no indices or data streams with the `profiling-` prefix.

[discrete]
[[profiling-from-scratch]]
=== Set up Universal Profiling from scratch

Refer to <<profiling-get-started>> to set up Universal Profiling from scratch.


[discrete]
[[profiling-start-data-ingestion]]
=== Start profiling data ingestion

If you stopped ingesting data by stopping routing requests to the Integrations Server, reenable traffic following the same steps but click **Start routing requests** instead of **Stop routing requests**.

[discrete]
[[profiling-verify-upgrade-success]]
=== Verify the update succeeds

Click any subheadings under Universal Profiling in the navigation menu. You should see incoming data.

If you see instructions on how to deploy the host-agent like in the <<profiling-install-host-agent,examples>> from the <<profiling-get-started,Get Started>> documentation, the agents did not reconnect to the Integrations Server replicas.

Refer to the <<profiling-troubleshooting,troubleshooting>> documentation and the <<profiling-get-started,Get Started>> documentation to investigate the issue.
