[[profiling-upgrade]]
= Upgrade Universal Profiling

++++
<titleabbrev>Upgrade</titleabbrev>
++++

This section is specific to upgrading Universal Profiling on {ecloud} or {ece}.

For self-hosted installations, refer to <<profiling-self-managed-upgrade,Upgrade Universal Profiling in self-hosted installations>>.

[discrete]
[[profiling-upgrade-process]]
== Upgrade process

To upgrade from all versions earlier than 8.10 (GA), you need to:

. Perform a stack upgrade in {ecloud}
. Stop profiling data ingestion
. Delete existing profiling data
. Setup Universal Profiling from scratch
. Start profiling data ingestion

To upgrade from version 8.10 or later, you need to:

. Perform a stack upgrade in {ecloud}

[discrete]
[[profiling-upgrade-in-cloud]]
=== Perform a stack upgrade in the {ecloud} console

To perform a stack upgrade in {ecloud}:

. Locate the deployment you wish to upgrade in https://cloud.elastic.co[{ecloud}].
. Click the *Manage deployment* icon next to your deployment to open the deployment settings.
. Find *Deployment version* on the right side of the page.
. Click *Upgrade*, and choose the desired version.
. Verify the upgrade was successful under **Your deployment → Activity** in the navigation menu.

[discrete]
[[profiling-stop-ingestion]]
=== Stop profiling data ingestion

During the Universal Profiling upgrade, you must stop data ingestion.

If you have an automated Universal Profiling Agent setup and control of the *full* fleet of machines where the Universal Profiling Agent is installed, deleting
all Universal Profiling Agent deployments stops ingestion.

If you do not have direct control of all Universal Profiling Agent deployments, you can stop data ingestion by stopping incoming requests to the
Integrations Server. To do this:

. From the deployment settings, scroll down to the *Instances* section and locate all Integrations Server instances.
. Click the three vertical dots in the upper-right corner of the Integrations Server card.
. Select *Stop routing requests*.
. Repeat this process for all Integrations Server instances.

NOTE: When stopping incoming requests, Universal Profiling Agent replicas back off and retry connecting to the {ecloud} endpoint at increasing time intervals.

[discrete]
[[profiling-delete-data]]
=== Delete existing profiling data

You can delete existing profiling data in Kibana:

. If you're upgrading from 8.9.0 or later, go to *Dev Tools* from the navigation menu, and execute the following snippet. If you're upgrading from an earlier version, skip this step.
+
[source,console]
----
PUT /_cluster/settings
{
  "persistent": {
    "xpack.profiling.templates.enabled": false
  }
}
----
. From the navigation menu, go to *Stack Management → Index Management*.
. Make sure you're in the *Data Streams* tab, and search for `profiling-` in the search bar.
. Select all resulting data streams, and click the *Delete data streams* button.
. Switch to the *Indices* tab, enable *Include hidden indices*, and  search for `profiling-` in the search bar.
. Select all resulting indices, click the *Manage indices* button, and select *Delete indices* from the drop-down menu.
. Switch to the *Index Templates* tab, and  search for `profiling-` in the search bar.
. Select all resulting index templates, and click the *Delete templates* button.
. Switch to the *Component Templates* tab, and  search for `profiling-` in the search bar.
. Select all resulting component templates, and click the *Delete component templates* button.
. From the navigation menu, go to *Index Lifecycle Policies*, search for `profiling` in the search bar, and click the trash icon in the *Actions* column.


Verify that no ingestion is happening by reloading the *Data Streams* and *Indices* pages and ensuring that there are no data streams or indices with the `profiling-` prefix.

[discrete]
[[profiling-from-scratch]]
=== Set up Universal Profiling from scratch

Refer to <<profiling-configure-data-ingestion>> to set up Universal Profiling from scratch.



[discrete]
[[profiling-start-data-ingestion]]
=== Start profiling data ingestion

If you stopped ingesting data by stopping routing requests to the Integrations Server, re-enable traffic following the same steps but click **Start routing requests** instead of **Stop routing requests**.

[discrete]
[[profiling-verify-upgrade-success]]
=== Verify the update succeeds

Click any subheadings under Universal Profiling in the navigation menu. You should see incoming data.

If you see instructions on how to deploy the Universal Profiling Agent like in the <<profiling-install-profiling-agent,examples>> from the <<profiling-get-started,Get Started>> documentation, the agents did not reconnect to the Integrations Server replicas.

Refer to the <<profiling-troubleshooting,troubleshooting>> documentation and the <<profiling-get-started,Get Started>> documentation to investigate the issue.
