[[profiling-advanced-configuration]]
= Advanced configuration

After completing the steps in the <<profiling-get-started, Get started>> documentation, you may need to continue to more advanced configuration for your deployment.
See the following sections for more information:

* <<profiling-tag-data-query, Tag data for querying>>: Tag data collected by the Universal Profiling Agent into multiple logical groups so they can be queried in Kibana.
* <<profiling-add-symbols, Add symbols for native frames>>: Push symbols to your cluster so you can see function names and line numbers in traces of applications written in programming languages that compile to native code (C, C++, Rust, Go, etc.).
* <<profiling-use-a-proxy,Use a proxy>>:  Set up an HTTP proxy if your infrastructure Universal Profiling Agent installation needs one to reach {ecloud}.
* <<profiling-no-kernel-version-check, Override kernel version check >>: Configure the Universal Profiling Agent to bypass the kernel version compatibility check.
* <<profiling-envs, Environment variables for the Universal Profiling Agent >>: Configure the Universal Profiling Agent using environment.
