["appendix",role="exclude",id="redirects"]
= Deleted pages

The following pages have moved or been deleted.

//Start links removed in Spacetime revamp (https://github.com/elastic/observability-docs/pull/2880)

[role="exclude",id="spin-up-stack"]
=== Spin up the {stack}

This page no longer exists in the Observability Guide. To learn how to sign up
for an {ess} trial, refer to our {ess-trial}[{es} Service Trial] page. To learn
how to install the {stack} on your own hardware, refer to
{stack-ref}/installing-elastic-stack.html[Installing the {stack}].

[role="exclude",id="deploy-beats-to-send-data"]
=== Deploy {beats} to send data

This page no longer exists in the Observability Guide. To learn how to deploy
{beats}, refer to the {beats-ref}/getting-started.html[Beats getting started documentation].

[role="exclude",id="ingest-logs"]
=== Ingest logs with {filebeat}

This page no longer exists in the Observability Guide. To learn how to deploy
{filebeat}, refer to the
{filebeat-ref}/filebeat-installation-configuration.html[{filebeat} quick start guide].

[role="exclude",id="ingest-metrics"]
=== Ingest metrics with {metricbeat}

This page no longer exists in the Observability Guide. To learn how to deploy
{metricbeat}, refer to the
{metricbeat-ref}/metricbeat-installation-configuration.html[{metricbeat} quick start guide].

[role="exclude",id="ingest-uptime"]
=== Ingest uptime data with {heartbeat}

This page no longer exists in the Observability Guide. To learn how to deploy
{heartbeat}, refer to the
{heartbeat-ref}/heartbeat-installation-configuration.html[{heartbeat} quick start guide].

[role="exclude",id="instrument-apps"]
=== Instrument applications with APM

This page no longer exists in the Observability Guide. To learn how to
instrument applications with APM, refer to
{observability-guide}/apm-getting-started-apm-server.html[Getting started with APM Server].

//End links removed in Spactime revamp (https://github.com/elastic/observability-docs/pull/2880)

[role="exclude",id="aws-elastic-serverless-forwarder"]
=== Elastic Serverless Forwarder for AWS

This page no longer exists in the Observability Guide.
Refer to {esf-ref}/aws-elastic-serverless-forwarder.html[Elastic Serverless Forwarder for AWS].

[role="exclude",id="aws-deploy-elastic-serverless-forwarder"]
=== Deploy Elastic Serverless Forwarder

This page no longer exists in the Observability Guide.
Refer to {esf-ref}/aws-deploy-elastic-serverless-forwarder.html[Deploy Elastic Serverless Forwarder].

[role="exclude",id="aws-elastic-serverless-forwarder-configuration"]
=== Configuration options for Elastic Serverless Forwarder

This page no longer exists in the Observability Guide.
Refer to {esf-ref}/aws-elastic-serverless-forwarder-configuration.html[Configuration options for Elastic Serverless Forwarder].

[role="exclude",id="aws-serverless-troubleshooting"]
=== Troubleshooting and error handling

This page no longer exists in the Observability Guide.
Refer to {esf-ref}/aws-serverless-troubleshooting.html[Troubleshooting and error handling].

[role="exclude",id="synthetic-monitoring-visualizations"]
=== Synthetic monitoring visualizations

Refer to <<exploratory-data-visualizations,Explore data>>.

[role="exclude",id="user-experience-visualizations"]
=== {user-experience} visualizations

Refer to <<exploratory-data-visualizations,Explore data>>.


[role="exclude",id="monitor-uptime"]
=== Lightweight synthetic monitoring

Refer to <<monitoring-uptime>>.

[role="exclude",id="synthetics-quickstart"]
=== Synthetic monitoring using Docker

Refer to <<synthetics-get-started>>.

[role="exclude",id="synthetics-quickstart-fleet"]
=== Synthetic monitoring using {agent} and {fleet}

Refer to <<synthetics-get-started>>.

[role="exclude" id="synthetic-monitoring"]
=== Real browser synthetic monitoring

Refer to <<monitoring-synthetics>>.

[role="exclude" id="uptime-set-up"]
=== Use lightweight monitors

Refer to <<synthetics-get-started>>.

[role="exclude" id="uptime-set-up-choose-heartbeat"]
=== Use lightweight monitors with {heartbeat}

Refer to <<uptime-get-started>>.

[role="exclude" id="synthetics-get-started-heartbeat"]
=== Create monitors with {heartbeat}

Refer to <<uptime-get-started>>.

[role="exclude" id="uptime-set-up-choose-agent"]
=== Use lightweight monitors with the {uptime-app}

Refer to <<synthetics-get-started-ui>>.

[role="exclude" id="uptime-set-up-choose-project-monitors"]
=== Use lightweight monitors with project monitors

Refer to <<synthetics-get-started-project>>.

[role="exclude" id="synthetic-run-tests"]
=== Create browser monitors

[[synthetic-monitor-choose-project]]

Refer to <<synthetics-get-started-project>>.

[role="exclude" id="synthetics-visualize"]
=== Visualize journeys

Refer to <<synthetics-analyze-journeys>>.

[role="exclude" id="ingest-traces"]
=== Ingest application traces with {agent}

Refer to <<traces-get-started>>.

[role="exclude" id="threshold-alert"]
=== Create a threshold rule

Refer to <<custom-threshold-alert>>.

[role="exclude" id="logs-observability-overview"]
=== Logs Overview

For an overview of ingesting and viewing logs in {observability}, refer to <<logs-checklist>>.

[role="exclude",id="apm-mutating-admission-webhook"]
==== APM Attacher

This page has moved.
Please see <<apm-k8s-attacher>>.
