["appendix",role="exclude",id="redirects"]
= Deleted pages

The following pages have moved or been deleted.

[role="exclude",id="add-observability-data"]
=== Send data to {es}

Refer to <<observability-get-started>>.

[role="exclude",id="spin-up-stack"]
=== Spin up the {stack}

This page no longer exists in the Observability Guide. To learn how to sign up
for an {ess} trial, refer to our {ess-trial}[{es} Service Trial] page. To learn
how to install the {stack} on your own hardware, refer to
{stack-ref}/installing-elastic-stack.html[Installing the {stack}].

[role="exclude",id="deploy-agent-to-send-data"]
=== Deploy {agent} to send data

Refer to <<observability-get-started>>.

[role="exclude",id="deploy-beats-to-send-data"]
=== Deploy {beats} to send data

This page no longer exists in the Observability Guide. To learn how to deploy
{beats}, refer to the {beats-ref}/getting-started.html[Beats getting started documentation].

[role="exclude",id="ingest-logs"]
=== Ingest logs with {filebeat}

This page no longer exists in the Observability Guide. To learn how to deploy
{filebeat}, refer to the
{filebeat-ref}/filebeat-installation-configuration.html[{filebeat} quick start guide].

[role="exclude",id="ingest-metrics"]
=== Ingest metrics with {metricbeat}

This page no longer exists in the Observability Guide. To learn how to deploy
{metricbeat}, refer to the
{metricbeat-ref}/metricbeat-installation-configuration.html[{metricbeat} quick start guide].

[role="exclude",id="ingest-uptime"]
=== Ingest uptime data with {heartbeat}

This page no longer exists in the Observability Guide. To learn how to deploy
{heartbeat}, refer to the
{heartbeat-ref}/metricbeat-installation-configuration.html[{heartbeat} quick start guide].

[role="exclude",id="instrument-apps"]
=== Instrument applications with APM

This page no longer exists in the Observability Guide. To learn how to
instrument applications with APM, refer to
//TODO: ADD LINK HERE

[role="exclude",id="ingest-logs-metrics-uptime"]
=== Ingest logs and metrics with {agent}

Refer to <<logs-metrics-get-started>>.

[role="exclude",id="ingest-traces"]
=== Ingest application traces with {agent}

Refer to <<traces-apm-get-started>>.

[role="exclude",id="synthetic-monitoring-visualizations"]
=== Synthetic monitoring visualizations

Refer to <<exploratory-data-visualizations,Explore data>>.

[role="exclude",id="user-experience-visualizations"]
=== {user-experience} visualizations

Refer to <<exploratory-data-visualizations,Explore data>>.


[role="exclude",id="monitor-uptime"]
=== Lightweight synthetic monitoring

Refer to <<monitoring-uptime>>.

[role="exclude",id="synthetics-quickstart"]
=== Synthetic monitoring using Docker

Refer to <<synthetics-get-started>>.

[role="exclude",id="synthetics-quickstart-fleet"]
=== Synthetic monitoring using {agent} and {fleet}

Refer to <<synthetics-get-started>>.

[role="exclude" id="synthetic-monitoring"]
=== Real browser synthetic monitoring

Refer to <<monitoring-synthetics>>.

[role="exclude" id="uptime-set-up"]
=== Use lightweight monitors

Refer to <<synthetics-get-started>>.

[role="exclude" id="uptime-set-up-choose-heartbeat"]
=== Use lightweight monitors with {heartbeat}

Refer to <<uptime-get-started>>.

[role="exclude" id="synthetics-get-started-heartbeat"]
=== Create monitors with {heartbeat}

Refer to <<uptime-get-started>>.

[role="exclude" id="uptime-set-up-choose-agent"]
=== Use lightweight monitors with the {uptime-app}

Refer to <<synthetics-get-started-ui>>.

[role="exclude" id="uptime-set-up-choose-project-monitors"]
=== Use lightweight monitors with project monitors

Refer to <<synthetics-get-started-project>>.

[role="exclude" id="synthetic-run-tests"]
=== Create browser monitors

[[synthetic-monitor-choose-project]]

Refer to <<synthetics-get-started-project>>.

[role="exclude" id="synthetics-visualize"]
=== Visualize journeys

Refer to <<synthetics-analyze-journeys>>.
