[[slo]]
= Service-Level Objectives (SLOs) 

++++
<titleabbrev>SLOs (beta)</titleabbrev>
++++

beta::[]


SLOs allow you to set clear, measurable targets for your service performance, based on factors like availability, response times, error rates, and other key metrics. 
You can define SLOs based on different types of data sources, such as custom KQL queries and APM latency or availability data.

Once you've defined your SLOs, you can monitor them in real time, with detailed dashboards and alerts that help you quickly identify and troubleshoot any issues that may arise. 
You can also track your progress against your SLO targets over time, with a clear view of your error budgets and burn rates.

[discrete]
[[slo-important-terms]]
== Important terms
//Can we be more technical with some of these terms? Are there equations we could add? perhaps we could turn these into sections and add more examples.

[horizontal]
Service level indicator (SLI):: The measurement the performance of your service. Some examples would be measuring service latency or availability.
SLO::                           The target you set for your SLI. It specifies the level of performance you expect from your service over a period of time.
Error budget::                  The amount of time that your SLI can not meet the SLO target before it violates your SLO.
Burn rate::                     The rate at which your service consumes your error budget.

[discrete]
[[slo-in-elastic]]
== SLOs in Elastic

[discrete]
[[slo-overview-next-steps]]
== Next steps
See the following sections for more on using SLOs to monitor your services:
* <<slo-create, Create an SLO>>
* <<slo-burn-rate-alert, Create an SLO burn rate alert>>