[[slo-create]]
= Create an SLO 

To create and SLO, go to *Observability → SLOs*: 
* If you're creating your first SLO, you'll see an introductory page. Click the *Create SLO* button.
* If you have previously created SLOs, click the *Create new SLO* button in the upper-right corner of the SLO page.

To create an SLO, you need to:

. Define your service level indicator (SLI)
. Set your objectives
. Describe your SLO

[discrete]
[[define-sli]]
== Define your SLI
You can choose one of the following SLI types:
* *Custom KQL* — This indicator is based on any elasticsearch index or index pattern you have. You simply define two queries, one that yields the good events and one that yields the total events from your index.
* *APM latency* — This indicator is based on the APM data that we receive from your instrumented services. We need the service name and the latency threshold at a minimum, but you can also provide an environment, transaction type, transaction name and a custom filter on the APM metrics data. 
* *APM availability* — This indicator is based on the APM data that we receive from your instrumented services. We need the service name and the list of good status codes at a minimum, but you can also provide an environment, transaction type, transaction name and a custom filter on the APM metrics data. 

[discrete]
[[custom-kql-sli]]
=== Custom KQL
When defining a custom KQL SLI, you need to set the following fields:

* *Index* —
* *Timestamp field* —
* *Query filter* —
* *Good query* —
* *Total query* —

[discrete]
[[apm-latency-sli]]
=== APM latency
When defining an APM latency SLI, you need to set the following fields:

* *Service name* —
* *Service environment* —
* *Transaction type* —
* *Transaction name* —
* *Threshold* —
* *Query filter* —

[discrete]
[[apm-availability-sli]]
=== APM availability
When defining an APM availability SLI, you need to set the following fields:

* *Service name* —
* *Service environment* —
* *Transaction type* —
* *Transaction name* —
* *Good status codes* —
* *Query filter* —

[discrete]
[[set-slo]]
== Set your objectives
After defining your SLI, you need to set your objectives. 

[discrete]
[[slo-budgeting-method]]
=== Budgeting method

[discrete]
[[slo-time-window]]
=== Time window

[discrete]
[[slo-target]]
=== Target/SLO (%)

[discrete]
[[slo-describe]]
== Describe your SLO
After setting your objectives, give your SLO a name, a short description, and add any relevant tags.

[discrete]
[[slo-alert-checkbox]]
== SLO burn rate alert rule
When the *Create an SLO burn rate alert rule* checkbox is selected, the *Create rule* window will open immediately after you click the *Create SLO* button.
Here you can define your SLO burn rate alert rule. 
For more information, see <<slo-burn-rate-alert, Create an SLO burn rate rule>>.