[[slo-troubleshoot-slos]]
= Troubleshoot SLOs

++++
<titleabbrev>Troubleshoot SLOs</titleabbrev>
++++

// tag::slo-license[]
[IMPORTANT]
====
To create and manage SLOs, you need an {subscriptions}[appropriate license] and <<slo-privileges,SLO access>> must be configured.
====
// end::slo-license[]

This section provides solutions to common questions and problems,
and processing and performance guidance.

TBD (table of contents with links APM style?)

screenshot available: https://github.com/elastic/kibana/pull/181351

transforms troubleshooting doc: https://www.elastic.co/guide/en/elasticsearch/reference/current/transform-troubleshooting.html


explain a SLO rely on Transforms (at least on stateful).

- Help users to to make use of the warning page introduced in 8.15 about unhealthy transforms, and point to the transform troubleshooting docs (https://www.elastic.co/guide/en/elasticsearch/reference/current/transform-troubleshooting.html). We shouldn't focus much on transforms troubleshooting as it's not our domain.

- explain a SLO rely on Transforms and the cluster requires at least 1 node with the transform role

- explain a SLO rely on Ingest pipelines and the cluster requires at least 1 node with the ingest role

- explain SLO relies on some built-in transforms slo-summary* and those have not be deleted or stopped - and eventually document if they're auto-recreated (or how to do it)

associated issue: https://github.com/elastic/observability-docs/issues/4237



[discrete]
[[slo-and-transforms]]
== SLO and Transforms relation

Explain the relation between SLOs and transforms

[discrete]
[[slo-and-pipelines]]
== SLO and Ingest Pipelines

Explain the relation between SLOs and Ingest pipelines

[discrete]
[[transforms-troubleshoot]]
== Transforms troubleshooting

Introduction and link to the relevant doc about transforms.
