[[synthetics-support-matrix]]
= Synthetics component support

There are various components that make up the Synthetics solution, which are supported in the following configurations:

[discrete]
== {synthetics-app}

* *GA support*: 8.8.0 and higher
* *Notes*:
** For creating and managing lightweight and browser monitors configured through the <<synthetics-get-started-ui,{synthetics-app}>>
** For reporting for lightweight and browser monitors configured through the <<synthetics-get-started-ui,{synthetics-app}>> and/or <<synthetics-get-started-project,{project-monitors-cap}>>

[discrete]
== {project-monitors-cap}

* *GA support*: 8.8.0 and higher
* *Notes*: For creating and managing lightweight and browser monitors configured as <<synthetics-get-started-project,{project-monitors-cap}>>

[discrete]
== Elastic’s global managed testing infrastructure

* *GA support*: 8.8.0 and higher
* *Notes*: Elastic’s infrastructure for running lightweight and browser monitors configured through the <<synthetics-get-started-ui,{synthetics-app}>> and/or <<synthetics-get-started-project,{project-monitors-cap}>>
+
include::synthetics-reference/global-managed-paid-for.asciidoc[]

[discrete]
== {private-location}s

* *GA support*: 8.8.0 and higher
* *Notes*:
** For running lightweight and browser monitors from your self-managed infrastructure
** Relies on the Synthetics integration 1.0.0 or above
*** Any _inline_ or _Zip URL_ monitors configured with the beta Synthetics integration prior to 1.0.0, are not supported and will stop running in the future
** Shipped as the `elastic-agent-complete` Docker image
** Must have a direct connection to {es}
*** Do not configure any ingest pipelines or Logstash output

[discrete]
== Heartbeat with Uptime

* *GA support*: As defined in the standard https://www.elastic.co/support/matrix[Support matrix]
* *Notes*:
** For running lightweight monitors via YML configuration running on self-managed infrastructure
** Browser-based monitors are not supported in this configuration

[discrete]
== Standalone {agent}

* *GA support*: As defined in the standard https://www.elastic.co/support/matrix[Support matrix]
* *Notes*:
** For running lightweight monitors via YML configuration running on self-managed infrastructure with standalone {agent}
** Browser-based monitors are not supported in this configuration
** Results for monitors configured using the standalone {agent} are available in the {uptime-app} (_not_ the {synthetics-app})

[discrete]
== Synthetics Recorder

System requirements:

* macOS - High Sierra and newer
* Windows - Windows 10 and newer
* Linux:
** Ubuntu - 14.04 and newer
** Fedora - 24 and newer
** Debian - 8 and newer

[discrete]
== Output to Elasticsearch

Synthetics must have a direct connection to {es}, whether running monitors from Elastic's global managed testing infrastructure or from {private-location}s.

Do not configure any ingest pipelines or output via Logstash as this will prevent Synthetics from working properly and is not supported.
