[[synthetics-journeys]]
= Use synthetic monitors

Synthetic monitoring extends traditional end-to-end testing techniques because it allows your tests to run continuously on the cloud.
With synthetic monitoring in the {uptime-app}, you can assert that your application continues to work after a deployment by reusing
the same journeys that you used to validate the software on your machine.

You can use synthetic monitors to detect bugs caused by invalid states you couldn't predict and didn't write tests for.
Synthetic monitors can also help you catch bugs in features that don't get much traffic by allowing you to periodically simulate users' actions.  

Start by learning the basics of synthetic monitoring, including how to:

* <<synthetics-create-test>>
* <<synthetic-run-tests>>

Then explore more synthetic monitoring topics to get the most out of your tests, including:

* <<synthetics-params-secrets>>
* <<synthetics-configuration>>
* <<synthetics-command-reference>>

Finally, learn how to view and interpret data from your synthetic monitors in the {uptime-app}:

* <<synthetics-visualize>>
