[[synthetics-role-setup]]
= Setup role

Administrators who set up Synthetics typically need to enable Monitor Management.

Monitor Management will be enabled automatically when a user with the required permissions
loads the Synthetics UI. This must be completed just once by an admin before any users with
the <<synthetics-role-write>> can create synthetic monitors. This applies to monitors created
via both <<synthetics-get-started-project,projects>> and <<synthetics-get-started-ui,the UI>>.

As a best practice, *grant the setup role to administrators only*, and use a more restrictive
role for event publishing.

Create a *setup role*, called something like `synthetics_setup`:

. Start with the `editor` {ref}/built-in-roles.html[built-in role].
This role grants full access to all features in {kib} (including the {observability} solution)
and read-only access to data indices.
+
[NOTE]
====
The `editor` {ref}/built-in-roles.html[built-in role] will grant write access
to _all_ {kib} apps. If you want to limit write access to the {synthetics-app} only,
refer to <<synthetics-write-privileges-limited>>.

If you choose this approach, you will still need to grant the privileges in the next step.
====

. Grant the role additional privileges that are required to enable Monitor Management:
+
.. Grant all of the following privileges:
+
[options="header"]
|====
| Type | Privilege | Purpose

| {ref}/security-privileges.html#privileges-list-cluster[Cluster]
| `monitor`
| Allows the user to retrieve cluster details.

| {ref}/security-privileges.html#privileges-list-cluster[Cluster]
| `manage_ilm`
| Allows the user access to all index lifecycle management operations related to managing policies.

| {ref}/security-privileges.html#privileges-list-cluster[Cluster]
| `read_pipeline`
| Gives the user read-only access to the ingest pipline.

| {ref}/security-privileges.html#privileges-list-indices[Index]
| `synthetics-*`: `view_index_metadata`
| Gives the user read-only access to index and data stream metadata.

| {ref}/security-privileges.html#privileges-list-indices[Index]
| `synthetics-*`: `create_doc`
| Allows the user to index documents.

| {ref}/security-privileges.html#privileges-list-indices[Index]
| `synthetics-*`: `auto_configure`
| Permits auto-creation of indices and data streams.

| {ref}/security-privileges.html#privileges-list-indices[Index]
| `synthetics-*`: `monitor`
| Gives access to all actions that are required for monitoring (recovery, segments info, index stats, and status).

|====

NOTE: If users with the setup role also need to create, modify, and delete monitors,
add the privileges defined in the <<synthetics-role-write,writer role>>.
