[[synthetics-lightweight]]
= Configure lightweight monitors

beta[]

To configure lightweight monitors define a set of `monitors` to check your remote hosts.
Each `monitor` item is an entry in a YAML list and begins with a dash (`-`).
You can define the type of monitor to use, the hosts to check, and other
optional settings.

Lightweight monitors can be configured using any of the following:

* *YAML files in {project-monitors}*.
  <<synthetics-get-started-project,Set up a project>> and configure monitors in YAML
  files in the `journeys` directory.
* *{synthetics-app}*.
  <<synthetics-get-started-ui,Go to the {synthetics-app}>> in {kib} and configure monitors.

[discrete]
[[synthetics-monitor-types]]
= Monitor types

`http`:: Connects via HTTP and optionally verifies that the host returns the
expected response. Will use `Elastic-Heartbeat` as
the user agent product.
`icmp`:: Uses an ICMP (v4 and v6) Echo Request to ping the configured hosts.
Requires special permissions or root access.
`tcp`:: Connects via TCP and optionally verifies the endpoint by sending and/or
receiving a custom payload.

The following example configures three monitors checking via the `http`, `icmp`, and `tcp`
protocols and demonstrates how to use TCP Echo and HTTP response verification:

[source,yaml]
----
heartbeat.monitors:
- type: http
  name: Todos Lightweight
  id: todos-lightweight
  urls: "https://elastic.github.io/synthetics-demo/"
  schedule: '@every 1m'
- type: icmp
  id: ping-myhost
  name: My Host Ping
  hosts: ["myhost"]
  schedule: '@every 5s'
- type: tcp
  id: myhost-tcp-echo
  name: My Host TCP Echo
  hosts: ["myhost:777"]  # default TCP Echo Protocol
  check.send: "Check"
  check.receive: "Check"
  schedule: '@every 5s'
heartbeat.scheduler:
  limit: 10
----

[discrete]
[[synthetics-monitor-options]]
= Configuration options

You can find a complete reference of available configuration options in
the {heartbeat} documentation.

[NOTE]
====
While the most commonly used {heartbeat} configuration options are supported,
some configuration options are not yet supported in {project-monitors} and the {synthetics-app}.
====

There are some common monitor configuration options that are the same for all monitors.
For a complete list, refer to {heartbeat-ref}/monitor-options.html[Common monitor options].

Each monitor type has additional configuration options that are specific to that monitor type.
Refer to:

* {heartbeat-ref}/monitor-http-options.html[HTTP monitors]
* {heartbeat-ref}/monitor-tcp-options.html[ICMP monitors]
* {heartbeat-ref}/monitor-tcp-options.html[TCP monitors]

The `tcp` and `http` monitor types both support SSL/TLS and some proxy
settings.
