[[synthetics-manage-monitors]]
= Manage synthetic monitors

After you've <<synthetic-run-tests, created a synthetic monitor>>,
you can update the contents of the tests that they run, update the monitor's configuration,
and permanently delete monitors.

The way you manage browser monitors will depend on how you created the monitor:

* If you used <<synthetic-monitor-choose-project>>, you'll manage the monitors using the `monitor` API or in {kib}'s Monitor Management UI.
* If you used <<synthetic-monitor-choose-heartbeat>>, you'll manage the monitors in the {heartbeat} config file.
* If you used <<synthetic-monitor-choose-agent>>, you'll manage the monitors in {kib}'s Integrations UI.

[discrete]
[[manage-monitors-journey]]
== Update a journey

After you create a monitor, you might want to update the journey it runs.
If you update your UI, for example, you may want to update your journey's selectors and assertions.

[discrete]
[[manage-monitors-journey-project]]
=== Project monitors

If you're using project monitors, you can update journeys directly through code.
Then run the <<elastic-synthetics-push-command, `push` command>> to replace any existing monitors from this project in {kib} with new monitors that use the updated test.

NOTE: Updates are linked to a monitor's `id`. To update a monitor you must keep its `id` unchanged.

[discrete]
[[manage-monitors-journey-heartbeat]]
=== {heartbeat}

Update the tests in the directory specified in the `source.zip_url` you referenced in the {heartbeat} configuration file, and the changes will be reflected in the monitors.

If you're using inline monitors within your `heartbeat.yml` configuration file, update your monitors directly in that file.

[discrete]
[[manage-monitors-journey-agent]]
=== {agent}

Update the tests at the **Zip URL** you referenced in the {agent} Integration when you <<monitor-use, configured the monitor>>,
and the changes will be reflected in the monitors.

[discrete]
[[manage-monitors-config]]
== Update a monitor's configuration

You might also want to update the monitor's configuration.
For example, you might want to change the interval at which the monitor runs a test.

[discrete]
[[manage-monitors-config-project]]
=== Project monitors

Update the monitor configuration options used in individual journeys in the test code (or in the
<<synthetics-configuration-monitor, global synthetics configuration file>>).
Then run the `push` command to replace the existing monitor in {kib} with a new monitor that uses the updated configuration options.

[discrete]
[[manage-monitors-config-heartbeat]]
=== {heartbeat}

Update the relevant options in the {heartbeat} configuration file, and the changes will be reflected in the monitors.

[discrete]
[[manage-monitors-config-agent]]
=== {agent}

After creating an integration you can edit the configuration.
Any changes you make will be applied to _all_ agents to which the policy (that contains an integration) applies.

[discrete]
[[manage-monitors-delete]]
== Delete a synthetic monitor 

Eventually you might want to delete a monitor altogether.
For example, if the user journey you were validating no longer exists.

Alternatively, you can temporarily disable a monitor by updating the monitor's configuration in your journey's code.

[discrete]
[[manage-monitors-delete-project]]
=== Project monitors

Delete the journey in the test code and push the project using the `push` command.
The monitor associated with that journey that existed in {kib} will be deleted.

[discrete]
[[manage-monitors-delete-heartbeat]]
=== {heartbeat}

To remove a monitor using {heartbeat}, delete the monitor entry in the `heartbeat.yml` file.

[discrete]
[[manage-monitors-delete-agent]]
=== {agent}

To remove a monitor that you created using {agent}, delete the integration.
