[[synthetics-support-matrix]]
= Synthetics support matrix

There are various components that make up the Synthetics solution, which are supported in the following configurations:

* {synthetics-app}
** GA from 8.8.0
** For managing lightweight and browser monitors configured through the <<synthetics-get-started-ui,{synthetics-app}>>
** Reporting for lightweight and browser monitors configured through the <<synthetics-get-started-ui,{synthetics-app}>> and/or <<synthetics-get-started-project,{project-monitors-cap}>>
* {project-monitors-cap}
** GA from 8.8.0
** For managing lightweight and browser monitors configured as <<synthetics-get-started-project,{project-monitors-cap}>>
* Elastic’s global managed testing infrastructure
** GA from 8.8.0
** Elastic’s infrastructure for running lightweight and browser monitors configured through the <<synthetics-get-started-ui,{synthetics-app}>> and/or <<synthetics-get-started-project,{project-monitors-cap}>>
* {private-location}s
** GA from 8.8.0
** For running lightweight and browser monitors from your self-managed infrastructure
** Relies on the Synthetics integration 1.0.0 or above
*** Any _inline_ or _Zip URL_ monitors configured with the beta Synthetics integration prior to 1.0.0, are not supported and will stop running in the future
** Shipped as the `elastic-agent-complete` Docker image
* Heartbeat with Uptime
** GA as defined in the standard https://www.elastic.co/support/matrix[Support matrix]
** For running lightweight monitors via YML configuration running on self-managed infrastructure
*** Browser based monitors are not supported in this configuration
* Standalone {agent}
** GA as defined in the standard https://www.elastic.co/support/matrix[Support matrix]
** For running lightweight monitors via YML configuration running on self-managed infrastructure with standalone {agent}
*** Browser based monitors are not supported in this configuration
** Results for monitors configured in this way are be available in Uptime (not the {synthetics-app})
* Synthetics Recorder
** TBC

