[[synthetics-troubleshooting]]
= Troubleshooting Synthetics

++++
<titleabbrev>Troubleshooting</titleabbrev>
++++

[discrete]
[[synthetics-troubleshooting-local-debugging]]
= Local debugging

Use the `DEBUG=synthetics` environment variable to capture Synthetics agent logs when
running Synthetic tests locally with the <<synthetics-command-reference,Synthetics CLI>>.

[discrete]
[[synthetics-troubleshooting-common-issues]]
= Common issues

[discrete]
[[synthetics-troubleshooting-missing-api-key]]
== Monitors stopped running after upgrading to 8.8.0 or above

Synthetic monitors will stop running if you:

* Enabled Monitor Management (in the {uptime-app}) prior to 8.6.0.
* Created a synthetic monitor that is configured to run on Elastic's global managed infrastructure.
* Upgraded to 8.8.0 or above.

This happens because the permissions you gave the {uptime-app} by clicking *Enable Monitor Management*
in versions prior to 8.6.0 are not sufficient for using the {synthetics-app} in versions 8.8.0 and above.

To fix this, a user with <<synthetics-role-setup,admin permissions>> needs to visit the {synthetics-app}
in {kib}. In 8.8.0 and above, the equivalent of "enabling monitor management" happens automatically in the
background when a user with <<synthetics-role-setup,admin permissions>> visits the {synthetics-app}.

If a user without <<synthetics-role-setup,admin permissions>> visits the {synthetics-app} before an admin
has visited it, the user will get a message that Synthetics cannot running until an admin user visits the
{synthetics-app}.

// Should I add more details from the knowledge base link in a note or collapsible block?

[discrete]
[[synthetics-troubleshooting-no-agent-running]]
== No Agent running

No Agent running with the Private Location Agent Policy (so no results)

[discrete]
[[synthetics-troubleshooting-get-help]]
= Get help

[discrete]
[[synthetics-troubleshooting-support]]
== Elastic Support

include::troubleshooting.asciidoc[tag=support]

[discrete]
[[synthetics-troubleshooting-discussion]]
== Discussion forum

include::troubleshooting.asciidoc[tag=discussion]
