[[synthetics-security-encryption]]
= Synthetics Encryption and Security

Elastic Synthetics was designed with security in mind encrypting both persisted and transmitted data.
This page catalogs the points within the Elastic Synthetics app data is either stored or transmitted in an encrypted fashion.

== Synthetics UI (Kibana App)

Data is stored in Kibana Secure Saved Objects[https://www.elastic.co/guide/en/kibana/master/xpack-security-secure-saved-objects.html], 
with sensitive fields encrypted. These fields include your script source, params, and global params.

== Synthetics Service

The Global Elastic Synthetics Service performs all communication of sensitive data (both internally, and with Kibana) over encrypted connections
and encrypts all data persisted to disk as well.

== Synthetics Private Locations

Data is stored in Kibana Secure Saved Objects[https://www.elastic.co/guide/en/kibana/master/xpack-security-secure-saved-objects.html], and encrypted
in transit. See https://www.elastic.co/guide/en/fleet/current/_elastic_agent_configuration_encryption.html for more details.
