[[synthetics-manage-monitors]]
= Manage monitors

After you've <<synthetics-get-started, created a synthetic monitor>>,
you can update the contents of the tests that they run, update the monitor's configuration,
and permanently delete monitors.

[discrete]
[[manage-monitors-config]]
= Update a monitor's configuration

You can update a monitor's configuration, for example, changing the interval at which
the monitor runs a test.

You can also update the journey used in a browser monitor.
For example, if you update the UI used in your application, you may want to update
your journey's selectors and assertions.

include::tab-widgets/uptime-monitoring/manage-monitors-update-monitor-widget.asciidoc[]

[discrete]
[[manage-monitors-delete]]
= Delete a monitor 

Eventually you might want to delete a monitor altogether.
For example, if the user journey you were validating no longer exists.

include::tab-widgets/uptime-monitoring/manage-monitors-delete-monitor-widget.asciidoc[]

Alternatively, you can temporarily disable a monitor by updating the monitor's
configuration in your journey's code or on the {uptime-app}'s Monitor Management
page using the _Enabled_ toggle.
