[[synthetics-support-matrix]]
= Synthetics support matrix

There are various components that make up the Synthetics solution, which are supported in the following configurations:

|===
| Product area | GA support | Details

| *{synthetics-app}*
| 8.8.0 and higher
a| * For creating and managing lightweight and browser monitors configured through the <<synthetics-get-started-ui,{synthetics-app}>>
* For reporting for lightweight and browser monitors configured through the <<synthetics-get-started-ui,{synthetics-app}>> and/or <<synthetics-get-started-project,{project-monitors-cap}>>

| *{project-monitors-cap}*
| 8.8.0 and higher
a| For creating and managing lightweight and browser monitors configured as <<synthetics-get-started-project,{project-monitors-cap}>>

| *Elastic’s global managed testing infrastructure*
| 8.8.0 and higher
a| Elastic’s infrastructure for running lightweight and browser monitors configured through the <<synthetics-get-started-ui,{synthetics-app}>> and/or <<synthetics-get-started-project,{project-monitors-cap}>>

include::synthetics-reference/global-managed-paid-for.asciidoc[]

| *{private-location}s*
| 8.8.0 and higher
a| * For running lightweight and browser monitors from your self-managed infrastructure
* Relies on the Synthetics integration 1.0.0 or above
** Any _inline_ or _Zip URL_ monitors configured with the beta Synthetics integration prior to 1.0.0, are not supported and will stop running in the future
* Shipped as the `elastic-agent-complete` Docker image
* Must have a direct connection to {es}
** Do not configure any ingest pipelines or Logstash output

| *Heartbeat with Uptime*
| As defined in the standard https://www.elastic.co/support/matrix[Support matrix]
a| * For running lightweight monitors via YML configuration running on self-managed infrastructure
* Browser-based monitors are not supported in this configuration

| *Standalone {agent}*
| As defined in the standard https://www.elastic.co/support/matrix[Support matrix]
a| * For running lightweight monitors via YML configuration running on self-managed infrastructure with standalone {agent}
* Browser-based monitors are not supported in this configuration
* Results for monitors configured using the standalone {agent} are available in the {uptime-app} (_not_ the {synthetics-app})

| *Synthetics Recorder*
| 
a| System requirements: 

* macOS - High Sierra and newer
* Windows - Windows 10 and newer
* Linux:
** Ubuntu - 14.04 and newer
** Fedora - 24 and newer
** Debian - 8 and newer

| *Output to Elasticsearch*
| 
a| Synthetics must have a direct connection to {es}, whether running monitors from Elastic's global managed testing infrastructure or from {private-location}s.

Do not configure any ingest pipelines or output via Logstash as this will prevent Synthetics from working properly and is not supported.

|===
