[[synthetics-security-encryption]]
= Synthetics Encryption and Security

Elastic Synthetics was designed with security in mind encrypting both persisted and transmitted data.
This page catalogs the points within the Elastic Synthetics app data is either stored or transmitted in an encrypted fashion.

[discrete]
== Synthetics UI (Kibana App)

Data is stored in {kibana-ref}/xpack-security-secure-saved-objects.html[Kibana Secure Saved Objects], 
with sensitive fields encrypted. These fields include your script source, params, and global params.

[discrete]
== Synthetics Service

The Global Elastic Synthetics Service performs all communication of sensitive data (both internally, and with Kibana) over encrypted connections
and encrypts all data persisted to disk as well.

[discrete]
== Synthetics Private Locations

Data is stored both in encrypted {kibana-ref}/xpack-security-secure-saved-objects.html[Kibana Secure Saved Objects] and unencrypted saved objects for Fleet configuration.
The unencrypted objects are restricted to those with permissions to configure fleet.
Data is encrypted in transit. See {fleet-guide}/_elastic_agent_configuration_encryption.html[Elastic Agent configuration encryption] for more details.
