[[synthetics-migrate-from-heartbeat]]
= Migrate from {heartbeat}

++++
<titleabbrev>From {heartbeat}</titleabbrev>
++++

_Info on the status of {heartbeat} and why you should migrate..._

[discrete]
[[synthetics-migrate-heartbeat-compare]]
= Compare approaches

Below is a comparison of how you used {heartbeat} to create monitors
and how you'll use the {uptime-app} / Projects to create monitors:

|===
| | {heartbeat} | {uptime-app} / Projects

| *Supported monitors*
| Supported both lightweight and browser monitors
| Supports both lightweight and browser monitors

| *Where monitors run*
| You had to run monitors on your infrastrucuture.
a| You can run monitors on both:

* Your infrastructure using <<synthetics-private-location,private locations>>
* Elastic's global managed infrastructure

| *Where you configure monitors*
| Code (all monitors)
| Code (all monitors)

| *How to create monitors*
| 
a| Create a project that uses `@elastic/synthetics`

Write journeys in JavaScript or TypeScript files and configure monitors
in your journey code using `monitor.use`.

Configure lightweight monitors in YAML files.

Use the `push` command to create monitors.

Find more details in <<synthetics-get-started-project>>.
|===

[discrete]
[[synthetics-migrate-heartbeat-location]]
= Where monitors run

If you want to continue hosting on your infrastructure, you will need to create a
<<synthetics-private-location,private location>> before creating monitors.

Alternatively, you can start hosting on Elastic's global managed infrastructure.
With Elastic's global managed testing infrastructure, you can create and run monitors in multiple
locations without having to manage your own infrastructure.
Elastic takes care of software updates and capacity planning for you.