[[synthetics-get-started]]
= Quickstart: Synthetics monitoring via Docker

++++
<titleabbrev>Quickstart with Docker</titleabbrev>
++++

experimental::[]

A customizable Docker project template is provided to get started with Elastic Synthetics quickly.
This template provides two types of sample tests: a simple, two-step, inline test,
and a packaged todo application with a custom suite of tests.

[discrete]
== Step 1: Clone the `elastic/synthetics` repository

This template pulls the Elastic synthetics image, builds your synthetic tests,
schedules and runs them with Heartbeat, and sends the resulting data to the Elastic Stack.

Clone the https://github.com/elastic/synthetics[elastic/synthetics] repo
and `cd` into the `examples/docker` directory:

[source,sh]
----
git clone git@github.com:elastic/synthetics.git &&\
cd examples/docker
----

There are two files in `synthetics/examples/docker` that you'll need to edit:

[source,sh]
----
synthetics
  |- examples
     |- docker
        |- heartbeat.docker.yml <1>
        |- run.sh <2>
----
<1> `heartbeat.docker.yml` is your Heartbeat configuration file.
This is where you'll configure your synthetic test suites.
<2> `run.sh` provides the main `docker run` command that pulls the
Elastic synthetics image and runs Heartbeat.

[discrete]
== Step 2: Update `heartbeat.docker.yml`

There are two ways to configure a synthetic test.
Let's take a quick look at each.

Running a simple test::

If you're running a simple, browser based test, you can use the traditional Heartbeat flow to completely
configure your synthetic testing directly in `heartbeat.docker.yml`.
An example is provided:
+
[source,yml]
----
heartbeat.monitors:
- type: browser
  id: my-monitor <1>
  name: My Monitor
  schedule: "@every 1m"
  script: |- <2>
    step("load homepage", async () => {
        await page.goto('https://www.elastic.co');
    });
    step("hover over products menu", async () => {
        await page.hover('css=[data-nav-item=products]');
    });
----
<1> Each `monitor` gets its own ID in the {uptime-app} and, therefore its own schedule entry.
This allows tests to be run in parallel and analyzed separately.
<2> Synthetic tests are defined inline. This example uses a two-step script that first loads
a homepage and then hovers over a product menu. See <<synthetics-syntax-use>> for more information.

Running a test suite::

If you'd like to run multiple tests, you'd probably be better off creating a library of tests defined
outside of the `heartbeat.docker.yml` file.
This, for example, allows your tests to live with your application or in a separate Git repo.
+
[source,yml]
----
heartbeat.synthetic_suites: <1>
- name: Todos
  path: "/opt/examples/todos"
  schedule: "@every 1m"
----
<1> Specify the name, path, and schedule of your test suite.

[discrete]
== Step 3: Update `run.sh`

`run.sh` pulls the Elastic/synthetics image, shares your configuration details and test suites with Heartbeat,
and defines the location of your {es} instance.

[source,sh]
----
#...
docker run \
  --rm \
  --name=heartbeat \
  --user=heartbeat \
  --net=host \
  --security-opt seccomp=seccomp_profile.json \ <1>
  --volume="$(pwd)/heartbeat.docker.yml:/usr/share/heartbeat/heartbeat.yml:ro" \ <2>
  --volume="$(pwd)/../:/opt/examples:rw" \ <3>
  $IMAGE \
  --strict.perms=false -e \
  -E cloud.id=<cloud-id> \ <4>
  -E cloud.auth=elastic:<cloud-pass> <5>
#...
----
<1> Running a Chrome browser requires elevated privileges. Synthetic monitoring scripts can
escape the docker container. Do not run any scripts that you don't trust.
<2> Provides your `heartbeat.docker.yml` file as a volume.
<3> Provides the example `todos` journey as a volume.
<4> Your Elastic Cloud ID.
<5> Your Elastic Cloud `username:password`.

If you aren't using {elastic-cloud}, replace `-E cloud.id` and `-E cloud.auth` with your Elasticsearch hosts,
username, and password:

[source,sh]
----
  -E output.elasticsearch.hosts=["localhost:9200"] \
  -E output.elasticsearch.username=elastic \
  -E output.elasticsearch.password=changeme \
----

[discrete]
== Step 4: Run `run.sh`

To run the provided sample tests (or your own), you need to run `run.sh`.
Don't forget to update `run.sh` with your {es} credentials, as explained in the previous step.

[source,sh,subs="attributes"]
----
sh run.sh {version}
----

[discrete]
== Step 5: View in {kib}

That's it! Elastic synthetics is now sending synthetic monitoring data to the Elastic Stack.
Navigate to the {uptime-app} in {kib}, where you can see screenshots of each run,
set up alerts in case the test fails, and more.
If a test fails (shown as `down` in the app), you'll be able to view the step script that failed,
any errors, and a stack trace.
See <<synthetics-visualize>> for more information.

[discrete]
== Next steps

Now you can customize the provided Docker example with your own tests!
See <<synthetics-syntax-use>> to learn more.

// OLD WAY OF DOING THINGS
// Do we want to include this?
// Build the main package: npm run build
// Run: node dist/cli.js -s '{"homepage":"https://cloud.elastic.co"}' examples/inline/sample-inline-journey.js
