[[synthetics-manage-monitors]]
= Manage synthetic monitors

// Purpose of this page: to show users how to maintain their synthetic monitors
// after they are initially set up.

After you've <<synthetic-run-tests, created a synthetic monitor>>, you can manage those monitors including updating the contents of the tests that they run,
updating the monitor's configuration, and permanently deleting monitors.

[discrete]
[[manage-monitors-test]]
== Update a test

[discrete]
[[manage-monitors-test-project]]
=== Project monitors

Update the test code (wherever it's written).
Then run the `push` command to replace the existing monitor in {kib} with a new monitor that uses the updated test.

[discrete]
[[manage-monitors-test-heartbeat]]
=== {heartbeat}

Update the tests referenced in the {heartbeat} configuration file and the changes will be reflected in the monitors.

[discrete]
[[manage-monitors-test-agent]]
=== {agent}

Update the tests referenced in the {agent} Integration and the changes will be reflected in the monitors.

[discrete]
[[manage-monitors-config]]
== Update a monitor's configuration

[discrete]
[[manage-monitors-config-project]]
=== Project monitors

Update the monitor configuration options used in individual journeys in the test code (or the global synthetics configuration file).
Then run the `push` command to replace the existing monitor in {kib} with a new monitor that uses the updated configuration options.

[discrete]
[[manage-monitors-config-heartbeat]]
=== {heartbeat}

??? Update {heartbeat} configuration file ???

[discrete]
[[manage-monitors-config-agent]]
=== {agent}

??? Create a new monitor with updated configuration ???

[discrete]
[[manage-monitors-delete]]
== Delete a synthetic monitor 

[discrete]
[[manage-monitors-delete-project]]
=== Project monitors

Delete the journey in the test code and push the project using the `push` command.
The monitor associated with that journey that existed in {kib} will be deleted.

[discrete]
[[manage-monitors-delete-heartbeat]]
=== {heartbeat}

???

[discrete]
[[manage-monitors-delete-agent]]
=== {agent}

???