[[synthetics-params-secrets]]
// lint ignore params
= Working with params and secrets

++++
<titleabbrev>Working with parameters and secrets</titleabbrev>
++++

beta[] You may need to use dynamically defined values in your synthetic scripts, which may sometimes be sensitive. 
For instance, you may want to test a production website with a particular demo account whose password is only known to the team administering {heartbeat}. 
Another scenario might be using a different URL when running the tests under {heartbeat} and then running them locally using the Synthetics agent.
Solving these problems is where `params` come in. `params` are variables that you can use within a synthetic project. 
They can be defined either in the project config file, the synthetics agent command line, or in a {heartbeat} YAML config file.

You should also note that since synthetics is a full JavaScript environment, it is also possible to use regular environment variables via
the standard node `process.env` global object.

[discrete]
[[synthetics-basic-params]]
== Parameter Basics

When creating a project, parameters can be referenced via the `params` property available within the 
argument to a `journey`, `before`, `beforeAll`, `after`, or `afterAll` callback function.

[source,js]
----
beforeAll(({params}) => {
  console.log(`Visiting ${params.url}`)
})

journey("My Journey", ({ page, params }) => {
    step('launch app', async () => {
      await page.goto(params.url);<1>
    });
});
----
<1> Note that in a typescript program you would want to instead use `params.url as string`.

If you try to run the example above you'll notice an error because we haven't specified a value for the `url` parameter.
Parameter values can be declared by any of the following methods:

* Declaring a default value for the parameter in a configuration file.
* Passing the `--params` CLI argument. 
* Specifying the parameter in the {heartbeat} YAML config using the `params` option.

The values in the configuration file are read first, then merged with either the CLI argument, or the {heartbeat}
option, with the CLI and {heartbeat} options taking precedence over the configuration file.

These options are discussed in detail in the sections below.

[discrete]
[[synthetics-dynamic-configs]]
// lint ignore params
== Use a config file to set params

Use a `synthetics.config.js` or `synthetics.config.ts` file to define variables your tests always need to be defined. 
This file should be placed in the root of your synthetics project. 

[source,js]
----
export default (env) => {
  let url = "http://localhost:8080";
  if (env === "production") {
    url = "https://elastic.github.io/synthetics-demo/"
  }
  return {
    params: {
      url,
    },
  };
};
----

Note that we use the `env` variable in the above example, which corresponds to the value of the `NODE_ENV` environment variable
, or the `environment` parameter in the `browser` monitor definition when using {heartbeat}. 

[discrete]
[[synthetics-cli-params]]
// lint ignore params
== Use CLI arguments to set params

To set parameters when running `elastic-synthetics` on the command line, use the `--params` or `-p` flag to the `elastic-synthetics` program. The provided map is merged over any existing variables defined in the `synthetics.config.{js,ts}` file.

To override the `url` parameter, you would run: `elastic-synthetics . --params '{"url": "http://localhost:8080"}'`

[discrete]
[[synthetics-request-param]]
== Use the `request` parameter

Use the `request` parameter to make API requests independently of the browser interactions.

// Link to Playwright docs?
// https://playwright.dev/docs/test-api-testing#sending-api-requests-from-ui-tests

NOTE: The `request` parameter is not intended to be used for writing pure API tests. Instead, it is a way to support
writing plain HTTP requests in service of a browser-based test.

Below is an example of how to use the `request` object to communicate with HTTP endpoints.
The example demonstrates how to retrieve a token from an HTTP endpoint and use it in a subsequent webpage request.

[source,js]
-----
import { journey, step, expect } from '@elastic/synthetics';

journey('Retrieve and use HTTP Headers', ({ page, params, request }) => {
  // We will populate these variable from example HTTP API responses
  let apiKey;
  let decodedApiKey;

  // We will use httpbin.org endpoints for demonstration
  const apiBaseUrl = 'https://httpbin.org';

  // Let's say we expect the following header key:value from an Auth API
  const exampleAPIHeaderKey = 'x-api-key';
  const exampleAPIHeaderValue = 'some api key'; // base64 of 'Example-HTTP-Header-Value'

  // /response-headers endpoint returns passed query params in headers
  step('Retrieve headers from API', async() => {
    const resp = await request.get(`${apiBaseUrl}/response-headers?${exampleAPIHeaderKey}=${exampleAPIHeaderValue}`);
    apiKey = resp.headers()[exampleAPIHeaderKey];
    expect(apiKey).toEqual(exampleAPIHeaderValue);
  });

  // /base64 endpoint returns the decoded string
  step('Use API Key in HTTP request', async() => {
    const resp = await request.get(`${apiBaseUrl}/base64/${apiKey}`);
    decodedApiKey = await resp.text();
    expect(decodedApiKey).toEqual('Example-HTTP-Header-Value');
  });

  // httpbin.org/headers prints all request headers
  step('Use API Key in page request', async() => {
    await page.setExtraHTTPHeaders({ [exampleAPIHeaderKey]: decodedApiKey });
    await page.goto('https://httpbin.org/headers');
    await page.waitForSelector(`text=${decodedApiKey}`);
  });

  step('Send headers to API', async () => {
    const resp = await request.get('https://httpbin.org/headers', { headers: { 'Foo': 'Bar' } });
    const respJson = await resp.json();
    expect(respJson.headers['Foo']).toEqual('Bar');
  });
});
-----

You can also use the `request` parameter in inline journeys:

[source,js]
-----
// The apiKey here is just a base64 of 'Example-HTTP-Header-Value'
const apiKey = 'some api key';

// We will update this from an HTTP API response
let decodedKey;

step('Retrieve API key', async () => {
  // /base64 endpoint returns the decoded string
  const resp = await request.get('https://httpbin.org/base64/' + apiKey);
  decodedKey = await resp.text();
  expect(decodedKey).toEqual('Example-HTTP-Header-Value');
});

step('Use API key', async () => {
  await page.setExtraHTTPHeaders({ 'Example-HTTP-Header': decodedKey });

  // httpbin.org/headers prints all sent headers
  await page.goto('https://httpbin.org/headers');
  await page.waitForSelector('text=' + decodedKey);
});
-----

[discrete]
[[synthetics-hb-params]]
// lint ignore params
== Use {heartbeat} options to set params

When running via {heartbeat} use the `params` option to set additional parameters, passed through the `--params` flag
mentioned above and have their values merged over any default values. In the example below we run the `todos` app, overriding the `url`
parameter.

[source,yaml]
----
- name: Todos
  id: todos
  type: browser
  schedule: "@every 3m"
  tags: todos-app
  params:
    url: "https://elastic.github.io/synthetics-demo/"
  source:
    zip_url:
      url: "https://github.com/elastic/synthetics-demo/archive/refs/heads/main.zip"
      folder: "synthetics-tests"
----

[discrete]
[[synthetics-secrets-sensitive]]
== Working with secrets and sensitive values

Your synthetics scripts may require the use of passwords or other sensitive secrets that are not known till runtime. Before we continue, it is 
important to remember that since synthetics scripts have no limitations, a malicious script author could write a synthetics journey that 
exfiltrates `params` and other data at runtime. Therefore, it is generally best not to use truly sensitive passwords (e.g. an admin password to test an admin
panel, or a real credit card) in *any* synthetics tools. Instead, set up limited dummy accounts, or fake credit cards with limited functionality.

Use either environment variables or the {heartbeat} keystore to handle any values needing encryption at rest. 
As an example, the syntax `${URL}` for instance, to reference a variable named `URL` in either the secret store or the environment. For example: 

[source,yaml]
----
- name: Todos
  id: todos
  type: browser
  schedule: "@every 3m"
  tags: todos-app
  params:
    url: ${URL}
  source:
    zip_url:
      url: "https://github.com/elastic/synthetics-demo/archive/refs/heads/main.zip"
      folder: "synthetics-tests"
----

To setup the {heartbeat} keystore see the https://www.elastic.co/guide/en/beats/heartbeat/current/keystore.html[{heartbeat} keystore documentation]. 
