[[synthetics-support-matrix]]
= Synthetics support matrix

There are various components that make up the Synthetics solution, which are supported in the following configurations:

* Synthetics app (Kibana) 
** GA from 8.8.0
** For managing lightweight and browser monitors configured through the [Synthetics app](synthetics-get-started-ui.html)
** Reporting for lightweight and browser monitors configured through the [Synthetics app](synthetics-get-started-ui.html) and/or [project monitors](synthetics-get-started-project.html)
* Project Monitors
** GA from 8.8.0
** For managing lightweight and browser monitors configured as [project monitors](synthetics-get-started-project.html)
* Elastic’s global managed testing infrastructure
** GA from 8.8.0
** Elastic’s infrastructure for running lightweight and browser monitors configured through the [Synthetics app](synthetics-get-started-ui.html) and/or [project monitors](synthetics-get-started-project.html)
* Private locations
** GA from 8.8.0
** For running lightweight and browser monitors from your self-managed infrastructure
** Relies on the Synthetics integration 1.0.0 or above
*** Any _inline_ or _Zip URL_ monitors configured with the beta Synthetics integration prior to 1.0.0, are not supported and will stop running in the future
** Shipped as a Docker image using the [elastic-agent-complete](synthetics-private-location.html#synthetics-private-location-connect) version of the image
* Heartbeat with Uptime
** GA as defined in the standard [Support matrix](https://www.elastic.co/support/matrix)
** For running lightweight monitors via YML configuration running on self-managed infrastructure
*** Browser based monitors are not supported in this configuration
* Standalone Elastic Agent
** GA as defined in the standard [Support matrix](https://www.elastic.co/support/matrix)
** For running lightweight monitors via YML configuration running on self-managed infrastructure with standalone Elastic Agent
*** Browser based monitors are not supported in this configuration
** Results for monitors configured in this way are be available in Uptime (not the Synthetics app)
* Synthetics Recorder
** TBC

