[[synthetics-role-write]]
= Writer role

IMPORTANT: To minimize the privileges required by the writer role, use the
<<synthetics-role-setup,setup role>> to enable Monitor Management.
This section assumes another user has already enabled Monitor Management.

For users who need to create, modify, and delete monitors, provide write access.
Two types of write access are outlined below:

* *General write access*: For most users, you can use <<synthetics-write-privileges-general>>,
which grants write access to all {kib} apps and requires little configuration.
* *Limited write access*: If you want to limit write access to the {synthetics-app} only,
you can use <<synthetics-write-privileges-limited>>, which requires additional configuration.

[discrete]
[[synthetics-write-privileges-general]]
= General write access

Create a *writer role*, called something like `synthetics_writer`:

. Start with the `editor` {ref}/built-in-roles.html[built-in role].
This role grants full access to all features in {kib} (including the {observability} solution)
and read-only access to data indices.
+
NOTE: The `editor` {ref}/built-in-roles.html[built-in role] will grant write access
to _all_ {kib} apps. If you want to limit write access to the {synthetics-app} only,
refer to <<synthetics-write-privileges-limited>>.

. _If the user should have permission to create, modify, and delete project monitors_,
they will need an API key that can be used to `push` monitors.
To create API keys, the user will also need _at least one_ of the following privileges in addition to the
privileges included in the `editor` built-in role:
+
[options="header"]
|====
|Type | Privilege | Purpose

| {ref}/security-privileges.html#privileges-list-cluster[Cluster]
| `manage_own_api_key`
| Allows access to all security-related operations on {es} API keys that are owned by the current authenticated user.

| {ref}/security-privileges.html#privileges-list-cluster[Cluster]
| `manage_security`
| Allows access to all security-related operations such as CRUD operations on users and roles and cache clearing.

| {ref}/security-privileges.html#privileges-list-cluster[Cluster]
| `manage_api_key`
| Allows access to all security-related operations on {es} API keys.

|====

[discrete]
[[synthetics-write-privileges-limited]]
= Limited write access

If you want to limit write access to the {synthetics-app} only, do _not_ use the
`editor` {ref}/built-in-roles.html[built-in role].

Instead to you can create a writer role, called something like `synthetics_writer_limited`,
and start by granting the following privileges:

[options="header"]
|====
|Type | Privilege | Purpose

| {ref}/security-privileges.html#privileges-list-indices[Index]
| `synthetics-*`: `read`
| Read-only access to synthetics indices.

| {ref}/security-privileges.html#privileges-list-indices[Index]
| `.alerts-observability.uptime.alerts-*`: `read`
| Read-only access to synthetics alert indices.

| {kibana-ref}/kibana-privileges.html[Kibana]
| `Synthetics and Uptime`: `All`
| Access to the {synthetics-app} in {kib}.

|====

Additional privileges will depend on the factors below.

[discrete]
[[disable-managed-locations]]
== To restrict using Elastic's global managed infrastructure

To restrict users assigned this role from using monitors hosted on Elastic's global managed infrastructure:

. Expand `Synthetics and Uptime` in the list of {kibana-ref}/kibana-privileges.html[Kibana] privileges.
. Toggle _Customize sub-feature privileges_.
. Uncheck _Elastic managed locations enabled_.

[discrete]
[[synthetics-role-write-private-locations]]
== If using Private Locations

The user who initially sets up a new Private Location needs additional privileges. Users who create or update monitors hosted on that Private Location do not need any additional permissions.

The user who is setting up a new Private Location will need the following privileges when creating the agent policy in {fleet}:

[options="header"]
|====
|Type | Privilege | Purpose

| {kibana-ref}/kibana-privileges.html[Kibana]
| `Fleet`: `All`
| Access to Fleet in {kib}.

| {kibana-ref}/kibana-privileges.html[Kibana]
| `Integrations`: `read`
| Access to Integrations in {kib}.

|====

[discrete]
== If using projects

If the user should be able to create and update monitors using
<<choose-projects,projects>>, add _at least one_ of following privileges:

[options="header"]
|====
|Type | Privilege | Purpose

| {ref}/security-privileges.html#privileges-list-cluster[Cluster]
| `manage_own_api_key`
| Allows access to all security-related operations on {es} API keys that are owned by the current authenticated user.

| {ref}/security-privileges.html#privileges-list-cluster[Cluster]
| `manage_security`
| Allows access to all security-related operations such as CRUD operations on users and roles and cache clearing.

| {ref}/security-privileges.html#privileges-list-cluster[Cluster]
| `manage_api_key`
| Allows access to all security-related operations on {es} API keys.

|====
