[[synthetics-private-location]]
= Monitor resources on private networks

To monitor resources on private networks you can either:

* Allow Elastic's global managed infrastructure to access your private endpoints.
* Use {agent} to create a {private-location}.

{private-location}s via Elastic Agent require only outbound connections from your network,
while allowing Elastic's global managed infrastructure to access a private endpoint requires
inbound access, thus posing an additional risk that users must assess.

[discrete]
[[monitor-via-access-control]]
= Allow access to your private network

To give Elastic's global managed infrastructure access to a private endpoint, use IP address filtering, HTTP authentication, or both.

To grant access via IP, use https://manifest.synthetics.elastic-cloud.com/v1/ip-ranges.json[this list of egress IPs].
The addresses and locations on this list may change, so automating updates to
filtering rules is recommended. IP filtering alone will allow all users of Elastic's global managed infrastructure access to your endpoints, if this
is a concern consider adding additional protection via user/password authentication via a proxy like nginx.

[discrete]
[[monitor-via-private-agent]]
= Monitor via a private agent

{private-location}s allow you to run monitors from your own premises.
Before running a monitor on a {private-location}, you'll need to:

* <<synthetics-private-location-fleet-agent>>.
* <<synthetics-private-location-connect,Connect {fleet} to the {stack}>> and enroll an {agent} in {fleet}.
* <<synthetics-private-location-add>> in the {synthetics-app}.

[IMPORTANT]
====
{private-location}s running through {agent} must have a direct connection to {es}.
Do not configure any ingest pipelines, or output via Logstash as this will prevent Synthetics from working properly and is not <<synthetics-support-matrix,supported>>.
====

[discrete]
[[synthetics-private-location-fleet-agent]]
= Set up {fleet-server} and {agent}

Start by setting up {fleet-server} and {agent}:

* *Set up {fleet-server}*: If you are using {ecloud}, {fleet-server} will already be provided and you can skip this step.
To learn more, refer to {fleet-guide}/fleet-server.html[Set up {fleet-server}].
* **Create an agent policy**: For more information on agent policies and creating them,
refer to {fleet-guide}/agent-policy.html#create-a-policy[{agent} policy].

[IMPORTANT]
====
A {private-location} should be set up against an agent policy that runs on a single {agent}.
The {agent} must be **enrolled in Fleet** ({private-location}s cannot be set up using **standalone** {agents}).
Do _not_ run the same agent policy on multiple agents being used for {private-location}s, as you may
end up with duplicate or missing tests. {private-location}s do not currently load balance tests across
multiple {agents}. See <<synthetics-private-location-scaling>> for information on increasing the capacity
within a {private-location}.

By default {private-location}s are configured to allow two simultaneous browser tests and an unlimited number of lightweight checks.
As a result, if more than two browser tests are assigned to a particular {private-location}, there may be a delay to run them.
====

[discrete]
[[synthetics-private-location-connect]]
= Connect to the {stack}

After setting up {fleet}, you'll connect {fleet} to the {stack}
and enroll an {agent} in {fleet}.

[[synthetics-private-location-docker]]
Elastic provides Docker images that you can use to run {fleet} and an {agent} more easily.
For monitors running on {private-location}s, you _must_ use the `elastic-agent-complete`
Docker image to create a self-hosted {agent} node. The standard {ecloud} or self-hosted
{agent} will not work.

ifeval::["{release-state}"=="unreleased"]

Version {version} has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

To pull the Docker image run:

[source,sh,subs="attributes"]
----
docker pull docker.elastic.co/beats/elastic-agent-complete:{version}
----

endif::[]

Then enroll and run an {agent}.
You'll need an enrollment token and the URL of the {fleet-server}.
You can use the default enrollment token for your policy or create new policies
and {fleet-guide}/fleet-enrollment-tokens.html[enrollment tokens] as needed.

For more information on running {agent} with Docker, refer to
{fleet-guide}/elastic-agent-container.html[Run {agent} in a container].

ifeval::["{release-state}"=="unreleased"]

Version {version} has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

[source,sh,subs="attributes"]
----
docker run \
  --env FLEET_ENROLL=1 \
  --env FLEET_URL={fleet-server-host-url} \
  --env FLEET_ENROLLMENT_TOKEN={enrollment-token} \
  --cap-add=NET_RAW \
  --cap-add=SETUID \
  --rm docker.elastic.co/beats/elastic-agent-complete:{version}
----

endif::[]

[IMPORTANT]
====
The `elastic-agent-complete` Docker image requires additional capabilities to operate correctly. Ensure
`NET_RAW` and `SETUID` are enabled on the container.
====

[NOTE]
====
You may need to set other environment variables.
Learn how in {fleet-guide}/agent-environment-variables.html[{agent} environment variables guide].
====

[discrete]
[[synthetics-private-location-add]]
= Add a {private-location}

When the {agent} is running you can add a new {private-location} in {kib}:

. Go to **{observability}** -> **Synthetics**.
. Click **Settings**.
. Click **{private-location}s**.
. Click **Add location**.
. Give your new location a unique _Location name_ and select the _Agent policy_ you created above.
. Click **Save**.

IMPORTANT: It is not currently possible to use custom CAs for synthetics browser tests in private locations without following a workaround. To learn more about the workaround, refer to the following GitHub issue: https://github.com/elastic/synthetics/issues/717[elastic/synthetics#717].

[discrete]
[[synthetics-private-location-scaling]]
= Scaling {private-location}s

By default {private-location}s are configured to allow two simultaneous browser tests, and an unlimited number of lightweight checks.
These limits can be set via the environment variables `SYNTHETICS_LIMIT_{TYPE}`, where `{TYPE}` is one of `BROWSER`, `HTTP`, `TCP`, and `ICMP`
for the container running the {agent} docker image.

It is critical to allocate enough memory and CPU capacity to handle configured limits.
Start by allocating at least 2 GiB of memory and two cores per browser instance to ensure consistent
performance and avoid out-of-memory errors. Then adjust as needed. Resource requirements will vary depending on workload.
Much less memory is needed for lightweight monitors. Start by allocating at least 512MiB of memory and two cores for
lightweight checks. Then increase allocated memory and CPU based on observed usage patterns.

These limits are for simultaneous tests, not total tests. For example, if
60 browser tests were scheduled to run once per hour and each took 1 minute to run, that would fully occupy one execution slot.
However, it is a good practice to set up execution slots with extra capacity. A good starting point would be to over-allocate by
a factor of 5. In the previous example that would mean allocating 5 slots.

[discrete]
[[synthetics-private-location-next]]
= Next steps

Now you can add monitors to your {private-location} in <<synthetics-get-started-ui,the {synthetics-app}>> or using the <<synthetics-get-started-project,Elastic Synthetics library's `push` method>>.
