[[synthetics-manage-monitors]]
= Manage browser monitors

beta[]

After you've <<synthetic-run-tests, created a synthetic monitor>>,
you can update the contents of the tests that they run, update the monitor's configuration,
and permanently delete monitors using the `monitor` API or in {kib}'s Monitor Management UI.

[discrete]
[[manage-monitors-journey]]
== Update a journey

After you create a monitor, you might want to update the journey it runs.
If you update your UI, for example, you may want to update your journey's selectors and assertions.

include::tab-widgets/uptime-monitoring/manage-monitors-update-monitor-widget.asciidoc[]

[discrete]
[[manage-monitors-config]]
== Update a monitor's configuration

You might also want to update the monitor's configuration.
For example, you might want to change the interval at which the monitor runs a test.

include::tab-widgets/uptime-monitoring/manage-monitors-update-test-widget.asciidoc[]

[discrete]
[[manage-monitors-delete]]
== Delete a synthetic monitor 

Eventually you might want to delete a monitor altogether.
For example, if the user journey you were validating no longer exists.

Alternatively, you can temporarily disable a monitor by updating the monitor's configuration in your journey's code.

include::tab-widgets/uptime-monitoring/manage-monitors-delete-monitor-widget.asciidoc[]
