[[synthetics-create-test]]
= Create a new synthetic test

++++
<titleabbrev>Create a test</titleabbrev>
++++

[discrete]
[[synthetics-syntax]]
== Syntax

beta[] To write synthetic tests for your application, you'll need to know basic JavaScript and
{playwright-url}[Playwright] syntax.
The Elastic Synthetics agent exposes an API for creating and running tests:

* `journey(name, ({ page, browser, context, params }) => {})` -- A journey tests one discrete unit of functionality.
For example, logging into a website, adding something to a cart, or joining a mailing list.
Each journey provides a fresh playwright `browser`, `context`, and `page` instance.
See <<synthetics-create-journey>> for more information.
* `step(name, function)` -- A journey consists of multiple steps, i.e., actions that should be completed in a specific order.
Steps are displayed individually in the {uptime-app} for easy debugging and error tracking.
* `beforeAll(({ params }) => {})` -- Runs a provided function prior to all `journey` runs.
If the provided function is a promise, the runner will wait for the promise to resolve before invoking the journey.
This function is useful for setting up global state or a server that will be used across multiple journeys.
* `before(({ params }) => {})` -- Runs a provided function prior to a single `journey` runs.
This function is useful for setting up global state or a server that will be used for a single journey.
* `afterAll(({ params }) => {})` -- Runs a provided function after all the journeys have completed.
This function is useful for removing global state or closing a server that was used in multiple journeys.
* `after(({ params }) => {})` -- Runs a provided function after a single journey has completed.
This function is useful for removing global state or closing a server that was used in a single journey.

TIP: {playwright-url}[Playwright] is a browser testing library developed by Microsoft.
It is reliable and fast and features a modern API that auto waits for page elements to be ready.

[discrete]
[[synthetics-create-journey]]
== Write a synthetic test

Start by creating a new file using the `.journey.ts` or `.journey.js` file extension,
importing the synthetics library, and adding a new journey.
A _journey_ tests one discrete unit of functionality.
For example, logging into a website, adding something to a cart, or joining a mailing list.

The journey function takes two parameters: a `name` and a `callback`.
The `name` helps you identify an individual journey.
The `callback` argument is a function that encapsulates what the journey does.

[source,js]
----
journey('Journey name', ({ page, browser, context, params }) => {
  // Add steps here
});
----

The callback provides access to fresh Playwright `page`, `params`, `browser`, and `context` instances:

[horizontal]
`name`::        A string you provide to describe the journey.
`page`::        A https://playwright.dev/docs/api/class-page[page] object from Playwright
                that lets you control the browser's current page.
`browser`::     A {playwright-api-docs}[browser] object created by Playwright.
`context`::     A https://playwright.dev/docs/api/class-browsercontext[browser context] 
                that doesn't share cookies or cache with other browser contexts.
`params`::      User-defined variables that allow you to invoke the Synthetics suite with custom parameters.
                For example, if you want to use a different homepage depending on the `env`
                (`localhost` for `dev` and a URL for `prod`). See <<synthetics-params-secrets>>
                for more information.


[discrete]
[[synthetics-create-step]]
=== Add steps

A journey consists of multiple _steps_. Steps are actions that should be completed in a specific order.
Steps are displayed individually in the {uptime-app} along with screenshots for easy debugging and error tracking.

A basic two-step journey would look like this:

[source,js]
----
journey('Journey name', ({ page, browser, client, params }) => {
    step('Step 1 name', () => {
      // Do something here
    });
    step('Step 2 name', () => {
      // Do something else here
    });
});
----

Steps can be as simple or complex as you need them to be.
For example, a basic first step might load a web page:

[source,js]
----
step('Load the demo page', () => {
  await page.goto('https://elastic.github.io/synthetics-demo/'); <1>
});
----
<1> See the https://playwright.dev/docs/api/class-page#page-goto[`page.goto` reference] for more information.

A more complex step might wait for a page element to be selected
and then ensure that it matches an expected value.

For example, on a page using the following HTML:

[source,html]
----
<header class="header">
  <h1>todos</h1>
  <input class="new-todo"
    autofocus autocomplete="off"
    placeholder="What needs to be done?">
</header>
----

You can verify that the `input` element with class `new-todo` contains the expected `placeholder` value
(the hint text for `input` elements) with the following test:

[source,js]
----
step('Assert placeholder text', async () => {
  const placeholderValue = await page.getAttribute(
      'input.new-todo',
      'placeholder'
  ); <1>
  expect(placeholderValue).toBe('What needs to be done?'); <2>
});
----
<1> Find the `input` element with class `new-todo` and get the value of the `placeholder` attribute.
See the https://playwright.dev/docs/api/class-page#page-get-attribute[`page.getAttribute` reference] for more information.
<2> Use the assertion library provided by the Synthetics agent to look for the
expected value. See https://jestjs.io/docs/expect[Jest expect docs] for more information.

[discrete]
[[synthetics-sample-test]]
=== Sample synthetic test

A complete example of a basic synthetic test looks like this:

[source,js]
----
import { journey, step, expect } from '@elastic/synthetics';

journey('Ensure placeholder is correct', ({ page }) => {
  step('Load the demo page', async () => {
    await page.goto('https://elastic.github.io/synthetics-demo/');
  });
  step('Assert placeholder text', async () => {
    const placeholderValue = await page.getAttribute(
      'input.new-todo',
      'placeholder'
    );
    expect(placeholderValue).toBe('What needs to be done?');
  });
});
----
