[[synthetics-get-started]]
= Get started

beta[]

To set up a synthetic monitor, you need to configure the monitor, run it, and send data back to {es}.
After setup is complete, the data will be available in {kib} to view, analyze, and alert on.

[[uptime-set-up-choose]]
There are two ways to set up a synthetic monitor:

* Project Monitors
* The Synthetics UI

Read more about each option below, and choose the approach that works best for you.

[discrete]
[[choose-projects]]
= Project Monitors

With Elastic Project Monitors, you write tests in an external version-controlled
project using YAML for lightweight monitors and JavaScript or TypeScript for browser monitors.
Then, you use the `@elastic/synthetics` NPM library’s `push` command to create
monitors in {kib}.

This approach works well if you want to create both browser monitors and lightweight
monitors. It also allows you to configure and update monitors using a GitOps workflow.
However, **this functionality is in beta and is subject to change.**

Get started in <<synthetics-get-started-project>>.

// to do
++++
<div style="background-color:#feedf5;color:#F04E98;height:400px;width:100%;text-align:center;padding-top:180px;margin-top:32px;margin-bottom:32px">
  To do: Add updated diagram
</div>
++++

[discrete]
[[choose-ui]]
= Synthetics UI

The Synthetics UI is an application in {kib}.
You can create monitors directly in the Synthetics UI using the user interface.
To try out this beta functionality, you will need to enable Monitor Management.

This approach works well if you want to configure and update monitors using a
UI in your browser.
However, **this functionality is in beta and is subject to change.**

Get started in <<synthetics-get-started-ui>>.

// to do
++++
<div style="background-color:#feedf5;color:#F04E98;height:400px;width:100%;text-align:center;padding-top:180px;margin-top:32px;margin-bottom:32px">
  To do: Add updated diagram
</div>
++++

[NOTE]
====
The Elastic Synthetics integration is a method for creating
synthetic monitors that is no longer recommended.
*Do not use the Elastic Synthetics integration to set up new monitors.*

For details on how to migrate from Elastic Synthetics integration to
Project Monitors or the Synthetics UI, refer to <<synthetics-migrate-from-integration>>.

If you've used the Elastic Synthetics integration to create monitors in the past
and need to reference documentation about the integration, go to the
https://www.elastic.co/guide/en/observability/8.3/uptime-set-up.html#uptime-set-up-choose-agent[8.3 documentation].
====
