[[synthetics-manage-monitors]]
= Manage synthetic monitors

After you've <<synthetic-run-tests, created a synthetic monitor>>,
you can manage those monitors including updating the contents of the tests that they run,
updating the monitor's configuration, and permanently deleting monitors.

[discrete]
[[manage-monitors-test]]
== Update a test

After you create a monitor, you might want to update the test it runs.
For example, you might change the steps in a journey that simulates the user navigating the UI to reflect recent UI updates.

[discrete]
[[manage-monitors-test-project]]
=== Project monitors

If you're using project monitors, you can update the test code wherever it's written.
Then run the <<elastic-synthetics-push-command, `push` command>> to replace any existing monitors from this project in {kib} with new monitors that uses the updated test.

[discrete]
[[manage-monitors-test-heartbeat]]
=== {heartbeat}

Update the tests in the directory specified in the `source.zip_url` you referenced in the {heartbeat} configuration file, and the changes will be reflected in the monitors.

[discrete]
[[manage-monitors-test-agent]]
=== {agent}

Update the tests at the **Zip URL** you referenced in the {agent} Integration, and the changes will be reflected in the monitors.

[discrete]
[[manage-monitors-config]]
== Update a monitor's configuration

You might also want to update the monitor's configuration.
For example, you might want to change the interval at which the monitor runs a test.

[discrete]
[[manage-monitors-config-project]]
=== Project monitors

Update the monitor configuration options used in individual journeys in the test code (or the global synthetics configuration file).
Then run the `push` command to replace the existing monitor in {kib} with a new monitor that uses the updated configuration options.

[discrete]
[[manage-monitors-config-heartbeat]]
=== {heartbeat}

Update the relevant options in the {heartbeat} configuration file, and the changes will be reflected in the monitors.

[discrete]
[[manage-monitors-config-agent]]
=== {agent}

??? Create a new monitor with updated configuration ???

[discrete]
[[manage-monitors-delete]]
== Delete a synthetic monitor 

Eventually you might want to delete a monitor altogether.
For example, if the workflow you were testing is no longer relevant to your users.

Alternatively, you can temporarily disable a monitor by updating the monitor's configuration.

[discrete]
[[manage-monitors-delete-project]]
=== Project monitors

Delete the journey in the test code and push the project using the `push` command.
The monitor associated with that journey that existed in {kib} will be deleted.

[discrete]
[[manage-monitors-delete-heartbeat]]
=== {heartbeat}

???

[discrete]
[[manage-monitors-delete-agent]]
=== {agent}

???