[[troubleshoot-uptime-mapping-issues]]

:beatname_lc: heartbeat

= Troubleshoot mapping issues

[discrete]
== Mapping issues

There are situations in which {heartbeat} data can be indexed without the correct mappings applied.
These situations cannot occur with the {elastic-agent} configured via {fleet}, only with standalone {heartbeat} or {elastic-agent} running in standalone mode.
This can occur when the underlying `heartbeat-VERSION` {ilm-init} alias is deleted manually or when {heartbeat} writes data
through an intermediary such as {ls} without the `setup` command being run.
When running {elastic-agent} in standalone mode this can happen if manually setup data streams have incorrect mappings.

To fix this problem, you typically need to remove your {heartbeat} indices and data streams.
Then you must create new ones with the appropriate mappings installed. To achieve this, follow the steps below.

[discrete]
=== Stop your {heartbeat}/{elastic-agent} instances

It is necessary to stop all {heartbeat}/{elastic-agent} instances that are targeting the cluster, so they will not write to or re-create indices prematurely.

[discrete]
=== Delete your {heartbeat} indices / {elastic-agent} data streams

To ensure the mapping is applied to all {heartbeat} data going forward,
delete all the {heartbeat} indices that match the pattern the {uptime-app} will use.

There are multiple ways to achieve this.
You can read about performing this using the {ref}/index-mgmt.html[Index Management UI] or with the {ref}/indices-delete-index.html[Delete index API].

If using {elastic-agent} you will want to fix any issues with custom data stream mappings. We encourage the use of {fleet} to eliminate this issue.

[discrete]
=== If using {heartbeat}, perform {heartbeat} setup

The below command will cause {heartbeat} to perform its setup processes and recreate the index template properly.

[source,bash]
----
./heartbeat setup -e
----

For more information on how to use this command, or if you're using DEB, RPM, or Windows, see the {heartbeat-ref}/heartbeat-installation-configuration.html[{heartbeat} quickstart guide].

This command performs the necessary startup tasks and ensures that your indices have the appropriate mapping going forward.

[discrete]
=== Run {heartbeat}/{elastic-agent} again

Now, when you run {heartbeat}/{elastic-agent}, your data will be indexed with the appropriate mappings. When
the {uptime-app} attempts to fetch your data, it should be able to render without issues.

:!beatname_lc:
