[[troubleshoot-uptime]]
= Uptime troubleshooting

== Mapping issues

There are situations in which {heartbeat} data can be indexed without the correct mappings applied.
These situations cannot occur with the {elastic-agent} configured via {fleet}, only with standalone {heartbeat}.
This can occur when the underlying `heartbeat-VERSION` ILM alias is deleted manually or when {heartbeat} writes data
through an intermediary such as {ls} without the `setup` command being run.

To fix this problem, you typically need to remove your {heartbeat} indices and create
new ones with the appropriate mappings installed. To achieve this, follow the steps below.

=== Step 1: Delete your {heartbeat} indices

To ensure the mapping is applied to all {heartbeat} data going forward,
delete all the {heartbeat} indicies that match the pattern the {uptime-app} will use.



=== Step 2: Run the {heartbeat} setup command

There are multiple ways to achieve this.
You can read about performing this using the {ref}/index-mgmt.html[Index Management UI] or with the {ref}/indices-delete-index.html[Delete index API].

=== Step 3: Perform {heartbeat} setup

The below command will cause {heartbeat} to perform its setup processes.

NOTE: For more information on how to use this command, you can reference the
{heartbeat-ref}/heartbeat-installation-configuration.html[Heartbeat quickstart guide].

["source","sh"]
----
./heartbeat setup -e 
----

This command performs the necessary startup tasks and ensures that your indicies have the appropriate mapping going forward.

=== Step 3: Run {heartbeat} again

Now, when you run {heartbeat}, your data will be indexed with the appropriate mappings. When
the {uptime-app} attempts to fetch your data, it should be able to render without issues.
