[[uptime-set-up]]
= Set up monitors

To set up an uptime monitor, you need to configure the monitor, run it, and send data back to {es}.
After setup is complete, the data will be available in the {uptime-app} in {kib} to view, analyze, and alert on.

[discrete]
[[uptime-set-up-choose]]
== Choose an approach

There are three ways to set up an uptime monitor: *{heartbeat}*, the *{uptime-app}*, or *project monitors*.

|===
| **{heartbeat}** | {heartbeat} is a lightweight daemon that you install on a remote server to periodically
check the status of your services and determine if they are available. Performance data is
then gathered and reported back to {heartbeat}, where it's formatted and sent to the {stack}.

This approach works well for system administrators wanting to configure monitors using YAML files.

Read more in <<uptime-set-up-choose-heartbeat>>.
| **{uptime-app}** | beta[] The {uptime-app} is an application in {kib}.
You can now create monitors directly in the {uptime-app}.
To try out this beta functionality, you will need to enable Monitor Management.

This approach works well if you want to configure and update monitors using a UI in your browser.
However, **this functionality is in beta and is subject to change.**

Read more in <<uptime-set-up-choose-agent>>.
| **Project monitors** | beta[] Use the `@elastic/synthetics` library's `push` command to create monitors from an external project.
Pushing your project creates a new browser monitor in {kib} for each journey in the project.

Using the `push` command allows you to manage all browser monitors using a GitOps workflow.
However, unlike the other approaches, this method can only be used to create _browser_ monitors.
**This functionality is in beta and is subject to change.**

Read more in <<synthetic-monitor-choose-project>>.
|===

NOTE: To use the Elastic Synthetics integration, see the https://www.elastic.co/guide/en/observability/8.3/uptime-set-up.html#uptime-set-up-choose-agent[8.3 documentation]. The Elastic Synthetics integration is similar to the {uptime-app} approach described above, but contains fewer configuration options and does not allow you to run monitors against Elastic's global managed testing locations.
