[[whats-new]]
= What's new in {minor-version}

Here are the highlights of what's new and improved in {minor-version}.

coming[8.0.0]

Other versions:
{observability-guide-all}/8.2/whats-new.html[8.2] |
{observability-guide-all}/8.1/whats-new.html[8.1] |
{observability-guide-all}/8.0/whats-new.html[8.0] |
{observability-guide-all}/7.17/whats-new.html[7.17] |

// tag::whats-new[]

// What's new content goes in here. Don't uncomment or remove the tags surrounding this content :)

[discrete]
== APM Server introduces support for OpenTelemetry protocol over HTTP transport
Starting in version 8.3, APM Server supports the OpenTelemetry protocol over
HTTP transport (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#otlphttp[OTLP/HTTP]).
This new support is in addition to the existing OTLP
protocol over gRPC transport (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#otlpgrpc[OTLP/gRPC]).
Both OTLP/gRPC and OTLP/HTTP use the
same ProtoBuf payload.

The OTLP/HTTP protocol is useful for users with gRPC-based infrastructure
limitations, or users who want to take advantage of the smaller HTTP dependency.
These benefits and additional details are outlined in the official https://github.com/open-telemetry/oteps/blob/main/text/0099-otlp-http.md#motivation[OpenTelemetry
HTTP proposal].

// end::whats-new[]
