[[whats-new]]
= What's new in {minor-version}

Here are the highlights of what's new and improved in {minor-version}.

Other versions:
{observability-guide-all}/8.15/whats-new.html[8.15] |
{observability-guide-all}/8.14/whats-new.html[8.14] |
{observability-guide-all}/8.13/whats-new.html[8.13] |
{observability-guide-all}/8.12/whats-new.html[8.12] |
{observability-guide-all}/8.11/whats-new.html[8.11] |
{observability-guide-all}/8.10/whats-new.html[8.10] |
{observability-guide-all}/8.9/whats-new.html[8.9] |
{observability-guide-all}/8.8/whats-new.html[8.8] |
{observability-guide-all}/8.7/whats-new.html[8.7] |
{observability-guide-all}/8.6/whats-new.html[8.6] |
{observability-guide-all}/8.5/whats-new.html[8.5] |
{observability-guide-all}/8.4/whats-new.html[8.4] |
{observability-guide-all}/8.3/whats-new.html[8.3] |
{observability-guide-all}/8.2/whats-new.html[8.2] |
{observability-guide-all}/8.1/whats-new.html[8.1] |
{observability-guide-all}/8.0/whats-new.html[8.0] |
{observability-guide-all}/7.17/whats-new.html[7.17]

// tag::whats-new[]

[discrete]
== Elastic Observability 8.16 announces several key capabilities:

**Amazon Bedrock integration for LLM observability**  adds comprehensive monitoring capabilities for LLM applications built on Amazon Bedrock. This new integration provides out-of-the-box dashboards and detailed insights into model performance, usage patterns, and costs — enabling SREs and developers to effectively monitor and optimize their generative AI (GenAI) applications built on Amazon Bedrock in addition to existing support for applications that use Azure OpenAI.

**Unified Kubernetes observability with Elastic Distributions of OpenTelemetry (EDOT)** delivers automated deployment and configuration of OpenTelemetry collectors through the OpenTelemetry Operator. This streamlined approach includes zero-code instrumentation options and preconfigured dashboards, allowing organizations to quickly gain comprehensive visibility into their Kubernetes environments without manual setup.

**Enhanced log analytics and streamlined onboarding** introduce a context-aware Discover experience and new quickstart onboarding workflows. The improved Discover interface automatically adjusts data presentation based on content type, while the new onboarding workflows simplify the setup process for host monitoring, Kubernetes monitoring, and the Amazon Firehose delivery stream.

Elastic Observability 8.16 is available now on {ess-trial}[{ecloud}] — the only hosted Elasticsearch offering to include all of the new features in this latest release. You can also https://www.elastic.co/downloads/[download the Elastic Stack] and our cloud orchestration products — Elastic Cloud Enterprise and Elastic Cloud for Kubernetes — for a self-managed experience.

What else is new in Elastic 8.16? Check out the https://www.elastic.co/blog/whats-new-elastic-8-16-0[8.16 announcement post] to learn more.

// end::whats-new[]
