[[whats-new]]
= What's new in {minor-version}

Here are the highlights of what's new and improved in {minor-version}.

Other versions:
{observability-guide-all}/8.16/whats-new.html[8.16] |
{observability-guide-all}/8.15/whats-new.html[8.15] |
{observability-guide-all}/8.14/whats-new.html[8.14] |
{observability-guide-all}/8.13/whats-new.html[8.13] |
{observability-guide-all}/8.12/whats-new.html[8.12] |
{observability-guide-all}/8.11/whats-new.html[8.11] |
{observability-guide-all}/8.10/whats-new.html[8.10] |
{observability-guide-all}/8.9/whats-new.html[8.9] |
{observability-guide-all}/8.8/whats-new.html[8.8] |
{observability-guide-all}/8.7/whats-new.html[8.7] |
{observability-guide-all}/8.6/whats-new.html[8.6] |
{observability-guide-all}/8.5/whats-new.html[8.5] |
{observability-guide-all}/8.4/whats-new.html[8.4] |
{observability-guide-all}/8.3/whats-new.html[8.3] |
{observability-guide-all}/8.2/whats-new.html[8.2] |
{observability-guide-all}/8.1/whats-new.html[8.1] |
{observability-guide-all}/8.0/whats-new.html[8.0] |
{observability-guide-all}/7.17/whats-new.html[7.17]

// tag::whats-new[]

**Elasticsearch logsdb index mode:** A dramatically reduced storage footprint of log data in {es} by up to 65%.
This means more Observability storage and search without exceeding your budget.
Learn more in the https://www.elastic.co/search-labs/blog/elasticsearch-logsdb-index-mode[logsdb index mode blog].

**Goodbye Logs Explorer, hello Discover:** As we continue our work towards a central, contextual experience for log analytics in Discover, we are making changes to both the Logs Explorer and Logs Stream apps.
See the {kibana-ref}/release-notes-8.17.0.html[Kibana release notes] for a detailed explanation of the changes and deprecations that will enable Discover to be the one stop for all logging workflows.

**Find your Kubernetes Infrastructure with full OTel support:** Within our new inventory, you can now find the core components of your Kubernetes infrastructure such as clusters, nodes, deployments, pods and services—enabling you to drill into any problems you are facing for the services you are running on Kubernetes.

What else is new in Elastic 8.17?
Check out the https://www.elastic.co/blog/whats-new-elastic-8-17-0[8.17 release blog] to find out!

// end::whats-new[]
