. Make sure your application logs to stdout/stderr.
. Follow the {filebeat-ref}/running-on-kubernetes.html[Run {filebeat} on Kubernetes] guide.
. Enable {filebeat-ref}/configuration-autodiscover-hints.html[hints-based autodiscover] (uncomment the corresponding section in `filebeat-kubernetes.yaml`).

ifdef::ecs_logs[]
. Add these annotations to your pods that log using ECS-compatible JSON. This will make sure the logs are parsed appropriately.
+
[source,yaml]
----
annotations:
co.elastic.logs/json.overwrite_keys: true   <1>
co.elastic.logs/json.add_error_key: true   <2>
co.elastic.logs/json.expand_keys: true   <3>
----
+
<1> Values from the decoded JSON object overwrite the fields that {filebeat} normally adds (type, source, offset, etc.) in case of conflicts.
+
<2> {filebeat} adds an "error.message" and "error.type: json" key in case of JSON unmarshalling errors.
+
<3> {filebeat} will recursively de-dot keys in the decoded JSON, and expand them into a hierarchical object structure.
endif::[]

ifdef::plaintext[]

endif::[]
