[[apm-view-and-analyze-data]]
= View and analyze data

After you've started <<apm-collect-application-data,sending application data to Elastic>>,
you can open the Applications UI in {kib} to view your data in a variety of visualizations and
start analyzing data.

The Applications UI allows you to monitor your software services and applications in real-time.
You can visualize detailed performance information on your services,
identify and analyze errors,
and monitor host-level and APM agent-specific metrics like JVM and Go runtime metrics.

Having access to application-level insights with just a few clicks can drastically decrease the time you spend
debugging errors, slow response times, and crashes.

For example, you can see information about response times, requests per minute, and status codes per endpoint.
You can even dive into a specific request sample and get a complete waterfall view of what your application is spending its time on.
You might see that your bottlenecks are in database queries, cache calls, or external requests.
For each incoming request and each application error,
you can also see contextual information such as the request header, user information,
system values, or custom data that you manually attached to the request.

To get started with the Applications UI:

* Start with quick, high-level <<apm-ui,overviews>> that show you the overall health and performance of
  your application.
* <<apm-ui-drill-down,Drill down into data>> for specific services or traces to get additional insight into
  your application.
* Learn how to get the most out of your data by mastering how to <<apm-filter-and-search-data,search and filter data>>
  in {kib}, getting tips on <<apm-interpret-data,how to interpret data>>, and taking advantage of
  <<apm-machine-learning-integration,machine learning>>.

include::{observability-docs-root}/docs/en/observability/apm/view-and-analyze/ui-overview/index.asciidoc[leveloffset=+1]
include::{observability-docs-root}/docs/en/observability/apm/view-and-analyze/drill-down/index.asciidoc[leveloffset=+1]
include::{observability-docs-root}/docs/en/observability/apm/view-and-analyze/filter-and-search/index.asciidoc[leveloffset=+1]
include::{observability-docs-root}/docs/en/observability/apm/view-and-analyze/interpret/index.asciidoc[leveloffset=+1]
include::{observability-docs-root}/docs/en/observability/apm/view-and-analyze/machine-learning.asciidoc[leveloffset=+1]
include::{observability-docs-root}/docs/en/observability/apm/view-and-analyze/agent-explorer.asciidoc[leveloffset=+1]
include::{observability-docs-root}/docs/en/observability/apm/view-and-analyze/settings.asciidoc[leveloffset=+1]
