[[ingest-aws-beats]]
== Ingest with Beats

++++
<titleabbrev>Ingest with Beats</titleabbrev>
++++

Beats are lightweight data shippers that send operational data to Elasticsearch. Elastic provides separate Beats for different types of data, such as logs, metrics, and uptime. Depending on what data you want to collect, you may need to install multiple shippers on a single host.

[discrete]
[[aws-beats-data-streams]]
=== What type of data can I collect

With Beats you can collect two types of data: logs and metrics. Use https://www.elastic.co/guide/en/beats/filebeat/8.12/filebeat-overview.html[Filebeat module] for AWS logs and https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-overview.html[Metricbeat module] for AWS metrics.

[discrete]
[[aws-beats-prerequisites]]
=== Prerequisites

* An account on Elastic Cloud and a deployed stack on AWS. For instructions, refer to Installing the Elastic Stack.
* An AWS account with permissions to pull the necessary data from AWS.

[discrete]
[[aws-beats-setup]]
=== Setup

*Filebeat module for AWS logs*

Filebeat monitors the log files or locations that you specify, collects log events, and forwards them either to Elasticsearch or Logstash for indexing.

- https://www.elastic.co/guide/en/beats/filebeat/8.12/setting-up-and-running.html[Set up and run Filebeat]
- https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-aws.html[Configure the AWS module]

*Metricbeat module for AWS metrics*

Metricbeats collects metrics from the operating system and from services running on the server and ships them to the output that you specify, such as Elasticsearch or Logstash.

- https://www.elastic.co/guide/en/beats/metricbeat/current/setting-up-and-running.html[Set up and run Metricbeat]
- https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-aws.html[Configure the AWS module]