[[ingest-aws-agent]]
== Ingest with Elastic Agent

++++
<titleabbrev>Ingest with Elastic Agent</titleabbrev>
++++

Elastic Agent is a single agent for logs, metrics, security data, and threat prevention. The Elastic Agent can be deployed in two different modes:

* Managed by Fleet — The Elastic Agent policies and lifecycle are centrally managed by the Fleet app in Kibana. The Integrations app also lets you centrally add integrations with other popular services and systems. This is the recommended option for most users.

* Standalone mode — All policies are applied to the Elastic Agent manually as a YAML file. This is intended for more advanced users. See Install standalone Elastic Agents (advanced users)for more information.

For general information on Elastic Agent and central management in Fleet, check https://www.elastic.co/guide/en/fleet/current/fleet-overview.html[Fleet and Elastic Agent overview].

[discrete]
[[aws-agent-data-streams]]
=== What type of data can I collect

With Elastic Agent you can collect two types of data: logs and metrics.

[discrete]
[[aws-agent-prerequisites]]
=== Prerequisites

* An account on Elastic Cloud and a deployed stack on AWS. For instructions, refer to Installing the Elastic Stack.
* An AWS account with permissions to pull the necessary data from AWS.

[discrete]
[[aws-agent-setup]]
=== Setup

Follow the installation instructions in the https://www.elastic.co/guide/en/fleet/current/fleet-elastic-agent-quick-start.html[Quick starts] to get you started.