[[ingest-aws-beats]]
== Ingest with Beats

++++
<titleabbrev>Ingest with Beats</titleabbrev>
++++

Beats are lightweight data shippers that send operational data to Elasticsearch. Elastic provides separate Beats for different types of data, such as logs, metrics, and uptime. Depending on what data you want to collect, you may need to install multiple shippers on a single host.

[discrete]
=== Filebeat module for AWS logs

Filebeat is a lightweight shipper for forwarding and centralizing log data. Installed as an agent on your servers, Filebeat monitors the log files or locations that you specify, collects log events, and forwards them either to Elasticsearch or Logstash for indexing.

To configure the AWS module, check the https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-aws.html[module-specific documentation].

[discrete]
=== Metricbeat module for AWS metrics

Metricbeat is a lightweight shipper that you can install on your servers to periodically collect metrics from the operating system and from services running on the server. Metricbeat takes the metrics and statistics that it collects and ships them to the output that you specify, such as Elasticsearch or Logstash.

To configure the AWS module, check the https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-aws.html[module-specific documentation].

