[[ingest-aws-firehose]]
== Ingest with Amazon Data Firehose

++++
<titleabbrev>Ingest with Amazon Data Firehose</titleabbrev>
++++

Amazon Data Firehose is a popular service that delivers streaming data from over 20 AWS services such as AWS IoT Core and Amazon CloudWatch logs to over 15 analytical and observability tools such as Elastic. Amazon Data Firehose provides a fast and easy way to send your VPC flow logs data to Elastic in minutes without a single line of code and without building or managing your own data ingestion and delivery infrastructure.

[discrete]
[[aws-firehose-data-streams]]
=== What type of data can I collect

With Amazon Data Firehose you can collect logs.

[discrete]
[[aws-firehose-prerequisites]]
=== Prerequisites

* An account on Elastic Cloud and a deployed stack on AWS. For instructions, refer to Installing the Elastic Stack.
* An AWS account with permissions to pull the necessary data from AWS.

[discrete]
[[aws-firehose-setup]]
=== Setup


Reuse content from this blog: 
https://aws.amazon.com/blogs/big-data/accelerate-data-insights-with-elastic-and-amazon-kinesis-data-firehose/


