[[monitor-aws-firelens]]
== Monitor Amazon Web Services ({aws}) with with Firelens

++++
<titleabbrev>Monitor {aws} with Firelens</titleabbrev>
++++

AWS FireLens is a container log router for Amazon Elastic Container Service (Amazon ECS) launch types: Amazon Elastic Compute Cloud (Amazon EC2) and AWS Fargate. You can now directly ship container logs and events to Elastic Cloud with Amazon Web Services (AWS) FireLens. This integration enables DevOps and DevSecOps experts to streamline AWS log management from shipping and cost-efficient log retention, to monitoring and analyzing threats.

[discrete]
[[aws-firelens-data-streams]]
=== What type of data can I collect

With AWS FireLens you can collect logs.

[discrete]
[[aws-firelens-prerequisites]]
=== Prerequisites

* An account on Elastic Cloud and a deployed stack on AWS. For instructions, refer to Installing the Elastic Stack.
* An AWS account with permissions to pull the necessary data from AWS.

[discrete]
[[aws-firelens-setup]]
=== Setup

Reuse content from this blog: https://www.elastic.co/blog/elastic-cloud-with-aws-firelens-accelerate-time-to-insight-with-agentless-data-ingestion