[[monitor-aws-cloudtrail-firehose]]
= Monitor CloudTrail logs

++++
<titleabbrev>Monitor CloudTrail logs</titleabbrev>
++++

In this section, you'll learn how to monitor and analyze the CloudTrail logs you sent to Elastic with Amazon Data Firehose. 

[discrete]
[[firehose-cloudtrail-prerequisites]]
== Before you begin

We assume that you already have:

- An AWS account with permissions to pull the necessary data from AWS.
- A deployment using our hosted {ess} on {ess-trial}[{ecloud}]. The deployment includes an {es} cluster for storing and searching your data, and {kib} for visualizing and managing your data. AWS Data Firehose works with Elastic Stack version 7.17 or greater, running on Elastic Cloud only.

IMPORTANT: Make sure the deployment is on AWS, because the Firehose delivery stream connects specifically to an endpoint that needs to be on AWS.

[discrete]
[[firehose-cloudtrail-step-one]]
== Step 1: Export Cloudtrail events to CloudWatch

[discrete]
[[firehose-cloudtrail-step-two]]
== Step 2: Set up a Firehose delivery stream

[discrete]
[[firehose-cloudtrail-step-three]]
== Step 3: Set up a subscription filter to route Cloudtrail events to a delivery stream


