[[monitor-aws-firehose]]
== Monitor Amazon Web Services ({aws}) with Amazon Data Firehose

++++
<titleabbrev>Monitor {aws} with Amazon Data Firehose</titleabbrev>
++++

Amazon Data Firehose is a popular service that delivers streaming data from over 20 AWS services such as AWS IoT Core and Amazon CloudWatch logs to over 15 analytical and observability tools such as Elastic. Amazon Data Firehose provides a fast and easy way to send your VPC flow logs data to Elastic in minutes without a single line of code and without building or managing your own data ingestion and delivery infrastructure.

[discrete]
[[aws-firehose-what-you-learn]]
=== What you'll learn


[discrete]
[[aws-firehose-prerequisites]]
=== Before you begin

Create a deployment using our hosted {ess} on {ess-trial}[{ecloud}].
The deployment includes an {es} cluster for storing and searching your data,
and {kib} for visualizing and managing your data.
You also need an AWS account with permissions to pull the necessary data from AWS.

[discrete]
[[aws-firehose-setup]]
=== Setup

Reuse content from this blog: 
https://aws.amazon.com/blogs/big-data/accelerate-data-insights-with-elastic-and-amazon-kinesis-data-firehose/


