[[monitor-aws-cloudtrail-firehose]]
= Monitor CloudTrail logs

++++
<titleabbrev>Monitor CloudTrail logs</titleabbrev>
++++

In this section, you'll learn how to monitor and analyze the CloudTrail logs you sent to Elastic with Amazon Data Firehose. 

[discrete]
[[firehose-cloudtrail-prerequisites]]
== Before you begin

We assume that you already have:

- An AWS account with permissions to pull the necessary data from AWS.
- A deployment using our hosted {ess} on {ess-trial}[{ecloud}]. The deployment includes an {es} cluster for storing and searching your data, and {kib} for visualizing and managing your data. AWS Data Firehose works with Elastic Stack version 7.17 or greater, running on Elastic Cloud only.

IMPORTANT: Make sure the deployment is on AWS, because the Firehose delivery stream connects specifically to an endpoint that needs to be on AWS.

[discrete]
[[firehose-cloudtrail-step-one]]
== Step 1: Install AWS integration in {kib}

. Install AWS integrations to load index templates, ingest pipelines, and dashboards into {kib}. In {kib}, navigate to *Management* > *Integrations* in the sidebar. Find the AWS Integration by browsing the catalog.

. Navigate to the *Settings* tab and click *Install AWS assets*. Confirm by clicking *Install AWS* in the popup.

. Install AWS Firehose integration assets in Kibana. 

NOTE: Firehose integration is currently in beta. Make sure to enable *Display beta integrations*.

[discrete]
[[firehose-cloudtrail-step-two]]
== Step 2: Export Cloudtrail events to CloudWatch

. Go to the https://console.aws.amazon.com/[AWS console] and navigate to CloudTrail.  

. Click *Create trail* and configure the general details on the *Choose trail attributes* panel.
+
NOTE: By default, CloudTrail exports data to either a new or an existing S3 bucket. It is not possible to opt ot from S3, but you can ptionally enable CloudWatch logs.

. Enable *CloudWatch Logs* and confirm the *Log group name*.

. From the *Choose log events* panel, select the event types you want to send to Elastic.

. Review the attributes and log events you have just defined and click *Create trail*.

[discrete]
[[firehose-cloudtrail-step-three]]
== Step 3: Set up a Firehose delivery stream


[discrete]
[[firehose-cloudtrail-step-four]]
== Step 4: Set up a subscription filter to route Cloudtrail events to a delivery stream


