[[observability-apm-agents-opentelemetry-limitations]]
= Limitations

// :keywords: serverless, observability, overview

[discrete]
[[observability-apm-agents-opentelemetry-limitations-opentelemetry-traces]]
== OpenTelemetry traces

* Traces of applications using `messaging` semantics might be wrongly displayed as `transactions` in the Applications UI, while they should be considered `spans` (see issue https://github.com/elastic/apm-server/issues/7001[#7001]).
* Inability to see Stack traces in spans.
* Inability in APM views to view the "Time Spent by Span Type"  (see issue https://github.com/elastic/apm-server/issues/5747[#5747]).

[discrete]
[[open-telemetry-logs-intake]]
== OpenTelemetry logs

* preview:[]  The OpenTelemetry logs intake via Elastic is in technical preview.
* The application logs data stream (`app_logs`) has dynamic mapping disabled. This means the automatic detection and mapping of new fields is disabled (see issue https://github.com/elastic/apm-server/issues/9093[#9093]).

[discrete]
[[open-telemetry-otlp-limitations]]
== OpenTelemetry Line Protocol (OTLP)

Elastic supports both the
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#otlpgrpc[(OTLP/gRPC)] and
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#otlphttp[(OTLP/HTTP)] protocol
with ProtoBuf payload. Elastic does not yet support JSON Encoding for OTLP/HTTP.

[discrete]
[[open-telemetry-collector-exporter]]
== OpenTelemetry Collector exporter for Elastic

The https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/elasticsearchexporter#legacy-opentelemetry-collector-exporter-for-elastic[OpenTelemetry Collector exporter for Elastic]
has been deprecated and replaced by the native support of the OpenTelemetry Line Protocol in Elastic Observability (OTLP). To learn more, see https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/elasticsearchexporter#migration[migration].

The https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/elasticsearchexporter[OpenTelemetry Collector exporter for Elastic]
(which is different from the legacy exporter mentioned above) is not intended to be used with Elastic APM and {obs-serverless}. Use <<observability-apm-agents-opentelemetry-opentelemetry-native-support,Elastic's native OTLP support>> instead.
