[[apm-data-model-spans]]
= Spans

status_badge::[serverless, ga]
status_badge::[stack, ga]

include::{observability-docs-root}/docs/en/observability/partials/apm-server-vs-mis.asciidoc[]

*Spans* contain information about the execution of a specific code path.
They measure from the start to the end of an activity,
and they can have a parent/child relationship with other spans.

Agents automatically instrument a variety of libraries to capture these spans from within your application,
but you can also use the Agent API for custom instrumentation of specific code paths.

Among other things, spans can contain:

* A `transaction.id` attribute that refers to its parent <<apm-data-model-transactions,transaction>>.
* A `parent.id` attribute that refers to its parent span or transaction.
* Its start time and duration.
* A `name`, `type`, `subtype`, and `action`—see the {span-name-type-sheet}[span name/type alignment]
sheet for span name patterns and examples by {apm-agent}.
In addition, some APM agents test against a public {span-spec}[span type/subtype spec].
* An optional `stack trace`. Stack traces consist of stack frames,
which represent a function call on the call stack.
They include attributes like function name, file name and path, line number, etc.

TIP: Most agents limit keyword fields, like `span.id`, to 1024 characters,
and non-keyword fields, like `span.start.us`, to 10,000 characters.

[float]
[[apm-data-model-dropped-spans]]
== Dropped spans

For performance reasons, APM agents can choose to sample or omit spans purposefully.
This can be useful in preventing edge cases, like long-running transactions with over 100 spans,
that would otherwise overload both the Agent and the {apm-server-or-mis}.
When this occurs, the Applications UI will display the number of spans dropped.

To configure the number of spans recorded per transaction, see the relevant Agent documentation:

* Android: _Not supported_
* Go: {apm-go-ref-v}/configuration.html#config-transaction-max-spans[`ELASTIC_APM_TRANSACTION_MAX_SPANS`]
* iOS: _Not supported_
* Java: {apm-java-ref-v}/config-core.html#config-transaction-max-spans[`transaction_max_spans`]
* .NET: {apm-dotnet-ref-v}/config-core.html#config-transaction-max-spans[`TransactionMaxSpans`]
* Node.js: {apm-node-ref-v}/configuration.html#transaction-max-spans[`transactionMaxSpans`]
* PHP: {apm-php-ref-v}/configuration-reference.html#config-transaction-max-spans[`transaction_max_spans`]
* Python: {apm-py-ref-v}/configuration.html#config-transaction-max-spans[`transaction_max_spans`]
* Ruby: {apm-ruby-ref-v}/configuration.html#config-transaction-max-spans[`transaction_max_spans`]

[float]
[[apm-data-model-missing-spans]]
== Missing spans

Agents stream spans to the {apm-server-or-mis} separately from their transactions.
Because of this, unforeseen errors may cause spans to go missing.
Agents know how many spans a transaction should have;
if the number of expected spans does not equal the number of spans received by the {apm-server-or-mis},
the Applications UI will calculate the difference and display a message.

[float]
== Data streams

Spans are stored with transactions in the following data streams:

include::{observability-docs-root}/docs/en/observability/apm/manage-storage/data-streams.asciidoc[tag=traces-data-streams]

See <<apm-data-streams>> to learn more.

[float]
== Example span document

This example shows what span documents can look like when indexed in {es}.

[%collapsible]
.Expand {es} document
====
// Temporarily remove for status-badge test
// [source,json]
// ----
// include::{apm-server-root}/docs/data/elasticsearch/generated/spans.json[]
// ----
====

[float]
[[apm-spans-span-compression]]
== Span compression

In some cases, APM agents may collect large amounts of very similar or identical spans in a transaction.
For example, this can happen if spans are captured inside of a loop, or in unoptimized SQL queries that use multiple queries instead of joins to fetch related data.
In such cases, the upper limit of spans per transaction (by default, 500 spans) can be reached quickly, causing the agent to stop capturing potentially more relevant spans for a given transaction.

Such repeated similar spans often aren't very relevant for themselves, especially if they are of very short duration.
They also can clutter the UI, and cause processing and storage overhead.

To address this problem, the APM agents can compress such spans into a single span.
The compressed span retains most of the original span information, such as overall duration and the number of spans it represents.

Regardless of the compression strategy, a span is eligible for compression if:

- It has not propagated its trace context.
- Is an _exit_ span (such as database query spans).
- Its outcome is not `"failure"`.


[float]
[[apm-span-compression-strategy]]
=== Compression strategies

The {apm-agent} can select between two strategies to decide if two adjacent spans can be compressed.
Both strategies have the benefit that only one previous span needs to be kept in memory.
This is important to ensure that the agent doesn't require large amounts of memory to enable span compression.

[float]
[[apm-span-compression-same]]
==== Same-Kind strategy

The agent selects this strategy if two adjacent spans have the same:

 * span type
 * span subtype
 * `destination.service.resource` (e.g. database name)

[float]
[[apm-span-compression-exact]]
==== Exact-Match strategy

The agent selects this strategy if two adjacent spans have the same:

 * span name
 * span type
 * span subtype
 * `destination.service.resource` (e.g. database name)

[float]
[[apm-span-compression-settings]]
=== Settings

The agent has configuration settings to define upper thresholds in terms of span duration for both strategies.
For the "Same-Kind" strategy, the default limit is 0 milliseconds, which means that the "Same-Kind" strategy is disabled by default. For the "Exact-Match" strategy, the default limit is 50 milliseconds.
Spans with longer duration are not compressed. Please refer to the agent documentation for specifics.

[float]
[[apm-span-compression-support]]
=== Agent support

Support for span compression is available in these agents:

[options="header"]
|====
| Agent | Same-kind config | Exact-match config
| **Go agent**
| {apm-go-ref-v}/configuration.html#config-span-compression-same-kind-duration[`ELASTIC_APM_SPAN_COMPRESSION_SAME_KIND_MAX_DURATION`]
| {apm-go-ref-v}/configuration.html#config-span-compression-exact-match-duration[`ELASTIC_APM_SPAN_COMPRESSION_EXACT_MATCH_MAX_DURATION`]
| **Java agent**
| {apm-java-ref-v}/config-huge-traces.html#config-span-compression-same-kind-max-duration[`span_compression_same_kind_max_duration`]
| {apm-java-ref-v}/config-huge-traces.html#config-span-compression-exact-match-max-duration[`span_compression_exact_match_max_duration`]
| **.NET agent**
| {apm-dotnet-ref-v}/config-core.html#config-span-compression-same-kind-max-duration[`SpanCompressionSameKindMaxDuration`]
| {apm-dotnet-ref-v}/config-core.html#config-span-compression-exact-match-max-duration[`SpanCompressionExactMatchMaxDuration`]
| **Node.js agent**
| {apm-node-ref-v}/configuration.html#span-compression-same-kind-max-duration[`spanCompressionSameKindMaxDuration`]
| {apm-node-ref-v}/configuration.html#span-compression-exact-match-max-duration[`spanCompressionExactMatchMaxDuration`]
// | **PHP agent**
// | {apm-php-ref-v}[``]
// | {apm-php-ref-v}[``]
| **Python agent**
| {apm-py-ref-v}/configuration.html#config-span-compression-same-kind-max-duration[`span_compression_same_kind_max_duration`]
| {apm-py-ref-v}/configuration.html#config-span-compression-exact-match-max_duration[`span_compression_exact_match_max_duration`]
// | **Ruby agent**
// | {apm-ruby-ref-v}[``]
// | {apm-ruby-ref-v}[``]
|====
