[[apm-data-model-errors]]
= Errors

An error event contains at least
information about the original `exception` that occurred
or about a `log` created when the exception occurred.
For simplicity, errors are represented by a unique ID.

An Error contains:

* Both the captured `exception` and the captured `log` of an error can contain a `stack trace`,
which is helpful for debugging.
* The `culprit` of an error indicates where it originated.
* An error might relate to the <<apm-data-model-transactions,transaction>> during which it happened,
via the `transaction.id`.
* Data about the environment in which the event is recorded:
** Service - environment, framework, language, etc.
** Host - architecture, hostname, IP, etc.
** Process - args, PID, PPID, etc.
** URL - full, domain, port, query, etc.
** <<apm-data-model-user,User>> - (if supplied) email, ID, username, etc.

In addition, agents provide options for users to capture custom <<apm-data-model-metadata,metadata>>.
Metadata can be indexed - <<apm-data-model-labels,`labels`>>, or not-indexed - <<apm-data-model-custom,`custom`>>.

TIP: Most agents limit keyword fields (e.g. `error.id`) to 1024 characters,
non-keyword fields (e.g. `error.exception.message`) to 10,000 characters.

Errors are stored in error indices.

[float]
== Data streams

Errors are stored in the following data streams:

include::{observability-docs-root}/docs/en/observability/apm/manage-storage/data-streams.asciidoc[tag=logs-data-streams]

See <<apm-data-streams>> to learn more.

[float]
== Example error document

This example shows what error documents can look like when indexed in {es}.

[%collapsible]
.Expand {es} document
====
[source,json]
----
include::{apm-server-root}/docs/data/elasticsearch/generated/errors.json[]
----
====
