[[apm-agents]]
= APM agents

status_badge::[serverless, ga]
status_badge::[stack, ga]

Elastic APM agents automatically measure application performance and track errors.
They offer built-in support for popular frameworks and technologies, and provide easy-to-use
APIs that allow you to instrument any application.

[discrete]
== Available APM agents

Elastic APM agents are built and maintained by Elastic. While they are similar, different
programming languages have different nuances and requirements. Refer to each APM agent's
documentation to learn how to install the agent, configure it, and more:

* {apm-android-ref}/intro.html[APM Android agent]
status_badge::[serverless, unavailable]
* {apm-go-ref}/introduction.html[APM Go agent]
* {apm-ios-ref}/intro.html[APM iOS agent]
status_badge::[serverless, unavailable]
* {apm-java-ref}/intro.html[APM Java agent]
* {apm-dotnet-ref}/intro.html[APM .NET agent]
* {apm-node-ref}/intro.html[APM Node.js agent]
* {apm-php-ref}/intro.html[APM PHP agent]
* {apm-py-ref}/getting-started.html[APM Python agent]
* {apm-ruby-ref}/introduction.html[APM Ruby agent]
* {apm-rum-ref}/intro.html[APM Real User Monitoring JavaScript agent]
status_badge::[serverless, unavailable]

[discrete]
== More APM agent resources

Though you should refer to each APM agent's documentation for information on using the agent,
there are some tasks you can complete in the Applications UI:

* <<apm-agent-configuration>> status_badge::[serverless, unavailable]
* <<apm-source-map-how-to,Upload a RUM source map>> status_badge::[serverless, unavailable]

////
Subsections
////

include::{observability-docs-root}/docs/en/observability/apm/collect-application-data/agents/agent-configuration.asciidoc[leveloffset=+1]
include::{observability-docs-root}/docs/en/observability/apm/collect-application-data/agents/rum.asciidoc[leveloffset=+1]
include::{observability-docs-root}/docs/en/observability/apm/collect-application-data/agents/source-map-how-to.asciidoc[leveloffset=+1]
