|===
| Option (type) | Description

| [[monitor-tcp-hosts]]**`hosts`**
(<<synthetics-lightweight-data-string,string>>)
a| **Required**. The host to ping. The value can be:

* **A hostname and port, such as `localhost:12345`.**
Synthetics connects to the port on the specified host. If the monitor is {heartbeat-ref}/configuration-ssl.html[configured to use SSL], Synthetics establishes an SSL/TLS-based connection. Otherwise, it establishes a TCP connection.
* **A full URL using the syntax `scheme://<host>:[port]`**, where:
+
** `scheme` is one of `tcp`, `plain`, `ssl` or `tls`. If `tcp` or `plain` is specified, Synthetics establishes a TCP connection even if the monitor is configured to use SSL. If `tls` or `ssl` is specified, Synthetics establishes an SSL connection. However, if the monitor is not configured to use SSL, the system defaults are used (currently not supported on Windows).
** `host` is the hostname.
** `port` is the port number.

**Examples**:

[source,yaml]
----
hosts: "localhost:8000"
----

[source,yaml]
----
hosts: "tcp://localhost:8000"
----

| [[monitor-tcp-check]]**`check`**
a| An optional payload string to send to the remote host and the expected answer. If no payload is specified, the endpoint is assumed to be available if the connection attempt was successful. If `send` is specified without `receive`, any response is accepted as OK. If `receive` is specified without `send`, no payload is sent, but the client expects to receive a payload in the form of a "hello message" or "banner" on connect.

**Example**:

[source,yaml]
----
check.send: 'Hello World'
check.receive: 'Hello World'
----

[source,yaml]
----
check:
  send: 'Hello World'
  receive: 'Hello World'
----

| [[monitor-tcp-proxy_url]]**`proxy_url`**
a| The URL of the SOCKS5 proxy to use when connecting to the server. The value must be a URL with a scheme of socks5://.

If the SOCKS5 proxy server requires client authentication, then a username and password can be embedded in the URL.

When using a proxy, hostnames are resolved on the proxy server instead of on the client. You can change this behavior by setting the `proxy_use_local_resolver` option.

**Examples**:

A proxy URL that requires client authentication:

[source,yaml]
----
proxy_url: socks5://user:password@socks5-proxy:2233
----

| [[monitor-tcp-proxy_use_local_resolver]]**`proxy_use_local_resolver`**
(<<synthetics-lightweight-data-bool,boolean>>)
a| A Boolean value that determines whether hostnames are resolved locally instead of being resolved on the proxy server. The default value is `false`, which means that name resolution occurs on the proxy server.

**Default**: `false`

| [[monitor-tcp-ssl]]**`ssl`**
({heartbeat-ref}/configuration-ssl.html[SSL])
a| The TLS/SSL connection settings. If the monitor is {heartbeat-ref}/configuration-ssl.html[configured to use SSL], it will attempt an SSL handshake. If `check` is not configured, the monitor will only check to see if it can establish an SSL/TLS connection. This check can fail either at TCP level or during certificate validation.

**Example**:

[source,yaml]
----
ssl:
  certificate_authorities: ['/etc/ca.crt']
  supported_protocols: ["TLSv1.0", "TLSv1.1", "TLSv1.2"]
----

Also see {heartbeat-ref}/configuration-ssl.html[Configure SSL] for a full description of the `ssl` options.
|===
