[[debug-standalone-agents]]
= Debug standalone {agent}s

When you run standalone {agent}s, you are responsible for monitoring the status
of your deployed {agent}s. You cannot view the status or logs in {fleet}.

Use the following tips to help identify potential issues.

Also refer to <<fleet-troubleshooting>> for guidance on specific problems.

NOTE: You might need to log in as a root user (or Administrator on Windows) to
run these commands.

[discrete]
== Check the status of the running {agent}

To check the status of the running {agent} daemon and other processes managed by
{agent}, run the `status` command. For example:

[source,shell]
----
elastic-agent status
----

Returns something like: 

[source,yaml]
----
Status: HEALTHY
Message: (no message)
Applications:
  * metricbeat  (HEALTHY)
                Running
  * filebeat    (STOPPING)
                (no message)
----

By default, this command returns the status in human-readable format. Use the
`--output` flag to change it to `json` or `yaml`.

For more information about this command, refer to
<<elastic-agent-status-command>>.

//REVIEWERS: Looks like JSON and YAML return status codes instead of healthy,
//stopping, etc. Where can I find the mapping of status code to status?

[discrete]
[[inspect-standalone-agent-logs]]
== Inspect {agent} and related logs

If the {agent} status is unhealthy, or behaving unexpectedly, inspect the logs
of the running {agent}. The log location varies by platform. Refer to
<<installation-layout>> for the correct location.

//REVIEWERS: Can we add more guidance here about how to explore logs, what to
//look for, etc.

[discrete]
[[increase-log-level]]
== Increase the log level of the running {agent}

The log level of the running agent is set to `info` by default. At this level,
{agent} will log informational messages, including the number of events that are
published. It also logs any warnings, errors, or critical errors.

To increase the log level, set it to `debug` in the `elastic-agent.yml` file.

The `debug` setting configures {agent} to log debug messages, including a
detailed printout of all flushed events, plus all the information collected at
other log levels.

Set other options if you want write logs to a file. For example:

[source,yaml]
----
agent.logging.level: debug
agent.logging.to_files: true
agent.logging.files:
  path: /var/log/elastic-agent
  name: elastic-agent
  keepfiles: 7
  permissions: 0600
----

For other log settings, refer to <<elastic-agent-standalone-logging-config>>.

//REVIEWERS: Should we also talk about exposing the agent monitoring endpoint
//here? Sounds like that could be risky. We could point to the topic and
//let users decides.

[discrete]
[[inspect-configuration]]
== Inspect the {agent} configuration

To inspect the {agent} configuration, run the `inspect` command. For example:

[source,shell]
----
elastic-agent inspect
----

Use the `--output` flag to inspect the configuration passed to other processes,
such as {filebeat}. For example:

[source,shell]
----
elastic-agent inspect output --output default --program filebeat
----

Returns something like:

["source","yaml",subs="attributes"]
----
[default] filebeat:
filebeat:
  inputs:
  - exclude_files:
    - .gz$
    id: logfile-system.auth-default-system
    index: logs-system.auth-default
    meta:
      package:
        name: system
        version: {version}
    multiline:
      match: after
      pattern: ^\s
    name: system-1
    paths:
    - /var/log/auth.log*
    - /var/log/secure*
    processors:
    - add_locale: null
    - add_fields:
        fields:
          dataset: system.auth
          namespace: default
          type: logs
        target: data_stream
    - add_fields:
        fields:
          dataset: system.auth
        target: event
    - add_fields:
        fields:
          id: 3c4a8f14-561a-449f-8935-7485cd494bac
          snapshot: false
          version: {version}
        target: elastic_agent
    - add_fields:
        fields:
          id: 3c4a8f14-561a-449f-8935-7485cd494bac
        target: agent
    revision: 1
    type: log
  - exclude_files:
    - .gz$
    id: logfile-system.syslog-default-system
    index: logs-system.syslog-default
    meta:
      package:
        name: system
        version: 1.6.4
    multiline:
      match: after
      pattern: ^\s
    name: system-1
    paths:
    - /var/log/messages*
    - /var/log/syslog*
    processors:
    - add_locale: null
    - add_fields:
        fields:
          dataset: system.syslog
          namespace: default
          type: logs
        target: data_stream
    - add_fields:
        fields:
          dataset: system.syslog
        target: event
    - add_fields:
        fields:
          id: 3c4a8f14-561a-449f-8935-7485cd494bac
          snapshot: false
          version: {version}
        target: elastic_agent
    - add_fields:
        fields:
          id: 3c4a8f14-561a-449f-8935-7485cd494bac
        target: agent
    revision: 1
    type: log
output:
  elasticsearch:
    api_key: your:apikey
    hosts:
    - https://5d87573b66ed4d7f6cd1d2d3f1e30bc5.us-central1.gcp.foundit.no:443
----

For more information about this command, refer to
<<elastic-agent-inspect-command>>.
