[[elastic-agent-configuration]]
[role="xpack"]
= Policy settings

The policy settings for {fleet}-managed agents are specified through the UI.
You do not set them explicitly in a configuration file.

For standalone agents, you need to configure settings in the `elastic-agent.yml`
file. Prior to installation, edit the file located in the extracted {agent}
package. After installation, edit the file located in the directory
described in <<installation-layout>>. 

TIP: To get started quickly, you can use {fleet} to generate a standalone
configuration. For more information, see <<run-elastic-agent-standalone>>.

//TODO: Revisit this topic after merging
// https://github.com/elastic/observability-docs/pull/424.

// include output settings
include::configuration/outputs/output-configuration.asciidoc[]

[discrete]
[[elastic-agent-monitoring-configuration]]
== {beats} monitoring settings

{agent} monitors {beats} by default. To disable or change monitoring
settings, set options under `agent.monitoring`:

[source,yaml]
-------------------------------------------------------------------------------------
agent.monitoring:
  # enabled turns on monitoring of running processes
  enabled: true
  # enables log monitoring
  logs: true
  # enables metrics monitoring
  metrics: true
  # specifies output to be used
  use_output: monitoring
-------------------------------------------------------------------------------------


To disable monitoring, set `agent.monitoring.enabled` to `false`. When set to
`false`, {beats} monitoring is turned off, and all other options in this section
are ignored.

To enable monitoring, set `agent.monitoring.enabled` to `true`. Also set the
`logs` and `metrics` settings to control whether logs, metrics, or both are
collected. If neither setting is specified, monitoring is disabled. Set
`use_output` to specify the output to which monitoring events are sent.

[discrete]
[[elastic-agent-input-configuration]]
== Input settings

By default {agent} collects system metrics, such as cpu, memory, network, and
filesystem metrics, and sends them to the default output. For example:


[source,yaml]
-------------------------------------------------------------------------------------
inputs:
  - type: system/metrics
    data_stream.namespace: default
    use_output: default
    streams:
      - metricset: cpu
        data_stream.dataset: system.cpu
      - metricset: memory
        data_stream.dataset: system.memory
      - metricset: network
        data_stream.dataset: system.network
      - metricset: filesystem
        data_stream.dataset: system.filesystem
-------------------------------------------------------------------------------------

If `use_output` is not specified, the `default` output is used.

[discrete]
== Reference yaml

The {agent} installation includes an `elastic-agent.reference.yml` file that
describes all the settings available in a standalone configuration.

The contents of the file are included here for your convenience.

[source,yaml]
----
include::elastic-agent-reference-yaml.yml[]
----
