[[elastic-agent-installation]]
= Install {agent}s

You have a few options for installing and managing an {agent}:

* **Install a {fleet}-managed {agent} (recommended)**
+
With this approach, you install {agent} and use {fleet} in {kib} to define,
configure, and manage your agents in a central location.
+
We recommend using {fleet} management because it makes the management and
upgrade of your agents considerably easier.
+
Refer to <<install-fleet-managed-elastic-agent>>.

* **Install {agent} in standalone mode (advanced users)**
+
With this approach, you install {agent} and manually configure the agent locally
on the system where it’s installed. You are responsible for managing and
upgrading the agents. This approach is reserved for advanced users only.
+
Refer to <<install-standalone-elastic-agent>>.
+
include::{fleet-repo-dir}/standalone-note.asciidoc[]

*  **Install {agent} in a containerized environment**
+
You can run {agent} inside of a container -- either with {fleet-server} or
standalone. Docker images for all versions of {agent} are available from the
Elastic Docker registry, and we provide deployment manifests for running on
Kubernetes.
+
Refer to:
+
--
* <<elastic-agent-container>>
* <<running-on-kubernetes-managed-by-fleet>>
* <<running-on-kubernetes-standalone>>
* {eck-ref}/k8s-elastic-agent.html[Run {agent} on ECK] -- for {eck} users
--

[discrete]
== Minimum Requirements

// lint ignore 2vcpu 1gb
Minimum requirements have been determined by running the {agent} (`v8.0.0`) on a GCP `e2-micro` instance (2vCPU/1GB).
The {agent} used the default policy, running the system integration and self-monitoring.

// lint ignore mem
|===
| **CPU** | Under 2% total, including all monitoring processes
| **Disk** | 640 MB
| **RSS Mem Size** | 300 MB
|===
Adding integrations will increase the memory used by the agent and its processes.
