["appendix",role="exclude",id="install-fleet-managed-agent"]
= Install a {fleet}-managed {agent}

This guide describes how to:

* Install an {agent} that will be managed with {fleet}
* Enroll the {agent} in {fleet}

These steps assume that {stack} is running and an Elastic Integration
has been added in {kib}.  If this is not true -- don't worry, check
out one of the
link:https://www.elastic.co/training/free#quick-starts[Quick Starts]
and get started with {ecloud}.

[discrete]
[[minimal-elastic-agent-prereqs]]
== Prerequisites

* The {stack} is running.

* You have added an integration in {kib} and are now ready to download
and enroll {agent} on your system.

[discrete]
[[minimal-add-agent-to-fleet]]
== Step 1: Add an {agent} to {fleet}

{agent} is a single, unified agent that you can deploy to hosts or containers to
collect data and send it to the {stack}. Behind the scenes, {agent} runs the
{beats} shippers or {elastic-endpoint} required for your configuration.

Choose the operating system and run the provided commands to download and extract
{agent} on your system.

include::../tab-widgets/download-widget.asciidoc[]

[discrete]
[[enroll-agent]]
== Step 2: Enroll and start the {agent}

// lint ignore elastic-agent
Return to {kib} and follow the **Enroll and start the Elastic Agent** instructions.  The command provided in {kib} includes the information that {agent} needs to connect and authenticate with the {stack}.  When the {agent} enrolls it will be configured to send the data associated with the policy that you created.

