[[elastic-agent-installation]]
[role="xpack"]

= Install {agent}s

// tag::agent-install-intro[]
{agent} is a single, unified agent that you can deploy to hosts or containers to
collect data and send it to the {stack}. Behind the scenes, {agent} runs the
{beats} shippers or Elastic Endpoint required for your configuration.
// end::agent-install-intro[]

You have a few options for installing and managing an {agent}:

* **Install a {fleet}-managed {agent} (recommended)**
+
With this approach, you install {agent} on each host you want to monitor and
use {fleet} in {kib} to define, configure, and manage your agents in a central
location.
+
We recommend using {fleet} management because it makes the management and
upgrade of your agents considerably easier. 
+
Refer to <<install-fleet-managed-elastic-agent>>.

* **Install {agent} in standalone mode (advanced users)**
+
With this approach, you install {agent} on each host you want to monitor and
manually configure the agent locally on the system where it’s installed. You are
responsible for managing and upgrading the agents. This approach is reserved
for advanced users only.
+
Refer to <<install-standalone-elastic-agent>>.

*  **Install {agent} in a containerized environment**
+
You can run {agent} inside of a container -- either with {fleet-server} or
standalone. Docker images for all versions of {agent} are available from the
Elastic Docker registry, and we provide deployment manifests for running on
Kubernetes.
+
Refer to:
+
--
* <<elastic-agent-container>>
* <<running-on-kubernetes-managed-by-fleet>>
* <<running-on-kubernetes-standalone>>
* {eck-ref}/k8s-elastic-agent.html[Run {agent} on ECK] -- for {eck} users
--

