[[elastic-agent-installation]]
[role="xpack"]
= Install {agent}s

To collect and ship data to the {stack}, install an {agent} on each host you
want to monitor. These steps assume that you're running a fresh installation. If
{agent} is already running on your system and you want to upgrade to a new
version, see <<upgrade-elastic-agent>>.

You have a couple options for installing and managing an {agent}:

* **Install a {fleet}-managed {agent} (recommended)**
+
With {fleet}, you enroll each agent in a policy defined in {kib} and stored in
{es}. The policy specifies how to collect observability data from the services
you want to monitor. The {agent} connects to a trusted {fleet-server} instance
to retrieve the policy and report agent events.
+
We recommend using {fleet} management because it makes the management and
upgrade of your agents considerably easier.
+
See <<install-fleet-managed-agent>>.

* **Run an {agent} standalone (advanced users)**
+
With standalone mode, you manually configure and manage {agent}s locally on
the systems where they are installed. This approach is recommended for advanced
users only.
+
See <<run-elastic-agent-standalone>>.

[discrete]
[[install-fleet-managed-agent]]
== Install a {fleet}-managed {agent}

This section shows the commands to install an {agent} and enroll it in {fleet}.
If you're a new user, read the <<fleet-quick-start,Quick Start>> and follow the
in-product steps in {kib}, if possible, instead of following the steps described
here.

**Prerequisites:**

* {fleet} is currently only available to users with the
{ref}/built-in-roles.html[superuser role].

* A {fleet-server} must be running in a location accessible to the {agent}. See
<<fleet-server>>.

* An internet connection is required for {kib} to download integration packages
from the Elastic Package Registry. Make sure the {kib} server can connect to
`https://epr.elastic.co` on port `443`.

* You must have an enrollment token generated by {fleet}. Don't have a {fleet}
enrollment key? Read <<fleet-enrollment-tokens>> to learn how to get one from
{fleet}.

* You must have the host and IP where {fleet-server} is running. Not sure where
it's running? Look at the {fleet} settings in {kib}.

* If you're running {agent} 7.9 or earlier, stop the agent and manually remove
it from your host.

To install an {agent} and enroll it in {fleet}:

. On your host, download and extract the installation package.
+
--
// tag::install-elastic-agent[]

include::{tab-widgets}/download-widget.asciidoc[]

// end::install-elastic-agent[]
--

. From the agent directory, run the following commands to install {agent},
enroll it in {fleet}, and start it as a service.
+
NOTE: On macOS, Linux (tar package), and Windows, run the `install` command to
install {agent} as a managed service, enroll it in {fleet}, and start the
service. The DEB and RPM packages include a service unit for Linux systems with
systemd, so use the `enroll` command instead of `install`.
+
--
include::{tab-widgets}/install-widget.asciidoc[]
--
+
TIP: If you see an "x509: certificate signed by unknown authority" error, you
might be trying to enroll in a {fleet-server} that uses self-signed certs. To
fix this problem in a non-production environment, pass the `--insecure` flag.
For more information, refer to the <<agent-enrollment-certs,troubleshooting guide>>.
+
Refer to <<installation-layout>> for the location of installed {agent} files.

Because {agent} is installed as an auto-starting service, it will restart
automatically if the system is rebooted.

To confirm that {agent} is installed and running, go to the **Agents** tab in
{fleet}. 

If you run into problems:

* Check the {agent} logs. If you use the default policy, agent logs and metrics
are collected automatically unless you change the default settings. For more
information, refer to <<elastic-agent-logging>>.

* Refer to <<fleet-troubleshooting>>.

[discrete]
[[installation-layout]]
== Installation layout

When you run the `install` command, {agent} installs files in the following
locations. You cannot override these installation paths because they are
required for upgrades.

include::{tab-widgets}/install-layout-widget.asciidoc[]


// Add Javascript and CSS for tabbed panels
include::{tab-widgets}/code.asciidoc[]
