[[elastic-agent-installation]]
= Install {agent}s

****
// tag::agent-install-intro[]
{agent} is a single, unified way to add monitoring for logs, metrics, and other
types of data to a host. It can also protect hosts from security threats, query
data from operating systems, and more. A single agent makes it easy and fast to
deploy monitoring across your infrastructure. Each agent has a single policy (a
collection of input settings) that you can update to add integrations for new
data sources, security protections, and more.
// end::agent-install-intro[]
****

//TODO: Follow up with Jason to see where and what we need to say about allowlists
//for restricting access to the file system.
You have a few options for installing and managing an {agent}:

* **Install a {fleet}-managed {agent} (recommended)**
+
With this approach, you install {agent} on each host you want to monitor and
use {fleet} in {kib} to define, configure, and manage your agents in a central
location.
+
We recommend using {fleet} management because it makes the management and
upgrade of your agents considerably easier.
+
Refer to <<install-fleet-managed-elastic-agent>>.

* **Install {agent} in standalone mode (advanced users)**
+
With this approach, you install {agent} on each host you want to monitor and
manually configure the agent locally on the system where it’s installed. You are
responsible for managing and upgrading the agents. This approach is reserved
for advanced users only.
+
Refer to <<install-standalone-elastic-agent>>.
+
include::{fleet-repo-dir}/standalone-note.asciidoc[]

*  **Install {agent} in a containerized environment**
+
You can run {agent} inside of a container -- either with {fleet-server} or
standalone. Docker images for all versions of {agent} are available from the
Elastic Docker registry, and we provide deployment manifests for running on
Kubernetes.
+
Refer to:
+
--
* <<elastic-agent-container>>
* <<running-on-kubernetes-managed-by-fleet>>
* <<running-on-kubernetes-standalone>>
* {eck-ref}/k8s-elastic-agent.html[Run {agent} on ECK] -- for {eck} users
--

[discrete]
== Minimum Requirements

Minimum requirements have been determined by running the {agent} (`v8.0.0`) on a GCP `e2-micro` instance (2vCPU/1GB).
The {agent} used the default policy, running the system integration and self-monitoring.

|===
| **CPU** | Under 2% total, including all monitoring processes
| **Disk** | 640MB
| **RSS Mem Size** | 300 MB
|===
Adding integrations will increase the memory used by the agent and its processes.
