[[running-on-aks-managed-by-fleet]]
= Run {agent} on Azure AKS managed by {fleet}

Please follow the steps to run the {agent} on <<running-on-kubernetes-managed-by-fleet>> page.

[discrete]
== Important notes:

On managed Kubernetes solutions like AKS, {agent} has no access to several data sources. Find below the list of the non available data:

1. Metrics from https://kubernetes.io/docs/concepts/overview/components/#control-plane-components[Kubernetes control plane]
components are not available. Consequently metrics are not available for `kube-scheduler` and `kube-controller-manager` components.
In this regard, the respective **dashboards** will not be populated with data.
2. **Audit logs** are available only on Kubernetes master nodes as well, hence cannot be collected by {agent}.
3. Fields `orchestrator.cluster.name` and `orchestrator.cluster.url` are not populated. `orchestrator.cluster.name` field is used as a cluster selector for default Kubernetes dashboards, shipped with https://docs.elastic.co/en/integrations/kubernetes[Kubernetes integration].
+
In this regard, you can use https://www.elastic.co/guide/en/beats/filebeat/current/add-fields.html[`add_fields` processor] to add `orchestrator.cluster.name` and `orchestrator.cluster.url` fields for each https://docs.elastic.co/en/integrations/kubernetes[Kubernetes integration]'s component:
+
[source,yaml]
.Processors configuration
------------------------------------------------
- add_fields:
    target: orchestrator.cluster
    fields:
      name: clusterName
      url: clusterURL
------------------------------------------------
