[[running-on-kubernetes-managed-by-fleet]]
= Run {agent} on Kubernetes managed by {fleet}

:manifest: https://raw.githubusercontent.com/elastic/elastic-agent/{branch}/deploy/kubernetes/elastic-agent-managed-kubernetes.yaml


== What you need

- https://kubernetes.io/docs/tasks/tools/[kubectl installed].

- {es} for storing and searching your data, and {kib} for visualizing and managing it.
+
--
include::{observability-docs-root}/docs/en/shared/spin-up-the-stack/widget.asciidoc[]
--

- `kube-state-metrics`.
+
include::run-container-common/deploy-kube-state-metrics.asciidoc[]


[discrete]
== Step 1: Download the {agent} manifest

include::run-container-common/download-elastic-agent.asciidoc[]


[discrete]
== Step 2: Configure {agent} policy

The {agent} needs to be assigned to a policy to enable the proper inputs. To achieve Kubernetes observability, the policy needs to include the Kubernetes integration. 
Refer to <<create-a-policy>> and <<add-integration>> to learn how to configure the https://docs.elastic.co/en/integrations/kubernetes[Kubernetes integration].

[discrete]
== Step 3: Enroll {agent} to the policy

Enrollment of an {agent} is defined as the action to register a specific agent to a running {fleet-server}. 

{agent} is enrolled to a running {fleet-server} by using `FLEET_URL` parameter. Additionally, the `FLEET_ENROLLMENT_TOKEN` parameter is used to connect {agent} to a specific {agent} policy. 

A new `FLEET_ENROLLMENT_TOKEN` will be created upon new policy creation and will be inserted inside the Elastic Agent Manifest during the Guided installation.

Find more information for https://www.elastic.co/guide/en/fleet/current/fleet-enrollment-tokens.html[Enrollment Tokens].

To specify different destination/credentials, change the following parameters in the manifest file:

[source,yaml]
------------------------------------------------
- name: FLEET_URL
  value: "https://fleet-server_url:port" <1>
- name: FLEET_ENROLLMENT_TOKEN
  value: "token" <2>
- name: FLEET_SERVER_POLICY_ID
  value: "fleet-server-policy" <3>
- name: KIBANA_HOST
  value: "" <4>
- name: KIBANA_FLEET_USERNAME
  value: "" <5>
- name: KIBANA_FLEET_PASSWORD
  value: "" <6>
------------------------------------------------
<1> URL to enroll the {fleet-server} into. You can find it in {kib}. Select *Management -> {fleet} -> Fleet Settings*, and copy the {fleet-server} host URL.
<2> The token to use for enrollment. Close the flyout panel and select *Enrollment tokens*. Find the Agent policy you created before to enroll {agent} into, and display and copy the secret token.
<3> The policy ID for {fleet-server} to use on itself.
<4> The {kib} host.
<5> The basic authentication username used to connect to {kib} and retrieve a `service_token` to enable {fleet}.
<6> The basic authentication password used to connect to {kib} and retrieve a `service_token` to enable {fleet}.

Refer to <<agent-environment-variables>> for all available options.


[discrete]
== Step 4: Configure tolerations
include::run-container-common/agent-tolerations.asciidoc[]

[discrete]
== Step 5: Deploy the {agent}
include::run-container-common/deploy-elastic-agent.asciidoc[]

[discrete]
== Step 6: View your data in {kib}

include::run-container-common/kibana-fleet-data.asciidoc[]


:manifest: