[[uninstall-elastic-agent]]
[role="xpack"]
= Uninstall {agent}

beta[]

[discrete]
== Uninstall on macOS, Linux, and Windows

To uninstall {agent}, run the `uninstall` command from the directory where
{agent} is running. Not sure where the agent is running? See 
<<installation-layout>>.

--
include::{tab-widgets}/uninstall-widget.asciidoc[]

--

Follow the prompts to confirm that you want to uninstall {agent}. The command
stops and uninstalls any managed programs, such as {beats} and
{elastic-endpoint}, before it stops and uninstalls {agent}.

If you run into problems, see <<fleet-troubleshooting>>.

For DEB or RPM installations, you must uninstall the {agent} manually.

//QUESTION: Is this true ^^? Are there any other ways to uninstall that are less
//manual?

[discrete]
== Remove {agent} files manually

//QUESTION: Are the following steps complete and accurate? 

You might need to remove {agent} files manually if there's a failure during
installation, or you're using a distribution, like DEB or RPM, that doesn't
support the `uninstall` command.

To uninstall {agent} manually and completely remove it from your system:

. <<unenroll-elastic-agent,Unenroll the agent>> if it's managed by {fleet}.

. For standalone agents, back up any configuration files you want to preserve. 

. On your host, <<stop-elastic-agent,stop the agent>>. If any {agent}-related
processes are still running, stop them too.
+
TIP: Search for these processes and stop them if they're still running:
`filebeat`, `metricbeat`, `fleet-server`, and `elastic-endpoint`.

. Manually remove the {agent} files from your system. For example, if you're
running {agent} on macOS, delete `/Library/Elastic/Agent/*`. Not sure where the
files are installed? See <<installation-layout>>.

. If you've configured the Elastic Endpoint integration, also remove the files
installed for endpoint protection. The directory structure is similar to {agent},
for example, `/Library/Elastic/Endpoint/*`.

// Add Javascript and CSS for tabbed panels
include::{tab-widgets}/code.asciidoc[]
