[[add-a-fleet-server]]
= Add a {fleet-server}

To use {fleet} for central management, a <<fleet-server,{fleet-server}>> must
be running and accessible to your hosts. This page describes how to add a
{fleet-server} to an {ecloud} or self-managed deployment.

[discrete]
[[fleet-server-compatibility]]
== Compatibility and prerequisites

{fleet-server} is compatible with the following Elastic products:

* {stack} 7.13 or later ({ess-product}[hosted {ess}] on {ecloud}, or
a self-managed cluster).
** For version compatibility: {es} >= {fleet-server} >= {agent} (except for
bugfix releases)
** {kib} should be on the same minor version as {es}.

* {ece} 2.9--requires you to self-manage the {fleet-server}.
* {ece} 2.10 or later--allows you to use a hosted {fleet-server} on {ecloud}.
+
--
** Requires additional wildcard domains and certificates (which normally only
cover `*.cname`, not `*.*.cname`). This enables us to provide the URL for
{fleet-server} of `https://.fleet.`.
** The deployment template must contain an {integrations-server} node.
--
+
For more information about hosting {fleet-server} on {ece}, refer to
{ece-ref}/ece-manage-integrations-server.html[Manage your {integrations-server}].

== How to add a {fleet-server}

The steps for running {fleet-server} on our {ess-product}[hosted {ess}] on
{ecloud} are different from the steps for running it as self-managed.

NOTE: When using our hosted {ess}, it's recommended that you use our hosted
version of {integrations-server}. However, you can choose to deploy and
self-manage your own {fleet-server}s or add an extra self-managed
{fleet-server} in addition to our hosted one. 

include::{tab-widgets}/add-fleet-server/widget.asciidoc[]

Now you're ready to add {agent}s to your host systems. To learn how, see
<<install-fleet-managed-elastic-agent>>.
