[[fleet-limitations]]
[role="xpack"]
= Limitations of this release

beta[]

{fleet} is currently only available to users with the
{ref}/built-in-roles.html[superuser role]. This role is necessary to create
indices, install integration assets, and update {agent} policies. In order
to use {fleet}, the {agent}s must have a direct network connection to {kib} and
{es}. It is also possible to run the {agent}s in standalone mode in cases where
a network connection is not available or not needed.

This feature has additional limitations at the current time:

*   Support for a limited number of integrations (more coming soon)
*   No output to {ls}, Kafka, or other remote clusters
*   No proxy support for Fleet Server
*   Requires internet access for {kib} to download integration packages from the Elastic Package Registry
*   Limited support in the Fleet app for advanced {beats} settings like multiline, processors, and so
on
*   On {ecloud}, there's a limit to the number of enrolled {agent}s that a
single {kib} instance can handle:
+
[%header]
|===
|{kib} instance size {ess-icon} |Max. number of {agent}s
|8gb| 8000
|4gb| 4000
|1gb| 2000
|===

Beta releases are not supported at a production level, but we encourage you to
report issues in our {forum}[discuss forum].
