[[manage-agents-in-fleet]]
= Centrally manage {agent}s in {fleet}

****
The {fleet} app in {kib} supports both {agent} infrastructure management and
agent policy management. You can use {fleet} to:

* Manage {agent} binaries and specify settings installed on the host that
determine whether the {agent} is enrolled in {fleet}, what version of the
agent is running, and which agent policy is used.

* Manage agent policies that specify agent configuration settings, which
integrations are running, whether agent monitoring is turned on, input
settings, and so on. 

Advanced users who don't want to use {fleet} for central management can use an
external infrastructure management solution and
<<install-standalone-elastic-agent,install {agent} in standalone mode>> instead.
****

IMPORTANT: {fleet} currently requires a {kib} user with `All` privileges on
{fleet} and {integrations}. Since many Integrations assets are shared across
spaces, users need the {kib} privileges in all spaces.

To learn how to add {agent}s to {fleet}, refer to
<<install-fleet-managed-elastic-agent>>.

To use {fleet} go to *Management > {fleet}* in {kib}. The following table
describes the main management actions you can perform in {fleet}: 

[options,header]
|===
| Component  | Management actions

|<<fleet-settings>>
|Configure global settings available to all {agent}s managed by {fleet},
including {fleet-server} hosts and output settings.

|<<manage-agents>>
|Enroll, unenroll, upgrade, and view {agent} status and logs.

|<<agent-policy>>
|Create and edit agent policies and add integrations to them.

|<<fleet-enrollment-tokens>>
|Create and revoke enrollment tokens.

|<<data-streams>>
|View data streams and navigate to dashboards to analyze your data.

|===