[[set-inactivity-timeout]]
= Set inactivity timeout

[[why-set-inactivity-timeout]]
== Why set an inactivity timeout?

The inactivity timeout moves {agent}s to inactive status after being offline for a set amount of time. 
Inactive {agent}s are still valid {agent}s, but are removed from the main {fleet} UI allowing you to better manage {agent}s and 
declutter the {fleet} UI.

Once {fleet-server} receives a check-in from an inactive {agent}, it returns to healthy status. 

For example, if an employee is on holiday with their laptop off, 
the {agent} will transition to offline then inactive once the inactivity timeout limit is reached. 
This prevents the inactive {agent} from cluttering the {fleet} UI.
Once the employee returns, the {agent} checks in and returns to healthy status with valid API keys. 

If an {agent} is no longer valid, you can manually <<unenroll-elastic-agent,unenroll>> inactive {agent}s to revoke the API keys. 
Unenrolled agents need to be re-enrolled to be operational again.

For more on {agent} statuses, see <<view-agent-status, view agent status>>.


[[setting-inactivity-timeout]]
== Set the inactivity timeout

Set the inactivity timeout in the {agent} policy to the amount of time after which you want an offline {agent} become inactive.

To set the inactivity timeout:

. In *{fleet}*, select *Agent policies*.

. Click the policy name, then click *Settings*.

. In the *Inactivity timeout* field, enter a value in seconds. The default value is 1209600 seconds or two weeks.