[[apm-manage-storage]]
= Manage storage

status_badge::[stack, ga]
status_badge::[serverless, ga]
pass:[<span class="availability-note"></span>]

{agent} uses <<apm-data-streams,data streams>> to store time series data across multiple indices.
<<apm-custom-index-template,Index templates>> are used to configure the backing indices of data streams as they are created.
Each data stream ships with a customizable <<apm-ilm-how-to,index lifecycle policy>> that automates data retention as your indices grow and age.
Use <<apm-ingest-pipelines,ingest pipelines>> to process and enrich APM documents before indexing them.

The <<apm-storage-guide,storage and sizing guide>> attempts to define a "typical" storage reference for Elastic APM,
and there are additional settings you can tweak to <<apm-reduce-apm-storage,reduce storage>>,
or to <<apm-tune-elasticsearch,tune data ingestion in {es}>>.

In addition, the Applications UI makes it easy to visualize your APM data usage with
<<apm-storage-explorer,storage explorer>>.
Storage explorer allows you to analyze the storage footprint of each of your services to see
which are producing large amounts of data--so you can better reduce the data you're collecting
or forecast and prepare for future storage needs.

:leveloffset: +1

include::{observability-docs-root}/docs/en/observability/apm/manage-storage/storage-explorer.asciidoc[]

include::{observability-docs-root}/docs/en/observability/apm/manage-storage/data-streams.asciidoc[]

include::{observability-docs-root}/docs/en/observability/apm/manage-storage/ilm-how-to.asciidoc[]

include::{observability-docs-root}/docs/en/observability/apm/manage-storage/custom-index-template.asciidoc[]

include::{observability-docs-root}/docs/en/observability/apm/manage-storage/ingest-pipelines.asciidoc[]

include::{observability-docs-root}/docs/en/observability/apm/manage-storage/storage-and-sizing.asciidoc[]

include::{observability-docs-root}/docs/en/observability/apm/manage-storage/reduce-apm-storage.asciidoc[]

include::{observability-docs-root}/docs/en/observability/apm/manage-storage/exploring-es-data.asciidoc[]

:!leveloffset:
