[[apm-data-security-delete]]
= Delete sensitive data

If you accidentally ingest sensitive data, follow these steps to remove or redact the offending data:

. Stop collecting the sensitive data.
Use the *remedy* column of the <<apm-sensitive-fields,sensitive fields>> table to determine how to stop collecting
the offending data.

. Delete or redact the ingested data. With data collection fixed, you can now delete or redact the offending data:
+
* <<apm-redact-field-data>>
* <<apm-delete-doc-data>>

[float]
[[apm-redact-field-data]]
== Redact specific fields

To redact sensitive data in a specific field, use the {ref}/docs-update-by-query.html[update by query API].

For example, the following query removes the `client.ip` address
from APM documents in the `logs-apm.error-default` data stream:

[source, console]
----
POST /logs-apm.error-default/_update_by_query
{
  "query": {
    "exists": {
      "field": "client.ip"
    }
  }
  "script": {
    "source": "ctx._source.client.ip = params.redacted",
    "params": {
      "redacted": "[redacted]"
    }
  }
}
----

Or, perhaps you only want to redact IP addresses from European users:

[source, console]
----
POST /logs-apm.error-default/_update_by_query
{
  "query": {
    "term": {
      "client.geo.continent_name": {
        "value": "Europe"
      }
    }
  },
  "script": {
    "source": "ctx._source.client.ip = params.redacted",
    "params": {
      "redacted": "[redacted]"
    }
  }
}
----

See {ref}/docs-update-by-query.html[update by query API] for more information and examples.

[float]
[[apm-delete-doc-data]]
== Delete {es} documents

WARNING: This will permanently delete your data.
You should test your queries with the {ref}/search-search.html[search API] prior to deleting data.

To delete an {es} document,
you can use the {ref}/docs-delete-by-query.html[delete by query API].

For example, to delete all documents in the `apm-traces-*` data stream with a `user.email` value, run the following query:

[source, console]
----
POST /apm-traces-*/_delete_by_query
{
  "query": {
    "exists": {
      "field": "user.email"
    }
  }
}
----

See {ref}/docs-delete-by-query.html[delete by query API] for more information and examples.
