[[apm-filtering]]
= Built-in data filters

include::{observability-docs-root}/docs/en/observability/apm/security/data-security/index.asciidoc[tag=data-filters]

[discrete]
[[apm-filters-http-header]]
== HTTP headers

By default, APM agents capture HTTP request and response headers (including cookies).
Most Elastic APM agents provide the ability to sanitize HTTP header fields,
including cookies and `application/x-www-form-urlencoded` data (POST form fields).
Query string and captured request bodies, like `application/json` data, are not sanitized.

The default list of sanitized fields attempts to target common field names for data relating to
passwords, credit card numbers, authorization, etc., but can be customized to fit your data.
This sensitive data never leaves the instrumented service.

This setting supports <<apm-agent-configuration,Central configuration>>,
which means the list of sanitized fields can be updated without needing to redeploy your services:

* Go: {apm-go-ref-v}/configuration.html#config-sanitize-field-names[`ELASTIC_APM_SANITIZE_FIELD_NAMES`]
* Java: {apm-java-ref-v}/config-core.html#config-sanitize-field-names[`sanitize_field_names`]
* .NET: {apm-dotnet-ref-v}/config-core.html#config-sanitize-field-names[`sanitizeFieldNames`]
* Node.js: {apm-node-ref-v}/configuration.html#sanitize-field-names[`sanitizeFieldNames`]
// * PHP: {apm-php-ref-v}[``]
* Python: {apm-py-ref-v}/configuration.html#config-sanitize-field-names[`sanitize_field_names`]
* Ruby: {apm-ruby-ref-v}/configuration.html#config-sanitize-field-names[`sanitize_field_names`]

Alternatively, you can completely disable the capturing of HTTP headers.
This setting also supports <<apm-agent-configuration,Central configuration>>:

* Go: {apm-go-ref-v}/configuration.html#config-capture-headers[`ELASTIC_APM_CAPTURE_HEADERS`]
* Java: {apm-java-ref-v}/config-core.html#config-capture-headers[`capture_headers`]
* .NET: {apm-dotnet-ref-v}/config-http.html#config-capture-headers[`CaptureHeaders`]
* Node.js: {apm-node-ref-v}/configuration.html#capture-headers[`captureHeaders`]
// * PHP: {apm-php-ref-v}[``]
* Python: {apm-py-ref-v}/configuration.html#config-capture-headers[`capture_headers`]
* Ruby: {apm-ruby-ref-v}/configuration.html#config-capture-headers[`capture_headers`]

[discrete]
[[apm-filters-http-body]]
== HTTP bodies

By default, the body of HTTP requests is not recorded.
Request bodies often contain sensitive data like passwords or credit card numbers,
so use care when enabling this feature.

This setting supports <<apm-agent-configuration,Central configuration>>,
which means the list of sanitized fields can be updated without needing to redeploy your services:

* Go: {apm-go-ref-v}/configuration.html#config-capture-body[`ELASTIC_APM_CAPTURE_BODY`]
* Java: {apm-java-ref-v}/config-core.html#config-capture-body[`capture_body`]
* .NET: {apm-dotnet-ref-v}/config-http.html#config-capture-body[`CaptureBody`]
* Node.js: {apm-node-ref-v}/configuration.html#capture-body[`captureBody`]
// * PHP: {apm-php-ref-v}[``]
* Python: {apm-py-ref-v}/configuration.html#config-capture-body[`capture_body`]
* Ruby: {apm-ruby-ref-v}/configuration.html#config-capture-body[`capture_body`]

[discrete]
[[apm-filters-personal-data]]
== Personal data

By default, the APM Server captures some personal data associated with trace events:

* `client.ip`: The client's IP address. Typically derived from the HTTP headers of incoming requests.
`client.ip` is also used in conjunction with the {ref}/geoip-processor.html[`geoip` processor] to assign
geographical information to trace events. To learn more about how `client.ip` is derived,
see <<apm-derive-client-ip>>.
* `user_agent`: User agent data, including the client operating system, device name, vendor, and version.

The capturing of this data can be turned off by setting
**Capture personal data** to `false`.

NOTE: This setting only prevents APM Server from capturing already ingested personal data.
It does not prevent such data from appearing in ingestion logs where applicable.
See <<apm-filters-in-agent,APM agent filters>> for redacting data on ingestion.

[discrete]
[[apm-filters-real-user-data]]
== Real user monitoring data

Protecting user data is important.
For that reason, individual RUM instrumentations can be disabled in the RUM agent with the
{apm-rum-ref-v}/configuration.html#disable-instrumentations[`disableInstrumentations`] configuration variable.
Disabled instrumentations produce no spans or transactions.

[options="header"]
|====
|Disable |Configuration value
|HTTP requests |`fetch` and `xmlhttprequest`
|Page load metrics including static resources |`page-load`
|JavaScript errors on the browser |`error`
|User click events including URLs visited, mouse clicks, and navigation events |`eventtarget`
|Single page application route changes |`history`
|====

[discrete]
[[apm-filters-database-statements]]
== Database statements

For SQL databases, APM agents do not capture the parameters of prepared statements.
Note that Elastic APM currently does not make an effort to strip parameters of regular statements.
Not using prepared statements makes your code vulnerable to SQL injection attacks,
so be sure to use prepared statements.

For non-SQL data stores, such as {es} or MongoDB,
Elastic APM captures the full statement for queries.
For inserts or updates, the full document is not stored.
To filter or obfuscate data in non-SQL database statements,
or to remove the statement entirely,
you can set up an ingest node pipeline.

[discrete]
[[apm-filters-agent-specific]]
== Agent-specific options

Certain agents offer additional filtering and obfuscating options:

**Agent configuration options**

* (Node.js) Remove errors raised by the server-side process:
disable with {apm-node-ref-v}/configuration.html#capture-exceptions[captureExceptions].

* (Java) Remove process arguments from transactions:
disabled by default with {apm-java-ref-v}/config-reporter.html#config-include-process-args[`include_process_args`].
