[float]
[[configuration-monitor]]
=== Settings for internal collection

Use the following settings to configure internal collection when you are not
using {metricbeat} to collect monitoring data.

You specify these settings in the X-Pack monitoring section of the
+apm-server.yml+ config file:

[float]
==== `monitoring.enabled`

The `monitoring.enabled` config is a boolean setting to enable or disable {monitoring}.
If set to `true`, monitoring is enabled.

The default value is `false`.

[float]
==== `monitoring.elasticsearch`

The {es} instances that you want to ship your APM Server metrics to. This
configuration option contains the following fields:

[float]
===== `api_key`

The detail of the API key to be used to send monitoring information to {es}.
See <<beats-api-keys>> for more information.

[float]
===== `bulk_max_size`

The maximum number of metrics to bulk in a single {es} bulk API index request.
The default is `50`. For more information, see <<elasticsearch-output>>.

[float]
===== `backoff.init`

The number of seconds to wait before trying to reconnect to {es} after
a network error. After waiting `backoff.init` seconds, APM Server tries to
reconnect. If the attempt fails, the backoff timer is increased exponentially up
to `backoff.max`. After a successful connection, the backoff timer is reset. The
default is `1s`.

[float]
===== `backoff.max`

The maximum number of seconds to wait before attempting to connect to
{es} after a network error. The default is `60s`.

[float]
===== `compression_level`

The gzip compression level. Setting this value to `0` disables compression. The
compression level must be in the range of `1` (best speed) to `9` (best
compression). The default value is `0`. Increasing the compression level
reduces the network usage but increases the CPU usage.

[float]
===== `headers`

Custom HTTP headers to add to each request. For more information, see
<<elasticsearch-output>>.

[float]
===== `hosts`

The list of {es} nodes to connect to. Monitoring metrics are distributed to
these nodes in round robin order. For more information, see
<<elasticsearch-output>>.

[float]
===== `max_retries`

The number of times to retry sending the monitoring metrics after a failure.
After the specified number of retries, the metrics are typically dropped. The
default value is `3`. For more information, see <<elasticsearch-output>>.

[float]
===== `parameters`

Dictionary of HTTP parameters to pass within the URL with index operations.

[float]
===== `password`

The password that APM Server uses to authenticate with the {es} instances for
shipping monitoring data.

[float]
===== `metrics.period`

The time interval (in seconds) when metrics are sent to the {es} cluster. A new
snapshot of APM Server metrics is generated and scheduled for publishing each
period. The default value is 10 * time.Second.

[float]
===== `state.period`

The time interval (in seconds) when state information are sent to the {es} cluster. A new
snapshot of APM Server state is generated and scheduled for publishing each
period. The default value is 60 * time.Second.

[float]
===== `protocol`

The name of the protocol to use when connecting to the {es} cluster. The options
are: `http` or `https`. The default is `http`. If you specify a URL for `hosts`,
however, the value of protocol is overridden by the scheme you specify in the URL.

[float]
===== `proxy_url`

The URL of the proxy to use when connecting to the {es} cluster. For more
information, see <<elasticsearch-output>>.

[float]
===== `timeout`

The HTTP request timeout in seconds for the {es} request. The default is `90`.

[float]
===== `ssl`

Configuration options for Transport Layer Security (TLS) or Secure Sockets Layer
(SSL) parameters like the certificate authority (CA) to use for HTTPS-based
connections. If the `ssl` section is missing, the host CAs are used for
HTTPS connections to {es}. For more information, see <<configuration-ssl>>.

[float]
===== `username`

The user ID that APM Server uses to authenticate with the {es} instances for
shipping monitoring data.