#!/usr/bin/env groovy
@Library('apm@current') _

pipeline {
  agent { label 'metal || darwin || master' }
  options {
    timeout(time: 10)
    buildDiscarder(logRotator(numToKeepStr: '100', artifactNumToKeepStr: '30', daysToKeepStr: '30'))
    timestamps()
    ansiColor('xterm')
    disableResume()
    durabilityHint('PERFORMANCE_OPTIMIZED')
    rateLimitBuilds(throttle: [count: 60, durationName: 'hour', userBoost: true])
    quietPeriod(10)
  }
  stages {
    /**
     This creates a GitHub comment linking to the preview of the docs build. The docs preview build itself is generated here:
     https://elasticsearch-ci.elastic.co/view/Docs/job/elastic+observability-docs+pull-request+build-docs/
    */
    stage('Generate Docs Link') {
      when { changeRequest() }
      steps {
        deleteDir()
        githubPrComment(message: "A docs preview will be available soon: </br> - [HTML diff](https://observability-docs_${CHANGE_ID}.docs-preview.app.elstc.co/diff) </br> - [Observability guide](https://observability-docs_${CHANGE_ID}.docs-preview.app.elstc.co/guide/en/observability/master/index.html)")
      }
    }
  }
}
