name: 8.7 Documentation request
description: Request a documentation change or enhancement for Elastic Stack version 8.7.
title: "[REQUEST]: "
labels: ["8.7-request", "Team:Docs"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this request! This form will create an issue that the obs-docs team will triage and prioritize. Filling out this form does not guarantee that your issue will be prioritized for the selected iteration.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe what needs to be documented.
      placeholder: I need...
    validations:
      required: true
  - type: textarea
    id: related
    attributes:
      label: Resources
      description: Please link to as many related resources as possible. Think about issues, PRs, demos, Slack threads, etc.
      placeholder: How can the docs team learn more about this feature?
    validations:
      required: true
  - type: checkboxes
    id: collaboration
    attributes:
      label: Collaboration
      description: Choose the expected collaboration model
      options:
        - label: The **documentation** team will proide the initial content.
        - label: The **product** team will provide the initial content.
        - label: TBD. The docs and product team will work together to determine the best path forward.
        - label: Other (please describe above).
    validations:
      required: true
  - type: textarea
    id: contact
    attributes:
      label: Point of contact.
      description: Please assign at least one point of contact using the GitHub `@` mention. Add as many stakeholders as you'd like.
      value: "**Main contact:** @\n\n**Stakeholders:**\n"
    validations:
      required: true