name: "[Internal] 8.9 Documentation request"
description: Request a documentation change or enhancement for the 8.9 release (Elastic employees).
title: "[REQUEST]: "
labels: ["8.9-request", "Team:Docs"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this request! This form will create an issue that the obs-docs team will triage and prioritize. Filling out this form does not guarantee that your issue will be prioritized for the selected iteration but completing this issue as early and as comprehensively as possible will help us understand and plan the work better!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe what needs to be documented.
      placeholder: I need...
    validations:
      required: true
  - type: textarea
    id: related
    attributes:
      label: Resources
      description: Please link to as many related resources as possible. Think about issues, PRs, demos, Slack threads, existing or related docs pages, etc.
      placeholder: How can the docs team learn more about this feature?
    validations:
      required: true
  - type: dropdown
    id: collaboration
    attributes:
      label: Collaboration
      description: Choose the expected collaboration model
      options:
        - "The documentation team will investigate the issue and create the initial content."
        - "The product team will provide the initial content."
        - "TBD. The docs and product team will work together to determine the best path forward."
        - "Other (please describe below in the Point of contact section)."
    validations:
      required: true
  - type: textarea
    id: contact
    attributes:
      label: Point of contact.
      description: Please assign at least one point of contact using the GitHub `@` mention. Add as many stakeholders as you'd like.
      value: "**Main contact:** @\n\n**Stakeholders:**\n"
    validations:
      required: true
