name: "Internal documentation request (Elastic employees)"
description: Request a documentation change or enhancement.
title: "[REQUEST]: "
labels: ["Team:Docs"]
body:
  - type: markdown
    attributes:
      value: |
        Hi 👋. This form will create an issue that the [@elastic/obs-docs](https://github.com/orgs/elastic/teams/obs-docs) team will triage and prioritize. Please do not add any labels to your issue—that will happen automagically.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe what needs to be documented.
      placeholder: I need...
    validations:
      required: true
  - type: textarea
    id: related
    attributes:
      label: Resources
      description: Please link to as many related resources as possible. Think about issues, PRs, demos, Slack threads, existing or related docs pages, etc.
      placeholder: How can the docs team learn more about this feature?
    validations:
      required: true
  - type: dropdown
    id: doc-set
    attributes:
      label: Which documentation set does this change impact?
      description: Stateful, Serverless, or both?
      options:
        - Stateful and Serverless
        - Stateful only
        - Serverless only
        - Integrations
        - Unknown
      default: 0
    validations:
      required: true
  - type: textarea
    id: doc-set-differences
    attributes:
      label: Feature differences
      description: If you selected both Stateful and Serverless above, please describe how, if at all, the feature differs in each deployment method.
      placeholder: The feature is identical in Stateful and Serverless.
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: What release is this request related to?
      description: Some requests may be tied to the Elastic Stack release schedule. Some, like Serverless requests, may not. Please select an option.
      options:
        - 'N/A'
        - '8.11'
        - '8.12'
        - '8.13'
        - '8.14'
        - '8.15'
        - '8.16'
      default: 0
    validations:
      required: true
  - type: dropdown
    id: collaboration
    attributes:
      label: Collaboration model
      description: Which team do you expect to create the initial content?
      options:
        - "The documentation team"
        - "The product team"
        - "The engineering team"
        - "Unknown"
        - "Other (please describe below)"
      default: 0
    validations:
      required: true
  - type: textarea
    id: contact
    attributes:
      label: Point of contact.
      description: Please assign at least one point of contact using the GitHub `@` mention. Add as many stakeholders as you'd like.
      value: "**Main contact:** @\n\n**Stakeholders:**\n"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for filling out this form. Note that this form does not guarantee that your issue will be prioritized for the selected iteration. _But_, completing this issue as early and as comprehensively as possible will help us understand and plan the work better!