[[integrations-tsdb-synthetic-source]]
= Working with new indexing features

These pages include details for incorporating new indexing features into your integrations, such as TSDB, `doc-value-only` fields, and synthetic source.

* <<developer-tsdb-guidelines>>
* <<testing-new-indexing-features>>

[[developer-tsdb-guidelines]]
== TSDB guidelines

Important related resources:

* Meta link:https://github.com/elastic/integrations/issues/5233[issue] with all migrated packages
* TSDB link:https://github.com/elastic/TSDB-migration-test-kit[test] migration kit

In this document you can find:

* <<integrations-dev-tsdb-background>>
* <<integrations-dev-tsdb-migrating>>
* <<integrations-dev-tsdb-testing>>
* <<integrations-dev-tsdb-best-practices>>
* <<integrations-dev-tsdb-troubleshooting>>

[discrete]
[[integrations-dev-tsdb-background]]
=== Background

tbd

[discrete]
[[integrations-dev-tsdb-migrating]]
=== Steps for migrating an existing package

tbd

[discrete]
[[integrations-dev-tsdb-testing]]
=== Testing

tbd

[discrete]
[[integrations-dev-tsdb-best-practices]]
=== Best practices

tbd

[discrete]
[[integrations-dev-tsdb-troubleshooting]]
=== Troubleshooting

tbd

[[testing-new-indexing-features]]
== How to test new indexing features

Elasticsearch has been adding new indexing modes and features that allow optimization of storage size and query performance.

We'd like to enable integration developers to start testing the ingest and query performance of enabling these features before we start making any changes in the integrations themselves or allowing end users to enable these from the Fleet UI.

Today, each of these can already be enabled by leveraging the *@custom component templates that Fleet installs for each integration data stream, to varying degrees of ease of use (details below). We could improve the UX around this for integration developers by adding an explicit API in Fleet to enable this, however it may not be necessary. See link:https://github.com/elastic/kibana/issues/132818[elastic/kibana#132818] for discussion around how a feature flag API could be added to ease this a bit more.

See the following instructions for testing new indexing features:

* <<integrations-dev-synthetic-source>>
* <<integrations-dev-doc-value-only-fields>>
* <<integrations-dev-test-tsdb>>

[[integrations-dev-synthetic-source]]
=== Testing synthetic source

* For background, refer to link:elastic/elasticsearch#85649[#85649]
* For integrations support, refer to link:elastic/package-spec#340[#340]

This one is quite easy to enable on an integration using the component template. Here's how to do this for the nginx substatus metrics for example:

. Install the nginx package
. Run this dev tools command:
+
[source,console]
----
PUT /_component_template/metrics-nginx.substatus@custom
{
  "template": {
    "settings": {},
    "mappings": {
      "_source": {
        "mode": "synthetic"
      }
    }
  },
  "_meta": {
    "package": {
      "name": "nginx"
    }
  }
}
----

. If a data stream already existed, rollover the data stream to get the new mappings: `POST metrics-nginx.substatus-default/_rollover`

One challenge with leveraging synthetic source is that it doesn't support keyword fields that have a ignore_above configured. It may be worth removing this setting for testing on those fields. This can be done by editing the package in dev and installing it via elastic-package or overriding it via the custom component template, similar to the doc-value-only example below.

[[integrations-dev-doc-value-only-fields]]
=== Testing doc-value-only fields

* For background, refer to link:https://www.elastic.co/blog/whats-new-elasticsearch-kibana-cloud-8-1-0[Elasticsearch, Kibana, Elastic Cloud 8.1: Faster indexing, less disk storage, and smarter analytics capabilities]
* For integrations support, refer to link:https://github.com/elastic/integrations/issues/3419[#3419]

This one is the most painful with component templates because it required adding `index: false` to every long and double field. Providing an API in Fleet would make this a bit easier. Here's how to do this manually:

. Install the nginx package
. Get the mappings included with the package: `GET /_component_template/logs-nginx.access@package`
. Copy the output into your favorite text editor, search for each `"type": "long"` and `"type": "double"`, and add `"index": false`
. Update the custom component template with the new mappings. For example, here's how to set the long fields to `index: false`
+
[source,console]
----
PUT /_component_template/merics-nginx.substatus@custom
{
  "template": {
    "settings": {},
    "mappings": {
      "properties": {
        "nginx": {
          "properties": {
            "stubstatus": {
              "properties": {
                "hostname": {
                  "ignore_above": 1024,
                  "type": "keyword"
                },
                "current": {
                  "type": "long",
                  "index": false
                },
                "waiting": {
                  "type": "long",
                  "index": false
                },
                "accepts": {
                  "type": "long",
                  "index": false
                },
                "handled": {
                  "type": "long",
                  "index": false
                },
                "writing": {
                  "type": "long",
                  "index": false
                },
                "dropped": {
                  "type": "long",
                  "index": false
                },
                "active": {
                  "type": "long",
                  "index": false
                },
                "reading": {
                  "type": "long",
                  "index": false
                },
                "requests": {
                  "type": "long",
                  "index": false
                }
              }
            }
          }
        }
      }
    }
  },
  "_meta": {
    "package": {
      "name": "nginx"
    }
  }
}
----

. If a data stream already existed, rollover the data stream to get the new mappings: `POST metrics-nginx.substatus-default/_rollover`

[[integrations-dev-test-tsdb]]
=== Time-series indexing (TSDB) (not GA)

* For background, refer to link:https://github.com/elastic/elasticsearch/issues/74660[#74660]
* For integrations support, refer to link:https://github.com/elastic/package-spec/issues/311[#311]

Usage of TSDB indexing requires the following:

* Mapping parameters must be added for `time_series_dimension` and `time_series_metric` on appropriate fields. This is already supported by the package ecosystem and Fleet, so packages can already define these options.
* The `mode: time_series` and `routing_path` index settings must be added, this can be done by editing the custom component template.

Note that the `routing_path` setting should correspond to fields with `time_series_dimension` specified. In the future, ES may automate this setting.

. Install the kubernetes package (already has TSDB mappings set up)
. Run this dev tools command:
+
[source,console]
----
PUT /_component_template/metrics-kubernetes.pod@custom
{
  "template": {
    "settings": {
      "index.mode": "time_series",
      "index.routing_path": ["kubernetes.pod.uid"]
    },
    "mappings": {}
  },
  "_meta": {
    "package": {
      "name": "kubernetes"
    }
  }
}
----

. If a data stream already existed, rollover the data stream to get the new mappings: `POST metrics-kubernetes.pod-default/_rollover`
