[[specification]]
= Specification

Integrations are a type of package and therefore must adhere to the Elastic package specification.
The package specification describes:

* The folder structure of a package and the expected files within these folders
* The structure of expected files' contents

[discrete]
[[asset-organization]]
== Asset organization

In general, assets within a package are organized by `<elastic-stack-component>/<asset-type>`.
For example, ingest pipelines are stored in the `elasticsearch/ingest-pipeline` folder.
This logic applies to all Elasticsearch, Kibana, and Agent assets.

Top-level assets are picked up as JSON documents, and pushed to the corresponding Elasticsearch and Kibana APIs.

[discrete]
[[data-streams]]
=== Data streams

There is a special folder called `data_stream`.
Each data stream should have its own folder of assets within this folder,
and the names of these data streams must follow the data stream naming scheme.

The contents of these folders follow the `<elastic-stack-component>/<asset-type>` structure.
During installation, Fleet enforces data stream naming rules.
All assets in this folder belong directly or indirectly to data streams.

In most scenarios, only data stream assets are needed. There are exceptions where global assets are required to get more flexibility. This could be, for example, an ILM policy that applies to all data streams.

[discrete]
[[supported-assets]]
== Supported assets

The following assets are typically found in an Elastic package:

* Elasticsearch
** Ingest Pipeline
** Index Template
** Transform
** Index template settings
* Kibana
** Dashboards
** Visualization
** Index patterns
** ML Modules
** Map
** Search
** Security rules
* Other
** fields.yml

[discrete]
[[directory-structure]]
== Directory structure

[source,text]
----
apache
│   changelog.yml
│   manifest.yml
└───_dev
└───data_stream
└───docs
└───img
└───kibana
----

[discrete]
[[directory-spec]]
== Spec

Included from the package-spec repository. This will update when the spec is updated.

[source,yaml]
----
include::{package-spec}/spec.yml[]
----

[[dev-spec]]
== `_dev`

Development resources.

**required**

Included from the package-spec repository. This will update when the spec is updated.

[source,yaml]
----
include::{package-spec}/_dev/spec.yml[]
----

[[data-stream-spec]]
== `data_stream`

Data stream assets, including ingest pipelines, field definitions, metadata, and sample events.

**required**

Included from the package-spec repository. This will update when the spec is updated.

[source,yaml]
----
include::{package-spec}/data_stream/spec.yml[]
----

[[docs-spec]]
== `docs`

The built integration readme file.

**required**

Included from the package-spec repository. This will update when the spec is updated.

[source,yaml]
----
include::{package-spec}/docs/spec.yml[]
----

[[kibana-spec]]
== `kibana`

The integration's Kibana assets, like dashboards, visualizations, machine learning modules, etc.

**required**

Included from the package-spec repository. This will update when the spec is updated.

[source,yaml]
----
include::{package-spec}/kibana/spec.yml[]
----

[[changelog-spec]]
== `changelog.yml`

The integration's changelog.

**required**

Included from the package-spec repository. This will update when the spec is updated.

[source,yaml]
----
include::{package-spec}/changelog.spec.yml[]
----

[[manifest-spec]]
== `manifest.yml`

Integration metadata, like version, name, license level, description, category,
icon and screenshot mappings, and policy template definitions.

**required**

Included from the package-spec repository. This will update when the spec is updated.

[source,yaml]
----
include::{package-spec}/manifest.spec.yml[]
----
