[[apm-act-on-data]]
= Act on application data

++++
<titleabbrev>Act on data</titleabbrev>
++++

In addition to exploring visualizations in the Applications UI in {kib}, you can make your application data
more actionable with:

* *Alerts and rules*: The Applications UI allows you to define rules to detect complex
  conditions within your APM data and trigger built-in actions when those conditions are met.
  Read more about alerts and rules in the <<apm-alerts,Incident management section>>.
* *Custom links*: Build URLs that contain relevant metadata from a specific trace.
  For example, you can create a link that will take you to a page where you can open a new GitHub issue
  with context already auto-populated in the issue body.
  These links will be shown in the _Actions_ context menu in selected areas of the Applications UI (for example, by transaction details).
  Read more in <<apm-custom-links,Custom links>>.

:leveloffset: +1

include::{observability-docs-root}/docs/en/observability/apm/act-on-data/custom-links.asciidoc[]

:!leveloffset:
