//Contributors: If you include this file, you must set the integration-name
//attribute to the integration name that appears in Kibana

[%collapsible]
.**Quick guide: Add data**
====
****

. In the Observability UI, find **Integrations** in the main menu or use the {kibana-ref}/introduction.html#kibana-navigation-search[global search field].
. In the query bar, search for and select the **{integration-name}**
integration.
. Read the overview to make sure you understand integration requirements and
other considerations.
. Click **Add {integration-name}**.
+
TIP: If you're installing an integration for the first time, you may be prompted
to install {agent}. If you see this page, click
**Add integration only (skip agent installation)**.

. Configure the integration name and optionally add a description. Make sure you
configure all required settings.
. Choose where to add the integration policy.
* If {agent} is not already deployed locally or on an EC2 instance, click
**New hosts** and enter a name for the new agent policy.
* Otherwise, click **Existing hosts** and select an existing agent policy.
. Click **Save and continue**. This step takes a minute or two to complete. When
it's done, you'll have an agent policy that contains an integration policy
for the configuration you just specified. If an {agent} is already assigned to
the policy, you're done. Otherwise, you need to deploy an {agent}.
. To deploy an {agent}:
.. In the popup, click **Add {agent} to your hosts** to open the **Add agent**
flyout. If you accidentally close the popup or the flyout doesn't open, go to
**{fleet} -> Agents**, then click **Add agent** to access the flyout.
.. Follow the steps in the **Add agent** flyout to download, install,
and enroll the {agent}.
. When incoming data is confirmed--after a minute or two--click **View assets**
to access the dashboards.

For more information {agent} and integrations, refer to the
{fleet-guide}/index.html[{fleet} and {agent} documentation].
****
====