["appendix",role="exclude",id="redirects"]
== Deleted pages

The following pages have moved or been deleted.

// Event Types

[role="exclude",id="event-types"]
=== Event types

This page has moved. Please see {observability-guide}/data-model.html[APM data model].

// [role="exclude",id="errors"]
// === Errors

// This page has moved. Please see {apm-overview-ref-v}/errors.html[Errors].

// [role="exclude",id="transactions"]
// === Transactions

// This page has moved. Please see {apm-overview-ref-v}/transactions.html[Transactions].

// [role="exclude",id="transactions-spans"]
// === Spans

// This page has moved. Please see {apm-overview-ref-v}/transaction-spans.html[Spans].

// Error API

[role="exclude",id="error-endpoint"]
=== Error endpoint

The error endpoint has been deprecated. Instead, see <<api-events>>.

[role="exclude",id="error-schema-definition"]
=== Error schema definition

The error schema has moved. Please see {observability-guide}/api-error.html#api-error-schema[Error Schema].

[role="exclude",id="error-api-examples"]
=== Error API examples

The error API examples have moved. Please see <<api-events>>.

[role="exclude",id="error-payload-schema"]
=== Error payload schema

This schema has changed. Please see <<api-error>>.

[role="exclude",id="error-service-schema"]
=== Error service schema

This schema has changed. Please see <<api-error>>.

[role="exclude",id="error-system-schema"]
=== Error system schema

This schema has changed. Please see <<api-error>>.

[role="exclude",id="error-context-schema"]
=== Error context schema

This schema has changed. Please see <<api-error>>.

[role="exclude",id="error-stacktraceframe-schema"]
=== Error stack trace frame schema

This schema has changed. Please see <<api-error>>.

[role="exclude",id="payload-with-error"]
=== Payload with error

This is no longer helpful. Please see <<api-error>>.

[role="exclude",id="payload-with-minimal-exception"]
=== Payload with minimal exception

This is no longer helpful. Please see <<api-error>>.

[role="exclude",id="payload-with-minimal-log"]
=== Payload with minimal log

This is no longer helpful. Please see <<api-error>>.

// Transaction API

[role="exclude",id="transaction-endpoint"]
=== Transaction endpoint

The transaction endpoint has been deprecated. Instead, see <<api-events>>.

[role="exclude",id="transaction-schema-definition"]
=== Transaction schema definition

The transaction schema has moved. Please see {observability-guide}/api-transaction.html#api-transaction-schema[Transaction Schema].

[role="exclude",id="transaction-api-examples"]
=== Transaction API examples

The transaction API examples have moved. Please see <<api-events>>.

[role="exclude",id="transaction-span-schema"]
=== Transaction span schema

This schema has changed. Please see <<api-span>>.

[role="exclude",id="transaction-payload-schema"]
=== Transaction payload schema

This schema has changed. Please see <<api-transaction>>.

[role="exclude",id="transaction-service-schema"]
=== Transaction service schema

This schema has changed. Please see <<api-transaction>>.

[role="exclude",id="transaction-system-schema"]
=== Transaction system schema

This schema has changed. Please see <<api-transaction>>.

[role="exclude",id="transaction-context-schema"]
=== Transaction context schema

This schema has changed. Please see <<api-transaction>>.

[role="exclude",id="transaction-stacktraceframe-schema"]
=== Transaction stack trace frame schema

This schema has changed. Please see <<api-transaction>>.

[role="exclude",id="transaction-request-schema"]
=== Transaction request schema

This schema has changed. Please see <<api-transaction>>.

[role="exclude",id="transaction-user-schema"]
=== Transaction user schema

This schema has changed. Please see <<api-transaction>>.

[role="exclude",id="payload-with-transactions"]
=== Payload with transactions

This is no longer helpful. Please see <<api-transaction>>.

[role="exclude",id="payload-with-minimal-transaction"]
=== Payload with minimal transaction

This is no longer helpful. Please see <<api-transaction>>.

[role="exclude",id="payload-with-minimal-span"]
=== Payload with minimal span

This is no longer helpful. Please see <<api-span>>.

[role="exclude",id="example-intakev2-events"]
=== Example Request Body

This page has moved. Please see <<api-event-example>>.

// V1 intake API

[role="exclude",id="request-too-large"]
=== HTTP 413: Request body too large

This error can no longer occur. Please see <<common-problems>> for an updated overview of potential issues.

[role="exclude",id="configuration-v1-api"]
=== Configuration options: v1 Intake API

Intake API v1 is no longer supported. Please see {observability-guide}/configuration-process.html#configuration-apm-server[Configuration options] for current configuration options.

[role="exclude",id="max_unzipped_size"]
=== `max_unzipped_size`

This configuration option is no longer supported. Please see {observability-guide}/configuration-process.html#configuration-apm-server[Configuration options] for current configuration options.

[role="exclude",id="concurrent_requests"]
=== `concurrent_requests`

This configuration option is no longer supported. Please see {observability-guide}/configuration-process.html#configuration-apm-server[Configuration options] for current configuration options.

[role="exclude",id="metrics.enabled"]
=== `metrics.enabled`

This configuration option is no longer supported. Please see {observability-guide}/configuration-process.html#configuration-apm-server[Configuration options] for current configuration options.

[role="exclude",id="max_request_queue_time"]
=== `max_request_queue_time`

This configuration option is no longer supported. Please see {observability-guide}/configuration-process.html#configuration-apm-server[Configuration options] for current configuration options.

[role="exclude",id="configuration-v2-api"]
=== Configuration options: v2 Intake API

This section has moved. Please see {observability-guide}/configuration-process.html#configuration-apm-server[Configuration options] for current configuration options.

[role="exclude",id="configuration-rum-v1"]
=== `configuration-rum-v1`

This configuration option is no longer supported. Please see <<configuration-rum>> for current configuration options.

[role="exclude",id="rate_limit_v1"]
=== `rate_limit_v1`

This configuration option is no longer supported. Please see <<configuration-rum>> for current configuration options.

[role="exclude",id="configuration-rum-v2"]
=== `configuration-rum-v2`

This section has moved. Please see <<configuration-rum>> for current configuration options.

[role="exclude",id="configuration-rum-general"]
=== Configuration options: general

This section has moved. Please see <<configuration-rum>> for current configuration options.

[role="exclude",id="use-v1-and-v2"]
=== Tuning APM Server using both v1 and v2 intake API

This section has moved. Please see {observability-guide}/tune-data-ingestion.html#tune-apm-server[Tune APM Server] for how to tune APM Server.

// Dashboards

[role="exclude",id="load-dashboards-logstash"]
=== Tuning APM Server using both v1 and v2 intake API

Loading dashboards from APM Server is no longer supported. Please see the {kibana-ref}/xpack-apm.html[{kib} APM UI] documentation.

[role="exclude",id="url-option"]
=== setup.dashboards.url

Loading dashboards from APM Server is no longer supported. Please see the {kibana-ref}/xpack-apm.html[{kib} APM UI] documentation.

[role="exclude",id="file-option"]
=== setup.dashboards.file

Loading dashboards from APM Server is no longer supported. Please see the {kibana-ref}/xpack-apm.html[{kib} APM UI] documentation.

[role="exclude",id="load-kibana-dashboards"]
=== Dashboards

Loading {kib} dashboards from APM Server is no longer supported.
Please use the {kibana-ref}/xpack-apm.html[{kib} APM UI] instead.
As an alternative, a small number of dashboards and visualizations are available in the
https://github.com/elastic/apm-contrib/tree/main/kibana[apm-contrib] repository.

// [role="exclude",id="rum"]
// === Rum

// This section has moved. Please see <<configuration-rum>>.

[role="exclude",id="aws-lambda-arch"]
=== APM Architecture for AWS Lambda

This section has moved. See {apm-lambda-ref}/aws-lambda-arch.html[APM Architecture for AWS Lambda].

[role="exclude",id="aws-lambda-config-options"]
=== Configuration options

This section has moved. See {apm-lambda-ref}/aws-lambda-config-options.html[Configuration options].

[role="exclude",id="aws-lambda-secrets-manager"]
=== Using AWS Secrets Manager to manage APM authentication keys

This section has moved. See {apm-lambda-ref}/aws-lambda-secrets-manager.html[Using AWS Secrets Manager to manage APM authentication keys].

[role="exclude",id="go-compatibility"]
=== Go Agent Compatibility

This page has moved. Please see <<agent-server-compatibility>>.

[role="exclude",id="java-compatibility"]
=== Java Agent Compatibility

This page has moved. Please see <<agent-server-compatibility>>.

[role="exclude",id="dotnet-compatibility"]
=== .NET Agent Compatibility

This page has moved. Please see <<agent-server-compatibility>>.

[role="exclude",id="nodejs-compatibility"]
=== Node.js Agent Compatibility

This page has moved. Please see <<agent-server-compatibility>>.

[role="exclude",id="python-compatibility"]
=== Python Agent Compatibility

This page has moved. Please see <<agent-server-compatibility>>.

[role="exclude",id="ruby-compatibility"]
=== Ruby Agent Compatibility

This page has moved. Please see <<agent-server-compatibility>>.

[role="exclude",id="rum-compatibility"]
=== RUM Agent Compatibility

This page has moved. Please see <<agent-server-compatibility>>.

[role="exclude",id="apm-release-notes"]
=== APM release highlights

This page has moved.
Please see {observability-guide}/whats-new.html[What's new in {observability} {minor-version}].

Please see <<whats-new>>.

[role="exclude",id="whats-new"]
=== What's new in APM {minor-version}

This page has moved.
Please see {observability-guide}/whats-new.html[What's new in {observability} {minor-version}].

[role="exclude",id="troubleshooting"]
=== Troubleshooting

This page has moved.
Please see <<troubleshoot-apm>>.

[role="exclude",id="input-apm"]
=== Configuring

This page has moved.
Please see <<configuring-howto-apm-server>>.

[role="exclude",id="events-api"]
=== Events Intake API

[discrete]
[[events-api-errors]]
==== Errors

This page has been deleted.
Please see {observability-guide}/apm.html[APM overview].

[role="exclude",id="intake-api"]
=== API

This page has been deleted.
Please see {observability-guide}/apm.html[APM overview].

[role="exclude",id="metadata-api"]
=== Metadata

[discrete]
[[metadata-schema]]
==== Errors

This page has been deleted.
Please see {observability-guide}/apm.html[APM overview].

[role="exclude",id="errors"]
=== Errors

This page has been deleted.
Please see {observability-guide}/apm.html[APM overview].

[role="exclude",id="transaction-spans"]
=== Spans

This page has been deleted.
Please see {observability-guide}/apm.html[APM overview].

[role="exclude",id="transactions"]
=== Transactions

This page has been deleted.
Please see {observability-guide}/apm.html[APM overview].

[role="exclude",id="legacy-apm-overview"]
=== Legacy APM Overview

This page has been deleted.
Please see {observability-guide}/apm.html[APM overview].

[role="exclude",id="apm-components"]
=== Components and documentation

This page has been deleted.
Please see {observability-guide}/apm.html[APM overview].

[role="exclude",id="configuring-ingest-node"]
=== Parse data using ingest node pipelines

This page has been deleted.
Please see {observability-guide}/apm.html[APM overview].

[role="exclude",id="overview"]
=== Legacy APM Server Reference

This page has been deleted.
Please see {observability-guide}/apm.html[APM overview].

[role="exclude",id="metadata"]
=== Metadata

This page has been deleted.
Please see {observability-guide}/apm.html[APM overview].

[role="exclude",id="distributed-tracing"]
=== Distributed tracing

This page has been deleted.
Please see {observability-guide}/apm.html[APM overview].

[role="exclude",id="sourcemaps"]
=== How to apply source maps to error stack traces when using minified bundles

[discrete]
[[sourcemap-rum-generate]]
==== Sourcemap RUM Generate

[discrete]
[[sourcemap-rum-upload]]
==== Sourcemap RUM upload

This page has been deleted.
Please see {observability-guide}/apm.html[APM overview].

[role="exclude",id="apm-quick-start"]
=== Quick start with Elastic Cloud

Refer to {observability-guide}/apm-quick-start.html[Quick start with Elastic Cloud]

[role="exclude",id="getting-started-apm-server"]
=== Self manage APM Server

Refer to {observability-guide}/getting-started-apm-server.html[Self manage APM Server]

[role="exclude",id="_apm_server_binary"]
=== APM Server binary

Refer to {observability-guide}/_apm_server_binary.html[APM Server binary]

[role="exclude",id="installing"]
=== Step 1: Install

Refer to {observability-guide}/installing.html[Step 1: Install]

[role="exclude",id="apm-server-configuration"]
=== Step 2: Set up and configure

Refer to {observability-guide}/apm-server-configuration.html[Step 2: Set up and configure]

[role="exclude",id="apm-server-starting"]
=== Step 3: Start

Refer to {observability-guide}/apm-server-starting.html[Step 3: Start]

[role="exclude",id="next-steps"]
=== Step 4: Next steps

Refer to {observability-guide}/next-steps.html[Step 4: Next steps]

[role="exclude",id="setup-repositories"]
=== Repositories for APT and YUM

Refer to {observability-guide}/setup-repositories.html[Repositories for APT and YUM]

[role="exclude",id="running-on-docker"]
=== Run APM Server on Docker

Refer to {observability-guide}/running-on-docker.html[Run APM Server on Docker]

[role="exclude",id="_fleet_managed_apm_server"]
=== Fleet-managed APM Server

Refer to {observability-guide}/_fleet_managed_apm_server.html[Fleet-managed APM Server]

[role="exclude",id="_step_1_set_up_fleet"]
=== Step 1: Set up Fleet

Refer to {observability-guide}/_step_1_set_up_fleet.html[Step 1: Set up Fleet]

[role="exclude",id="_step_2_add_and_configure_the_apm_integration"]
=== Step 2: Add and configure the APM integration

Refer to {observability-guide}/_step_2_add_and_configure_the_apm_integration.html[Step 2: Add and configure the APM integration]

[role="exclude",id="_step_3_install_apm_agents"]
=== Step 3: Install APM agents

Refer to {observability-guide}/_step_3_install_apm_agents.html[Step 3: Install APM agents]

[role="exclude",id="_step_4_view_your_data"]
=== Step 4: View your data

Refer to {observability-guide}/_step_4_view_your_data.html[Step 4: View your data]

[role="exclude",id="data-model"]
=== Data Model

Refer to {observability-guide}/data-model.html[Data Model]

[role="exclude",id="data-model-spans"]
=== Spans

Refer to {observability-guide}/data-model-spans.html[Spans]

[role="exclude",id="data-model-transactions"]
=== Transactions

Refer to {observability-guide}/data-model-transactions.html[Transactions]

[role="exclude",id="data-model-errors"]
=== Errors

Refer to {observability-guide}/data-model-errors.html[Errors]

[role="exclude",id="data-model-metrics"]
=== Metrics

Refer to {observability-guide}/data-model-metrics.html[Metrics]

[role="exclude",id="data-model-metadata"]
=== Metadata

Refer to {observability-guide}/data-model-metadata.html[Metadata]

[role="exclude",id="features"]
=== Features

Refer to {observability-guide}/features.html[Features]

[role="exclude",id="apm-data-security"]
=== Data security

Refer to {observability-guide}/apm-data-security.html[Data security]

[role="exclude",id="filtering"]
=== Built-in data filters

Refer to {observability-guide}/filtering.html[Built-in data filters]

[role="exclude",id="custom-filter"]
=== Custom filters

Refer to {observability-guide}/custom-filter.html[Custom filters]

[role="exclude",id="data-security-delete"]
=== Delete sensitive data

Refer to {observability-guide}/data-security-delete.html[Delete sensitive data]

[role="exclude",id="apm-distributed-tracing"]
=== Distributed tracing

Refer to {observability-guide}/apm-distributed-tracing.html[Distributed tracing]

[role="exclude",id="apm-rum"]
=== Real User Monitoring (RUM)

Refer to {observability-guide}/apm-rum.html[Real User Monitoring (RUM)]

[role="exclude",id="sampling"]
=== Transaction sampling

Refer to {observability-guide}/sampling.html[Transaction sampling]

[role="exclude",id="configure-head-based-sampling"]
=== Configure head-based sampling

Refer to {observability-guide}/configure-head-based-sampling.html[Configure head-based sampling]

[role="exclude",id="configure-tail-based-sampling"]
=== Configure tail-based sampling

Refer to {observability-guide}/configure-tail-based-sampling.html[Configure tail-based sampling]

[role="exclude",id="log-correlation"]
=== Logging integration

Refer to {observability-guide}/log-correlation.html[Logging integration]

[role="exclude",id="cross-cluster-search"]
=== Cross-cluster search

Refer to {observability-guide}/cross-cluster-search.html[Cross-cluster search]

[role="exclude",id="span-compression"]
=== Span compression

Refer to {observability-guide}/span-compression.html[Span compression]

[role="exclude",id="monitoring-aws-lambda"]
=== Monitoring AWS Lambda Functions

Refer to {observability-guide}/monitoring-aws-lambda.html[Monitoring AWS Lambda Functions]

[role="exclude",id="apm-mutating-admission-webhook"]
=== APM Attacher

Refer to {observability-guide}/apm-mutating-admission-webhook.html[APM Attacher]

[role="exclude",id="how-to-guides"]
=== How-to guides

Refer to {observability-guide}/how-to-guides.html[How-to guides]

[role="exclude",id="source-map-how-to"]
=== Create and upload source maps (RUM)

Refer to {observability-guide}/source-map-how-to.html[Create and upload source maps (RUM)]

[role="exclude",id="jaeger-integration"]
=== Integrate with Jaeger

Refer to {observability-guide}/jaeger-integration.html[Integrate with Jaeger]

[role="exclude",id="ingest-pipelines"]
=== Parse data using ingest pipelines

Refer to {observability-guide}/ingest-pipelines.html[Parse data using ingest pipelines]

[role="exclude",id="custom-index-template"]
=== View the Elasticsearch index template

Refer to {observability-guide}/custom-index-template.html[View the Elasticsearch index template]

[role="exclude",id="open-telemetry"]
=== OpenTelemetry integration

Refer to {observability-guide}/open-telemetry.html[OpenTelemetry integration]

[role="exclude",id="open-telemetry-with-elastic"]
=== OpenTelemetry API/SDK with Elastic APM agents

Refer to {observability-guide}/open-telemetry-with-elastic.html[OpenTelemetry API/SDK with Elastic APM agents]

[role="exclude",id="open-telemetry-direct"]
=== OpenTelemetry native support

Refer to {observability-guide}/open-telemetry-direct.html[OpenTelemetry native support]

[role="exclude",id="open-telemetry-other-env"]
=== AWS Lambda Support

Refer to {observability-guide}/open-telemetry-other-env.html[AWS Lambda Support]

[role="exclude",id="open-telemetry-collect-metrics"]
=== Collect metrics

Refer to {observability-guide}/open-telemetry-collect-metrics.html[Collect metrics]

[role="exclude",id="open-telemetry-known-limitations"]
=== Limitations

Refer to {observability-guide}/open-telemetry-known-limitations.html[Limitations]

[role="exclude",id="open-telemetry-resource-attributes"]
=== Resource attributes

Refer to {observability-guide}/open-telemetry-resource-attributes.html[Resource attributes]

[role="exclude",id="manage-storage"]
=== Manage storage

Refer to {observability-guide}/manage-storage.html[Manage storage]

[role="exclude",id="apm-data-streams"]
=== Data streams

Refer to {observability-guide}/apm-data-streams.html[Data streams]

[role="exclude",id="ilm-how-to"]
=== Index lifecycle management

Refer to {observability-guide}/ilm-how-to.html[Index lifecycle management]

[role="exclude",id="storage-guide"]
=== Storage and sizing guide

Refer to {observability-guide}/storage-guide.html[Storage and sizing guide]

[role="exclude",id="reduce-apm-storage"]
=== Reduce storage

Refer to {observability-guide}/reduce-apm-storage.html[Reduce storage]

[role="exclude",id="exploring-es-data"]
=== Explore data in Elasticsearch

Refer to {observability-guide}/exploring-es-data.html[Explore data in Elasticsearch]

[role="exclude",id="configuring-howto-apm-server"]
=== Configure

Refer to {observability-guide}/configuring-howto-apm-server.html[Configure]

[role="exclude",id="configuration-process"]
=== General configuration options

Refer to {observability-guide}/configuration-process.html[General configuration options]

[role="exclude",id="configuration-anonymous"]
=== Anonymous authentication

Refer to {observability-guide}/configuration-anonymous.html[Anonymous authentication]

[role="exclude",id="apm-agent-auth"]
=== APM agent authorization

Refer to {observability-guide}/apm-agent-auth.html[APM agent authorization]

[role="exclude",id="configure-agent-config"]
=== APM agent configuration

Refer to {observability-guide}/configure-agent-config.html[APM agent configuration]

[role="exclude",id="configuration-instrumentation"]
=== Instrumentation

Refer to {observability-guide}/configuration-instrumentation.html[Instrumentation]

[role="exclude",id="setup-kibana-endpoint"]
=== Kibana endpoint

Refer to {observability-guide}/setup-kibana-endpoint.html[Kibana endpoint]

[role="exclude",id="configuration-logging"]
=== Logging

Refer to {observability-guide}/configuration-logging.html[Logging]

[role="exclude",id="configuring-output"]
=== Output

Refer to {observability-guide}/configuring-output.html[Output]

[role="exclude",id="configure-cloud-id"]
=== Elasticsearch Service

Refer to {observability-guide}/configure-cloud-id.html[Elasticsearch Service]

[role="exclude",id="elasticsearch-output"]
=== Elasticsearch

Refer to {observability-guide}/elasticsearch-output.html[Elasticsearch]

[role="exclude",id="logstash-output"]
=== Logstash

Refer to {observability-guide}/logstash-output.html[Logstash]

[role="exclude",id="kafka-output"]
=== Kafka

Refer to {observability-guide}/kafka-output.html[Kafka]

[role="exclude",id="redis-output"]
=== Redis

Refer to {observability-guide}/redis-output.html[Redis]

[role="exclude",id="console-output"]
=== Console

Refer to {observability-guide}/console-output.html[Console]

[role="exclude",id="configuration-path"]
=== Project paths

Refer to {observability-guide}/configuration-path.html[Project paths]

[role="exclude",id="configuration-rum"]
=== Real User Monitoring (RUM)

Refer to {observability-guide}/configuration-rum.html[Real User Monitoring (RUM)]

[role="exclude",id="configuration-ssl-landing"]
=== SSL/TLS settings

Refer to {observability-guide}/configuration-ssl-landing.html[SSL/TLS settings]

[role="exclude",id="configuration-ssl"]
=== SSL/TLS output settings

Refer to {observability-guide}/configuration-ssl.html[SSL/TLS output settings]

[role="exclude",id="agent-server-ssl"]
=== SSL/TLS input settings

Refer to {observability-guide}/agent-server-ssl.html[SSL/TLS input settings]

[role="exclude",id="tail-based-samling-config"]
=== Tail-based sampling

Refer to {observability-guide}/tail-based-samling-config.html[Tail-based sampling]

[role="exclude",id="config-env"]
=== Use environment variables in the configuration

Refer to {observability-guide}/config-env.html[Use environment variables in th]

[role="exclude",id="setting-up-and-running"]
=== Advanced setup

Refer to {observability-guide}/setting-up-and-running.html[Advanced setup]

[role="exclude",id="directory-layout"]
=== Installation layout

Refer to {observability-guide}/directory-layout.html[Installation layout]

[role="exclude",id="keystore"]
=== Secrets keystore

Refer to {observability-guide}/keystore.html[Secrets keystore]

[role="exclude",id="command-line-options"]
=== Command reference

Refer to {observability-guide}/command-line-options.html[Command reference]

[role="exclude",id="tune-data-ingestion"]
=== Tune data ingestion

Refer to {observability-guide}/tune-data-ingestion.html[Tune data ingestion]

[role="exclude",id="high-availability"]
=== High Availability

Refer to {observability-guide}/high-availability.html[High Availability]

[role="exclude",id="running-with-systemd"]
=== APM Server and systemd

Refer to {observability-guide}/running-with-systemd.html[APM Server and systemd]

[role="exclude",id="securing-apm-server"]
=== Secure communication

Refer to {observability-guide}/securing-apm-server.html[Secure communication]

[role="exclude",id="secure-agent-communication"]
=== With APM agents

Refer to {observability-guide}/secure-agent-communication.html[With APM agents]

[role="exclude",id="agent-tls"]
=== APM agent TLS communication

Refer to {observability-guide}/agent-tls.html[APM agent TLS communication]

[role="exclude",id="api-key"]
=== API keys

Refer to {observability-guide}/api-key.html[API keys]

[role="exclude",id="secret-token"]
=== Secret token

Refer to {observability-guide}/secret-token.html[Secret token]

[role="exclude",id="anonymous-auth"]
=== Anonymous authentication

Refer to {observability-guide}/anonymous-auth.html[Anonymous authentication]

[role="exclude",id="secure-comms-stack"]
=== With the Elastic Stack

Refer to {observability-guide}/secure-comms-stack.html[With the Elastic Stack]

[role="exclude",id="privileges-to-publish-events"]
=== Create a <em>writer</em> user

Refer to {observability-guide}/privileges-to-publish-events.html[Create a <em>writer</em> user]

[role="exclude",id="privileges-to-publish-monitoring"]
=== Create a <em>monitoring</em> user

Refer to {observability-guide}/privileges-to-publish-monitoring.html[Create a <em>monitoring</em> user]

[role="exclude",id="privileges-api-key"]
=== Create an <em>API key</em> user

Refer to {observability-guide}/privileges-api-key.html[Create an <em>API key</em> user]

[role="exclude",id="privileges-agent-central-config"]
=== Create a <em>central config</em> user

Refer to {observability-guide}/privileges-agent-central-config.html[Create a <em>central config</em> user]

[role="exclude",id="privileges-rum-source-map"]
=== Create a <em>source map</em> user

Refer to {observability-guide}/privileges-rum-source-map.html[Create a <em>source map</em> user]

[role="exclude",id="beats-api-keys"]
=== Grant access using API keys

Refer to {observability-guide}/beats-api-keys.html[Grant access using API keys]

[role="exclude",id="monitor-apm"]
=== Monitor

Refer to {observability-guide}/monitor-apm.html[Monitor]

[role="exclude",id="monitor-apm-self-install"]
=== Fleet-managed

Refer to {observability-guide}/monitor-apm-self-install.html[Fleet-managed]

[role="exclude",id="monitoring"]
=== APM Server binary

Refer to {observability-guide}/monitoring.html[APM Server binary]

[role="exclude",id="monitoring-internal-collection"]
=== Use internal collection

Refer to {observability-guide}/monitoring-internal-collection.html[Use internal collection]

[role="exclude",id="monitoring-local-collection"]
=== Use local collection

Refer to {observability-guide}/monitoring-local-collection.html[Use local collection]

[role="exclude",id="select-metrics"]
=== The select metrics

Refer to {observability-guide}/select-metrics.html[The select metrics]

[role="exclude",id="monitoring-metricbeat-collection"]
=== Use Metricbeat collection

Refer to {observability-guide}/monitoring-metricbeat-collection.html[Use Metricbeat collection]

[role="exclude",id="api"]
=== API

Refer to {observability-guide}/api.html[API]

[role="exclude",id="api-info"]
=== APM Server information API

Refer to {observability-guide}/api-info.html[APM Server information API]

[role="exclude",id="api-events"]
=== Elastic APM events intake API

Refer to {observability-guide}/api-events.html[Elastic APM events intake API]

[role="exclude",id="api-metadata"]
=== Metadata

Refer to {observability-guide}/api-metadata.html[Metadata]

[role="exclude",id="api-transaction"]
=== Transactions

Refer to {observability-guide}/api-transaction.html[Transactions]

[role="exclude",id="api-span"]
=== Spans

Refer to {observability-guide}/api-span.html[Spans]

[role="exclude",id="api-error"]
=== Errors

Refer to {observability-guide}/api-error.html[Errors]

[role="exclude",id="api-metricset"]
=== Metrics

Refer to {observability-guide}/api-metricset.html[Metrics]

[role="exclude",id="api-event-example"]
=== Example request body

Refer to {observability-guide}/api-event-example.html[Example request body]

[role="exclude",id="api-config"]
=== Elastic APM agent configuration API

Refer to {observability-guide}/api-config.html[Elastic APM agent configuration]

[role="exclude",id="api-otlp"]
=== OpenTelemetry intake API

Refer to {observability-guide}/api-otlp.html[OpenTelemetry intake API]

[role="exclude",id="api-jaeger"]
=== Jaeger event intake

Refer to {observability-guide}/api-jaeger.html[Jaeger event intake]

[role="exclude",id="troubleshoot-apm"]
=== Troubleshoot

Refer to {observability-guide}/troubleshoot-apm.html[Troubleshoot]

[role="exclude",id="common-problems"]
=== Common problems

Refer to {observability-guide}/common-problems.html[Common problems]

[role="exclude",id="server-es-down"]
=== What happens when APM Server or Elasticsearch is down?

Refer to {observability-guide}/server-es-down.html[What happens when APM Server or Ela]

[role="exclude",id="common-response-codes"]
=== APM Server response codes

Refer to {observability-guide}/common-response-codes.html[APM Server response codes]

[role="exclude",id="processing-and-performance"]
=== Processing and performance

Refer to {observability-guide}/processing-and-performance.html[Processing and performance]

[role="exclude",id="enable-apm-server-debugging"]
=== APM Server binary debugging

Refer to {observability-guide}/enable-apm-server-debugging.html[APM Server binary debugging]

[role="exclude",id="upgrade"]
=== Upgrade

Refer to {observability-guide}/upgrade.html[Upgrade]

[role="exclude",id="agent-server-compatibility"]
=== APM agent compatibility

Refer to {observability-guide}/agent-server-compatibility.html[APM agent compatibility]

[role="exclude",id="apm-breaking"]
=== Breaking Changes

Refer to {observability-guide}/apm-breaking.html[Breaking Changes]

[role="exclude",id="upgrading-to-8.x"]
=== Upgrade to version 8.11.3

Refer to {observability-guide}/upgrading-to-8.x.html[Upgrade to version 8.11.3]

[role="exclude",id="upgrade-8.0-self-standalone"]
=== Self-installation standalone

Refer to {observability-guide}/upgrade-8.0-self-standalone.html[Self-installation standalone]

[role="exclude",id="upgrade-8.0-self-integration"]
=== Self-installation APM integration

Refer to {observability-guide}/upgrade-8.0-self-integration.html[Self-installation APM integration]

[role="exclude",id="upgrade-8.0-cloud-standalone"]
=== Elastic Cloud standalone

Refer to {observability-guide}/upgrade-8.0-cloud-standalone.html[Elastic Cloud standalone]

[role="exclude",id="upgrade-8.0-cloud-integration"]
=== Elastic Cloud APM integration

Refer to {observability-guide}/upgrade-8.0-cloud-integration.html[Elastic Cloud APM integration]

[role="exclude",id="upgrade-to-apm-integration"]
=== Switch to the Elastic APM integration

Refer to {observability-guide}/upgrade-to-apm-integration.html[Switch to the Elastic APM integration]

[role="exclude",id="apm-integration-upgrade-steps"]
=== Switch a self-installation

Refer to {observability-guide}/apm-integration-upgrade-steps.html[Switch a self-installation]

[role="exclude",id="apm-integration-upgrade-steps-ess"]
=== Switch an Elastic Cloud cluster

Refer to {observability-guide}/apm-integration-upgrade-steps-ess.html[Switch an Elastic Cloud cluster]

[role="exclude",id="release-notes"]
=== Release notes

Refer to {observability-guide}/release-notes.html[Release notes]

[role="exclude",id="release-notes-8.11"]
=== APM version 8.11

Refer to {observability-guide}/release-notes-8.11.html[APM version 8.11]

[role="exclude",id="release-notes-8.10"]
=== APM version 8.10

Refer to {observability-guide}/release-notes-8.10.html[APM version 8.10]

[role="exclude",id="release-notes-8.9"]
=== APM version 8.9

Refer to {observability-guide}/release-notes-8.9.html[APM version 8.9]

[role="exclude",id="release-notes-8.8"]
=== APM version 8.8

Refer to {observability-guide}/release-notes-8.8.html[APM version 8.8]

[role="exclude",id="release-notes-8.7"]
=== APM version 8.7

Refer to {observability-guide}/release-notes-8.7.html[APM version 8.7]

[role="exclude",id="release-notes-8.6"]
=== APM version 8.6

Refer to {observability-guide}/release-notes-8.6.html[APM version 8.6]

[role="exclude",id="release-notes-8.5"]
=== APM version 8.5

Refer to {observability-guide}/release-notes-8.5.html[APM version 8.5]

[role="exclude",id="release-notes-8.4"]
=== APM version 8.4

Refer to {observability-guide}/release-notes-8.4.html[APM version 8.4]

[role="exclude",id="release-notes-8.3"]
=== APM version 8.3

Refer to {observability-guide}/release-notes-8.3.html[APM version 8.3]

[role="exclude",id="release-notes-8.2"]
=== APM version 8.2

Refer to {observability-guide}/release-notes-8.2.html[APM version 8.2]

[role="exclude",id="release-notes-8.1"]
=== APM version 8.1

Refer to {observability-guide}/release-notes-8.1.html[APM version 8.1]

[role="exclude",id="release-notes-8.0"]
=== APM version 8.0

Refer to {observability-guide}/release-notes-8.0.html[APM version 8.0]
