["appendix",role="exclude",id="redirects"]
= Deleted pages

The following pages have moved or been deleted.

// Event Types

[role="exclude",id="event-types"]
=== Event types

This page has moved. Please see {observability-guide}/apm-data-model.html[APM data model].

// [role="exclude",id="errors"]
// === Errors

// This page has moved. Please see {apm-overview-ref-v}/errors.html[Errors].

// [role="exclude",id="transactions"]
// === Transactions

// This page has moved. Please see {apm-overview-ref-v}/transactions.html[Transactions].

// [role="exclude",id="transactions-spans"]
// === Spans

// This page has moved. Please see {apm-overview-ref-v}/transaction-spans.html[Spans].

// Error API

[role="exclude",id="error-endpoint"]
=== Error endpoint

The error endpoint has been deprecated. Please see {observability-guide}/apm-api-events.html[API events].

[role="exclude",id="error-schema-definition"]
=== Error schema definition

The error schema has moved. Please see {observability-guide}/apm-api-events.html#apm-api-error[Error Schema].

[role="exclude",id="error-api-examples"]
=== Error API examples

The error API examples have moved. Please see {observability-guide}/apm-api-events.html[API events].

[role="exclude",id="error-payload-schema"]
=== Error payload schema

The error schema has moved. Please see {observability-guide}/apm-api-events.html#apm-api-error[Error Schema].

[role="exclude",id="error-service-schema"]
=== Error service schema

The error schema has moved. Please see {observability-guide}/apm-api-events.html#apm-api-error[Error Schema].

[role="exclude",id="error-system-schema"]
=== Error system schema

The error schema has moved. Please see {observability-guide}/apm-api-events.html#apm-api-error[Error Schema].

[role="exclude",id="error-context-schema"]
=== Error context schema

The error schema has moved. Please see {observability-guide}/apm-api-events.html#apm-api-error[Error Schema].

[role="exclude",id="error-stacktraceframe-schema"]
=== Error stack trace frame schema

The error schema has moved. Please see {observability-guide}/apm-api-events.html#apm-api-error[Error Schema].

[role="exclude",id="payload-with-error"]
=== Payload with error

This is no longer helpful. Please see {observability-guide}/apm-api-events.html#apm-api-error[Error Schema].

[role="exclude",id="payload-with-minimal-exception"]
=== Payload with minimal exception

This is no longer helpful. Please see {observability-guide}/apm-api-events.html#apm-api-error[Error Schema].

[role="exclude",id="payload-with-minimal-log"]
=== Payload with minimal log

This is no longer helpful. Please see {observability-guide}/apm-api-events.html#apm-api-error[Error Schema].

// Transaction API

[role="exclude",id="transaction-endpoint"]
=== Transaction endpoint

The transaction endpoint has been deprecated. Please see {observability-guide}/apm-api-events.html[API events].

[role="exclude",id="transaction-schema-definition"]
=== Transaction schema definition

The transaction schema has moved. Please see {observability-guide}/apm-api-transaction.html#apm-api-transaction-schema[Transaction Schema].

[role="exclude",id="transaction-api-examples"]
=== Transaction API examples

The transaction API examples have moved. Please see {observability-guide}/apm-api-events.html[API events].

[role="exclude",id="transaction-span-schema"]
=== Transaction span schema

This schema has changed. Please see {observability-guide}/apm-api-span.html[Spans].

[role="exclude",id="transaction-payload-schema"]
=== Transaction payload schema

This schema has changed. Please see {observability-guide}/apm-api-transaction.html[Transactions].

[role="exclude",id="transaction-service-schema"]
=== Transaction service schema

This schema has changed. Please see {observability-guide}/apm-api-transaction.html[Transactions].

[role="exclude",id="transaction-system-schema"]
=== Transaction system schema

This schema has changed. Please see {observability-guide}/apm-api-transaction.html[Transactions].

[role="exclude",id="transaction-context-schema"]
=== Transaction context schema

This schema has changed. Please see {observability-guide}/apm-api-transaction.html[Transactions].

[role="exclude",id="transaction-stacktraceframe-schema"]
=== Transaction stack trace frame schema

This schema has changed. Please see {observability-guide}/apm-api-transaction.html[Transactions].

[role="exclude",id="transaction-request-schema"]
=== Transaction request schema

This schema has changed. Please see {observability-guide}/apm-api-transaction.html[Transactions].

[role="exclude",id="transaction-user-schema"]
=== Transaction user schema

This schema has changed. Please see {observability-guide}/apm-api-transaction.html[Transactions].

[role="exclude",id="payload-with-transactions"]
=== Payload with transactions

This is no longer helpful. Please see {observability-guide}/apm-api-transaction.html[Transactions].

[role="exclude",id="payload-with-minimal-transaction"]
=== Payload with minimal transaction

This is no longer helpful. Please see {observability-guide}/apm-api-transaction.html[Transactions].

[role="exclude",id="payload-with-minimal-span"]
=== Payload with minimal span

This is no longer helpful. Please see {observability-guide}/apm-api-span.html[Spans].

[role="exclude",id="example-intakev2-events"]
=== Example Request Body

Refer to {observability-guide}/apm-api-event-example.html[Example request body].

// V1 intake API

[role="exclude",id="request-too-large"]
=== HTTP 413: Request body too large

This error can no longer occur. Refer to {observability-guide}/apm-common-problems.html[Common problems].

[role="exclude",id="configuration-v1-api"]
=== Configuration options: v1 Intake API

Intake API v1 is no longer supported. Please see {observability-guide}/apm-configuration-process.html#apm-configuration-apm-server[Configuration options] for current configuration options.

[role="exclude",id="max_unzipped_size"]
=== `max_unzipped_size`

This configuration option is no longer supported. Please see {observability-guide}/apm-configuration-process.html#apm-configuration-apm-server[Configuration options] for current configuration options.

[role="exclude",id="concurrent_requests"]
=== `concurrent_requests`

This configuration option is no longer supported. Please see {observability-guide}/apm-configuration-process.html#apm-configuration-apm-server[Configuration options] for current configuration options.

[role="exclude",id="metrics.enabled"]
=== `metrics.enabled`

This configuration option is no longer supported. Please see {observability-guide}/apm-configuration-process.html#apm-configuration-apm-server[Configuration options] for current configuration options.

[role="exclude",id="max_request_queue_time"]
=== `max_request_queue_time`

This configuration option is no longer supported. Please see {observability-guide}/apm-configuration-process.html#apm-configuration-apm-server[Configuration options] for current configuration options.

[role="exclude",id="configuration-v2-api"]
=== Configuration options: v2 Intake API

This section has moved. Please see {observability-guide}/apm-configuration-process.html#apm-configuration-apm-server[Configuration options] for current configuration options.

[role="exclude",id="configuration-rum-v1"]
=== `configuration-rum-v1`

This configuration option is no longer supported. Refer to {observability-guide}/apm-configuration-rum.html[Real User Monitoring (RUM)].

[role="exclude",id="rate_limit_v1"]
=== `rate_limit_v1`

This configuration option is no longer supported. Refer to {observability-guide}/apm-configuration-rum.html[Real User Monitoring (RUM)].

[role="exclude",id="configuration-rum-v2"]
=== `configuration-rum-v2`

This section has moved. Refer to {observability-guide}/apm-configuration-rum.html[Real User Monitoring (RUM)].

[role="exclude",id="configuration-rum-general"]
=== Configuration options: general

This section has moved. Refer to {observability-guide}/apm-configuration-rum.html[Real User Monitoring (RUM)].

[role="exclude",id="use-v1-and-v2"]
=== Tuning APM Server using both v1 and v2 intake API

This section has moved. Please see {observability-guide}/apm-tune-data-ingestion.html#apm-tune-apm-server[Tune APM Server] for how to tune APM Server.

// Dashboards

[role="exclude",id="load-dashboards-logstash"]
=== Tuning APM Server using both v1 and v2 intake API

Loading dashboards from APM Server is no longer supported. Please see the {observability-guide}/apm-ui.html[{kib} APM UI] documentation.

[role="exclude",id="url-option"]
=== setup.dashboards.url

Loading dashboards from APM Server is no longer supported. Please see the {observability-guide}/apm-ui.html[{kib} APM UI] documentation.

[role="exclude",id="file-option"]
=== setup.dashboards.file

Loading dashboards from APM Server is no longer supported. Please see the {observability-guide}/apm-ui.html[{kib} APM UI] documentation.

[role="exclude",id="load-kibana-dashboards"]
=== Dashboards

Loading {kib} dashboards from APM Server is no longer supported.
Please use the {observability-guide}/apm-ui.html[{kib} APM UI] instead.
As an alternative, a small number of dashboards and visualizations are available in the
https://github.com/elastic/apm-contrib/tree/main/kibana[apm-contrib] repository.

[role="exclude",id="aws-lambda-arch"]
=== APM Architecture for AWS Lambda

This section has moved. See {apm-lambda-ref}/aws-lambda-arch.html[APM Architecture for AWS Lambda].

[role="exclude",id="aws-lambda-config-options"]
=== Configuration options

This section has moved. See {apm-lambda-ref}/aws-lambda-config-options.html[Configuration options].

[role="exclude",id="aws-lambda-secrets-manager"]
=== Using AWS Secrets Manager to manage APM authentication keys

This section has moved. See {apm-lambda-ref}/aws-lambda-secrets-manager.html[Using AWS Secrets Manager to manage APM authentication keys].

[role="exclude",id="go-compatibility"]
=== Go Agent Compatibility

This page has moved. Refer to {observability-guide}/apm-agent-server-compatibility.html[APM agent compatibility].

[role="exclude",id="java-compatibility"]
=== Java Agent Compatibility

This page has moved.Refer to {observability-guide}/apm-agent-server-compatibility.html[APM agent compatibility].

[role="exclude",id="dotnet-compatibility"]
=== .NET Agent Compatibility

This page has moved. Refer to {observability-guide}/apm-agent-server-compatibility.html[APM agent compatibility].

[role="exclude",id="nodejs-compatibility"]
=== Node.js Agent Compatibility

This page has moved. Refer to {observability-guide}/apm-agent-server-compatibility.html[APM agent compatibility].

[role="exclude",id="python-compatibility"]
=== Python Agent Compatibility

This page has moved. Refer to {observability-guide}/apm-agent-server-compatibility.html[APM agent compatibility].

[role="exclude",id="ruby-compatibility"]
=== Ruby Agent Compatibility

This page has moved. Refer to {observability-guide}/apm-agent-server-compatibility.html[APM agent compatibility].

[role="exclude",id="rum-compatibility"]
=== RUM Agent Compatibility

This page has moved. Refer to {observability-guide}/apm-agent-server-compatibility.html[APM agent compatibility].

[role="exclude",id="apm-release-notes"]
=== APM release highlights

This page has moved.
Please see {observability-guide}/whats-new.html[What's new in {observability} {minor-version}].

[role="exclude",id="whats-new"]
=== What's new in APM {minor-version}

This page has moved.
Please see {observability-guide}/whats-new.html[What's new in {observability} {minor-version}].

[role="exclude",id="troubleshooting"]
=== Troubleshooting

This page has moved.
Refer to {observability-guide}/apm-troubleshoot-apm.html[Troubleshoot].

[role="exclude",id="input-apm"]
=== Configuring

This page has moved.
Refer to {observability-guide}/apm-configuring-howto-apm-server.html[Configure].

[role="exclude",id="events-api"]
=== Events Intake API

[discrete]
[[events-api-errors]]
==== Errors

This page has been deleted.
Please see {observability-guide}/apm.html[APM overview].

[role="exclude",id="intake-api"]
=== API

This page has been deleted.
Please see {observability-guide}/apm.html[APM overview].

[role="exclude",id="metadata-api"]
=== Metadata

[discrete]
[[metadata-schema]]
==== Errors

This page has been deleted.
Please see {observability-guide}/apm.html[APM overview].

[role="exclude",id="errors"]
=== Errors

This page has been deleted.
Please see {observability-guide}/apm.html[APM overview].

[role="exclude",id="transaction-spans"]
=== Spans

This page has been deleted.
Please see {observability-guide}/apm.html[APM overview].

[role="exclude",id="transactions"]
=== Transactions

This page has been deleted.
Please see {observability-guide}/apm.html[APM overview].

[role="exclude",id="legacy-apm-overview"]
=== Legacy APM Overview

This page has been deleted.
Please see {observability-guide}/apm.html[APM overview].

[role="exclude",id="apm-components"]
=== Components and documentation

This page has been deleted.
Please see {observability-guide}/apm.html[APM overview].

[role="exclude",id="configuring-ingest-node"]
=== Parse data using ingest node pipelines

This page has been deleted.
Please see {observability-guide}/apm.html[APM overview].

[role="exclude",id="overview"]
=== Legacy APM Server Reference

This page has been deleted.
Please see {observability-guide}/apm.html[APM overview].

[role="exclude",id="metadata"]
=== Metadata

This page has been deleted.
Please see {observability-guide}/apm.html[APM overview].

[role="exclude",id="distributed-tracing"]
=== Distributed tracing

This page has been deleted.
Please see {observability-guide}/apm.html[APM overview].

[role="exclude",id="sourcemaps"]
=== How to apply source maps to error stack traces when using minified bundles

[discrete]
[[sourcemap-rum-generate]]
==== Sourcemap RUM Generate

[discrete]
[[sourcemap-rum-upload]]
==== Sourcemap RUM upload

This page has been deleted.
Please see {observability-guide}/apm.html[APM overview].

// Redirects for move to Observability guide

[role="exclude",id="apm-overview"]
=== APM overview

{move-notice}

Refer to {observability-guide}/apm.html[Application Performance Monitoring (APM)].

[role="exclude",id="apm-quick-start"]
=== Quick start with Elastic Cloud

{move-notice}

Refer to {observability-guide}/get-started-with-fleet-apm-server.html[Quick start with Elastic Cloud].

[role="exclude",id="getting-started-apm-server"]
=== Self manage APM Server

{move-notice}

Refer to {observability-guide}/apm-getting-started-apm-server.html[Self manage APM Server].

[role="exclude",id="_apm_server_binary"]
=== APM Server binary

{move-notice}

Refer to {observability-guide}/_apm_server_binary.html[APM Server binary].

[role="exclude",id="installing"]
=== Step 1: Install

{move-notice}

Refer to {observability-guide}/_apm_server_binary.html#apm-installing[Step 1: Install].

[role="exclude",id="apm-server-configuration"]
=== Step 2: Set up and configure

{move-notice}

Refer to {observability-guide}/_apm_server_binary.html#apm-server-configuration[Step 2: Set up and configure].

[role="exclude",id="apm-server-starting"]
=== Step 3: Start

{move-notice}

Refer to {observability-guide}/_apm_server_binary.html#apm-server-starting[Step 3: Start].

[role="exclude",id="next-steps"]
=== Step 4: Next steps

{move-notice}

Refer to {observability-guide}/_apm_server_binary.html#apm-next-steps[Step 4: Next steps].

[role="exclude",id="setup-repositories"]
=== Repositories for APT and YUM

{move-notice}

Refer to {observability-guide}/_apm_server_binary.html#apm-setup-repositories[Repositories for APT and YUM].

[role="exclude",id="running-on-docker"]
=== Run APM Server on Docker

{move-notice}

Refer to {observability-guide}/_apm_server_binary.html#apm-running-on-docker[Run APM Server on Docker].

[role="exclude",id="_fleet_managed_apm_server"]
=== Fleet-managed APM Server

{move-notice}

Refer to {observability-guide}/get-started-with-fleet-apm-server.html[Fleet-managed APM Server].

[role="exclude",id="_step_1_set_up_fleet"]
=== Step 1: Set up Fleet

{move-notice}

Refer to {observability-guide}/get-started-with-fleet-apm-server.html#_step_1_set_up_fleet[Step 1: Set up Fleet].

[role="exclude",id="_step_2_add_and_configure_the_apm_integration"]
=== Step 2: Add and configure the APM integration

{move-notice}

Refer to {observability-guide}/get-started-with-fleet-apm-server.html#add-apm-integration[Step 2: Add and configure the APM integration].

[role="exclude",id="_step_3_install_apm_agents"]
=== Step 3: Install APM agents

{move-notice}

Refer to {observability-guide}/get-started-with-fleet-apm-server.html#_step_3_install_apm_agents[Step 3: Install APM agents].

[role="exclude",id="_step_4_view_your_data"]
=== Step 4: View your data

{move-notice}

Refer to {observability-guide}/get-started-with-fleet-apm-server.html#_step_4_view_your_data[Step 4: View your data].

[role="exclude",id="data-model"]
=== Data Model

{move-notice}

Refer to {observability-guide}/apm-data-model.html[Data Model].

[role="exclude",id="data-model-spans"]
=== Spans

{move-notice}

Refer to {observability-guide}/apm-data-model-spans.html[Spans].

[discrete]
[[data-model-dropped-spans]]
==== Dropped spans

Refer to {observability-guide}/apm-data-model-spans.html#apm-data-model-dropped-spans[Dropped spans]

[role="exclude",id="data-model-transactions"]
=== Transactions

{move-notice}

Refer to {observability-guide}/apm-data-model-transactions.html[Transactions].

[role="exclude",id="data-model-errors"]
=== Errors

{move-notice}

Refer to {observability-guide}/apm-data-model-errors.html[Errors].

[role="exclude",id="data-model-metrics"]
=== Metrics

{move-notice}

Refer to {observability-guide}/apm-data-model-metrics.html[Metrics].

[role="exclude",id="data-model-metadata"]
=== Metadata

{move-notice}

Refer to {observability-guide}/apm-data-model-metadata.html[Metadata]..

[discrete]
[[data-model-custom]]
=== Custom context

Refer to {observability-guide}/apm-data-model-metadata.html#apm-data-model-custom[Custom context].

[discrete]
[[data-model-labels]]
=== Labels

Refer to {observability-guide}/apm-data-model-metadata.html#apm-data-model-labels[Labels].

[role="exclude",id="features"]
=== Features

{move-notice}

Refer to {observability-guide}/apm-features.html[Features].

[role="exclude",id="apm-data-security"]
=== Data security

{move-notice}

Refer to {observability-guide}/apm-data-security.html[Data security].

[role="exclude",id="filtering"]
=== Built-in data filters

{move-notice}

Refer to {observability-guide}/apm-filtering.html[Built-in data filters].

[role="exclude",id="custom-filter"]
=== Custom filters

{move-notice}

Refer to {observability-guide}/apm-custom-filter.html[Custom filters].

[role="exclude",id="data-security-delete"]
=== Delete sensitive data

{move-notice}

Refer to {observability-guide}/apm-data-security-delete.html[Delete sensitive data].

[role="exclude",id="apm-distributed-tracing"]
=== Distributed tracing

{move-notice}

Refer to {observability-guide}/apm-distributed-tracing.html[Distributed tracing].

[role="exclude",id="apm-rum"]
=== Real User Monitoring (RUM)

{move-notice}

Refer to {observability-guide}/apm-rum.html[Real User Monitoring (RUM)].

[role="exclude",id="sampling"]
=== Transaction sampling

{move-notice}

Refer to {observability-guide}/apm-sampling.html[Transaction sampling].

[role="exclude",id="configure-head-based-sampling"]
=== Configure head-based sampling

{move-notice}

Refer to {observability-guide}/apm-sampling.html#apm-configure-head-based-sampling[Configure head-based sampling].

[role="exclude",id="configure-tail-based-sampling"]
=== Configure tail-based sampling

{move-notice}

Refer to {observability-guide}/apm-sampling.html#apm-configure-tail-based-sampling[Configure tail-based sampling].

[role="exclude",id="log-correlation"]
=== Logging integration

{move-notice}

Refer to {observability-guide}/application-logs.html[Stream application logs].

[discrete]
[[ingest-logs-in-es]]
==== Ingest your logs into Elasticsearch

Refer to {observability-guide}/application-logs.html[Stream application logs].

[role="exclude",id="cross-cluster-search"]
=== Cross-cluster search

{move-notice}

Refer to {observability-guide}/apm-cross-cluster-search.html[Cross-cluster search].

[role="exclude",id="span-compression"]
=== Span compression

{move-notice}

Refer to {observability-guide}/apm-span-compression.html[Span compression].

[role="exclude",id="monitoring-aws-lambda"]
=== Monitoring AWS Lambda Functions

{move-notice}

Refer to {observability-guide}/apm-monitoring-aws-lambda.html[Monitoring AWS Lambda Functions].

[role="exclude",id="apm-mutating-admission-webhook"]
=== APM Attacher

{move-notice}

Refer to {observability-guide}/apm-mutating-admission-webhook.html[APM Attacher].

[role="exclude",id="how-to-guides"]
=== How-to guides

{move-notice}

Refer to {observability-guide}/apm-how-to-guides.html[How-to guides].

[role="exclude",id="source-map-how-to"]
=== Create and upload source maps (RUM)
Refer to {observability-guide}/apm-source-map-how-to.html[Create and upload source maps (RUM)]

[discrete]
[[source-map-rum-generate]]
==== Generate a source map

Refer to {observability-guide}/apm-source-map-how-to.html#apm-source-map-rum-generate[Generate a source map]

[discrete]
[[source-map-rum-upload]]
==== Upload the source map

Refer to {observability-guide}/apm-source-map-how-to.html#apm-source-map-rum-upload[Upload the source map]

[role="exclude",id="jaeger-integration"]
=== Integrate with Jaeger

{move-notice}

Refer to {observability-guide}/apm-jaeger-integration.html[Integrate with Jaeger].

[role="exclude",id="ingest-pipelines"]
=== Parse data using ingest pipelines

{move-notice}

Refer to {observability-guide}/apm-ingest-pipelines.html[Parse data using ingest pipelines].

[role="exclude",id="custom-index-template"]
=== View the Elasticsearch index template

{move-notice}

Refer to {observability-guide}/apm-custom-index-template.html[View the Elasticsearch index template].

[role="exclude",id="open-telemetry"]
=== OpenTelemetry integration

{move-notice}

Refer to {observability-guide}/apm-open-telemetry.html[OpenTelemetry integration].

[role="exclude",id="open-telemetry-with-elastic"]
=== OpenTelemetry API/SDK with Elastic APM agents

{move-notice}

Refer to {observability-guide}/apm-open-telemetry-with-elastic.html[OpenTelemetry API/SDK with Elastic APM agents].

[role="exclude",id="open-telemetry-direct"]
=== OpenTelemetry native support

{move-notice}

Refer to {observability-guide}/apm-open-telemetry-direct.html[OpenTelemetry native support].

[role="exclude",id="open-telemetry-other-env"]
=== AWS Lambda Support

{move-notice}

Refer to {observability-guide}/apm-open-telemetry-other-env.html[AWS Lambda Support].

[role="exclude",id="open-telemetry-collect-metrics"]
=== Collect metrics

{move-notice}

Refer to {observability-guide}/apm-open-telemetry-collect-metrics.html[Collect metrics].

[role="exclude",id="open-telemetry-known-limitations"]
=== Limitations

{move-notice}

Refer to {observability-guide}/apm-open-telemetry-known-limitations.html[Limitations].

[role="exclude",id="open-telemetry-resource-attributes"]
=== Resource attributes

{move-notice}

Refer to {observability-guide}/apm-open-telemetry-resource-attributes.html[Resource attributes].

[role="exclude",id="manage-storage"]
=== Manage storage

{move-notice}

Refer to {observability-guide}/apm-manage-storage.html[Manage storage].

[role="exclude",id="apm-data-streams"]
=== Data streams

{move-notice}

Refer to {observability-guide}/apm-data-streams.html[Data streams].

[role="exclude",id="ilm-how-to"]
=== Index lifecycle management

{move-notice}

Refer to {observability-guide}/apm-ilm-how-to.html[Index lifecycle management].

[discrete]
[[data-streams-custom-policy]]
==== Configure a custom index lifecycle policy

Refer to {observability-guide}/apm-ilm-how-to.html#apm-data-streams-custom-policy[Configure a custom index lifecycle policy]

[role="exclude",id="storage-guide"]
=== Storage and sizing guide

{move-notice}

Refer to {observability-guide}/apm-storage-guide.html[Storage and sizing guide].

[role="exclude",id="reduce-apm-storage"]
=== Reduce storage

{move-notice}

Refer to {observability-guide}/apm-reduce-apm-storage.html[Reduce storage].

[role="exclude",id="exploring-es-data"]
=== Explore data in Elasticsearch

{move-notice}

Refer to {observability-guide}/apm-exploring-es-data.html[Explore data in Elasticsearch].

[role="exclude",id="configuring-howto-apm-server"]
=== Configure

{move-notice}

Refer to {observability-guide}/apm-configuring-howto-apm-server.html[Configure].

[role="exclude",id="configuration-process"]
=== General configuration options

{move-notice}

Refer to {observability-guide}/apm-configuration-process.html[General configuration options].

[discrete]
[[max_event_size]]
==== Max event size

Refer to {observability-guide}/apm-configuration-process.html#apm-max_event_size[Max event size].

[role="exclude",id="configuration-anonymous"]
=== Anonymous authentication

{move-notice}

Refer to {observability-guide}/apm-configuration-anonymous.html[Anonymous authentication].

[role="exclude",id="apm-agent-auth"]
=== APM agent authorization

{move-notice}

Refer to {observability-guide}/apm-agent-auth.html[APM agent authorization].

[role="exclude",id="configure-agent-config"]
=== APM agent configuration

{move-notice}

Refer to {observability-guide}/apm-configure-agent-config.html[APM agent configuration].

[role="exclude",id="configuration-instrumentation"]
=== Instrumentation

{move-notice}

Refer to {observability-guide}/apm-configuration-instrumentation.html[Instrumentation].

[role="exclude",id="setup-kibana-endpoint"]
=== Kibana endpoint

{move-notice}

Refer to {observability-guide}/apm-setup-kibana-endpoint.html[Kibana endpoint].

[role="exclude",id="configuration-logging"]
=== Logging

{move-notice}

Refer to {observability-guide}/apm-configuration-logging.html[Logging].

[role="exclude",id="configuring-output"]
=== Output

{move-notice}

Refer to {observability-guide}/apm-configuring-output.html[Output].

[role="exclude",id="configure-cloud-id"]
=== Elasticsearch Service

{move-notice}

Refer to {observability-guide}/apm-configure-cloud-id.html[Elasticsearch Service].

[role="exclude",id="elasticsearch-output"]
=== Elasticsearch

{move-notice}

Refer to {observability-guide}/apm-elasticsearch-output.html[Elasticsearch].

[role="exclude",id="logstash-output"]
=== Logstash

{move-notice}

Refer to {observability-guide}/apm-logstash-output.html[Logstash].

[role="exclude",id="kafka-output"]
=== Kafka

{move-notice}

Refer to {observability-guide}/apm-kafka-output.html[Kafka].

[role="exclude",id="redis-output"]
=== Redis

{move-notice}

Refer to {observability-guide}/apm-redis-output.html[Redis].

[role="exclude",id="console-output"]
=== Console

{move-notice}

Refer to {observability-guide}/apm-console-output.html[Console].

[role="exclude",id="configuration-path"]
=== Project paths

{move-notice}

Refer to {observability-guide}/apm-configuration-path.html[Project paths].

[role="exclude",id="configuration-rum"]
=== Real User Monitoring (RUM)

{move-notice}

Refer to {observability-guide}/apm-configuration-rum.html[Real User Monitoring (RUM)].

[discrete]
[[rum-library-pattern]]
==== Library Frame Pattern

Refer to {observability-guide}/apm-configuration-rum.html#apm-rum-library-pattern[Library Frame Pattern].

[discrete]
[[rum-allow-origins]]
==== Allowed Origins

Refer to {observability-guide}/apm-configuration-rum.html#apm-rum-allow-origins[Allowed Origins].

[role="exclude",id="configuration-ssl-landing"]
=== SSL/TLS settings

{move-notice}

Refer to {observability-guide}/apm-configuration-ssl-landing.html[SSL/TLS settings].

[role="exclude",id="configuration-ssl"]
=== SSL/TLS output settings

{move-notice}

Refer to {observability-guide}/apm-configuration-ssl.html[SSL/TLS output settings].

[role="exclude",id="agent-server-ssl"]
=== SSL/TLS input settings

{move-notice}

Refer to {observability-guide}/apm-agent-server-ssl.html[SSL/TLS input settings].

[role="exclude",id="tail-based-samling-config"]
=== Tail-based sampling

{move-notice}

Refer to {observability-guide}/apm-tail-based-samling-config.html[Tail-based sampling].

[role="exclude",id="config-env"]
=== Use environment variables in the configuration

{move-notice}

Refer to {observability-guide}/apm-config-env.html[Use environment variables in th].

[role="exclude",id="setting-up-and-running"]
=== Advanced setup

{move-notice}

Refer to {observability-guide}/apm-setting-up-and-running.html[Advanced setup].

[role="exclude",id="directory-layout"]
=== Installation layout

{move-notice}

Refer to {observability-guide}/apm-directory-layout.html[Installation layout].

[role="exclude",id="keystore"]
=== Secrets keystore

{move-notice}

Refer to {observability-guide}/apm-keystore.html[Secrets keystore].

[role="exclude",id="command-line-options"]
=== Command reference

{move-notice}

Refer to {observability-guide}/apm-command-line-options.html[Command reference].

[role="exclude",id="tune-data-ingestion"]
=== Tune data ingestion

{move-notice}

Refer to {observability-guide}/apm-tune-data-ingestion.html[Tune data ingestion].

[role="exclude",id="high-availability"]
=== High Availability

{move-notice}

Refer to {observability-guide}/apm-high-availability.html[High Availability].

[role="exclude",id="running-with-systemd"]
=== APM Server and systemd

{move-notice}

Refer to {observability-guide}/apm-running-with-systemd.html[APM Server and systemd].

[role="exclude",id="securing-apm-server"]
=== Secure communication

{move-notice}

Refer to {observability-guide}/apm-securing-apm-server.html[Secure communication].

[role="exclude",id="secure-agent-communication"]
=== With APM agents

{move-notice}

Refer to {observability-guide}/apm-secure-agent-communication.html[With APM agents].

[role="exclude",id="agent-tls"]
=== APM agent TLS communication

{move-notice}

Refer to {observability-guide}/apm-agent-tls.html[APM agent TLS communication].

[discrete]
[[agent-client-cert]]
==== Client certificate authentication

Refer to {observability-guide}/apm-agent-tls.html#apm-agent-client-cert[Client certificate authentication].

[role="exclude",id="api-key"]
=== API keys

{move-notice}

Refer to {observability-guide}/apm-api-key.html[API keys].

[role="exclude",id="secret-token"]
=== Secret token

{move-notice}

Refer to {observability-guide}/apm-secret-token.html[Secret token].

[role="exclude",id="anonymous-auth"]
=== Anonymous authentication

{move-notice}

Refer to {observability-guide}/apm-anonymous-auth.html[Anonymous authentication].

[role="exclude",id="secure-comms-stack"]
=== With the Elastic Stack

{move-notice}

Refer to {observability-guide}/apm-secure-comms-stack.html[With the Elastic Stack].

[role="exclude",id="privileges-to-publish-events"]
=== Create a _writer_ user

{move-notice}

Refer to {observability-guide}/apm-privileges-to-publish-events.html[Create a _writer_ user].

[role="exclude",id="privileges-to-publish-monitoring"]
=== Create a _monitoring_ user

{move-notice}

Refer to {observability-guide}/apm-privileges-to-publish-monitoring.html[Create a _monitoring_ user].

[role="exclude",id="privileges-api-key"]
=== Create an _API key_ user

{move-notice}

Refer to {observability-guide}/apm-privileges-api-key.html[Create an _API key_ user].

[role="exclude",id="privileges-agent-central-config"]
=== Create a _central config_ user

{move-notice}

Refer to {observability-guide}/apm-privileges-agent-central-config.html[Create a _central config_ user].

[role="exclude",id="privileges-rum-source-map"]
=== Create a _source map_ user

{move-notice}

Refer to {observability-guide}/apm-privileges-rum-source-map.html[Create a _source map_ user].

[role="exclude",id="beats-api-keys"]
=== Grant access using API keys

{move-notice}

Refer to {observability-guide}/apm-beats-api-keys.html[Grant access using API keys].

[role="exclude",id="monitor-apm"]
=== Monitor

{move-notice}

Refer to {observability-guide}/apm-monitor-apm.html[Monitor].

[role="exclude",id="monitor-apm-self-install"]
=== Fleet-managed

{move-notice}

Refer to {observability-guide}/apm-monitor-apm-self-install.html[Fleet-managed].

[role="exclude",id="monitoring"]
=== APM Server binary

{move-notice}

Refer to {observability-guide}/apm-monitoring.html[APM Server binary].

[role="exclude",id="monitoring-internal-collection"]
=== Use internal collection

{move-notice}

Refer to {observability-guide}/apm-monitoring-internal-collection.html[Use internal collection].

[role="exclude",id="monitoring-local-collection"]
=== Use local collection

{move-notice}

Refer to {observability-guide}/apm-monitoring-local-collection.html[Use local collection].

[role="exclude",id="select-metrics"]
=== The select metrics

{move-notice}

Refer to {observability-guide}/apm-select-metrics.html[The select metrics].

[role="exclude",id="monitoring-metricbeat-collection"]
=== Use Metricbeat collection

{move-notice}

Refer to {observability-guide}/apm-monitoring-metricbeat-collection.html[Use Metricbeat collection].

[role="exclude",id="api"]
=== API

{move-notice}

Refer to {observability-guide}/apm-api.html[API].

[role="exclude",id="api-info"]
=== APM Server information API

{move-notice}

Refer to {observability-guide}/apm-api-info.html[APM Server information API].

[role="exclude",id="api-events"]
=== Elastic APM events intake API

{move-notice}

Refer to {observability-guide}/apm-api-events.html[Elastic APM events intake API].

[role="exclude",id="api-metadata"]
=== Metadata

{move-notice}

Refer to {observability-guide}/apm-api-events.html#apm-api-metadata[Metadata].

[discrete]
[[api-metadata-schema]]
==== Metadata scheme

Refer to {observability-guide}/apm-api-events.html#apm-api-metadata-schema[Metadata scheme].

[role="exclude",id="api-transaction"]
=== Transactions

{move-notice}

Refer to {observability-guide}/apm-api-events.html#apm-api-transaction[Transactions].

[role="exclude",id="api-span"]
=== Spans

{move-notice}

Refer to {observability-guide}/apm-api-events.html#apm-api-span[Spans].

[role="exclude",id="api-error"]
=== Errors

{move-notice}

Refer to {observability-guide}/apm-api-events.html#apm-api-error[Errors].

[role="exclude",id="api-metricset"]
=== Metrics
Refer to {observability-guide}/apm-api-events.html#apm-api-metricset[Metrics]

[role="exclude",id="api-event-example"]
=== Example request body

{move-notice}

Refer to {observability-guide}/apm-api-events.html#apm-api-event-example[Example request body].

[role="exclude",id="api-config"]
=== Elastic APM agent configuration API

{move-notice}

Refer to {observability-guide}/apm-api-config.html[Elastic APM agent configuration].

[role="exclude",id="api-otlp"]
=== OpenTelemetry intake API

{move-notice}

Refer to {observability-guide}/apm-api-otlp.html[OpenTelemetry intake API].

[role="exclude",id="api-jaeger"]
=== Jaeger event intake

{move-notice}

Refer to {observability-guide}/apm-api-jaeger.html[Jaeger event intake].

[role="exclude",id="troubleshoot-apm"]
=== Troubleshoot

{move-notice}

Refer to {observability-guide}/apm-troubleshoot-apm.html[Troubleshoot].

[role="exclude",id="common-problems"]
=== Common problems

{move-notice}

Refer to {observability-guide}/apm-common-problems.html[Common problems].

[role="exclude",id="server-es-down"]
=== What happens when APM Server or Elasticsearch is down?

{move-notice}

Refer to {observability-guide}/apm-server-es-down.html[What happens when APM Server or Ela].

[role="exclude",id="common-response-codes"]
=== APM Server response codes

{move-notice}

Refer to {observability-guide}/apm-common-response-codes.html[APM Server response codes].

[role="exclude",id="processing-and-performance"]
=== Processing and performance

{move-notice}

Refer to {observability-guide}/apm-processing-and-performance.html[Processing and performance].

[role="exclude",id="enable-apm-server-debugging"]
=== APM Server binary debugging

{move-notice}

Refer to {observability-guide}/apm-enable-apm-server-debugging.html[APM Server binary debugging].

[role="exclude",id="upgrade"]
=== Upgrade

{move-notice}

Refer to {observability-guide}/apm-upgrade.html[Upgrade].

[role="exclude",id="agent-server-compatibility"]
=== APM agent compatibility

{move-notice}

Refer to {observability-guide}/apm-agent-server-compatibility.html[APM agent compatibility].

[role="exclude",id="apm-breaking"]
=== Breaking Changes

{move-notice}

Refer to {observability-guide}/apm-breaking.html[Breaking Changes].

[role="exclude",id="upgrading-to-8.x"]
=== Upgrade to version 8.11.3

{move-notice}

Refer to {observability-guide}/apm-upgrading-to-8.x.html[Upgrade to version 8.11.3].

[role="exclude",id="upgrade-8.0-self-standalone"]
=== Self-installation standalone

{move-notice}

Refer to {observability-guide}/apm-upgrade-8.0-self-standalone.html[Self-installation standalone].

[role="exclude",id="upgrade-8.0-self-integration"]
=== Self-installation APM integration

{move-notice}

Refer to {observability-guide}/apm-upgrade-8.0-self-integration.html[Self-installation APM integration].

[role="exclude",id="upgrade-8.0-cloud-standalone"]
=== Elastic Cloud standalone

{move-notice}

Refer to {observability-guide}/apm-upgrade-8.0-cloud-standalone.html[Elastic Cloud standalone].

[role="exclude",id="upgrade-8.0-cloud-integration"]
=== Elastic Cloud APM integration

{move-notice}

Refer to {observability-guide}/apm-upgrade-8.0-cloud-integration.html[Elastic Cloud APM integration].

[role="exclude",id="upgrade-to-apm-integration"]
=== Switch to the Elastic APM integration

{move-notice}

Refer to {observability-guide}/apm-upgrade-to-apm-integration.html[Switch to the Elastic APM integration].

[role="exclude",id="apm-integration-upgrade-steps"]
=== Switch a self-installation

{move-notice}

Refer to {observability-guide}/apm-integration-upgrade-steps.html[Switch a self-installation].

[role="exclude",id="apm-integration-upgrade-steps-ess"]
=== Switch an Elastic Cloud cluster

{move-notice}

Refer to {observability-guide}/apm-integration-upgrade-steps-ess.html[Switch an Elastic Cloud cluster].

[role="exclude",id="release-notes"]
=== Release notes

{move-notice}

Refer to {observability-guide}/apm-release-notes.html[Release notes].

[role="exclude",id="release-notes-8.11"]
=== APM version 8.11

{move-notice}

Refer to {observability-guide}/apm-release-notes-8.11.html[APM version 8.11].

[role="exclude",id="release-notes-8.10"]
=== APM version 8.10

{move-notice}

Refer to {observability-guide}/apm-release-notes-8.10.html[APM version 8.10].

[role="exclude",id="release-notes-8.9"]
=== APM version 8.9

{move-notice}

Refer to {observability-guide}/apm-release-notes-8.9.html[APM version 8.9].

[role="exclude",id="release-notes-8.8"]
=== APM version 8.8

{move-notice}

Refer to {observability-guide}/apm-release-notes-8.8.html[APM version 8.8].

[role="exclude",id="release-notes-8.7"]
=== APM version 8.7

{move-notice}

Refer to {observability-guide}/apm-release-notes-8.7.html[APM version 8.7].

[role="exclude",id="release-notes-8.6"]
=== APM version 8.6

{move-notice}

Refer to {observability-guide}/apm-release-notes-8.6.html[APM version 8.6].

[role="exclude",id="release-notes-8.5"]
=== APM version 8.5

{move-notice}

Refer to {observability-guide}/apm-release-notes-8.5.html[APM version 8.5].

[role="exclude",id="release-notes-8.4"]
=== APM version 8.4

{move-notice}

Refer to {observability-guide}/apm-release-notes-8.4.html[APM version 8.4].

[role="exclude",id="release-notes-8.3"]
=== APM version 8.3

{move-notice}

Refer to {observability-guide}/apm-release-notes-8.3.html[APM version 8.3].

[role="exclude",id="release-notes-8.2"]
=== APM version 8.2

{move-notice}

Refer to {observability-guide}/apm-release-notes-8.2.html[APM version 8.2].

[role="exclude",id="release-notes-8.1"]
=== APM version 8.1

{move-notice}

Refer to {observability-guide}/apm-release-notes-8.1.html[APM version 8.1].

[role="exclude",id="release-notes-8.0"]
=== APM version 8.0

{move-notice}

Refer to {observability-guide}/apm-release-notes-8.0.html[APM version 8.0].
