:global-flags-link: For more flags, see <<elastic-agent-global-flags>>.

[[elastic-agent-cmd-options]]
[role="xpack"]
= Command reference

beta[]

{agent} provides commands for running {agent}, managing {fleet-server}, and
doing common tasks:

* <<elastic-agent-enroll-command,enroll>>
* <<elastic-agent-help-command,help>>
* <<elastic-agent-inspect-command,inspect>>
* <<elastic-agent-install-command,install>>
* <<elastic-agent-restart-command,restart>>
* <<elastic-agent-run-command,run>>
* <<elastic-agent-uninstall-command,uninstall>>
* <<elastic-agent-upgrade-command,upgrade>>
* <<elastic-agent-version-command,version>>
//* <<elastic-agent-watch-command,watch>>

NOTE: You might need to log in as a root user (or Administrator on Windows) to
run these commands.

++++
<hr>
++++

[discrete]
[[elastic-agent-enroll-command]]
== elastic-agent enroll

Enroll the {agent} in {fleet}.

Use this command to enroll the {agent} in {fleet} without installing the
agent as a service. You will need to do this if you installed
the {agent} from a DEB or RPM package and plan to use systemd commands to
start and manage the service. This command is also useful for testing
{agent} prior to installing it.

If you've already installed {agent}, use this command to modify the settings that {agent} runs with. 

TIP: To enroll an {agent} _and_ install it as a service, use the
<<elastic-agent-install-command,`install` command>> instead. Installing as a service is the most common scenario.

We recommend that you run the `enroll` (or `install`) command as the root user because some
integrations require root privileges to collect sensitive data. This command
overwrites the `elastic-agent.yml` file in the agent directory.

This command includes optional flags to set up <<fleet-server,{fleet-server}>>.

IMPORTANT: This command enrolls the {agent} in {fleet}; it does not start the
agent. To start the agent, either <<start-elastic-agent,start the service>>, if
one exists, or use the <<elastic-agent-run-command,`run` command>> to start the
agent from a terminal.


[discrete]
=== Synopsis

To enroll the {agent} in {fleet}:

[source,shell]
----
elastic-agent enroll --url <string>
                     --enrollment-token <string>
                     [--ca-sha256 <string>]
                     [--certificate-authorities <string>]
                     [--force]
                     [--help]
                     [--insecure ]
                     [global-flags]
----

To enroll the {agent} in {fleet} and set up {fleet-server}:

[source,shell]
----
elastic-agent enroll --fleet-server-es <string>
                     --fleet-server-service-token <string>
                     [--ca-sha256 <string>]
                     [--certificate-authorities <string>]
                     [--fleet-server-cert <string>] <1>
                     [--fleet-server-cert-key <string>]
                     [--fleet-server-es-ca <string>]
                     [--fleet-server-host <string>]
                     [--fleet-server-insecure-http]
                     [--fleet-server-policy <string>]
                     [--fleet-server-port <uint16>]
                     [--force]
                     [--help]
                     [--insecure ]
                     [global-flags]
----
<1> If no `fleet-server-cert*` flags are specified, {agent} auto-generates a
self-signed certificate with the hostname of the machine. Remote {agent}s
enrolling into a {fleet-server} with self-signed certificates must specify
the `insecure` flag.

[discrete]
=== Options

// These descriptions are included for the enroll and install commands
// tag::enroll-install-options[]

`--ca-sha256 <string>`::
Comma-separated list of certificate authority hash pins used for certificate
verification.

`--certificate-authorities <string>`::
Comma-separated list of root certificates used for server verification.

`--enrollment-token <string>`::
Enrollment token to use to enroll {agent} into {fleet}. You can use
the same enrollment token for multiple agents.

`--fleet-server-cert <string>`::
Certificate to use for exposed {fleet-server} HTTPS endpoint.

`--fleet-server-cert-key <string>`::
Private key to use for exposed {fleet-server} HTTPS endpoint.

`--fleet-server-es <string>`::
Start a {fleet-server} process when {agent} is started, and connect to the
specified {es} URL. 

`--fleet-server-es-ca <string>`::
Path to certificate authority to use to communicate with {es}.

`--fleet-server-host <string>`::
{fleet-server} HTTP binding host (overrides the policy).

`--fleet-server-insecure-http`::
Expose {fleet-server} over HTTP. This option is not recommended because it's
insecure. It's useful during development and testing, but should not be used in
production. When using this option, you should bind {fleet-server} to the
local host (this is the default).

`--fleet-server-policy <string>`::
Used when starting a self-managed {fleet-server} to allow a specific policy to be used,
instead of the Default Fleet Server policy.

`--fleet-server-port <uint16>`::
{fleet-server} HTTP binding port (overrides the policy).

`--fleet-server-service-token <string>`::
Service token to use for communication with {es}. 

`--force`::
Force overwrite of current configuration without prompting for confirmation.
This flag is helpful when using automation software or scripted deployments.

`--help`::
Show help for the `enroll` command.

`--insecure`::
Allow insecure connections to {fleet-server}. This setting is required in the
following situations:
+
--
* When connecting to an HTTP server. The API keys are sent in clear text.
* When connecting to an HTTPs server and the certificate chain cannot be
verified. The content is encrypted, but the certificate is not verified.
--
+
We strongly recommend that you use a secure connection.

`--url <string>`::
Fleet Server URL to use to enroll the {agent} into {fleet}.

// end::enroll-install-options[]

{global-flags-link}

[discrete]
=== Examples

Enroll the {agent} in {fleet}:

[source,shell]
----
elastic-agent enroll -f \
  --url=https://cedd4e0e21e240b4s2bbbebdf1d6d52f.fleet.eu-west-1.aws.cld.elstc.co:443 \
  --enrollment-token=NEFmVllaa0JLRXhKebVKVTR5TTI6N2JaVlJpSGpScmV0ZUVnZVlRUExFQQ==
----

Enroll the {agent} in {fleet} and start {fleet-server}:

[source,shell]
----
elastic-agent enroll -f --fleet-server-es=http://elasticsearch:9200 \
  --fleet-server-service-token=AbEAAdesYXN1abMvZmxlZXQtc2VldmVyL3Rva2VuLTE2MTkxMzg3MzIzMTg7dzEta0JDTmZUcGlDTjlwRmNVTjNVQQ
----

Start {agent} with {fleet-server} (running on a custom CA). This example
assumes you've generated the certificates with the following names:

* `ca.crt`: Root CA certificate
* `fleet-server.crt`: {fleet-server} certificate
* `fleet-server.key`: {fleet-server} private key

[source,shell]
----
elastic-agent enroll -f --fleet-server-es=https://elasticsearch:9200 \
  --fleet-server-es-ca=ca.crt --fleet-server-service-token=AbEAAdesYXN1abMvZmxlZXQtc2VldmVyL3Rva2VuLTE2MTkxMzg3MzIzMTg7dzEta0JDTmZUcGlDTjlwRmNVTjNVQQ \
  --fleet-server-cert fleet-server.crt --fleet-server-cert-key fleet-server.key
----

Then enroll another {agent} into the {fleet-server} started in the previous
example:

[source,shell]
----
elastic-agent enroll -f --url https://fleet-server-host:8220 \
  --enrollment-token NEFmVllaa0JLRXhKebVKVTR5TTI6N2JaVlJpSGpScmV0ZUVnZVlRUExFQQ==
  --certificate-authorities root.ca
----

++++
<hr>
++++

[discrete]
[[elastic-agent-help-command]]
== elastic-agent help

Show help for a specific command.

[discrete]
=== Synopsis

[source,shell]
----
elastic-agent help <command> [--help] [global-flags]
----

[discrete]
=== Options

`command`::
The name of the command.

`--help`::
Show help for the `help` command.

{global-flags-link}

[discrete]
=== Example

[source,shell]
----
elastic-agent help enroll
----

++++
<hr>
++++

[discrete]
[[elastic-agent-inspect-command]]
== elastic-agent inspect

Show the current {agent} configuration.

If no parameters are specified, shows the full {agent} configuration.

[discrete]
=== Synopsis

[source,shell]
----
elastic-agent inspect [--help] [global-flags]
elastic-agent inspect output [--output <string>]
                             [--program <string>]
                             [--help]
                             [global-flags]
----

[discrete]
=== Options

`output`:: Display the current configuration for the output. This command
accepts additional flags:
+
--
`--output <string>`::
The name of the output to inspect.

`--program <string>`::
The type of program to inspect. For example, `filebeat`. This option must be
combined with `--output`.
--

`--help`::
Show help for the `inspect` command.

{global-flags-link}

[discrete]
=== Examples

[source,shell]
----
elastic-agent inspect
elastic-agent inspect output --output default
elastic-agent inspect output --output default --program filebeat
----

++++
<hr>
++++

[discrete]
[[elastic-agent-install-command]]
== elastic-agent install

Install {agent} permanently on the system and manage it by using the system's
service manager. The agent will start automatically after installation is
complete. On Linux (tar package), this command requires a system and service
manager like systemd.

IMPORTANT: If you installed {agent} from a DEB or RPM package, use the
<<elastic-agent-enroll-command,`enroll` command>> instead of `install`. The DEB
and RPM packages include a service unit for Linux systems with systemd.

You must run this command as the root user (or Administrator on Windows)
to write files to the correct locations. This command overwrites the
`elastic-agent.yml` file in the agent directory.

[discrete]
=== Synopsis

To install the {agent} as a service, enroll it in {fleet}, and start the
`elastic-agent` service:

[source,shell]
----
elastic-agent install [--ca-sha256 <string>]
                      [--certificate-authorities <string>]
                      [--enrollment-token <string>]
                      [--force]
                      [--help]
                      [--insecure ]
                      [--url string]
                      [global-flags]
----

To install the {agent} as a service, enroll it in {fleet}, and start
a `fleet-server` process alongside the `elastic-agent` service:

[source,shell]
----
elastic-agent install [--ca-sha256 <string>]
                     [--certificate-authorities <string>]
                     [--fleet-server-cert <string>]
                     [--fleet-server-cert-key <string>]
                     [--fleet-server-es <string>]
                     [--fleet-server-es-ca <string>]
                     [--fleet-server-host <string>]
                     [--fleet-server-insecure-http]
                     [--fleet-server-policy <string>]
                     [--fleet-server-port <uint16>]
                     [--fleet-server-service-token <string>]
                     [--force]
                     [--help]
                     [--insecure ]
                     [global-flags]
----


[discrete]
=== Options

include::commands.asciidoc[tag=enroll-install-options]

{global-flags-link}

[discrete]
=== Examples

Install the {agent} as a service, enroll it in {fleet}, and start the
`elastic-agent` service:

[source,shell]
----
elastic-agent install -f \
  --url=https://cedd4e0e21e240b4s2bbbebdf1d6d52f.fleet.eu-west-1.aws.cld.elstc.co:443 \
  --enrollment-token=NEFmVllaa0JLRXhKebVKVTR5TTI6N2JaVlJpSGpScmV0ZUVnZVlRUExFQQ==
----
  
Install the {agent} as a service, enroll it in {fleet}, and start
a `fleet-server` process alongside the `elastic-agent` service:

[source,shell]
----
elastic-agent install -f --fleet-server-es=http://elasticsearch:9200 \
  --fleet-server-service-token=AbEAAdesYXN1abMvZmxlZXQtc2VldmVyL3Rva2VuLTE2MTkxMzg3MzIzMTg7dzEta0JDTmZUcGlDTjlwRmNVTjNVQQ
----

Start {agent} with {fleet-server} (running on a custom CA). This example
assumes you've generated the certificates with the following names:

* `ca.crt`: Root CA certificate
* `fleet-server.crt`: {fleet-server} certificate
* `fleet-server.key`: {fleet-server} private key

[source,shell]
----
elastic-agent install -f --fleet-server-es=https://elasticsearch:9200 \
  --fleet-server-es-ca=ca.crt --fleet-server-service-token=AbEAAdesYXN1abMvZmxlZXQtc2VldmVyL3Rva2VuLTE2MTkxMzg3MzIzMTg7dzEta0JDTmZUcGlDTjlwRmNVTjNVQQ \
  --fleet-server-cert fleet-server.crt --fleet-server-cert-key fleet-server.key
----

Then install another {agent} and enroll it into the {fleet-server} started in
the previous example:

[source,shell]
----
elastic-agent install -f --url https://fleet-server-host:8220 \
  --enrollment-token NEFmVllaa0JLRXhKebVKVTR5TTI6N2JaVlJpSGpScmV0ZUVnZVlRUExFQQ==
  --certificate-authorities root.ca
----


++++
<hr>
++++

[discrete]
[[elastic-agent-restart-command]]
== elastic-agent restart

Restart the currently running {agent} daemon.

[discrete]
=== Synopsis

[source,shell]
----
elastic-agent restart [--help] [global-flags]
----

[discrete]
=== Options

`--help`::
Show help for the `restart` command.

{global-flags-link}

[discrete]
=== Examples

[source,shell]
----
elastic-agent restart
----

++++
<hr>
++++

[discrete]
[[elastic-agent-run-command]]
== elastic-agent run

Start the `elastic-agent` process.

[discrete]
=== Synopsis

[source,shell]
----
elastic-agent run [global-flags]
----

[discrete]
[[elastic-agent-global-flags]]
=== Global flags

These flags are valid whenever you run `elastic-agent` on the command line.

`-c <string>`::
The configuration file to use. If not specified, {agent} uses
`{path.config}/elastic-agent.yml`.

`--e`::
Log to stderr and disable syslog/file output.

`--environment <environmentVar>`::
The environment in which the agent will run.

`--path.config <string>`::
The directory where {agent} looks for its configuration file. The default
varies by platform.

`--path.home <string>`::
The root directory of {agent}. `path.home` determines the location of the
configuration files and data directory.
+
If not specified, {agent} uses the current working directory.

`--path.logs <string>`::
Path to the log output for {agent}. The default varies by platform.

`--v`::
Set log level to INFO.

[discrete]
=== Example

[source,shell]
----
elastic-agent run -c myagentconfig.yml
----

++++
<hr>
++++

[discrete]
[[elastic-agent-uninstall-command]]
== elastic-agent uninstall

Permanently uninstall {agent} from the system.

You must run this command as the root user (or Administrator on Windows)
to remove files. 

[discrete]
=== Synopsis

[source,shell]
----
elastic-agent uninstall [--force] [--help] [global-flags]
----

[discrete]
=== Options

`--force`::
Uninstall {agent} and do not prompt for confirmation. This flag is helpful
when using automation software or scripted deployments.

`--help`::
Show help for the `uninstall` command.

{global-flags-link}

[discrete]
=== Examples

[source,shell]
----
elastic-agent uninstall
----

++++
<hr>
++++

[discrete]
[[elastic-agent-upgrade-command]]
== elastic-agent upgrade

Upgrade the currently running {agent} to the specified version. This should only
be used with agents running in standalone mode. Agents enrolled in {fleet}
should be upgraded through {fleet}.

[discrete]
=== Synopsis

[source,shell]
----
elastic-agent upgrade <version> [--source-uri <string>] [--help] [flags]
----

[discrete]
=== Options

`version`::
The version of {agent} to upgrade to.

`--source-uri <string>`::
The source URI to download the new version from. By default, {agent} uses the
Elastic Artifacts URL.

`--help`::
Show help for the `upgrade` command.

{global-flags-link}

[discrete]
=== Examples

[source,shell]
----
elastic-agent upgrade 7.10.1
----

++++
<hr>
++++

[discrete]
[[elastic-agent-version-command]]
== elastic-agent version

Show the version of {agent}.

[discrete]
=== Synopsis

[source,shell]
----
elastic-agent version [--help] [global-flags]
----

[discrete]
=== Options

`--help`::
Show help for the `version` command.

{global-flags-link}

[discrete]
=== Example

[source,shell]
----
elastic-agent version
----

++++
<hr>
++++

////
//commenting out until we decide whether we want to expose this in public docs
[discrete]
[[elastic-agent-watch-command]]
== elastic-agent watch

Watch the {agent} for failures and initiate rollback.

[discrete]
=== Synopsis

[source,shell]
----
elastic-agent watch [--help] [global-flags]
----

[discrete]
=== Options

`--help`::
Show help for the `watch` command.

{global-flags-link}

[discrete]
=== Example

[source,shell]
----
elastic-agent watch
----

++++
<hr>
++++
////
