[id="ingest-management-faq",titleabbrev="FAQ"]
[role="xpack"]
= Frequently asked questions

beta[]

We have collected the most frequently asked questions here. If your question
isn't answered here, contact us in the {im-forum}[discuss forum]. Your feedback
is very valuable to us.

Also read <<fleet-troubleshooting>>.

[discrete]
[[enrolled-agent-not-showing-up]]
== Why doesn't my enrolled agent show up in the {fleet} app?

If {agent} was successfully enrolled, but doesn't show up in the *Agents* list,
it might not be started. You need to <<run-elastic-agent,start {agent}>>.

[discrete]
[[where-are-the-agent-logs]]
== Where does {agent} store logs after startup?

When started successfully, {metricbeat} logs are stored in
`data/logs/metricbeat` under the folder where {agent} was started. If that log
path does not exist, {agent} was unable to start {metricbeat}, which is a
higher level problem to triage.

[discrete]
[[what-is-my-agent-config]]
== What policy is the {agent} running?

To find the policy file, inspect the `elastic-agent.yml` file in the
folder where you ran {agent}. If you're running the agent in {fleet} mode, this
file contains the following citation:

[source,yaml]
----
Management: mode: "fleet"
----

The `action_store.yml` contains the entire, unencrypted policy:

* To see the {es} location, look at `outputs:hosts`.
* To see the {agent} version, look at the download folder and zip filenames.

This file also shows the version of all packages used by the current
policy.

[discrete]
[[where-is-the-data-agent-is-sending]]
== Why can't I see the data {agent} is sending?

If {elastic-agent} is set up and running, but you don't see data in {kib}:



. Go to **Management > Dev Tools** in {kib}, and in the Console, search your
index for data. For example:
+
[source,console]
----
GET metrics-*/_search
----
+
Or if you prefer, go to the **Discover** app.

. Look at the data that {elastic-agent} has sent and see if the `name.host`
field contains your host machine name.

If you don't see data for your host, it's possible that the data is blocked
in the network, or that a firewall or security problem is preventing the {agent}
from sending the data.

Although it's redundant to install stand-alone {metricbeat}, you might want to
try installing it to see if it's able to send data successfully to {es}. For
more information, see
{metricbeat-ref}/metricbeat-installation-configuration.html[{metricbeat} quick start].

If {metricbeat} is able to send data to {es}, there is possibly a bug or
problem with {agent}, and you should report it.

[discrete]
[[i-deleted-my-agent]]
== How do I restore an {agent} that I deleted from {fleet}?

It's ok, we've got your back! The data is still in {es}. To add {agent}
to {fleet} again, <<stop-elastic-agent>>, re-enroll it on the host, then
run {agent}.

[discrete]
[[i-rebooted-my-host]]
== How do I restart {agent} after rebooting my host?

On Windows, if you used PowerShell to install {agent} as a service, the agent
should still be running after rebooting the host.

On Linux, if you used the DEB or RPM packages, the agent should still be running
after rebooting the host. 

On macOS, you need to restart {agent} from the command line after
rebooting the host, or follow the steps described in
<<elastic-agent-install-service-macos>> to run the agent as a service. 

Support for installing {agent} as a service on all supported systems will be
available in a future release.

[discrete]
[[does-agent-download-packages]]
== Does {agent} or {kib} download integration packages?

{agent} does not download integration packages. When you add an integration in
{fleet}, {kib} connects to the {package-registry} at `epr.elastic.co`,
downloads the integration package, and stores its assets in {es}. This means
that you no longer have to run a manual setup command to load integrations as
you did previously with {beats} modules.

[discrete]
[[does-agent-download-anything-from-internet]]
== Does {agent} download anything from the Internet?

In most cases, the data collection software required by {agent} is bundled
with the agent. There is one special exception: endpoint security. When an
{agent} policy is set to include the {elastic-endpoint-integration} integration,
{agent} must download software from the Elastic download site.

NOTE: Bundling endpoint security capabilities with {agent} is a known
feature request scoped for a future release. 

[discrete]
[[do-i-need-to-setup-elastic-agent]]
== Do I need to set up the {beats} managed by {agent}?

You might have noticed that {agent} runs {beats} under the hood. But note that
the {beats} managed by {agent} are set up and run differently from standalone
{beats}. 

For example, standalone {beats} use modules and require you to run a setup
command on the host to load assets, such as ingest pipelines and dashboards. In
contrast, {beats} managed by {agent} use integration packages that {kib}
downloads from the {package-registry} at `epr.elastic.co`. This means that
{agent} does not need extra privileges to set up assets because
{fleet} manages the assets.

[discrete]
[[what-is-the-endpoint-package]]
== What is the {elastic-endpoint-integration} integration in {ingest-manager}?

The {elastic-endpoint-integration} integration provides protection on your {agent}
controlled host. The integration monitors your host for security-related events,
allowing for investigation of security data through the {security-app} in {kib}.
The {elastic-endpoint-integration} integration is managed by {agent} in the
same way as other integrations. Try it out! For more information, see the
{security-guide}/index.html[{elastic-sec} solution documentation].
