[[ingest-management-limitations]]
[role="xpack"]
= Limitations of this release

beta[]

{ingest-manager} is currently only available to users with the
{ref}/built-in-roles.html[superuser role]. This role is necessary to create
indices, install integration assets, and update {agent} configurations. In order
to use {fleet}, the {agent}s must have a direct network connection to {kib} and
{es}. It is also possible to run the {agent}s in standalone mode in cases where
a network connection is not available or not needed.

This feature has additional limitations at the current time:

*   Support for a limited number of integrations (more coming soon)
*   Support for only {filebeat}, {metricbeat}, and Endpoint Security.
*   We recommend you enroll no more than 1000 Agents
*   No output to {ls}, Kafka, or other remote clusters
*   No proxy support in {agent}
*   Requires internet access for {kib} to download integration packages
*   No support for advanced {beats} settings like multiline, processors, and so
on
*   No support for Kubernetes or Docker autodiscovery

We encourage you to give feedback and report issues in our {im-forum}[discuss forum].
