[[migrate-auditbeat-to-agent]]
= Migrate from {auditbeat} to {agent}

In order to migrate from using {auditbeat} to using the {agent}, there
are some steps to take into account to be sure to have all the previous
functionality.

First of all, {auditbeat} needs to be uninstalled from the hosts and the {agent}
will need to be deployed instead. More information about how to do this can be
found https://www.elastic.co/guide/en/fleet/current/migrate-beats-to-agent.html[here].

[discrete]
[[compatibility]]
== Compatibility

The integrations that provide replacements for `auditd` and `file_integrity` modules,
are only available for versions of the stack bigger or equal to `8.3`.

[discrete]
[[migrating-from-auditbeat-modules]]
== Migrating from Auditbeat modules

Depending on what Auditbeat modules you are using, they will be replaced
by different components.

[discrete]
[[auditd-module]]
=== https://www.elastic.co/guide/en/beats/auditbeat/current/auditbeat-module-auditd.html[Auditd]

The `auditd` module has a direct replacement with the
https://docs.elastic.co/en/integrations/auditd_manager[Auditd Manager integration]. 
The rules and configuration can be ported to the integration. Starting from `8.4` stacks,
this integration also provides the ability to set the `immutable` flag to the audit
configuration.

If you do not need the integration to manage the rules, there is also the
https://docs.elastic.co/integrations/auditd[Auditd Logs] integration as an alternative,
which will only parse logs from the audit daemon `auditd`.

[discrete]
[[file-integrity-module]]
=== https://www.elastic.co/guide/en/beats/auditbeat/current/auditbeat-module-file_integrity.html[File Integrity]

The `file_integrity` module has a direct replacement with the
https://docs.elastic.co/integrations/fim[File Integrity Monitoring] integration.

Note that this integration is able to report real-time events but lacks the ability
to report who made the changes. If you need such functionality, the
https://www.elastic.co/guide/en/security/current/install-endpoint.html[Endpoint]
can report this information.

[discrete]
[[system-module]]
=== https://www.elastic.co/guide/en/beats/auditbeat/current/auditbeat-module-system.html[System]

The `system` module is discontinued as a standalone module and its functionality has been replaced by other integrations.

[discrete]
[[system-module-host]]
==== https://www.elastic.co/guide/en/beats/auditbeat/current/auditbeat-dataset-system-host.html[System.host]

In order to access the same information, the
https://docs.elastic.co/integrations/osquery[Osquery] or
https://docs.elastic.co/integrations/osquery_manager[Osquery Manager] integrations can be
used to schedule the collection of this information (and more).
The tables containing similar information are:

- https://www.osquery.io/schema/5.1.0/#system_info[system_info] for hostname, unique ID, and architecture
- https://www.osquery.io/schema/5.1.0/#os_version[os_version]
- https://www.osquery.io/schema/5.1.0/#interface_addresses[interface_addresses] for IPs and MACs

[discrete]
[[system-module-login]]
==== https://www.elastic.co/guide/en/beats/auditbeat/current/auditbeat-dataset-system-login.html[System.login]

In order to get login events, you can use
https://www.elastic.co/guide/en/security/current/install-endpoint.html[Endpoint], which
reports them. Alternatively with the https://docs.elastic.co/integrations/osquery[Osquery]
or https://docs.elastic.co/integrations/osquery_manager[Osquery Manager] integrations the
https://www.osquery.io/schema/5.1.0/#last[last] table can be used for Linux and macOS, while
our https://www.elastic.co/guide/en/fleet/current/fleet-overview.html[Fleet]
https://docs.elastic.co/integrations/system[system] integration collects login events for
Windows through the https://docs.elastic.co/integrations/system#security[Security event log].

[discrete]
[[system-module-package]]
==== https://www.elastic.co/guide/en/beats/auditbeat/current/auditbeat-dataset-system-package.html[System.package]

In order to access the same information, the
https://docs.elastic.co/integrations/osquery[Osquery] or
https://docs.elastic.co/integrations/osquery_manager[Osquery Manager] integrations can be
used to schedule the collection of this information (and more). The tables containing similar
information are:

- https://www.osquery.io/schema/5.1.0/#rpm_packages[rpm_packages]
- https://www.osquery.io/schema/5.1.0/#deb_packages[deb_packages] 
- https://www.osquery.io/schema/5.1.0/#homebrew_packages[homebrew_packages]
- https://www.osquery.io/schema/5.1.0/#apps[apps] (MacOS)
- https://www.osquery.io/schema/5.1.0/#programs[programs] (Windows)
- https://www.osquery.io/schema/5.1.0/#npm_packages[npm_packages] 
- https://www.osquery.io/schema/5.1.0/#atom_packages[atom_packages]
- https://www.osquery.io/schema/5.1.0/#chocolatey_packages[chocolatey_packages]
- https://www.osquery.io/schema/5.1.0/#portage_packages[portage_packages]
- https://www.osquery.io/schema/5.1.0/#python_packages[python_packages]

[discrete]
[[system-module-process]]
==== https://www.elastic.co/guide/en/beats/auditbeat/current/auditbeat-dataset-system-process.html[System.process]

In this case,
https://www.elastic.co/guide/en/security/current/install-endpoint.html[Endpoint] provides the
best replacement because out of the box it can report events for every process in
https://www.elastic.co/guide/en/ecs/current/index.html[ECS] format and has excellent
integration in https://www.elastic.co/guide/en/kibana/current/index.html[Kibana].

The https://docs.elastic.co/integrations/winlog[Custom Windows event log] and
https://docs.elastic.co/integrations/windows#sysmonoperational[Sysmon] integrations can
provide process data.

Alternatively you can use the https://docs.elastic.co/integrations/osquery[Osquery] or
https://docs.elastic.co/integrations/osquery_manager[Osquery Manager] integrations to collect
data from the https://www.osquery.io/schema/5.1.0/#process[process] table on some OSes
without polling.

[discrete]
[[system-module-socket]]
==== https://www.elastic.co/guide/en/beats/auditbeat/current/auditbeat-dataset-system-socket.html[System.socket]

In this case, https://www.elastic.co/guide/en/security/current/install-endpoint.html[Endpoint] provides the best replacement because it supports monitoring network connections on Linux, Windows, and MacOS. It includes process and user metadata. It currently does not do flow accounting (byte and packet counts) or domain name enrichment (but it does collect DNS queries separately).

You can also use the https://docs.elastic.co/integrations/osquery[Osquery] or
https://docs.elastic.co/integrations/osquery_manager[Osquery Manager] integrations to monitor
socket events via the https://www.osquery.io/schema/5.1.0/#socket_events[socket_events] table
for Linux and MacOS.

[discrete]
[[system-module-user]]
==== https://www.elastic.co/guide/en/beats/auditbeat/current/auditbeat-dataset-system-user.html[System.user]

The https://docs.elastic.co/integrations/osquery[Osquery] or
https://docs.elastic.co/integrations/osquery_manager[Osquery Manager] integrations can be
used to monitor local users via the https://www.osquery.io/schema/5.1.0/#user[user] table for Linux, Windows, and MacOS.