[[fleet-troubleshooting]]
[role="xpack"]
= Troubleshoot common problems

beta[]

We have collected the most common known problems and listed them here. If your problem
is not described here, please review the open issues in the following GitHub repositories:

* https://github.com/elastic/kibana/issues[{kib}]
* https://github.com/elastic/beats/issues[{beats}]
* https://github.com/elastic/fleet-server/issues[{fleet-server}]
* https://github.com/elastic/package-registry/issues[{package-registry}]

Have a question? Read our <<fleet-faq,FAQ>>, or contact us in the
{forum}[discuss forum]. Your feedback is valuable to us.

[discrete]
[[fleet-server-not-in-kibana-cloud]]
== When using {ecloud}, {fleet-server} is not listed in {kib}

If you are unable to see {fleet-server} in {kib}, make sure it's set up.

To set up {fleet-server} on {ecloud}:

. Go to your deployment on {ecloud}.
. Follow the {ecloud} prompts to set up *APM & Fleet*. Once complete, the {fleet-server} {agent}
will show up in {fleet}.

To enable {fleet} and set up {fleet-server} on a self-managed cluster:

. In the {es} configuration file, `config/elasticsearch.yml`, set the following
security settings to enable security and API keys:
+
[source,yaml]
----
xpack.security.enabled: true
xpack.security.authc.api_key.enabled: true
----

. In the {kib} configuration file, `config/kibana.yml`, enable {fleet}
and specify your user credentials:
+
[source,yaml]
----
xpack.fleet.enabled: true
xpack.fleet.agents.tlsCheckDisabled: true <1>
xpack.encryptedSavedObjects.encryptionKey: "something_at_least_32_characters"
xpack.security.enabled: true
elasticsearch.username: "my_username" <2>
elasticsearch.password: "my_password"
----
<1> Not required if you configure TLS checking.
<2> Specify a user who is authorized to use {fleet}.
+
To set up passwords, you can use the documented {es} APIs or the
`elasticsearch-setup-passwords` command. For example, `./bin/elasticsearch-setup-passwords auto`
+
After running the command:

 .. Copy the Elastic user name to the {kib} configuration file.
 .. Restart {kib}.
 .. Follow the documented steps for setting up a self-managed {fleet-server}.
 
// TODO: add link to Fleet server docs

[discrete]
[[fleet-setup-fails]]
== The `/api/fleet/setup` endpoint can't reach the package registry

To install {integrations}, the {fleet} app requires a connection to
an external service called the {package-registry}.

For this to work, the {kib} server must connect to `https://epr.elastic.co` on port `443`.

[discrete]
[[fleet-app-crashes]]
== {fleet} in {kib} crashes

. To investigate the error, open your browser's development console.
. Select the **Network** tab, and refresh the page.
+
One of the requests to the {fleet} API will most likely have returned an error. If the error
message doesn't give you enough information to fix the problem, please contact us in the {forum}[discuss forum].

[discrete]
[[agent-enrollment-timeout]]
== {agent} enrollment fails on the host with `Client.Timeout exceeded` message

To enroll in {fleet}, {agent} must connect to the {fleet-server} instance.
If the agent is unable to connect, you see the following failure:

[source,output]
-----
fail to enroll: fail to execute request to {fleet-server}:Post http://fleet-server:8220/api/fleet/agents/enroll?: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
-----

Here are several steps to help you troubleshoot the problem.

. Check for networking problems. From the host, run the `ping` command to confirm
that it can reach the {fleet-server} instance.

. Additionally, `curl` the `/status` api of {fleet-server}:
+
[source,shell]
----
curl -f http://<fleet-server-url>:8220/api/status
----
+
. Verify that you have specified the correct {kib} {fleet} settings URL and port for
your environment.
+
By default, HTTPS protocol and port 8220 is expected by {fleet-server} to communicate
with {es} unless you have explicitly set it otherwise.
+
. Check that you specified a valid enrollment key during enrollment. To do this:
.. In {fleet}, select **Agents** and then click **Enrollment tokens**.
.. To view the secret, click the eyeball icon. The secret should match the string
that you used to enroll {agent} on your host.
.. If the secret doesn't match, create a new enrollment token and use this
token when you run the `elastic-agent enroll` command.

[discrete]
[[general-fleet-server-triage]]
== Many {fleet-server} problems can be triaged and fixed with the below tips

IMPORTANT: When logging an SDH or sending a support forum communication, this section
can help you identify what is required.

{fleet-server} allows {agent} to connect to {es}, which is the same as the connection
to {kib} in prior releases. However, because {fleet-server} is on the edge host, it may
result in additional networking setup and troubleshooting.

[discrete]
=== Retrieve the {agent} version

. If you installed the {agent}, run the following command (the example is for POSIX
based systems):
+
[source,shell]
----
elastic-agent version
----
+
. If you have not installed the {agent} and you are running it as a temporary process, you can run:
+
[source,shell]
----
./elastic-agent version
----
+
NOTE: Both of the above commands are accessible via Windows or macOS with their OS-specific slight variation in
how you call them. If needed, please refer to <<elastic-agent-installation>>
for examples of how to adjust them.

[discrete]
=== Check the {agent} status

Run the following command to view the current status of the {agent}.

[source,shell]
----
elastic-agent status
----

Based on the information returned, you can take further action.

If {agent} is running, but you do not see what you expect, here are some items to review:

. In {fleet}, click **Agents**. Check which policy is associated with the running {agent}. If it is not the policy you expected, you can change it.
. In {fleet}, click **Agents**, and then select the {agent} policy. Check for the integrations that should be included.
+
For example, if you want to include system data, make sure the *System* integration is included in the policy.
+
. Confirm if the *Collect agent logs* and *Collect agent metrics* options are selected.
.. In {fleet}, click **Agents**, and then select the {agent} policy.
.. Select the *Settings* tab. If you want to collect agent logs or metrics, select these options.
+
IMPORTANT: The *Elastic Agent on Cloud policy* is created only in {ecloud} deployments and, by default,
does not include the collection of logs of metrics.

You can collect other files to assess and pass to the Elastic team for review for some more advanced debugging cases.
These files should all be in the {agent} directory on disk: `state.yml`, `fleet.yml` and `elastic-agent.yml`.

[discrete]
[[not-installing-no-logs-in-terminal]]
== Some problems occur so early that insufficient logging is available

If some problems occur early and insufficient logging is available, run the following command:

[source,shell]
----
./elastic-agent install -f
----

The stand-alone install command installs the {agent}, and all of the service configuration is set up. You can now run the
'enrollment' command. For example:

[source,shell]
----
elastic-agent enroll -f --fleet-server-es=https://<es-url>:443 --fleet-server-service-token=<token> --fleet-server-policy=<policy-id>
----

For information on where to find agent logs, see our <<where-are-the-agent-logs,FAQ>>.

[discrete]
[[agent-healthy-but-no-data-in-es]]
== The {agent} is cited as `Healthy` but still has set up problems sending data to {es}

. To confirm that the {agent} is running and its status is `Healthy`, select the *Agents* tab.
+
If you previously selected the *Collect agent logs* option, you can now look at the agent logs.
+
. Click the agent name and then select the *Logs* tab.
+
If there are no logs displayed, it suggests a communication problem between your host and {es}. The possible reason for this is
that the port is already in use.
+
. You can check the port usage using tools like Wireshark or netstat. On a POSIX system, you can run the following command:
+
[source,shell]
----
netstat -nat | grep :8220
----
+
Any response data indicates that the port is in use. This could be correct or not
if you had intended to uninstall the {fleet-server}. In which case, re-check and continue.

[discrete]
[[secondary-agent-not-connecting]]
== {fleet-server} is running and healthy with data, but other Agents cannot use it to connect to {es}

Some settings are only used when you have multiple {agent}s.  If this is the case, it may help
to check that the hosts can communicate with the {fleet-server}.

From the non-{fleet-server} host, run the following command:

[source,shell]
----
curl -f http://<fleet-server-ip>:8220/api/status
----

The response may yield errors that you can be debug further, or it may work and show that communication ports and
networking are not the problems.

One common problem is that the default {fleet-server} port of `8220` isn’t open on the {fleet-server}
host to communicate. You can review and correct this using common tools in alignment with any
networking and security concerns you may have.

[discrete]
[[es-apikey-failed]]
== {es} authentication service fails with `Authentication using apikey failed` message

To save API keys and encrypt them in {es}, {fleet} requires an encryption key.

To provide an API key, in the `kibana.yml` configuration file, set the `xpack.encryptedSavedObjects.encryptionKey` property.

[source,yaml]
----
xpack.encryptedSavedObjects.encryptionKey: "something_at_least_32_characters"
----

[discrete]
[[process-not-root]]
== {agent} fails with `Agent process is not root/admin or validation failed` message

Ensure the user running {agent} has root privileges as some integrations
require root privileges to collect sensitive data.

If you're running {agent} in the foreground (and not as a service) on Linux or macOS, run the
agent under the root user: `sudo` or `su`.

If you're using the {elastic-endpoint-integration} integration, make sure you're
running {agent} under the SYSTEM account.

TIP: If you install {agent} as a service as described in
<<elastic-agent-installation>>, {agent} runs under the SYSTEM account by
default.

To run {agent} under the SYSTEM account, you can do the following:

. Download https://docs.microsoft.com/en-us/sysinternals/downloads/psexec[PsExec]
and extract the contents to a folder. For example, `d:\tools`.
. Open a command prompt as an Administrator (right-click the command prompt
icon and select *Run As Administrator*).
. From the command prompt, run {agent} under the SYSTEM account:
+
[source,sh]
----
d:\tools\psexec.exe -sid "C:\Program Files\Elastic-Agent\elastic-agent.exe" run
----

[discrete]
[[agent-hangs-while-unenrolling]]
== {agent} hangs while unenrolling

When unenrolling {agent}, {fleet} waits for acknowledgement from the agent
before it completes the unenroll process. If {fleet} doesn't receive an
acknowledgement, the status hangs at `unenrolling.`

You can unenroll an agent to invalidate all API keys related to the agent and change the status to
`inactive` so that the agent no longer appears in {fleet}.

. In {fleet}, select **Agents**.

. Under Agents, choose **Unenroll agent** from the **Actions** menu next to the
agent you want to unenroll.

. Click **Force unenroll**. 

[discrete]
[[endpoint-unauthorized]]
== API key is unauthorized to send telemetry to `.logs-endpoint.diagnostic.collection-*` indices

By default, telemetry is turned on in the {stack} to helps us learn about the
features that our users are most interested in. This helps us to focus our efforts on
making features even better.

If you've recently upgraded from version `7.10` to `7.11`, you might see the
following message when you view {endpoint-sec} logs:

[source,sh]
----
action [indices:admin/auto_create] is unauthorized for API key id [KbvCi3YB96EBa6C9k2Cm]
of user [fleet_enroll] on indices [.logs-endpoint.diagnostic.collection-default]
----

The above message indicates that {elastic-endpoint} does not have the correct
permissions to send telemetry. This is a known problem in 7.11 that will be
fixed in an upcoming patch release.

To remove this message from your logs, you can turn off telemetry for the {endpoint-sec} integration
until the next patch release is available.

. In {fleet}, click **Integrations**, and then select the **Installed integrations** tab.

. Click **{endpoint-sec}**, and then select the **Policies** tab to view all the
installed integrations. 

. Click the integration to edit it.

. Under advanced settings, set `windows.advanced.diagnostic.enabled`
to `false`, and then save the integration.
