[[ingest-management-troubleshooting]]
[role="xpack"]
= Troubleshooting

beta[]

We have collected the most common known problems and frequently asked questions
here. If your question isn't answered here, please review open issues in the
following GitHub repositories:

* https://github.com/elastic/kibana/issues[{kib}]
* https://github.com/elastic/beats/issues[{beats}]
* https://github.com/elastic/package-registry/issues[{package-registry}]

Contact us in the {im-forum}[discuss forum]. Your feedback is very valuable to us.

//TODO: Break this into two separate files: Common problems and FAQ. It's getting too long.

**Common problems:**

* <<ingest-manager-not-in-kibana>>
* <<ingest-management-setup-fails>>
* <<ingest-manager-app-crashes>>
* <<agent-enrollment-timeout>>
* <<es-apikey-failed>>
* <<process-not-root>>
* <<agent-hangs-while-unenrolling>>

**Frequently asked questions:**

* <<enrolled-agent-not-showing-up>>
* <<where-are-the-agent-logs>>
* <<what-is-my-agent-config>>
* <<where-is-the-data-agent-is-sending>>
* <<i-deleted-my-agent>>
* <<i-rebooted-my-host>>
* <<what-is-the-endpoint-package>>

[discrete]
[[ingest-manager-not-in-kibana]]
== {ingest-manager} is not listed in the {kib} side navigation

The {ingest-manager} app is enabled by default. If you are unable to 
see the app in {kib}, make sure it's enabled.

**To enable {ingest-manager} on {ecloud}:**

. Go to your deployment in the user console.

. Under the deployment name in the side navigation, click **Edit**.

. In the {kib} section, expand **User setting overrides** and enter the
following setting:
+
[source,yaml]
----
xpack.ingestManager.enabled: true
----

. Click **Save**.

{kib} will restart automatically. When {kib} is available, refresh the browser
to see the {ingest-manager} app in the navigation menu.

**To enable {ingest-manager} on a self-managed cluster:**

. In the {es} configuration file, `config/elasticsearch.yml`, set the following
security settings to enable security and API keys:
+
[source,yaml]
----
xpack.security.enabled: true
xpack.security.authc.api_key.enabled: true
----

. In the {kib} configuration file, `config/kibana.yml`, enable {ingest-manager}
and specify user credentials:
+
[source,yaml]
----
xpack.ingestManager.enabled: true
xpack.ingestManager.fleet.tlsCheckDisabled: true <1>
xpack.security.enabled: true
elasticsearch.username: "elastic" <2>
elasticsearch.password: "abc123iUnbRftkABC123"
----
<1> This setting is not required if you configure TLS checking.
<2> Specify a user who is authorized to use {ingest-manager}.

[TIP]
=====
To set up passwords, you can use the documented {es} APIs or the
`elasticsearch-setup-passwords` command. For example:

`./bin/elasticsearch-setup-passwords auto`
=====

After running the command, copy the Elastic user name to the {kib} config file.
Then restart {kib}.

[discrete]
[[ingest-management-setup-fails]]
== The `/api/ingest_management/setup` endpoint returns an error because it can't reach the package registry

In order to install {integrations}, the {ingest-manager} app needs to connect to
an external service called the {package-registry}. For this to work, the {kib}
server must be able to connect to `https://epr.elastic.co` on port 443.

[discrete]
[[ingest-manager-app-crashes]]
== {ingest-manager} in {kib} crashes

To find more about the error, open your browser's development console, navigate
to the **Network** tab, and refresh the page. One of the requests to the
{ingest-manager} API will most likely have returned an error. If the error
message doesn't give you enough information to fix the problem, please contact
us in the {im-forum}[discuss forum].

[discrete]
[[agent-enrollment-timeout]]
== {agent} enrollment fails on the host with `Client.Timeout exceeded` message

{agent} must be able to connect to the {kib} instance to enroll in {fleet}.
If the agent is unable to connect, you will see the following failure:

[source,output]
-----
fail to enroll: fail to execute request to {kib}:Post http://kibana:5601/api/ingest_manager/fleet/agents/enroll?: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
-----

This may occur if the host is unable to connect to {kib}. To troubleshoot the
problem:

. Check for networking problems. Run the `ping` command from the host to confirm
that it can reach the {kib} instance.

. Verify that the URL and port you specified during enrollment are correct for
your environment.

. Check the enrollment key that you specified during enrollment to confirm that
the key is valid. To do this:
.. In {ingest-manager}, go to the {fleet} tab and click **Enrollment Tokens**. 
.. Click the eyeball icon to see the secret. The secret should match the string
that you used to enroll {agent} on your host.
.. If the secret doesn't match, create a new enrollment token and use the new
token when you run the `elastic-agent enroll` command.

[discrete]
[[es-apikey-failed]]
== {es} authentication service fails with `Authentication using apikey failed` message

{fleet} requires an encryption key in order to save API keys and encrypt them in
{kib}. To provide an API key, set the `xpack.encryptedSavedObjects.encryptionKey`
property in the `kibana.yml` configuration file. For example:

[source,yaml]
----
xpack.encryptedSavedObjects.encryptionKey: "something_at_least_32_characters"
----

[discrete]
[[process-not-root]]
== {agent} fails with `Agent process is not root/admin or validation failed` message

Make sure the user running {agent} has root privileges. If you're running
{agent} in the foreground (and not as a service) on Linux or macOS, run the
agent under the root user, for example, `sudo` or `su`. Some integrations
require root privileges to collect sensitive data.

If you're using the {elastic-endpoint} integration, also make sure you're
running {agent} under the SYSTEM account.

TIP: If you install {agent} as a service as described in
<<elastic-agent-installation>>, {agent} runs under the SYSTEM account by
default.

To run {agent} under the SYSTEM account, you can:

. Download https://docs.microsoft.com/en-us/sysinternals/downloads/psexec[PsExec]
and extract the contents to a folder, for example, `d:\tools`.
. Open a command prompt as an Administrator (right-click the Command Prompt
icon and select *Run As Administrator*).
. From the command prompt, run {agent} under the SYSTEM account:
+
[source,sh]
----
d:\tools\psexec.exe -sid "C:\Program Files\Elastic-Agent\elastic-agent.exe" run
----

[discrete]
[[agent-hangs-while-unenrolling]]
== {agent} hangs while unenrolling

When you unenroll an agent, {fleet} waits for acknowledgement from the agent
before it completes the unenrollment process. If {fleet} doesn't receive
acknowledgement, the status hangs at `unenrolling.`

If this happens, select **Force unenroll** from the *Actions* menu in {fleet}.

This will invalidate all API keys related to the agent and change the status to
`inactive` so that the agent no longer appears in {fleet}. 

[discrete]
[[enrolled-agent-not-showing-up]]
== Why doesn't my enrolled Agent show up in the {ingest-manager} app?

If {agent} was successfully enrolled, but doesn't show up in the {fleet} list,
it might not be started. You need to <<run-elastic-agent,start {agent}>>.

[discrete]
[[where-are-the-agent-logs]]
== Where does {agent} store logs after startup?

When started successfully, {agent} logs are stored in the folder where {agent} 
was started. Also, {metricbeat} logs are stored in `data/logs/default`. If that log 
path does not exist, {agent} was unable to start {metricbeat}, which is a higher 
level problem to triage.

[discrete]
[[what-is-my-agent-config]]
== What configuration is the {agent} running?

To find the configuration file, inspect the `elastic-agent.yml` file in the
folder where you ran {agent}. If you're running the agent in {fleet} mode, this
file contains the following citation:

[source,yaml]
----
Management: mode: "fleet"
----

The `action_store.yml` contains the entire, unencrypted configuration:

* To see the {es} location, look at `outputs:hosts`.
* To see the {agent} version, look at the download folder and zip filenames.

This file also shows the version of all packages used by the current
configuration.

[discrete]
[[where-is-the-data-agent-is-sending]]
== Why can't I see the data {agent} is sending?

If {elastic-agent} is set up and running, but you don't see data in {kib}:



. Go to **Management > Dev Tools** in {kib}, and in the Console, search your
index for data. For example:
+
[source,console]
----
GET metrics-*/_search
----
+
Or if you prefer, go to the **Discover** app.

. Look at the data that {elastic-agent} has sent and see if the `name.host`
field contains your host machine name.

If you don't see data for your host, it's possible that the data is blocked
in the network, or that a firewall or security problem is preventing the {agent}
from sending the data.

Although it's redundant to install stand-alone {metricbeat}, you might want to
try installing it to see if it's able to send data successfully to {es}. For
more information, see
{metricbeat-ref}/metricbeat-installation-configuration.html[{metricbeat} quick start].

If {metricbeat} is able to send data to {es}, there is possibly a bug or
problem with {agent}, and you should report it.

[discrete]
[[i-deleted-my-agent]]
== How do I restore an {agent} that I deleted from {fleet}?

It's ok, we've got your back! The data is still in {es}. To add {agent}
to {fleet} again, <<stop-elastic-agent>>, re-enroll it on the host, then
run {agent}.

[discrete]
[[i-rebooted-my-host]]
== How do I restart {agent} after rebooting my host?

On Windows, if you used PowerShell to install {agent} as a service, the agent
should still be running after rebooting the host.

On Linux, if you used the DEB or RPM packages, the agent should still be running
after rebooting the host. 

On macOS, you need to restart {agent} from the command line after
rebooting the host, or follow the steps described in
<<elastic-agent-install-service-macos>> to run the agent as a service. 

Support for installing {agent} as a service on all supported systems will be
available in a future release.

[discrete]
[[what-is-the-endpoint-package]]
== What is the Elastic {endpoint-sec} integration in {ingest-manager}?

The Elastic {endpoint-sec} integration provides protection on your {agent}
controlled host. The integration monitors your host for security-related events,
allowing for investigation of security data through the Elastic Security
application in {kib}. The Elastic {endpoint-sec} integration is managed by
{agent} in in the same way as other integrations. Try it out! For more
information, see the {security-guide}/index.html[Elastic Security solution
documentation].

// Add Javascript and CSS for tabbed panels
include::tab-widgets/code.asciidoc[]
