[[apm-open-telemetry-collect-metrics]]
= Collect metrics


IMPORTANT: When collecting metrics, please note that the https://www.javadoc.io/doc/io.opentelemetry/opentelemetry-api/latest/io/opentelemetry/api/metrics/DoubleValueRecorder.html[`DoubleValueRecorder`]
and https://www.javadoc.io/doc/io.opentelemetry/opentelemetry-api/latest/io/opentelemetry/api/metrics/LongValueObserver.html[`LongValueRecorder`] metrics are not yet supported.

Here's an example of how to capture business metrics from a Java application.

[source,java]
----
// initialize metric
Meter meter = GlobalMetricsProvider.getMeter("my-frontend");
DoubleCounter orderValueCounter = meter.doubleCounterBuilder("order_value").build();

public void createOrder(HttpServletRequest request) {

   // create order in the database
   ...
   // increment business metrics for monitoring
   orderValueCounter.add(orderPrice);
}
----

See the https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md[Open Telemetry Metrics API]
for more information.

[float]
[[apm-open-telemetry-verify-metrics]]
== Verify OpenTelemetry metrics data

Use *Discover* to validate that metrics are successfully reported to Elastic.

[float]
[[apm-open-telemetry-verify-metrics-kibana]]
=== Elasticsearch Service status_badge::[cloud_serverless, unavailable]

. Launch {kib}:
+
--
include::{observability-docs-root}/docs/en/observability/apm/tab-widgets/open-kibana-widget.asciidoc[]
--

. Find **Discover** in the main menu or use the {kibana-ref}/introduction.html#kibana-navigation-search[global search field].
. Select `apm-*` as your index pattern.
. Filter the data to only show documents with metrics: `[data_stream][type]: "metrics"`
. Narrow your search with a known OpenTelemetry field. For example, if you have an `order_value` field, add `order_value: *` to your search to return
only OpenTelemetry metrics documents.

[float]
[[apm-open-telemetry-verify-metrics-serverless]]
=== Elastic Cloud Serverless status_badge::[cloud_hosted, unavailable]

. Open your Observability project.
. In your {obs-serverless} project, go to **Discover**, and select the **Logs Explorer** tab.
. Click **All logs** → **Data Views** then select **APM**.
. Filter the data to only show documents with metrics: `processor.name :"metric"`
. Narrow your search with a known OpenTelemetry field. For example, if you have an `order_value` field, add `order_value: *` to your search to return
only OpenTelemetry metrics documents.

[float]
[[apm-open-telemetry-visualize]]
== Visualize data

Use *Lens* to create visualizations for OpenTelemetry metrics. Lens enables you to build visualizations by dragging and dropping data fields. It makes smart visualization suggestions for your data, allowing you to switch between visualization types.

For more information on using Lens, refer to the {kibana-ref}/lens.html[Lens documentation].
