[[apm-enable-apm-server-debugging]]
= Enable {apm-server} binary debugging

status_badge::[stack, ga]
status_badge::[serverless, unavailable]

++++
<titleabbrev>{apm-server} binary debugging</titleabbrev>
++++

NOTE: Fleet-managed users should see {fleet-guide}/monitor-elastic-agent.html[View {agent} logs]
to learn how to view logs and change the logging level of {agent}.

By default, {apm-server} sends all its output to syslog. When you run {apm-server} in
the foreground, you can use the `-e` command line flag to redirect the output to
standard error instead. For example:

["source","sh",subs="attributes"]
-----------------------------------------------
apm-server -e
-----------------------------------------------

The default configuration file is apm-server.yml (the location of the file varies by
platform). You can use a different configuration file by specifying the `-c` flag. For example:

["source","sh",subs="attributes"]
------------------------------------------------------------
apm-server -e -c myapm-serverconfig.yml
------------------------------------------------------------

You can increase the verbosity of debug messages by enabling one or more debug
selectors. For example, to view publisher-related messages, start {apm-server}
with the `publisher` selector:

["source","sh",subs="attributes"]
------------------------------------------------------------
apm-server -e -d "publisher"
------------------------------------------------------------

If you want all the debugging output (fair warning, it's quite a lot), you can
use `*`, like this:

["source","sh",subs="attributes"]
------------------------------------------------------------
apm-server -e -d "*"
------------------------------------------------------------