[[elastic-agent-processor-configuration]]
= Define processors

//TODO: This whole section needs work. We need to describe processors more
//generically now that they can be defined in several different places:
//Beats, standalone agent config, integrations config, etc.

Use processors in the {agent} configuration to process events before they are
sent to the configured output. {agent} supports processors that:

* reduce the number of exported fields
* enhance events with additional metadata
* perform additional processing and decoding

Each processor receives an event, applies a defined action to the event, and
returns the event. If you define a list of processors, they are executed in the
order they are defined in the {agent} configuration file.

[source,yaml]
-------
event -> processor 1 -> event1 -> processor 2 -> event2 ...
-------

[discrete]
[[where-valid]]
== Where are processors valid?

Processors are valid:

* At the top-level in the configuration. The processor is applied to all data
collected by {agent}.
* Under a specific input. The processor is applied to the data
collected for that input. For example:
+
[source,yaml]
------
- type: <input_type>
  processors:
    - <processor_name>:
        when:
          <condition>
        <parameters>
...
------
+
Similarly, you can define processors under the `input` section of the
configuration.

include::processor-syntax.asciidoc[leveloffset=+1]

include::processors-list.asciidoc[]
