[[install-uninstall-integration-assets]]
= Install and uninstall {agent} integration assets

{agent} integrations come with a number of assets, such as dashboards, saved
searches, and visualizations for analyzing data. When you add an integration to
an agent policy in {fleet}, the assets are installed automatically. If you're
building a policy file by hand, you need to install required assets such as
index templates.

[discrete]
[[install-integration-assets]]
== Install integration assets

. In {kib}, go to **Management > Integrations > Browse integrations**. Search for
and select an integration.

. Click the **Settings** tab.

. Click **Install <integration> assets** to set up the {kib} and {es} assets.

[discrete]
[[uninstall-integration-assets]]
== Uninstall integration assets

. In {kib}, go to **Management > Integrations > Installed integrations**. Search for
and select an integration.

. Click the **Settings** tab.

. Click **Uninstall <integration>** to remove {kib} and {es} assets that
were installed by this integration.

[discrete]
[[reinstall-integration-assets]]
== Reinstall integration assets

You may need to reinstall an integration package to resolve a specific problem,
such as:

* An asset was edited manually, and you want to reset assets to their original
state.
* A temporary problem (like a network issue) occurred during package
installation or upgrade.
* A package was installed in a prior version that had a bug in the install code.

To reinstall integration assets:

. In {kib}, go to **Management > Integrations > Installed integrations**. Search for
and select an integration.

. Click the **Settings** tab.

. Click **Reinstall <integration>** to set up the {kib} and {es} assets.
