[[integrations]]
= Manage {agent} integrations

****
Integrations are available for a wide array of popular services and platforms. To
see the full list of available integrations, go to *Management > Integrations*
in {kib}, or visit {integrations-docs}[Elastic Integrations].

{agent} integrations provide a simple, unified way to collect data from popular
apps and services, and protect systems from security threats.

Each integration comes pre-packaged with assets that support all of your
observability needs:

* Data ingestion, storage, and transformation rules
* Configuration options
* Pre-built, custom dashboards and visualizations
* Documentation
****

The following table shows the main actions you can perform in the *Integrations*
app in {kib}. You can perform some of these actions from other places in {kib},
too.

[options,header]
|===
| User action | Result

|<<add-integration-to-policy>>
|Configure an integration for a specific use case and add it to an {agent} policy.

|<<view-integration-policies>>
|View the integration policies created for a specific integration.

|<<edit-or-delete-integration-policy>>
|Change settings or delete the integration policy.

|<<view-integration-assets>>
|View the {kib} assets installed for a specific integration.

|<<upgrade-integration>>
|Upgrade an integration to the latest version.

|<<uninstall-integration>>
|Remove an integration and its assets from {kib}.

|===

[NOTE]
====
The *Integrations* app in {kib} needs access to the public {package-registry} to
discover integrations. If your deployment has network restrictions, you can
{fleet-guide}/air-gapped.html#air-gapped-diy-epr[deploy your own self-managed {package-registry}].
====
