[[apm-data-model-transactions]]
= Transactions

*Transactions* are a special kind of <<apm-data-model-spans,span>> that have additional attributes associated with them.
They describe an event captured by an Elastic {apm-agent} instrumenting a service.
You can think of transactions as the highest level of work you’re measuring within a service.
As an example, a transaction might be a:

* Request to your server
* Batch job
* Background job
* Custom transaction type

Agents decide whether to sample transactions or not,
and provide settings to control sampling behavior.
If sampled, the <<apm-data-model-spans,spans>> of a transaction are sent and stored as separate documents.
Within one transaction there can be 0, 1, or many spans captured.

A transaction contains:

* The timestamp of the event
* A unique id, type, and name
* Data about the environment in which the event is recorded:
** Service - environment, framework, language, etc.
** Host - architecture, hostname, IP, etc.
** Process - args, PID, PPID, etc.
** URL - full, domain, port, query, etc.
** <<apm-data-model-user,User>> - (if supplied) email, ID, username, etc.
* Other relevant information depending on the agent. Example: The JavaScript RUM agent captures transaction marks,
which are points in time relative to the start of the transaction with some label.

In addition, agents provide options for users to capture custom <<apm-data-model-metadata, metadata>>.
Metadata can be indexed - <<apm-data-model-labels,`labels`>>, or not-indexed - <<apm-data-model-custom,`custom`>>.

Transactions are grouped by their `type` and `name` in the Applications UI's
<<apm-transactions,Transaction overview>>.
If you're using a supported framework, APM agents will automatically handle the naming for you.
If you're not, or if you wish to override the default,
all agents have API methods to manually set the `type` and `name`.

* `type` should be a keyword of specific relevance in the service's domain,
e.g. `request`, `backgroundjob`, etc.
* `name` should be a generic designation of a transaction in the scope of a single service,
e.g. `GET /users/:id`, `UsersController#show`, etc.

TIP: Most agents limit keyword fields (e.g. `labels`) to 1024 characters,
non-keyword fields (e.g. `span.db.statement`) to 10,000 characters.

[float]
== Data streams

Transactions are stored with spans in the following data streams:

include::{observability-docs-root}/docs/en/observability/apm/manage-storage/data-streams.asciidoc[tag=traces-data-streams]

See <<apm-data-streams>> to learn more.

[float]
== Example transaction document

This example shows what transaction documents can look like when indexed in {es}.

[%collapsible]
.Expand {es} document
====
[source,json]
----
include::{apm-server-root}/docs/data/elasticsearch/generated/transactions.json[]
----
====

////
Subsections
////

include::{observability-docs-root}/docs/en/observability/apm/data-model/transactions/sampling.asciidoc[leveloffset=+1]
