[[fleet-security-model]]
= {fleet} security model

++++
<titleabbrev>Security model</titleabbrev>
++++

beta[]

coming[a future update]





## Service account

{fleet-server} utilises a service token to communicate with {es}, which contains a `fleet-server` service account. Each {fleet-server} can use its own service token, and you can share it across multiple servers. The advantage of using a separate token for each server is that you can invalidate each one separately.

//TODO: Find docs for service accounts: https://www.elastic.co/guide/en/elasticsearch/reference/7.x/security-api-get-service-accounts.html


You can create a service token by either using the {fleet} UI or the {es} API:

`POST _security/service/elastic/fleet-server/credential/token/<my-fleet-server-token>`

The above creates a {fleet-server} service token named `my-fleet-server-token`. After it's created, the token is returned by the API and must be copied. It is not possible to retrieve it afterwards again.

## API keys

As mentioned, the {fleet-server} connects to {es} using service tokens. {es} API keys are used for the connection between {agent} and the {fleet-server}. Each {agent} receives two API keys:

* The output API key is used to send data to {es}
* The communication API key is used to communicate with the {fleet-server}

The communication API key does not have any permissions apart from communicating with the {fleet-server}. The API key is validated by the {fleet-server} against {es}. If the API key is invalid, {fleet-server} stops communicating with the {agent}.

The output API key is used to ingest data into {es}. This API key will have the minimal permissions needed to ingest all the data that the policy could collect. If the API Key is invalid, the {agent} stops ingesting data into {es}.

IMPORTANT: Currently the API key has permissions to ingest data into all `logs-*` and `metrics-*` indices, but this will change soon.


## Enrollment token

The enrollment token is an {es} API key that can be retrieved multiple times by {fleet}. The enrollment token is used for the initial communication between {agent} and {fleet-server} and can be used as many times as required. If invalidated, you can not use it anymore.

After the initial connection request from the {agent} to the {fleet-server} using the enrollment token, {fleet-server} passes two API keys to the {agent} (see above).


//TODO: Describe the various ways to secure connections between Fleet Server
//and Elastic Agents:
// - Service accounts and tokens
// - ES credentials
// - Self-signed certs

//Also describe required privileges

//Use the [discrete] tag to keep sub-sections on this page.
