[[observability-elastic-entity-model]]
= Elastic Entity Model

// :description: Learn about the model that empowers entity-centric Elastic solution features and workflows.
// :keywords: serverless, observability, overview

The Elastic Entity Model consists of:

* a data model and related entity indices
* an Entity Discovery Framework, which consists of {ref}/transforms.html[transforms] and {ref}/ingest.html[Ingest pipelines] that read from signal indices and write data to entity indices
* a set of management APIs that empower entity-centric Elastic solution features and workflows

In Elastic Observability,
an _entity_ is an object of interest that can be associated with produced telemetry and identified as unique.
Note that this definition is intentionally closely aligned to the work of the https://github.com/open-telemetry/oteps/blob/main/text/entities/0256-entities-data-model.md#data-model[OpenTelemetry Entities SIG].
Examples of entities include (but are not limited to) services, hosts, and containers.

The concept of an entity is important as a means to unify observability signals based on the underlying entity that the signals describe.

.Notes
[NOTE]
====
The Elastic Entity Model currently supports the <<observability-inventory,new inventory experience>> limited to service, host, and container entities.
====

[discrete]
[[observability-elastic-entity-model-enable-the-elastic-entity-model]]
== Enable the Elastic Entity Model

:role: Admin
:goal: enable the Elastic Entity Model
include::./partials/roles.asciidoc[]
:role!:

:goal!:

You can enable the Elastic Entity Model from the new <<observability-inventory,Inventory>>. If already enabled, you will not be prompted to enable the Elastic Entity Model.

[discrete]
[[observability-elastic-entity-model-disable-the-elastic-entity-model]]
== Disable the Elastic Entity Model

:role: Admin
:goal: enable the Elastic Entity Model
include::./partials/roles.asciidoc[]
:role!:

:goal!:

From the Dev Console, run the command: `DELETE kbn:/internal/entities/managed/enablement`

[discrete]
[[observability-elastic-entity-model-limitations]]
== Limitations

* https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-cross-cluster-search.html[Cross-cluster search (CCS)] is not supported. EEM cannot leverage data stored on a remote cluster.
* Services are only detected from documents where `service.name` is detected in index patterns that match either `logs-*` or `apm-*`.
