[[observability-get-started]]
= Get started with Elastic Observability

++++
<titleabbrev>Get started</titleabbrev>
++++

New to Elastic {observability}? Discover more about our observability features and how to get started.

[discrete]
== Learn about Elastic {observability}

Learn about key features available to help you get value from your observability data and what it will cost you:

* <<observability-serverless-observability-overview>>
* <<observability-billing>>

[discrete]
[[get-started-with-use-case]]
== Get started with your use case

Learn how to create an Observability project and use Elastic
Observability to gain deeper insight into the behavior of your applications and
systems.

image::images/get-started.svg[]

1. **Choose your source.** Elastic integrates with hundreds of data sources for
unified visibility across all your applications and systems.

2. **Ingest your data.** Turn-key integrations provide a repeatable workflow to
ingest data from all your sources: you install an integration, configure it, and
deploy an agent to collect your data.

3. **View your data.** Navigate seamlessly between Observabilty UIs and
dashboards to identify and resolve problems quickly.

4. **Customize.** Expand your deployment and add features like alerting and anomaly
detection.

To get started, <<observability-create-an-observability-project,create an Observability project>>,
then follow one of our <<quickstarts-overview,quickstarts>> to learn how to ingest and visualize your observability data.

[discrete]
[[quickstarts-overview]]
=== Quickstarts

Our quickstarts dramatically reduce your time-to-value by offering a fast path to ingest and visualize your Observability data.
Each quickstart provides:

* A highly opinionated, fast path to data ingestion
* Sensible configuration defaults with minimal configuration required
* Auto-detection of logs and metrics for monitoring hosts
* Quick access to related dashboards and visualizations

Follow the steps in these guides to get started quickly:

* <<observability-quickstarts-monitor-hosts-with-elastic-agent>>
* <<observability-quickstarts-k8s-logs-metrics>>
* <<collect-data-with-aws-firehose>>

[discrete]
=== Get started with other features

Want to use {fleet} or some other feature not covered in the quickstarts?
Follow the steps in these guides to get started:

* <<observability-get-started-with-logs,Get started with system metrics>>
* <<observability-apm-get-started,Get started with application traces and APM>>
* <<observability-synthetics-get-started,Get started with synthetic monitoring>>

[discrete]
== Additional guides

Ready to dig into more features of Elastic Observability? See these guides:

* <<observability-alerting>>
* <<observability-slos>>
