:keywords: serverless, observability, overview

preview:[]

Elastic Observability accelerates problem resolution with open, flexible, and unified observability powered by advanced machine learning and analytics. Elastic ingests all operational and business telemetry and correlates for faster root cause detection.

.Production workloads
[IMPORTANT]
====
While in technical preview, Elastic Observability serverless projects should not be used for production workloads.
====

[discrete]
== Get started

* <<quickstarts-overview,*Quickstarts*>>: Learn how to ingest your observability data and get immediate value.
* <<get-started-with-logs,*Get started with Logs*>>: Add your log data to Elastic Observability and start exploring your logs.
* <<apm-get-started,*Get started with traces and APM*>>: Collect Application Performance Monitoring (APM) data and visualize it in real time.
* <<get-started-with-metrics,*Get started with metrics*>>: Add your metrics data to Elastic Observability and visualize it in real time.

[discrete]
== How to

* <<discover-and-explore-logs,*Explore log data*>>: Use Discover to explore your log data.
* <<create-manage-rules,*Trigger alerts and triage problems*>>: Create rules to detect complex conditions and trigger alerts.
* <<slos,*Track and deliver on your SLOs*>>: Measure key metrics important to the business.
* <<aiops-detect-anomalies,*Detect anomalies and spikes*>>: Find unusual behavior in time series data.
* <<apm,*Monitor application performance*>>: Monitor your software services and applications in real time.
* <<apm-agents-opentelemetry,*Integrate with OpenTelemetry*>>: Reuse existing APM instrumentation to capture logs, traces, and metrics.
* <<analyze-hosts,*Monitor your hosts and services*>>: Get a metrics-driven view of your hosts backed by an interface called Lens.

