// :keywords: serverless, observability, overview

Elastic Observability accelerates problem resolution with open, flexible, and unified observability powered by advanced machine learning and analytics. Elastic ingests all operational and business telemetry and correlates for faster root cause detection.

Not using serverless? Go to the {observability-guide}/index.html[Elastic Observability docs].

[discrete]
== Get started

* <<observability-get-started,*Get started*>>: Discover more about our observability features and how to get started.
* <<observability-quickstarts-monitor-hosts-with-elastic-agent,*Quickstart: Monitor hosts with Elastic Agent*>>: Scan your host to detect and collect logs and metrics.
* <<observability-quickstarts-k8s-logs-metrics,*Quickstart: Monitor your Kubernetes cluster with Elastic Agent*>>: Create the Kubernetes resources that are required to monitor your cluster infrastructure.
* <<observability-get-started-with-logs,*Get started with Logs*>>: Add your log data to Elastic Observability and start exploring your logs.
* <<observability-apm-get-started,*Get started with traces and APM*>>: Collect Application Performance Monitoring (APM) data and visualize it in real time.
* <<observability-get-started-with-metrics,*Get started with metrics*>>: Add your metrics data to Elastic Observability and visualize it in real time.

[discrete]
== How to

* <<observability-discover-and-explore-logs,*Explore log data*>>: Use Discover to explore your log data.
* <<observability-create-manage-rules,*Trigger alerts and triage problems*>>: Create rules to detect complex conditions and trigger alerts.
* <<observability-slos,*Track and deliver on your SLOs*>>: Measure key metrics important to the business.
* <<observability-aiops-detect-anomalies,*Detect anomalies and spikes*>>: Find unusual behavior in time series data.
* <<observability-apm,*Monitor application performance*>>: Monitor your software services and applications in real time.
* <<observability-apm-agents-opentelemetry,*Integrate with OpenTelemetry*>>: Reuse existing APM instrumentation to capture logs, traces, and metrics.
* <<observability-analyze-hosts,*Monitor your hosts and services*>>: Get a metrics-driven view of your hosts backed by an interface called Lens.

