// Use these for links to issue and pulls.
:kib-issue: https://github.com/elastic/kibana/issues/
:kibana-pull: https://github.com/elastic/kibana/pull/
:agent-issue: https://github.com/elastic/elastic-agent/issues/
:beats-issue: https://github.com/elastic/beats/issues/
:beats-pull: https://github.com/elastic/beats/pull/
:agent-libs-pull: https://github.com/elastic/elastic-agent-libs/pull/
:agent-pull: https://github.com/elastic/elastic-agent/pull/
:fleet-server-issue: https://github.com/elastic/fleet-server/issues/
:fleet-server-pull: https://github.com/elastic/fleet-server/pull/

[[release-notes]]
= Release notes

This section summarizes the changes in each release.

* <<release-notes-8.5.2>>
* <<release-notes-8.5.1>>
* <<release-notes-8.5.0>>

Also see:

* {kibana-ref}/release-notes.html[{kib} release notes]
* {beats-ref}/release-notes.html[{beats} release notes]

// begin 8.5.2 relnotes

[[release-notes-8.5.2]]
== {fleet} and {agent} 8.5.2

Review important information about the {fleet} and {agent} 8.5.2 release.

[discrete]
[[bug-fixes-8.5.2]]
=== Bug fixes

{fleet}::
* Fix known issue with adding {fleet-server} integration on Windows by always using posix paths for zip files {kib-issue}/144880[#144880] {kibana-pull}/144899[#144899]

{fleet-server}::
* Add `active: true` filter to enrollment key queries to allow {fleet-server} to handle cases where there are more than 10 inactive keys associated with a policy {fleet-server-issue}2029[#2029] {fleet-server-pull}2044[#2044]

{agent}::
* No bug fixes in this release

// end 8.5.2 relnotes

// begin 8.5.1 relnotes

[[release-notes-8.5.1]]
== {fleet} and {agent} 8.5.1

Review important information about the {fleet} and {agent} 8.5.1 release.

[discrete]
[[known-issues-8.5.1]]
=== Known issues

[[known-issue-144880]]
.Unable to add {fleet-server} integration on Windows
[%collapsible]
====

*Details*

We discovered a high severity issue in version 8.5.1 that only affects Windows
users in self-managed environments. When you attempt to add a {fleet-server},
{kib} is unable to add the {fleet-server} integration, and the {fleet-server}
polices are created without the necessary integration. For more information,
see {kib-issue}/144880[issue #144880].

*Impact* +

This issue will be resolved in version 8.5.2. We advise Windows users not to
upgrade to version 8.5.1.
====


[discrete]
[[enhancements-8.5.1]]
=== Enhancements

{agent}::
* Improve shutdown logs {agent-pull}1618[#1618]

[discrete]
[[bug-fixes-8.5.1]]
=== Bug fixes

{fleet}::
* Make asset tags space aware {kibana-pull}144066[#144066]

{fleet-server}::
* No bug fixes for this release

{agent}::
* Fix: Windows Agent left unhealthy after removing Endpoint integration {agent-pull}1286[#1286]
* Fix how multiple {fleet-server} hosts are handled {agent-pull}1329[#1329]
* Beats will now attempt to recover if a lock file has not been removed {beats-pull}33169[#33169]

// end 8.5.1 relnotes

// begin 8.5.0 relnotes

[[release-notes-8.5.0]]
== {fleet} and {agent} 8.5.0

Review important information about the {fleet} and {agent} 8.5.0 release.

[discrete]
[[breaking-changes-8.5.0]]
=== Breaking changes

Breaking changes can prevent your application from optimal operation and
performance. Before you upgrade, review the breaking changes, then mitigate the
impact to your application.

[discrete]
[[breaking-PR1709]]
.{fleet-server} and {agent} now reject certificates signed with SHA-1
[%collapsible]
====
*Details* +
With the upgrade to Go 1.18, {fleet-server} now rejects certificates signed with
SHA-1. For more information, refer to the Go 1.18
https://tip.golang.org/doc/go1.18#sha1[release notes].

*Impact* +
Do not sign certificates with SHA-1. If you are using old certificates signed
with SHA-1, update them now.
====

[discrete]
[[new-features-8.5.0]]
=== New features

The 8.5.0 release adds the following new and notable features.

{fleet}::
* Add agent activity flyout {kibana-pull}140510[#140510]
* Add a new event toggle to capture terminal output in endpoint {kibana-pull}139421[#139421]
* Make batch actions asynchronous {kibana-pull}138870[#138870]
* Add ability to tag integration assets {kibana-pull}137184[#137184]
* Add support for input-only packages {kibana-pull}140035[#140035]

{fleet-server}::
* Log redacted config when config updates {fleet-server-issue}1626[#1626] {fleet-server-pull}1671[#1671]

{agent}::
* Add `lumberjack` input type to the {filebeat} spec {agent-pull}959[#959]
* Add support for hints-based autodiscovery in Kubernetes provider {agent-pull}698[#698]
* Improve logging during upgrades {agent-pull}1287[#1287]

[discrete]
[[enhancements-8.5.0]]
=== Enhancements

{fleet}::
* Add toggle for experimental synthetic `_source` support in {fleet} data streams {kibana-pull}140132[#140132]
* Enhance the package policy API to create or update a package policy API with a simplified way to define inputs {kibana-pull}139420[#139420]
* Support new subscription and license fields {kibana-pull}137799[#137799]

{agent}::
* Improve logging of {fleet} check-in errors and only report the local state as degraded after two consecutive failed check-ins {agent-issue}1154[#1154] {agent-pull}1477[#1477]

[discrete]
[[bug-fixes-8.5.0]]
=== Bug fixes

{fleet}::
* Refresh search results when clearing category filter {kibana-pull}142853[#142853]
* Respect `default_field: false` when generating index settings {kibana-pull}142277[#142277]
* Fix repeated debug logs when bundled package directory does not exist {kibana-pull}141660[#141660]

{fleet-server}::
* Fix a race condition between the unenroller goroutine and the main
goroutine for the coordinator monitor {fleet-server-issue}1738[#1738]
* Remove events from agent check-in body {fleet-server-issue}1774[#1774]
* Improve authc debug logging {fleet-server-pull}1870[#1870]
* Add error detail to catch-all HTTP error response {fleet-server-pull}1854[#1854]
* Fix issue where errors were ignored when written to {es} {fleet-server-pull}1896[#1896]
* Update `apikey.cache_hit` log field name to match convention {fleet-server-pull}1900[#1900]
* Custom server limits are no longer ignored when default limits are loaded {fleet-server-issue}1841[#1841] {fleet-server-pull}1912[#1912]
* Use separate rate limiters for internal and external API listeners to prevent {fleet-server} from shutting down under load {fleet-server-issue}1859[#1859] {fleet-server-pull}1904[#1904]
* Fix `fleet.migration.total` log key overlap {fleet-server-pull}1951[#1951]

{agent}::
* Fix a panic caused by a race condition when installing the {agent} {agent-issue}806[#806] {agent-pull}823[#823]
* Use the {agent} configuration directory as the root of the `inputs.d` folder {agent-issue}663[#663] {agent-pull}840[#840]
* Fix unintended reset of source URI when downloading components {agent-pull}1252[#1252]
* Create separate status reporter for local-only events so that degraded {fleet} check-ins no longer affect health of successful {fleet} check-ins {agent-issue}1157[#1157] {agent-pull}1285[#1285]
* Add success log message after previous check-in failures {agent-pull}1327[#1327]
* Fix docker provider `add_fields` processors {agent-pull}1420[#1420]
* Fix admin permission check on localized windows {agent-pull}1552[#1552]

// end 8.5.0 relnotes

// ---------------------
//TEMPLATE
//Use the following text as a template. Remember to replace the version info.

// begin 8.5.x relnotes

//[[release-notes-8.5.x]]
//== {fleet} and {agent} 8.5.x

//Review important information about the {fleet} and {agent} 8.5.x release.

//[discrete]
//[[security-updates-8.5.x]]
//=== Security updates

//{fleet}::
//* add info

//{agent}::
//* add info

//[discrete]
//[[breaking-changes-8.5.x]]
//=== Breaking changes

//Breaking changes can prevent your application from optimal operation and
//performance. Before you upgrade, review the breaking changes, then mitigate the
//impact to your application.

//[discrete]
//[[breaking-PR#]]
//.Short description
//[%collapsible]
//====
//*Details* +
//<Describe new behavior.> For more information, refer to {kibana-pull}PR[#PR].

//*Impact* +
//<Describe how users should mitigate the change.> For more information, refer to {fleet-guide}/fleet-server.html[Fleet Server].
//====

//[discrete]
//[[known-issues-8.5.x]]
//=== Known issues

//[[known-issue-issue#]]
//.Short description
//[%collapsible]
//====

//*Details*

//<Describe known issue.>

//*Impact* +

//<Describe impact or workaround.>

//====

//[discrete]
//[[deprecations-8.5.x]]
//=== Deprecations

//The following functionality is deprecated in 8.5.x, and will be removed in
//8.5.x. Deprecated functionality does not have an immediate impact on your
//application, but we strongly recommend you make the necessary updates after you
//upgrade to 8.5.x.

//{fleet}::
//* add info

//{agent}::
//* add info

//[discrete]
//[[new-features-8.5.x]]
//=== New features

//The 8.5.x release adds the following new and notable features.

//{fleet}::
//* add info

//{agent}::
//* add info

//[discrete]
//[[enhancements-8.5.x]]
//=== Enhancements

//{fleet}::
//* add info

//{agent}::
//* add info

//[discrete]
//[[bug-fixes-8.5.x]]
//=== Bug fixes

//{fleet}::
//* add info

//{agent}::
//* add info

// end 8.5.x relnotes
