// Use these for links to issue and pulls.
:kibana-issue: https://github.com/elastic/kibana/issues/
:kibana-pull: https://github.com/elastic/kibana/pull/
:beats-issue: https://github.com/elastic/beats/issues/
:beats-pull: https://github.com/elastic/beats/pull/
:agent-libs-pull: https://github.com/elastic/elastic-agent-libs/pull/
:agent-issue: https://github.com/elastic/elastic-agent/issues/
:agent-pull: https://github.com/elastic/elastic-agent/pull/
:fleet-server-issue: https://github.com/elastic/fleet-server/issues/
:fleet-server-pull: https://github.com/elastic/fleet-server/pull/

[[release-notes]]
= Release notes

This section summarizes the changes in each release.

* <<release-notes-8.6.2>>
* <<release-notes-8.6.1>>
* <<release-notes-8.6.0>>

Also see:

* {kibana-ref}/release-notes.html[{kib} release notes]
* {beats-ref}/release-notes.html[{beats} release notes]

// begin 8.6.2 relnotes

[[release-notes-8.6.2]]
== {fleet} and {agent} 8.6.2

Review important information about the {fleet} and {agent} 8.6.2 release.

[discrete]
[[known-issues-8.6.2]]
=== Known issues

[discrete]
[[known-issue-issue-2066-8-6-2]]
.Osquery live query results can take up to five minutes to show up in {kib}.
[%collapsible]
====
*Details* +
A known issue in {agent} may prevent live query results from being available
in the {kib} UI even though the results have been successfully sent to {es}.
For more information, refer to {agent-issue}2066[#2066].

*Impact* +
Be aware that the live query results shown in {kib} may be delayed by up to 5 minutes.
====

[[known-issue-2170-8-6-2]]
.Adding a {fleet-server} integration to an agent results in panic if the agent was not bootstrapped with a {fleet-server}.
[%collapsible]
====

*Details*

A panic occurs because the {agent} does not have a `fleet.server` in the `fleet.enc`
configuration file. When this happens, the agent fails with a message like:

[source,shell]
----
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x557b8eeafc1d]
goroutine 86 [running]:
github.com/elastic/elastic-agent/internal/pkg/agent/application.FleetServerComponentModifier.func1({0xc000652f00, 0xa, 0x10}, 0x557b8fa8eb92?)
...
----

For more information, refer to {agent-issue}2170[#2170].

*Impact* +

To work around this problem, uninstall the {agent} and install it again with
{fleet-server} enabled during the bootstrap process.
====

[[known-issue-issue-2103-8.6.2]]
.Installing {agent} on MacOS Ventura may fail if Full Disk Access has not been granted to the application used for installation.
[%collapsible]
====
*Details* +
This issue occurs on MacOS Ventura when Full Disk Access is not granted to the application that runs the installation command.
This could be either a Terminal or any custom package that a user has built to distribute {agent}.

For more information, refer to {agent-issue}2103[#2103].

*Impact* +
{agent} will fail to install and produce "Error: failed to fix permissions: chown elastic-agent.app: operation not permitted" message.
Ensure that the application used to install {agent} (for example, the Terminal or custom package) has Full Disk Access before running `sudo ./elastic-agent install`.
====

[[known-issue-issue-2342-8.6.2]]
.{agent} upgrades scheduled for a future time do not run.
[%collapsible]
====
*Details* +
A known issue in {agent} that may prevent upgrades scheduled to execute at a later time from running.
For more incormation refer to {agent-issue}2342[#2342].

*Impact* +
{kib} may show an agent as being stuck with the `Updating` status.
If the scheduled start time has passed you may force it to run by sending the agent any action, such as a policy change or changing the log level.
====

[discrete]
[[enhancements-8.6.2]]
=== Enhancements

{fleet}::
* Adds the ability to run agent policy schema in batches during {fleet} setup.
Also adds `xpack.fleet.setup.agentPolicySchemaUpgradeBatchSize` config
{kibana-pull}150688[#150688]

[discrete]
[[bug-fixes-8.6.2]]
=== Bug fixes

{fleet}::
* Fix max 20 installed integrations returned from Fleet API {kibana-pull}150780[#150780]
* Fix updates available when beta integrations are off {kibana-pull}149515[#149515] {kibana-pull}149486[#149486]

{fleet-server}::
* Prevent {fleet-server} from crashing by allowing the the Warn log level to be
specified as "warning" or "warn" {fleet-server-issue}2328[#2328] {fleet-server-pull}2331[#2331]

{agent}::
* Ignore {fleet} connectivity state when considering whether an upgrade should be rolled back. Avoids unnecessary upgrade failures due to transient network errors {agent-pull}2239[#2239]
* Preserve persistent process state between upgrades. The {filebeat} registry is now correctly preserved during {agent} upgrades. {agent-issue}2136[#2136] {agent-pull}2207[#2207]
* Enable nodejs engine validation when bundling synthetics
{agent-issue}2249[#2249] {agent-pull}2256[#2256] {agent-pull}2225[#2225]
* Guarantee that services are stopped before they are started. Fixes occasional upgrade failures when Elastic Defend is installed {agent-pull}2226[#2226]
* Fix an issue where inputs in {beats} started by {agent} can be incorrectly disabled. This primarily occurs when changing the log level. {agent-issue}2232[#2232] {beats-pull}34504[#34504]

// end 8.6.2 relnotes

[[release-notes-8.6.1]]
== {fleet} and {agent} 8.6.1

Review important information about the {fleet} and {agent} 8.6.1 release.

[discrete]
[[known-issues-8.6.1]]
=== Known issues

[discrete]
[[known-issue-issue-2066-8-6-1]]
.Osquery live query results can take up to five minutes to show up in {kib}.
[%collapsible]
====
*Details* +
A known issue in {agent} may prevent live query results from being available
in the {kib} UI even though the results have been successfully sent to {es}.
For more information, refer to {agent-issue}2066[#2066].

*Impact* +
Be aware that the live query results shown in {kib} may be delayed by up to 5 minutes.
====

[[known-issue-2170]]
.Adding a {fleet-server} integration to an agent results in panic if the agent was not bootstrapped with a {fleet-server}.
[%collapsible]
====

*Details*

A panic occurs because the {agent} does not have a `fleet.server` in the `fleet.enc`
configuration file. When this happens, the agent fails with a message like:

[source,shell]
----
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x557b8eeafc1d]
goroutine 86 [running]:
github.com/elastic/elastic-agent/internal/pkg/agent/application.FleetServerComponentModifier.func1({0xc000652f00, 0xa, 0x10}, 0x557b8fa8eb92?)
...
----

For more information, refer to {agent-issue}2170[#2170].

*Impact* +

To work around this problem, uninstall the {agent} and install it again with
{fleet-server} enabled during the bootstrap process.
====

[[known-issue-2232-8-6-1]]
.Changing the {agent} log level can incorrectly disable inputs in supervised {beats}.
[%collapsible]
====

*Details*

Data collection may be disabled when the {agent} log level is changed. Avoid changing the {agent} log level.

Upgrade to 8.6.2 to fix the problem. For more information, refer to {agent-issue}2232[#2232].
====

[[known-issue-2328-8-6-1]]
.{fleet-server} will crash when configured to use the Warning log level.
[%collapsible]
====

*Details*

{fleet-server} will crash when configured to use the Warning log level. Do not use the Warning log level.
Affected {fleet-server} instances must be reinstalled to fix the problem.

Upgrade to 8.6.2 to fix the problem. For more information, refer to {fleet-server-issue}2328[#2328].
====

[[known-issue-issue-unsigned-8.6.1]]
.The initial release of {agent} 8.6.1 for MacOS contained an unsigned elastic-agent executable. On MacOS Ventura, upgrading from 8.6.1 to any other version will fail and can disable Elastic Defend protections.
[%collapsible]
====
*Details* +
The initial release of {agent} version 8.6.1 for MacOS contained an unsigned elastic-agent executable and a correctly signed endpoint-security
executable. The endpoint-security executable implements the endpoint protection functionality of the Elastic Defend integration.

New functionality in MacOS Gatekeeper in MacOS Ventura prevents the unsigned elastic-agent executable from modifying the installation of the signed endpoint-security executable causing upgrades from affected 8.6.1 versions to fail. The failed upgrade can leave {agent} in an unhealthy
state with the endpoint-security executable disabled. Note that MacOS Gatekeeper implements a signature cache, such that the upgrade is only likely to fail on MacOS Ventura machines that have been rebooted since the first upgrade to version 8.6.1.

As of February 27th 2023 the {agent} 8.6.1 artifacts for MacOS have been updated with a correctly signed elastic-agent executable. To verify that
the signature of the elastic-agent executable is correct, run the command below and ensure that Elasticsearch, Inc appears in the Authority field.

[source,shell]
----
tar xvfz elastic-agent-8.6.1-darwin-aarch64.tar.gz
cd elastic-agent-8.6.1-darwin-aarch64
codesign -dvvvv ./elastic-agent
...
Signature size=9068
Authority=Developer ID Application: Elasticsearch, Inc (2BT3HPN62Z)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Feb 24, 2023 at 4:33:02 AM
...
----

*Impact* +
Any {agent} deployed to MacOS Ventura that was upgraded to version 8.6.1 prior to February 27th 2023 must be reinstalled using a version with correctly signed executables.
Upgrades to any other version will fail and lead to broken functionality, including disabling the protections from Elastic Defend.

The specific steps to follow to correct this problem are:

1. Download a version of {agent} with correctly signed executables.
2. Unenroll the affected agents, either from the command line or the Fleet UI. A new agent ID will be generated when reinstalling.
3. Run the `elastic-agent uninstall` command to remove the incorrectly signed version of {agent}.
4. From the directory containing the new, correctly signed {agent} artifacts run the `elastic-agent install` command. The agent may be reenrolled at install time or separately with the `elastic-agent enroll` command.

====

[[known-issue-issue-2103-8.6.1]]
.Installing {agent} on MacOS Ventura may fail if Full Disk Access has not been granted to the application used for installation.
[%collapsible]
====
*Details* +
This issue occurs on MacOS Ventura when Full Disk Access is not granted to the application that runs the installation command.
This could be either a Terminal or any custom package that a user has built to distribute {agent}.

For more information, refer to {agent-issue}2103[#2103].

*Impact* +
{agent} will fail to install and produce "Error: failed to fix permissions: chown elastic-agent.app: operation not permitted" message.
Ensure that the application used to install {agent} (for example, the Terminal or custom package) has Full Disk Access before running `sudo ./elastic-agent install`.
====

[[known-issue-issue-2342-8.6.1]]
.{agent} upgrades scheduled for a future time do not run.
[%collapsible]
====
*Details* +
A known issue in {agent} that may prevent upgrades scheduled to execute at a later time from running.
For more incormation refer to {agent-issue}2342[#2342].

*Impact* +
{kib} may show an agent as being stuck with the `Updating` status.
If the scheduled start time has passed you may force it to run by sending the agent any action, such as a policy change or changing the log level.
====

[discrete]
[[bug-fixes-8.6.1]]
=== Bug fixes

{fleet}::
* Fix missing policy ID in installation URL for cloud integrations {kibana-pull}149243[#149243]
* Fix package installation APIs to install packages without a version {kibana-pull}149193[#149193]
* Fix issue where the latest GA version could not be installed if there was a newer prerelease version in the registry
{kibana-pull}149133[#149133] {kibana-pull}149104[#149104]

{fleet-server}::
* Update the `.fleet-agent` index when acknowledging policy changes when {ls}
is the configured output. Fixes agents always showing as Updating when using the
{ls} output {fleet-server-pull}2119[#2119]

{agent}::
* Fix issue where {beats} started by {agent} may fail with an `output unit has no config` error {agent-pull}2138[#2138] {agent-issue}2086[#2086]
* Restore the ability to set custom HTTP headers at enrollment time. Fixes traffic filters in Integrations Server cloud deployments {agent-pull}2158[#2158] {beats-issue}32993[#32993]
* Make it easier to filter agent logs from the combined agent log file {agent-pull}2044[#2044] {agent-issue}1810[#1810]

// end 8.6.1 relnotes

// begin 8.6.0 relnotes

[[release-notes-8.6.0]]
== {fleet} and {agent} 8.6.0

Review important information about the {fleet} and {agent} 8.6.0 release.

[discrete]
[[breaking-changes-8.6.0]]
=== Breaking changes

Breaking changes can prevent your application from optimal operation and
performance. Before you upgrade, review the breaking changes, then mitigate the
impact to your application.

[discrete]
[[breaking-1994]]
.Each input in an agent policy must have a unique ID
[%collapsible]
====
*Details* +
Each input in an agent policy must have a unique ID, like `id: my-unique-input-id`.
This change only affects standalone agents. Unique IDs are automatically generated in
agent policies managed by {fleet}. For more information, refer to
{agent-pull}/1994[#1994]

*Impact* +
Make sure that your standalone agent policies have a unique ID.
====

[discrete]
[[breaking-1140]]
.Diagnostics `--pprof` argument has been removed and is now always provided
[%collapsible]
====
*Details* +
The `diagnostics` command gathers diagnostic information about the {agent} and
each component/unit it runs. Starting in 8.6.0, the `--pprof`
argument is no longer available because `pprof` information is now always
provided. For more information, refer to {agent-pull}1140[#1140].

*Impact* +
Remove the `--pprof` argument from any scripts or commands you use.
====

[discrete]
[[breaking-1398]]
.Not dedoted Kubernetes pod labels to be used for autodiscover conditions
[%collapsible]
====
*Details* +
Kubernetes pod labels used in autodiscover conditions are not dedoted anymore. This means that
`.` are not replaced with `_` in labels like `app.kubernetes.io/component=controller`.
This follows the same approach as kubernetes annotations. For more information refer to <<kubernetes-provider>>.

*Impact* +
Any template used for standalone elastic agent or installed integration that makes use
of dedoted kubernetes labels inside conditions has to be updated.
====

[discrete]
[[known-issues-8.6.0]]
=== Known issues

[discrete]
[[known-issue-issue-2066]]
.Osquery live query results can take up to five minutes to show up in {kib}.
[%collapsible]
====
*Details* +
A known issue in {agent} may prevent live query results from being available
in the {kib} UI even though the results have been successfully sent to {es}.
For more information, refer to {agent-issue}2066[#2066].

*Impact* +
Be aware that the live query results shown in {kib} may be delayed by up to 5 minutes.
====

[[known-issue-issue-2103-8.6.0]]
.Installing {agent} on MacOS Ventura may fail if Full Disk Access has not been granted to the application used for installation.
[%collapsible]
====
*Details* +
This issue occurs on MacOS Ventura when Full Disk Access is not granted to the application that runs the installation command.
This could be either a Terminal or any custom package that a user has built to distribute {agent}.

For more information, refer to {agent-issue}2103[#2103].

*Impact* +
{agent} will fail to install and produce "Error: failed to fix permissions: chown elastic-agent.app: operation not permitted" message.
Ensure that the application used to install {agent} (for example, the Terminal or custom package) has Full Disk Access before running `sudo ./elastic-agent install`.
====


[[known-issue-issue-2086]]
.Beats started by agent may fail with `output unit has no config` error.
[%collapsible]
====
*Details* +
A known issue in {agent} may lead to Beat processes being started without a
valid output. To correct the problem, trigger a restart of {agent}
or the affected Beats. For Beats managed by {agent}, you can trigger a restart by changing the
{agent} log level or the output section of the {agent} policy.
For more information, refer to {agent-issue}2086[#2086].

*Impact* +
{agent} will appear unhealthy and the affected Beats will not be able to write
event data to {es} or Logstash.
====

[[known-issue-issue-2342-8.6.0]]
.{agent} upgrades scheduled for a future time do not run.
[%collapsible]
====
*Details* +
A known issue in {agent} that may prevent upgrades scheduled to execute at a later time from running.
For more incormation refer to {agent-issue}2342[#2342].

*Impact* +
{kib} may show an agent as being stuck with the `Updating` status.
If the scheduled start time has passed you may force it to run by sending the agent any action, such as a policy change or changing the log level.
====

[discrete]
[[new-features-8.6.0]]
=== New features

The 8.6.0 release adds the following new and notable features.

{fleet}::
* Differentiate kubernetes integration multipage experience {kibana-pull}145224[#145224]
* Add prerelease toggle to Integrations list {kibana-pull}143853[#143853]
* Add link to allow users to skip multistep add integration workflow {kibana-pull}143279[#143279]

{agent}::
* Upgrade Node to version 18.12.0 {agent-pull}1657[#1657]
* Add experimental support for running the elastic-agent-shipper {agent-pull}1527[#1527] {agent-issue}219[#219]
* Collect logs from sub-processes via stdout and stderr and write them to a single, unified Elastic Agent log file {agent-pull}1702[#1702] {agent-issue}221[#221]
* Remove inputs when all streams are removed {agent-pull}1869[#1869] {agent-issue}1868[#1868]
* No longer restart {agent} on log level change {agent-pull}1914[#1914] {agent-issue}1896[#1896]
* Add `inspect components` command to inspect the computed components/units model of the current configuration (for example, `elastic-agent inspect components`) {agent-pull}1701[#1701] {agent-issue}836[#836]
* Add support for the Common Expression Language (CEL) {filebeat} input type {agent-pull}1719[#1719]
* Only support {es} as an output for the beta synthetics integration {agent-pull}1491[#1491]
* New control protocol between the {agent} and its subprocesses enables per integration health reporting and simplifies new input development {agent-issue}836[#836] {agent-pull}1701[#1701]
* All binaries for every supported integration are now bundled in the {agent} by default {agent-issue}836[#836] {agent-pull}126[#126]

[discrete]
[[enhancements-8.6.0]]
=== Enhancements

{fleet}::
* Add `?full` option to get package info endpoint to return all package fields {kibana-pull}144343[#144343]

{agent}::
* Health Status: {agent} now indicates detailed status information for each sub-process and input type {fleet-server-pull}1747[#1747] {agent-issue}100[#100]
* Change internal directory structure: add a components directory to contain binaries and associated artifacts, and remove the downloads directory {agent-issue}836[#836] {agent-pull}1701[#1701]

[discrete]
[[bug-fixes-8.6.0]]
=== Bug fixes

{fleet}::
* Only show {fleet}-managed data streams on data streams list page {kibana-pull}143300[#143300]
* Fix synchronization bug in {fleet-server} that can lead to {es} being flooded by requests to `/.fleet-actions/_fleet/_fleet_search` {fleet-server-pull}2205[#2205].

{agent}::
* {agent} now uses the locally bound port (8221) when running {fleet-server} instead of the external port (8220) {agent-pull}1867[#1867]
// end 8.6.0 relnotes


// ---------------------
//TEMPLATE
//Use the following text as a template. Remember to replace the version info.

// begin 8.6.x relnotes

//[[release-notes-8.6.x]]
//== {fleet} and {agent} 8.6.x

//Review important information about the {fleet} and {agent} 8.6.x release.

//[discrete]
//[[security-updates-8.6.x]]
//=== Security updates

//{fleet}::
//* add info

//{agent}::
//* add info

//[discrete]
//[[breaking-changes-8.6.x]]
//=== Breaking changes

//Breaking changes can prevent your application from optimal operation and
//performance. Before you upgrade, review the breaking changes, then mitigate the
//impact to your application.

//[discrete]
//[[breaking-PR#]]
//.Short description
//[%collapsible]
//====
//*Details* +
//<Describe new behavior.> For more information, refer to {kibana-pull}PR[#PR].

//*Impact* +
//<Describe how users should mitigate the change.> For more information, refer to {fleet-guide}/fleet-server.html[Fleet Server].
//====

//[discrete]
//[[known-issues-8.6.x]]
//=== Known issues

//[[known-issue-issue#]]
//.Short description
//[%collapsible]
//====

//*Details*

//<Describe known issue.>

//*Impact* +

//<Describe impact or workaround.>

//====

//[discrete]
//[[deprecations-8.6.x]]
//=== Deprecations

//The following functionality is deprecated in 8.6.x, and will be removed in
//8.6.x. Deprecated functionality does not have an immediate impact on your
//application, but we strongly recommend you make the necessary updates after you
//upgrade to 8.6.x.

//{fleet}::
//* add info

//{agent}::
//* add info

//[discrete]
//[[new-features-8.6.x]]
//=== New features

//The 8.6.x release adds the following new and notable features.

//{fleet}::
//* add info

//{agent}::
//* add info

//[discrete]
//[[enhancements-8.6.x]]
//=== Enhancements

//{fleet}::
//* add info

//{agent}::
//* add info

//[discrete]
//[[bug-fixes-8.6.x]]
//=== Bug fixes

//{fleet}::
//* add info

//{agent}::
//* add info

// end 8.6.x relnotes
