

Every new connection to the managed intake service starts with a `metadata` stanza.
This provides general metadata concerning the other objects in the stream.

Rather than send this metadata information from the agent multiple times,
the managed intake service hangs on to this information and applies it to other objects in the stream as necessary.

[TIP]
====
Metadata is stored under `context` when viewing documents in {es}.
====

[discrete]
[[metadata-schema]]
==== Metadata Schema

The managed intake service uses JSON Schema to validate requests. The specification for metadata is defined on
https://github.com/elastic/apm-server/blob/main/docs/spec/v2/metadata.json[GitHub] and included below.

.Click to expand the schema
[%collapsible]
=====
include::../../transclusion/apm/guide/spec/v2/metadata.asciidoc[]
=====

[discrete]
[[kubernetes-data]]
==== Kubernetes data

APM agents automatically read Kubernetes data and send it to the managed intake service.
In most instances, agents are able to read this data from inside the container.
If this is not the case, or if you wish to override this data, you can set environment variables for the agents to read.
These environment variable are set via the Kubernetes https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#use-pod-fields-as-values-for-environment-variables[Downward API].
Here's how you would add the environment variables to your Kubernetes pod spec:

[source,yaml]
----
         - name: KUBERNETES_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: KUBERNETES_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: KUBERNETES_POD_UID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
----

The table below maps these environment variables to the APM metadata event field:

|===
| Environment variable| Metadata field name

| `KUBERNETES_NODE_NAME`
| system.kubernetes.node.name

| `KUBERNETES_POD_NAME`
| system.kubernetes.pod.name

| `KUBERNETES_NAMESPACE`
| system.kubernetes.namespace

| `KUBERNETES_POD_UID`
| system.kubernetes.pod.uid
|===
