Elastic supports receiving traces, metrics, and logs over the
https://opentelemetry.io/docs/specs/otlp/[OpenTelemetry Protocol (OTLP)].
OTLP is the default transfer protocol for OpenTelemetry and is supported natively by the managed intake service.

The managed intake service supports two OTLP communication protocols on the same port:

* OTLP/HTTP (protobuf)
* OTLP/gRPC

[discrete]
[[otlpgrpc-paths]]
=== OTLP/gRPC paths

|===
| Name| Endpoint

| OTLP metrics intake
| `/opentelemetry.proto.collector.metrics.v1.MetricsService/Export`

| OTLP trace intake
| `/opentelemetry.proto.collector.trace.v1.TraceService/Export`

| OTLP logs intake
| `/opentelemetry.proto.collector.logs.v1.LogsService/Export`
|===

[discrete]
[[otlphttp-paths]]
=== OTLP/HTTP paths

|===
| Name| Endpoint

| OTLP metrics intake
| `/v1/metrics`

| OTLP trace intake
| `/v1/traces`

| OTLP logs intake
| `/v1/logs`
|===

[TIP]
====
See our <<apm-agents-opentelemetry-opentelemetry-native-support,OpenTelemetry docs>> to learn how to send data to the managed intake service from an OpenTelemetry agent OpenTelemetry collector.
====
