// tag::deb[]
ifeval::["{release-state}"=="unreleased"]

Version {version} of {agent} has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

IMPORTANT: To simplify upgrading to future versions of {agent}, we recommended
that you use the tarball distribution instead of the DEB distribution.

["source","sh",subs="attributes"]
----
curl -L -O https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-{version}-amd64.deb
sudo dpkg -i elastic-agent-{version}-amd64.deb
----

endif::[]
// end::deb[]

// tag::rpm[]
ifeval::["{release-state}"=="unreleased"]

Version {version} of {agent} has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

IMPORTANT: To simplify upgrading to future versions of {agent}, we recommended
that you use the tarball distribution instead of the RPM distribution.

["source","sh",subs="attributes"]
----
curl -L -O https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-{version}-x86_64.rpm
sudo rpm -vi elastic-agent-{version}-x86_64.rpm
----
endif::[]
// end::rpm[]

// tag::mac[]
ifeval::["{release-state}"=="unreleased"]

Version {version} of {agent} has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

["source","sh",subs="attributes"]
----
curl -L -O https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-{version}-darwin-x86_64.tar.gz
tar xzvf elastic-agent-{version}-darwin-x86_64.tar.gz
----

endif::[]
// end::mac[]

// tag::linux[]
ifeval::["{release-state}"=="unreleased"]

Version {version} of {agent} has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

["source","sh",subs="attributes"]
----
curl -L -O https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-{version}-linux-x86_64.tar.gz
tar xzvf elastic-agent-{version}-linux-x86_64.tar.gz
----

endif::[]
// end::linux[]

// tag::win[]
ifeval::["{release-state}"=="unreleased"]

Version {version} of {agent} has not yet been released.

endif::[]

ifeval::["{release-state}"!="unreleased"]

["source","powershell",subs="attributes"]
----
# PowerShell 5.0+
wget https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-{version}-windows-x86_64.zip -OutFile elastic-agent-{version}-windows-x86_64.zip 
Expand-Archive .\elastic-agent-{version}-windows-x86_64.zip
----
Or manually:

. Download the {agent} Windows zip file from the
https://www.elastic.co/downloads/beats/elastic-agent[download page].

. Extract the contents of the zip file.

endif::[]
// end::win[]
