[[apm-agents-elastic-apm-agents]]
= Elastic APM agents

:keywords: serverless, observability, overview

preview:[]

:role: Admin
:goal: use APM agents
include::../partials/roles.asciidoc[]
:role!:

:goal!:

Elastic APM agents automatically measure application performance and track errors.
They offer built-in support for popular frameworks and technologies, and provide easy-to-use APIs that allow you to instrument any application.

Elastic APM agents are built and maintained by Elastic. While they are similar, different programming languages have different nuances and requirements. Select your preferred language below to learn more about how each agent works.

++++
<div class="tabs" data-tab-group="apm-agents-apm-agents-elastic-apm-agents">
  <div role="tablist" aria-label="apm-agents-apm-agents-elastic-apm-agents">
    <button role="tab" aria-selected="true" aria-controls="apm-agents-apm-agents-elastic-apm-agents-java-panel" id="apm-agents-apm-agents-elastic-apm-agents-java-button">
      Java
    </button>
    <button role="tab" aria-selected="false" aria-controls="apm-agents-apm-agents-elastic-apm-agents-nodejs-panel" id="apm-agents-apm-agents-elastic-apm-agents-nodejs-button" tabindex="-1">
      Node.js
    </button>
    <button role="tab" aria-selected="false" aria-controls="apm-agents-apm-agents-elastic-apm-agents-python-panel" id="apm-agents-apm-agents-elastic-apm-agents-python-button" tabindex="-1">
      Python
    </button>
    <button role="tab" aria-selected="false" aria-controls="apm-agents-apm-agents-elastic-apm-agents-ruby-panel" id="apm-agents-apm-agents-elastic-apm-agents-ruby-button" tabindex="-1">
      Ruby
    </button>
    <button role="tab" aria-selected="false" aria-controls="apm-agents-apm-agents-elastic-apm-agents-go-panel" id="apm-agents-apm-agents-elastic-apm-agents-go-button" tabindex="-1">
      Go
    </button>
    <button role="tab" aria-selected="false" aria-controls="apm-agents-apm-agents-elastic-apm-agents-net-panel" id="apm-agents-apm-agents-elastic-apm-agents-net-button" tabindex="-1">
      .NET
    </button>
    <button role="tab" aria-selected="false" aria-controls="apm-agents-apm-agents-elastic-apm-agents-php-panel" id="apm-agents-apm-agents-elastic-apm-agents-php-button" tabindex="-1">
      PHP
    </button>
  </div>
  <div tabindex="0" role="tabpanel" id="apm-agents-apm-agents-elastic-apm-agents-java-panel" aria-labelledby="apm-agents-apm-agents-elastic-apm-agents-java-button">
++++
include::../transclusion/apm/guide/about/java.asciidoc[]

++++
  </div>
  <div tabindex="0" role="tabpanel" id="apm-agents-apm-agents-elastic-apm-agents-nodejs-panel" aria-labelledby="apm-agents-apm-agents-elastic-apm-agents-nodejs-button" hidden="">
++++
include::../transclusion/apm/guide/about/node.asciidoc[]

++++
  </div>
  <div tabindex="0" role="tabpanel" id="apm-agents-apm-agents-elastic-apm-agents-python-panel" aria-labelledby="apm-agents-apm-agents-elastic-apm-agents-python-button" hidden="">
++++
include::../transclusion/apm/guide/about/python.asciidoc[]

++++
  </div>
  <div tabindex="0" role="tabpanel" id="apm-agents-apm-agents-elastic-apm-agents-ruby-panel" aria-labelledby="apm-agents-apm-agents-elastic-apm-agents-ruby-button" hidden="">
++++
include::../transclusion/apm/guide/about/ruby.asciidoc[]

++++
  </div>
  <div tabindex="0" role="tabpanel" id="apm-agents-apm-agents-elastic-apm-agents-go-panel" aria-labelledby="apm-agents-apm-agents-elastic-apm-agents-go-button" hidden="">
++++
include::../transclusion/apm/guide/about/go.asciidoc[]

++++
  </div>
  <div tabindex="0" role="tabpanel" id="apm-agents-apm-agents-elastic-apm-agents-net-panel" aria-labelledby="apm-agents-apm-agents-elastic-apm-agents-net-button" hidden="">
++++
include::../transclusion/apm/guide/about/net.asciidoc[]

++++
  </div>
  <div tabindex="0" role="tabpanel" id="apm-agents-apm-agents-elastic-apm-agents-php-panel" aria-labelledby="apm-agents-apm-agents-elastic-apm-agents-php-button" hidden="">
++++
include::../transclusion/apm/guide/about/php.asciidoc[]

++++
  </div>
</div>
++++

[discrete]
[[apm-agents-elastic-apm-agents-minimum-supported-versions]]
== Minimum supported versions

The following versions of Elastic APM agents are supported:

|===
| Agent name| Agent version

| **APM AWS Lambda extension**
| ≥`1.x`

| **Go agent**
| ≥`1.x`

| **Java agent**
| ≥`1.x`

| **.NET agent**
| ≥`1.x`

| **Node.js agent**
| ≥`4.x`

| **PHP agent**
| ≥`1.x`

| **Python agent**
| ≥`6.x`

| **Ruby agent**
| ≥`3.x`
|===

[NOTE]
====
Some recently added features may require newer agent versions than those listed above.
In these instances, the required APM agent versions will be documented with the feature.
====
