// tag::deb[]
["source","sh",subs="attributes"]
----
curl -L -O https\://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{version}-amd64.deb
sudo dpkg -i filebeat-{version}-amd64.deb
----

// end::deb[]

// tag::rpm[]
["source","sh",subs="attributes"]
----
curl -L -O https\://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{version}-x86_64.rpm
sudo rpm -vi filebeat-{version}-x86_64.rpm
----

// end::rpm[]

// tag::mac[]

// lint disable
["source","sh",subs="attributes"]
----
curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{version}-darwin-x86_64.tar.gz
tar xzvf filebeat-{version}-darwin-x86_64.tar.gz
----

// end::mac[]

// tag::linux[]
["source","sh",subs="attributes"]
----
curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{version}-linux-x86_64.tar.gz
tar xzvf filebeat-{version}-linux-x86_64.tar.gz
----

// end::linux[]

// tag::win[]


. Download the {filebeat} Windows zip file: https\://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{version}-windows-x86_64.zip[https\://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{version}-windows-x86_64.zip]
. Extract the contents of the zip file into `C:\Program Files`.
. Rename the `filebeat-{version}-windows-x86_64` directory to `{filebeat}`.
. Open a PowerShell prompt as an Administrator (right-click the PowerShell icon
and select **Run As Administrator**).
. From the PowerShell prompt, run the following commands to install
{filebeat} as a Windows service:
+
["source","powershell",subs="attributes"]
----
PS > cd 'C:\Program Files\\{filebeat}'
PS C:\Program Files\\{filebeat}> .\install-service-filebeat.ps1
----

If script execution is disabled on your system, you need to set the
execution policy for the current session to allow the script to run. For
example:
`PowerShell.exe -ExecutionPolicy UnRestricted -File .\install-service-filebeat.ps1`.

// end::win[]