[[apm-feature-roles]]
= Create and assign feature roles to APM Server users

++++
<titleabbrev>Use feature roles</titleabbrev>
++++

Manage access on a feature-by-feature basis by creating several custom feature-related _roles_ and assigning one or more of these roles to each _user or group_ based on which features they need to access.

[TIP]
====
A _role_ identifies a set of permissions that translates to privileges on resources. You can associate a _user or group_ with an arbitrary number of roles. The total set of permissions that a user has is defined by the union of the permissions in all its roles.

In general, there are three types of privileges you'll work with when creating roles:

* **{es} cluster privileges**: Manage the actions a user can perform against your cluster.
* **{es} index privileges**: Control access to the data in specific indices of your cluster.
* **{kib} space privileges**: Grant users write or read access to features and apps within {kib}.
====

The following are common roles that APM Server users might need:

* <<apm-privileges-to-publish-events,*Writer role*>>:
Allows a user to publish events collected by APM Server, which is *required* to write to {es}.
* <<apm-privileges-agent-central-config,*Central configuration management role*>>:
Allows a user to view APM Agent central configurations, which is *required* when
<<apm-agent-configuration,central configuration management>> is enabled (it is enabled by default).
* <<apm-privileges-to-publish-monitoring,*Monitoring role*>>: Allows a user to publish monitoring data,
view monitoring data, or both.
* <<apm-privileges-rum-source-mapping,*RUM source mapping role*>>: Allows a user to read RUM source maps.

.Example: Assigning multiple roles to an APM Server user
*****
If you want to create an APM Server user who can use the Elastic APM Real User Monitoring (RUM)
JavaScript Agent to ingest data from a frontend application and you use central configuration
to manage APM agents, you would need to assign these three roles to the user:

* <<apm-privileges-to-publish-events,Writer role>>
* <<apm-privileges-agent-central-config,Central configuration management role>>
* <<apm-privileges-rum-source-mapping,RUM source mapping role>>
*****

////
***********************************  ***********************************
***********************************  ***********************************
////

[float]
[[apm-privileges-to-publish-events]]
== Create a _writer_ role

APM users that publish events to {es} _must_ have privileges to write to APM data streams.

// Not sure if I captured this accurately...
[NOTE]
====
This is not needed when APM Server doesn't write to {es} directly.
For example, in some cases you may configure APM Server to write to another
output like Logstash, Kafka, or any other output supported by libbeat.
In these cases, different authentication credentials will need to be passed to
<<apm-agent-config-elasticsearch,`apm-server.agent.config.elasticsearch`>>.
====

To grant an APM Server user the required privileges for writing events to {es}:

. Create a *general writer role*, called something like `apm_writer`,
that has the following privileges:
+
[options="header"]
|====
|Type | Privilege | Purpose

|Index
|`auto_configure` on `traces-apm*`, `logs-apm*`, and `metrics-apm*` indices
|Permits auto-creation of indices and data streams

|Index
|`create_doc` on `traces-apm*`, `logs-apm*`, and `metrics-apm*` indices
|Write events into {es}

|Cluster
|`monitor`
a|* Allows cluster UUID checks, which are performed as part of APM server startup preconditions
if {ref}/security-settings.html[Elasticsearch security] is enabled (it is enabled by default).
* Allows a license check, which is required if <<apm-tail-based-sampling,tail-based sampling>> is enabled.

NOTE: If you have explicitly disabled Elastic security _and_ you are _not_ using tail-based sampling,
this privilege may not be necessary.
|====

. Assign the *general writer role* to APM Server users who need to publish APM data.

[NOTE]
====
Assign <<apm-feature-roles,additional APM feature roles>> to users as needed including the
_Central configuration management role_, which is <<apm-central-config-role-note,required in most cases>>.
====

////
***********************************  ***********************************
***********************************  ***********************************
////

[float]
[[apm-privileges-agent-central-config]]
== Create a _central configuration management_ role

[[apm-central-config-role-note]]
[IMPORTANT]
====
The privileges included in this role are *required* for all users when <<apm-agent-configuration,central configuration management>> is enabled (it is enabled by default). You need this role unless central configuration management has been explicitly disabled in the Applications UI.
====

[[apm-privileges-agent-central-config-server]]
APM Server acts as a proxy between your APM agents and the Applications UI.
The Applications UI communicates any changed settings to APM Server so that your agents only need to poll the Server
to determine which central configuration settings have changed.

To create a role with the required privileges for managing central configuration in {es} without {kib},
you must use the {ref}/security-api-put-role.html[Roles API] (the required privileges can't be assigned to a role in Kibana):

[source,console]
----
POST /_security/role/apm_agentcfg
{
 "description": "Allow APM Server to manage central configurations in Elasticsearch.",
 "indices": [
   {
     "names": [".apm-agent-configuration"],
     "privileges": ["read"],
     "allow_restricted_indices": true
   }
 ]
}
----

The previous privileges should be sufficient for APM agent central configuration to work properly
as long as APM Server communicates with {es} successfully.
If it fails, it may fallback to read agent central configuration through {kib} if configured,
which requires the following privileges:

[options="header"]
|====
|Type | Privilege | Purpose

| Spaces
|`Read` on Applications UI
|Allow APM Server to manage central configurations via the Applications UI
|====

[NOTE]
====
Assign <<apm-feature-roles,additional APM feature roles>> to users as needed including the
_Writer role_, which is <<apm-privileges-to-publish-events,required in most cases>>.
====

TIP: Looking for privileges and roles needed to use central configuration from the Applications UI or APM UI API?
See <<apm-app-central-config-user,Applications UI central configuration user>>.

////
***********************************  ***********************************
***********************************  ***********************************
////

[float]
[[apm-privileges-to-publish-monitoring]]
== Create a _monitoring_ role

{es-security-features} provides built-in users and roles for publishing and viewing monitoring data.
The privileges and roles needed to publish monitoring data
depend on the method used to collect that data.

* <<apm-privileges-to-publish-monitoring-write>>
** <<apm-privileges-to-publish-monitoring-internal>>
** <<apm-privileges-to-publish-monitoring-metricbeat>>
* <<apm-privileges-to-publish-monitoring-view>>

[float]
[[apm-privileges-to-publish-monitoring-write]]
=== Publish monitoring data

[IMPORTANT]
====
**{ecloud} users:** This section does not apply to our
https://www.elastic.co/cloud/elasticsearch-service[hosted {ess}].
Monitoring on {ecloud} is enabled by clicking the *Enable* button in the *Monitoring* panel.
====

[float]
[[apm-privileges-to-publish-monitoring-internal]]
==== Internal collection

If you're using <<apm-monitoring-internal-collection,internal collection>> to
collect metrics about APM Server, either:

* Use the built-in `apm_system` user or role
* Create a custom role

*Use a built-in user or role*

{es-security-features} provides the +apm_system+ {ref}/built-in-users.html[built-in user] and
+apm_system+ {ref}/built-in-roles.html[built-in role] to send
monitoring information. You can use the built-in user, if it's available in your
environment, create a user who has the built-in role assigned,
or create a user and manually assign the privileges needed to send monitoring
information.

If you use the built-in +apm_system+ user,
make sure you set the password before using it.

*Create a custom role*

If you don't use the +apm_system+ user, you can create a custom role:

. Create a *monitoring role*, called something like
+apm_monitoring_writer+, that has the following privileges:
+
[options="header"]
|====
|Type | Privilege | Purpose

|Index
|`create_index` on `.monitoring-beats-*` indices
|Create monitoring indices in {es}

|Index
|`create_doc` on `.monitoring-beats-*` indices
|Write monitoring events into {es}
|====
+
. Assign the *monitoring role* to APM Server users who need to write monitoring data to {es}.

[NOTE]
====
Assign <<apm-feature-roles,additional APM feature roles>> to users as needed including the
<<apm-privileges-to-publish-events,_Writer role_>> and <<apm-central-config-role-note,_Central configuration management role_>>,
both of which are required in most cases.
====

[float]
[[apm-privileges-to-publish-monitoring-metricbeat]]
==== {metricbeat} collection

NOTE: When using {metricbeat} to collect metrics,
no roles or users need to be created with APM Server.
See <<apm-monitoring-metricbeat-collection>>
for complete details on setting up {metricbeat} collection.

If you're <<apm-monitoring-metricbeat-collection,using {metricbeat}>> to collect
metrics about APM Server, you can either:

* Use the built-in `remote_monitoring_user` user or role
* Create a custom user

*Use a built-in user or role*

{es-security-features} provides the `remote_monitoring_user`
{ref}/built-in-users.html[built-in user], and the `remote_monitoring_collector`
and `remote_monitoring_agent` {ref}/built-in-roles.html[built-in roles] for
collecting and sending monitoring information. You can use the built-in user, if
it's available in your environment, or create a user who has the privileges
needed to collect and send monitoring information.

If you use the built-in `remote_monitoring_user` user,
make sure you set the password before using it.

*Create a custom user*

If you don't use the `remote_monitoring_user` user, you can create a custom user:

. Create a *monitoring user* on the production cluster who will collect and send monitoring
information. Assign the following roles to the *monitoring user*:
+
[options="header"]
|====
|Role | Purpose

|`remote_monitoring_collector`
|Collect monitoring metrics from APM Server

|`remote_monitoring_agent`
|Send monitoring data to the monitoring cluster
|====

[NOTE]
====
Assign <<apm-feature-roles,additional APM feature roles>> to users as needed including the
<<apm-privileges-to-publish-events,_Writer role_>> and <<apm-central-config-role-note,_Central configuration management role_>>,
both of which are required in most cases.
====

[float]
[[apm-privileges-to-publish-monitoring-view]]
=== View monitoring data

To grant users the required privileges for viewing monitoring data:

. Create a *monitoring role*, called something like
+apm_monitoring_viewer+, that has the following privileges:
+
[options="header"]
|====
|Type | Privilege | Purpose

| Spaces
|`Read` on Stack monitoring
|Read-only access to the {stack-monitor-app} feature in {kib}.

| Spaces
|`Read` on Dashboards
|Read-only access to the Dashboards feature in {kib}.
|====
+
. Assign the *monitoring role*, along with the following built-in roles, to users who
need to view monitoring data for APM Server:
+
[options="header"]
|====
|Role | Purpose

|`monitoring_user`
|Grants access to monitoring indices for APM Server
|====

[NOTE]
====
Assign <<apm-feature-roles,additional APM feature roles>> to users as needed including the
<<apm-privileges-to-publish-events,_Writer role_>> and <<apm-central-config-role-note,_Central configuration management role_>>,
both of which are required in most cases.
====

////
***********************************  ***********************************
***********************************  ***********************************
////

[float]
[[apm-privileges-rum-source-map]]
== Create a _source map_ role

[[apm-privileges-rum-source-mapping]]
If <<apm-configuration-rum,real user monitoring>> is enabled, additional privileges are required to read source maps.

To grant an APM Server user with the required privileges for reading RUM source maps from {es} directly without {kib},
assign the user the following privileges:

[options="header"]
|====
|Type | Privilege | Purpose

|Index
|`read` on `.apm-source-map` index
|Allow APM Server to read RUM source maps from {es}
|====

[NOTE]
====
Assign <<apm-feature-roles,additional APM feature roles>> to users as needed including the
<<apm-privileges-to-publish-events,_Writer role_>> and <<apm-central-config-role-note,_Central configuration management role_>>,
both of which are required in most cases.
====

The previous privileges should be sufficient for RUM source mapping to work properly
as long as APM Server communicates with {es} successfully.
If it fails, it may fallback to read source maps through {kib} if configured,
which requires additional {kib} privileges.
See <<apm-rum-sourcemap-api,RUM source map API>> for more details.