[[apm-secure-comms-stack]]
= Secure communication with the {stack}

NOTE: This documentation only applies to the APM Server binary.

Use role-based access control or API keys to grant APM Server users access to secured resources.

[discrete]
[[apm-secure-comms-stack-role-based]]
== Role-based access

Manage access on a feature-by-feature basis by creating several custom feature-related roles and assigning
one or more of these roles to each APM Server user based on which features they need to access.

<<apm-feature-roles,*Read more in Use feature roles →*>>

[discrete]
[[apm-secure-comms-stack-api-keys]]
== API keys

Instead of using usernames and passwords, you can use API keys to grant access to Elasticsearch resources. You can set API keys to expire at a certain time, and you can explicitly invalidate them.

<<apm-beats-api-keys,*Read more in Grant access using API keys →*>>

[discrete]
== More resources

After privileged users have been created, use authentication to connect to a secured Elastic cluster.

* <<apm-securing-communication-elasticsearch>>
* <<apm-configuring-ssl-logstash>>

For secure communication between APM Server and APM Agents, see <<apm-secure-agent-communication>>.

A reference of all available <<apm-configuration-ssl-landing,SSL configuration settings>> is also available.

[[apm-security-overview]]
[IMPORTANT]
====
APM Server exposes an HTTP endpoint, and as with anything that opens ports on your servers,
you should be careful about who can connect to it.
Firewall rules are recommended to ensure only authorized systems can connect.
====



////
***********************************  ***********************************
***********************************  ***********************************
////

include::{observability-docs-root}/docs/en/observability/apm/security/elastic-stack/feature-roles.asciidoc[leveloffset=+1]
include::{observability-docs-root}/docs/en/observability/apm/security/elastic-stack/access-api-keys.asciidoc[leveloffset=+1]
