[[decompress_gzip_field-processor]]
= Decompress gzip fields

++++
<titleabbrev>decompress_gzip_field</titleabbrev>
++++

The `decompress_gzip_field` processor specifies a field to gzip decompress.
The `field` key contains a `from: old-key` and a `to: new-key` pair. `from` is
the origin and `to` the target name of the field.

To overwrite fields either first rename the target field or use the `drop_fields`
processor to drop the field and then rename the field.

[discrete]
== Example

[source,yaml]
-------
  - decompress_gzip_field:
      field:
        from: "field1"
        to: "field2"
      ignore_missing: false
      fail_on_error: true
-------

In this example, `field1` is decoded in `field2`.

[discrete]
== Configuration settings

`ignore_missing`:: (Optional) If set to `true`, no error is logged when a key
that should be base64 decoded is missing. Default is `false`.

`fail_on_error`:: (Optional) If set to `true` and an error occurs, base64
decoding of fields is stopped, and the original event is returned. If set to
`false`, decoding continues even if an error occurs during decoding. Default is
`true`.

See <<conditions>> for a list of supported conditions.
