[[decode_base64_field-processor]]
= Decode Base64 fields

++++
<titleabbrev>decode_base64_field</titleabbrev>
++++

The `decode_base64_field` processor specifies a field to base64 decode.
The `field` key contains a `from: old-key` and a `to: new-key` pair. `from` is
the origin and `to` the target name of the field.

To overwrite fields, either rename the target field or use the `drop_fields`
processor to drop the field, and then rename the field.

[discrete]
== Example

[source,yaml]
-------
  - decode_base64_field:
      field:
        from: "field1"
        to: "field2"
      ignore_missing: false
      fail_on_error: true
-------

In this example, `field1` is decoded in `field2`.

[discrete]
== Configuration settings

[options="header"]
|===
| Name | Required | Default | Description

| `ignore_missing`
| No
| `false`
| If `true`, no error is logged if a key that should be base64 decoded is missing.

| `fail_on_error`
| No
| `true`
| If `true` and an error occurs, the base64 decoding of fields is stopped, and the original event is returned. If `false`, decoding continues even if an error occurs during decoding.
|===

See <<conditions>> for a list of supported conditions.
