[id="http_endpoint-input-{type}"]
= HTTP Endpoint input

++++
<titleabbrev>HTTP Endpoint</titleabbrev>
++++

beta[]

Use the `http_endpoint` input to create a HTTP listener that can receive
incoming HTTP POST requests.

For example, this input can be used to receive incoming webhooks from a
third-party application or service.

Basic example:

[source,yaml]
----
inputs:
  - type: http_endpoint
    enabled: true
    listen_address: 192.168.1.1
    listen_port: 8080
----

Custom response example:

[source,yaml]
----
inputs:
  - type: http_endpoint
    enabled: true
    listen_address: 192.168.1.1
    listen_port: 8080
    response_code: 200
    response_body: '{"message": "success"}'
    url: "/"
    prefix: "json"
----

Disable Content-Type checks:

[source,yaml]
----
inputs:
  - type: http_endpoint
    enabled: true
    listen_address: 192.168.1.1
    content_type: ""
    prefix: "json"
----

Basic auth and SSL example:

[source,yaml]
----
inputs:
  - type: http_endpoint
    enabled: true
    listen_address: 192.168.1.1
    listen_port: 8080
    ssl.enabled: true
    ssl.certificate: "/home/user/server.pem"
    ssl.key: "/home/user/server.key"
    ssl.verification_mode: "none"
    ssl.certificate_authority: "/home/user/ca.pem"
    basic_auth: true
    username: someuser
    password: somepassword
----

Authentication or checking that a specific header includes a specific value:

[source,yaml]
----
inputs:
  - type: http_endpoint
    enabled: true
    listen_address: 192.168.1.1
    listen_port: 8080
    secret.header: someheadername
    secret.value: secretheadertoken
----

[[input-http_endpoint-configuration-settings]]
== Configuration settings

The `http_endpoint` input supports the following settings. Many of these
settings have sensible defaults that allow you to run {agent} with minimal
configuration.

{also-see-common-input-settings}

[id="input-http_endpoint-basic_auth-setting"]
`basic_auth`::
(boolean) If `true`, HTTP basic auth is used for each incoming request. You
must also set `username` and `password`.
+
Default: `????`

****
**Reviewers:** What is the default here ^^? Filebeat docs don't say.
****

[id="input-http_endpoint-content_type-setting"]
`content_type`::
(string) The Content-Type expected in the incoming POST.
+
Default: `application/json`
+
By default, the input expects the incoming POST to have a Content-Type of
`application/json`. This ensures the incoming data is valid JSON. If the source
of the request is unable to set the Content-Type to `application/json`, use this
setting to specify a different value, or set it to null.

[id="input-http_endpoint-listen_address-setting"]
`listen_address`::
(string) If multiple interfaces are present, use this setting to control which
IP address the listener binds to.
+
Default: `127.0.0.1`

[id="input-http_endpoint-listen_port-setting"]
`listen_port`::
(int) Which port the listener binds to.
+
Default: `8000`

[id="input-http_endpoint-password-setting"]
`password`::
(string) If `basic_auth` is `true`, specify the password used to authenticate
against the HTTP listener. You must also set `username`.
+
Default: `????`

[id="input-http_endpoint-prefix-setting"]
`prefix`::
(string) The prefix the incoming request will be mapped to.

[id="input-http_endpoint-response_body-setting"]
`response_body`::
(string) The response body returned upon success.

[id="input-http_endpoint-response_code-setting"]
`response_code`::
(string) The HTTP response code returned upon success. This value should be in
the 2XX range.

[id="input-http_endpoint-secret.header-setting"]
`secret.header`::
(string) The header to check for a specific value specified by `secret.value`.
Some webhooks provide the ability to include a special header and secret to
identify the source.

[id="input-http_endpoint-secret.value-setting"]
`secret.value`::
(string) The secret stored in the header name specified by `secret.header`.
Some webhooks provide the ability to include a special header and secret to
identify the source.

[id="input-http_endpoint-url-setting"]
`url`::
(string) The URL path to accept requests on.
+
Default: `/`

[id="input-http_endpoint-username-setting"]
`username`::
(string) If `basic_auth` is `true`, specify the username used to authenticate
against the HTTP listener. You must also set `password`.
