[[cometd-input]]
= CometD input

++++
<titleabbrev>CometD</titleabbrev>
++++

Use the https://docs.cometd.org/[cometd] input to stream the real-time events
from a https://resources.docs.salesforce.com/sfdc/pdf/api_streaming.pdf[Salesforce generic subscription Push Topic].

This input can, for example, be used to receive Login and Logout events that are
generated when users log in or out of the Salesforce instance.

Example configuration:

****
**Reviewers:** This config is incorrect. Waiting to fix until I know what is
correct.
****

[source,yaml]
----
inputs:
- type: cometd
  channel_name: /event/MyEventStream
  auth.oauth2:
    client.id: my-client-id
    client.secret: my-client-secret
    token_url: https://login.salesforce.com/services/oauth2/token
    user: my.email@mail.com
    password: my-password
----

== Configuration settings

The `cometd` input supports the following settings.

{also-see-common-input-settings}

[[input-cometd-auth-oauth2-setting]]
`auth.oauth2`::
Authentication settings:

`client.id` (required):::
(string) The client ID used as part of the authentication flow.

`client.secret` (required):::
(string) The client secret used as part of the authentication flow.

`password` (required):::
The password used as part of the authentication flow. It is required for
authentication - grant type password.

`token_url` (required):::
(string) The endpoint that will be used to generate the token during the oauth2
flow.

`user` (required):::
(string) The user used as part of the authentication flow. It is required for
authentication - grant type password.

[[input-cometd-channel_name-setting]]
`channel_name` (required)::
(string) Salesforce generic subscription Push Topic name.
