:input-type: nginx-metrics

[[nginx-metrics-input]]
== Nginx/metrics input

Use the `nginx/metrics` input to periodically fetch metrics from
https://nginx.org/[Nginx] servers. The default metricset is `stubstatus`. 

*Compatibility:* The Nginx metricsets were tested with Nginx 1.9 and are
expected to work with all version >= 1.9.

This example fetches data from the Nginx `ngx_http_stub_status` module every
10 seconds:

[source,yaml]
----
inputs:
  - id: 9675f4bf-4f7g-4964-ab99-43cd4e678746
    name: nginx-1
    revision: 1
    type: nginx/metrics
    use_output: default
    meta:
      package:
        name: nginx
        version: 0.10.9
    data_stream:
      namespace: default
    streams:
      - id: nginx/metrics-nginx.stubstatus-9675f4bf-4f7g-4964-ab99-43cd4e678746
        data_stream:
          dataset: nginx.stubstatus
          type: metrics
        metricsets: ["stubstatus"]
        enabled: true
        period: 10s
        # Nginx hosts
        hosts: ["http://127.0.0.1"]
        # Path to server status. Default nginx_status
        server_status_path: "nginx_status"
...
----


The `nginx/metrics` input supports the following settings, grouped by category.
Many of these settings have sensible defaults that allow you to run {agent}
with minimal configuration.

<<input-nginx-metrics-metricset-settings>>::
Available metricsets and their settings.

<<input-nginx-metrics-standard-settings>>::
Standard settings available to any metrics input.

<<input-nginx-metrics-standard-http-settings>>::
Standard settings for inputs or metricsets that define the host as an HTTP URL.

//TODO: Add missing agent-related settings.

[[input-nginx-metrics-metricset-settings]]
=== Metricsets

{agent} provides the following metricset for collecting Nginx metrics.

//Comment this out if there is only one metricset for an input.
// Some metricsets have additional settings that you can specify to alter their
//behavior.

[cols="2*<a"]
|===
| Metricset type | Description and settings

|
[[stubstatus-metricset]]
`stubstatus`

| Collects data from the Nginx
http://nginx.org/en/docs/http/ngx_http_stub_status_module.html[ngx_http_stub_status]
module. This metricset scrapes the server status data from the web page generated by
`ngx_http_stub_status`.

//QUESTION: server_status_path is shown in the example, but not documented. Is
//this a metricset setting that needs to be documented here?

|===

[[input-nginx-metrics-standard-settings]]
=== Standard config settings

Standard config settings available to any metrics input.

[cols="2*<a"]
|===
| Settings | Description

include::input-shared-metrics-settings.asciidoc[tag=enabled-setting]

include::input-shared-metrics-settings.asciidoc[tag=fields-setting]

include::input-shared-metrics-settings.asciidoc[tag=hosts-setting]

//QUESTION: Remove this?
include::input-shared-metrics-settings.asciidoc[tag=index-setting]

include::input-shared-metrics-settings.asciidoc[tag=keep_null-setting]

include::input-shared-metrics-settings.asciidoc[tag=metricsets-setting]

include::input-shared-metrics-settings.asciidoc[tag=period-setting]

include::input-shared-metrics-settings.asciidoc[tag=processors-setting]

include::input-shared-metrics-settings.asciidoc[tag=service.name-setting]

include::input-shared-metrics-settings.asciidoc[tag=tags-setting]

|===

[[input-nginx-metrics-standard-http-settings]]
=== Standard HTTP settings

Standard settings for inputs or metricsets that define the host as an HTTP URL.

[NOTE]
====
Metricsets that define the host as an HTTP URL can use the standard
schemes for HTTP (`http://` and `https://`) and the following schemes to connect
to local pipes:

* `http+unix://` to connect to UNIX sockets.
* `http+npipe://` to connect to Windows named pipes.
====

[cols="2*<a"]
|===
| Settings | Description

include::input-shared-metrics-settings.asciidoc[tag=basepath-setting]

include::input-shared-metrics-settings.asciidoc[tag=bearer_token_file-setting]

include::input-shared-metrics-settings.asciidoc[tag=connect_timeout-setting]

include::input-shared-metrics-settings.asciidoc[tag=headers-setting]

include::input-shared-metrics-settings.asciidoc[tag=password-setting]

include::input-shared-metrics-settings.asciidoc[tag=query-setting]

include::input-shared-metrics-settings.asciidoc[tag=ssl-setting]

include::input-shared-metrics-settings.asciidoc[tag=timeout-setting]

include::input-shared-metrics-settings.asciidoc[tag=username-setting]

|===

:input-type!: