:input-type: tcp

[[tcp-input]]
= TCP input

++++
<titleabbrev>TCP</titleabbrev>
++++

Use the `TCP` input to read events over TCP.

Example configuration:

[source,yaml]
----
inputs:
  - type: tcp
    max_message_size: 10MiB
    host: "localhost:9000"
----

[[input-tcp-configuration-settings]]
== Configuration settings

The `tcp` input supports the following settings. Many of these settings have
sensible defaults that allow you to run {agent} with minimal configuration.

{also-see-common-input-settings}

// tag::tcp-settings[]

[id="input-{input-type}-tcp-framing-setting"]
`framing`::
(string) The framing used to split incoming events.  Can be one of
`delimiter` or `rfc6587`. `delimiter` uses the characters specified
in `line_delimiter` to split the incoming events. `rfc6587` supports
octet counting and non-transparent framing as described in
https://tools.ietf.org/html/rfc6587[RFC6587]. `line_delimiter` is
used to split the events in non-transparent framing.
+
Default: `delimiter`


[id="input-{input-type}-tcp-host-setting"]
`host`::
(string) The host and TCP port to listen on for event streams.

[id="input-{input-type}-tcp-line_delimiter-setting"]
`line_delimiter`::
(string) The characters used to split the incoming events.
+
Default: `'\n'`

[id="input-{input-type}-tcp-max_connections-setting"]
`max_connections`::
(int) The maximum number of connections to accept at any time.
+
Default: `????`

****
**Reviewers:** What is the default here ^^? Filebeat docs don't say.
****

[id="input-{input-type}-tcp-max_message_size-setting"]
`max_message_size`::
(string) The maximum size of the message received over TCP.
+
Default: `20MiB`

[id="input-{input-type}-ssl-setting"]
`ssl`::
Configuration settings for SSL parameters like the certificate, key, and the
certificate authorities to use.

//See <<configuration-ssl>> for more information.

//TODO: Add section about SSL settings.

[id="input-{input-type}-tcp-timeout-setting"]
`timeout`::
(string) The number of seconds of inactivity before a remote connection is
closed.
+
Default: `300s`

// end::tcp-settings[]
