[[elastic-agent-input-configuration]]
= Configure inputs for Standalone {agent}s

include::{fleet-repo-dir}/standalone-note.asciidoc[]


The `inputs` section of the `elastic-agent.yml` file specifies how {agent} locates and processes input data.

By default {agent} collects system metrics, such as CPU, memory, network, and file system metrics, and sends them to the default output. For example, to define the datastream for `cpu` metrics, this is the configuration:

["source","yaml"]
-----------------------------------------------------------------------
- name: system-metrics <1>
  type: system/metrics <2>
  use_output: default <3>
  meta:
    package: <4>
      name: system
      version: 0.10.9
  data_stream:
    namespace: default <5>
  streams:
    - data_stream:
        dataset: system.cpu <6>
        type: metrics <7>
      metricsets: <8>
        - cpu
      period: 10s
      cpu.metrics:
        - percentages
        - normalized_percentages
-----------------------------------------------------------------------

<1> User-defined name for the input.
<2> A generic type describing the data.
<3> The name of the `output` to use. If not specified, `default` will be used.
<4> Package specification.
<5> A user-defined namespace.
<6> A user-defined dataset. It can contain anything that makes sense to signify the source of the data.
<7> The type of the data stream.
<8> Enabled module metricsets.
+
In the {metricbeat-ref}/metricbeat-module-system.html[System module] there are several options. The `cpu` is just one of them. Its fields can be configured.