[[o365audit-input]]
= Office 365 Management Activity API input

++++
<titleabbrev>Office 365 Management Activity API</titleabbrev>
++++

beta[]

Use the `o365audit` input to retrieve audit messages from Office 365
and Azure AD activity logs. These are the same logs that are available under
_Audit_ _log_ _search_ in the _Security_ _and_ _Compliance_ center.

A single input instance can be used to fetch events for multiple tenants as long
as a single application is configured to access all tenants. Certificate-based
authentication is recommended in this scenario.

This input doesn't perform any transformation on the incoming messages, notably
no {ecs-ref}/ecs-reference.html[Elastic Common Schema fields] are populated, and
some data is encoded as arrays of objects, which are difficult to query in
{es}.

Example configuration:

****
**Reviewers:** These configs are incorrect. Waiting to fix until I know what is
correct.
****

[source,yaml]
----
inputs:
  - type: o365audit
    application_id: my-application-id
    tenant_id: my-tenant-id
    client_secret: my-client-secret
----

Multi-tenancy and certificate-based authentication is also supported:

[source,yaml]
----
inputs:
  - type: o365audit
    application_id: my-application-id
    tenant_id:
      - tenant-id-A
      - tenant-id-B
      - tenant-id-C
    certificate: /path/to/cert.pem
    key: /path/to/private.pem
    # key_passphrase: "my key's password"
----

[[input-o365audit-configuration-settings]]
== Configuration settings

The `o365audit` input supports the following settings. Many of these settings
have sensible defaults that allow you to run {agent} with minimal configuration.

{also-see-common-input-settings}

[[input-o365audit-api.authentication_endpoint-setting]]
`api.authentication_endpoint`::
(string) The authentication endpoint used to authorize the Azure app.
+
Default: `https://login.microsoftonline.com/`

[[input-o365audit-api.max_query_size-setting]]
`api.max_query_size`::
(string) The maximum time window that API allows in a single query.
+
Default: `24h` (Microsoft documented limit)

[[input-o365audit-api.max_requests_per_minute-setting]]
`api.max_requests_per_minute`::
(int) The maximum number of requests to perform per minute, for each tenant.
+
Default: `2000` (the server-side limit per tenant)

[[input-o365audit-api.max_retention-setting]]
`api.max_retention`::
(string) The maximum data retention period to support. When {agent} runs for
the first time, it fetches all retained data for a tenant.
+
Default: `168h`

[[input-o365audit-api.poll_interval-setting]]
`api.poll_interval`::
(string) The interval to wait before polling the API server for new events.
+
Default: `3m`

[[input-o365audit-api.preserve_original_event-setting]]
`api.preserve_original_event`::
(boolean) Controls whether the original o365 audit object will be kept in `event.original`
or not.
+
Default: `false`

[[input-o365audit-api.resource-setting]]
`api.resource`::
(string) The API resource to retrieve information from.
+
Default: `https://manage.office.com`

[[input-o365audit-application_id-setting]]
`application_id`::
(string) The Application ID (also known as Client ID) of the Azure application
to authenticate as.

[[input-o365audit-content_type-setting]]
`content_type`::
(list) List of content types to fetch.
+
Default: fetch all known content types:
+
- Audit.AzureActiveDirectory
- Audit.Exchange
- Audit.SharePoint
- Audit.General
- DLP.All

[[input-o365audit-certificate-setting]]
`certificate`::
(string) Path to the public certificate file used for certificate-based
authentication.

[[input-o365audit-client_secret-setting]]
`client_secret`::
(string) The client secret used for authentication.

[[input-o365audit-key-setting]]
`key`::
(string) Path to the certificate's private key file for certificate-based
authentication.

[[input-o365audit-key_passphrase-setting]]
`key_passphrase`::
(string) Passphrase used to decrypt the private key.

[[input-o365audit-tenant_id-setting]]
`tenant_id`::
(string) The tenant ID (also known as Directory ID) whose data is to be
fetched. It's also possible to specify a list of tenant IDs to fetch data from
more than one tenant.
