[[mqtt-input]]
= MQTT input

++++
<titleabbrev>MQTT</titleabbrev>
++++

Use the `mqtt` input to read data transmitted using lightweight messaging
protocol for small and mobile devices, optimized for high-latency or unreliable
networks.

This input connects to the MQTT broker, subscribes to selected topics, and
parses data into common message lines. Everything happens before line filtering,
multiline, and JSON decoding, so this input can be used in combination with
those settings.

Example configuration:

[source,yaml]
----
inputs:
  - type: mqtt
    hosts:
      - tcp://broker:1883
      - ssl://secure_broker:8883
    topics:
      - sample_topic
----

[[input-mqtt-configuration-settings]]
== Configuration settings

The `mqtt` input supports the following settings. Many of these settings have
sensible defaults that allow you to run {agent} with minimal configuration.

{also-see-common-input-settings}

[id="input-mqtt-client_id-setting"]
`client_id`::
(string) A unique identifier of each MQTT client connecting to a MQTT broker.

[id="input-mqtt-hosts-setting"]
`hosts` (required)::
(list) A list of MQTT brokers to connect to.

[id="input-mqtt-password-setting"]
`password`::
(string) A client password used for authentication provided on the application
level by the MQTT protocol.

[id="input-mqtt-qos-setting"]
`qos`::
(int) An agreement level between the sender of a message and the receiver of a
message that defines the guarantee of delivery.
+
There are 3 QoS levels in MQTT:
+
* At most once (`0`),
* At least once (`1`),
* Exactly once (`2`).

[id="input-mqtt-ssl-setting"]
`ssl`::
Configuration settings for SSL parameters like the certificate, key, and the
certificate authorities to use.

//See <<configuration-ssl>> for more information.

//TODO: Might make more sense to just add a link at the top of the page to a
//full listing of SSL settings.

[id="input-mqtt-topics-setting"]
`topics` (required)::
(list) A list of topics to subscribe to and read from.

[id="input-mqtt-username-setting"]
`username`::
(string) A client username used for authentication provided on the application
level by the MQTT protocol.
