:input-type: container

[[container-input]]
= Container input
 
++++
<titleabbrev>Container</titleabbrev>
++++

****
**REVIEWERS:** Do we need to document this input for Elastic Agent? It has a
lot of shared options with the filestream input and hasn't been updated for
quite awhile.

I'll wait to hear back before I add the settings reference info here.
****

Use the `container` input to read logs from containers.

This input searches for container logs under the given path, and parse them into
common message lines, extracting timestamps too. Everything happens before line
filtering, multiline, and JSON decoding, so this input can be used in
combination with those settings.

Example configuration:

[source,yaml]
----
inputs:
  - type: container
    paths: <1>
      - '/var/lib/docker/containers/*/*.log'
----

<1> `paths` is required. All other settings are optional.

[[input-container-configuration-settings]]
== Configuration settings

The `container` input supports the following settings. Many of these settings
have sensible defaults that allow you to run {agent} with minimal configuration.

{also-see-common-input-settings}

:input-type!:
