[[input-common-settings]]
= Common input settings

These configuration settings are available to all inputs.


[[input-enabled-setting]]
`enabled`::
(boolean) Enable or disable the input.

[[input-fields-setting]]
`fields`::
Optional fields to add to the output. You can add fields to use for
filtering data. Fields can be scalar values, arrays, dictionaries, or any
nested combination. By default, the fields are grouped under a `fields`
sub-dictionary in the output. To create top-level fields, set
`fields_under_root` to `true`. If a duplicate field is declared in the general
configuration, its value will be overwritten by the value declared here.
+
Example:
+
[source,yaml]
-----
inputs:
  - type: {input-type}
    . . .
    fields:
      app_id: query_engine_12
-----

[[input-fields-under-root-setting]]
`fields_under_root`::
(boolean) If `true`, custom fields are stored as top-level fields in the
output document instead of being grouped under a `fields` sub-dictionary. If the
custom field names conflict with other field names, the custom fields overwrite
the other fields.
+
Default: `false`

[[input-keep_null-setting]]
`keep_null`::
(boolean) If `true`, fields with `null` values are published in the output
document.
+
Default: `false`

[[input-pipeline-setting]]
`pipeline`::
(string) The ingest pipeline ID to set for the events generated by this input.
+
NOTE: The pipeline ID can also be configured in the {es} output, but this
setting usually results in simpler configuration files. If the pipeline is
configured both in the input and output, the setting from the input is used.

[[input-processors-setting]]
`processors`::
(list) A list of processors to apply to the input data.

//See <<filtering-and-enhancing-data>> for information about specifying
//processors in your config.

[[input-publisher_pipeline.disable_host-setting]]
`publisher_pipeline.disable_host`::
(boolean) Removes `host.name` from all events.
+
Default: `false`

[[input-tags-setting]]
`tags`::
(list) A list of tags to include in the `tags` field of each published event.
Tags make it easy to select specific events in {kib} or apply conditional
filtering in {ls}. These tags are appended to the list of tags specified in the
general configuration.
+
Example:
+
[source,yaml]
-----
inputs:
  - type: {input-type}
    . . .
    tags: ["json"]
-----
