[role="xpack"]

:input-type: netflow

[[netflow-input]]
== NetFlow input

++++
<titleabbrev>NetFlow</titleabbrev>
++++

Use the `netflow` input to read NetFlow and IPFIX exported flows
and options records over UDP.

This input supports NetFlow versions 1, 5, 6, 7, 8 and 9, as well as
IPFIX. For NetFlow versions older than 9, fields are mapped automatically
to NetFlow v9.

Example configuration:

["source","yaml",subs="attributes"]
----
inputs:
  - type: netflow
    max_message_size: 10KiB
    host: "0.0.0.0:2055"
    protocols: [ v5, v9, ipfix ]
    expiration_timeout: 30m
    queue_size: 8192
    custom_definitions:
    - path/to/fields.yml
    detect_sequence_reset: true
----

The `netflow` input supports the following settings, grouped by category.
Many of these settings have sensible defaults that allow you to run {agent}
with minimal configuration.

<<input-netflow-commonly-used-settings>>::
Settings frequently changed for this input type.

<<input-netflow-custom-field-settings>>::
Settings used to override existing field definitions.

<<input-netflow-data-parsing-settings>>::
Settings used to parse, filter, and transform data.

[[input-netflow-commonly-used-settings]]
=== Commonly used settings

Settings frequently changed for this input type.

[cols="2*<a"]
|===
| Settings | Description

// =============================================================================

// tag::detect_sequence_reset-setting[]
|
[id="input-{input-type}-detect_sequence_reset-setting"]
`detect_sequence_reset`

| (boolean) Controls whether {agent} monitors sequence numbers in the Netflow
packets to detect an Exporting Process reset. When this condition is detected,
record templates for the given exporter will be dropped. This will cause flow
loss until the exporter provides new templates. If set to `false`, {agent}
ignores sequence numbers, which can cause some invalid flows if the exporter
process is reset. This option is only applicable to Netflow V9 and IPFIX.

*Default:* `true`

// end::detect_sequence_reset-setting[]

// =============================================================================

include::input-shared-settings.asciidoc[tag=udp-host-setting]

// =============================================================================

include::input-shared-settings.asciidoc[tag=udp-max_message_size-setting]

// =============================================================================

// tag::protocols-setting[]
|
[id="input-{input-type}-protocols-setting"]
`protocols`

| (list) List of enabled protocols. Valid values are `v1`, `v5`, `v6`, `v7`,
`v8`, `v9` and `ipfix`.

*Default:* `????`

//QUESTION: What is the default?

// end::protocols-setting[]

// =============================================================================

// tag::queue_size-setting[]
|
[id="input-{input-type}-NAME-setting"]
`queue_size`

| (int) The maximum number of packets that can be queued for processing. Use
this setting to avoid packet loss when dealing with occasional bursts of
traffic.

*Default:* `????`

//QUESTION: What is the default?

// end::queue_size-setting[]

// =============================================================================

// tag::internal_networks-setting[]
|
[id="input-{input-type}-internal_networks-setting"]
`internal_networks`

A list of CIDR ranges describing the IP addresses that you consider internal.
This is used in determining the values of `source.locality`,
`destination.locality`, and `flow.locality`. The values can be either a CIDR
value or one of the named ranges supported by the
<<condition-network, `network`>> condition. The default value is `[private]`
which classifies RFC 1918 (IPv4) and RFC 4193 (IPv6) addresses as internal.

// end::internal_networks-setting[]

// =============================================================================

|===

[[input-netflow-custom-field-settings]]
=== Custom field settings

Settings used to override existing field definitions.

[cols="2*<a"]
|===
| Settings | Description

// tag::custom_definitions-setting[]
|
[id="input-{input-type}-custom_definitions-setting"]
`custom_definitions`

| (list) A list of paths to YAML files containing field definitions. Use these
custom definitions to update the NetFlow/IPFIX fields with vendor extensions and
to override existing fields.

The expected format is the same as used by the {ls} NetFlow codec
{logstash-ref}/plugins-codecs-netflow.html#plugins-codecs-netflow-ipfix_definitions[ipfix_definitions]
and
{logstash-ref}/plugins-codecs-netflow.html#plugins-codecs-netflow-netflow_definitions[netflow_definitions].
{agent} detects which of the two formats is used.

NetFlow format example:

[source,yaml]
----
id:
- default length in bytes
- :name
id:
- :uintN or :intN: or :ip4_addr or :ip6_addr or :mac_addr or :string
- :name
id:
- :skip
----

Where `id` is the numeric field ID.

The IPFIX format, grouped by Private Enterprise Number (PEN):

[source,yaml]
----
pen1:
  id:
  - :uintN or :ip4_addr or :ip6_addr or :mac_addr or :string
  - :name
  id:
  - :skip
pen2:
  id:
  - :octetarray
  - :name
----

Note that fields are shared between NetFlow V9 and IPFIX. Changes to
IPFIX PEN zero are equivalent to changes to NetFlow fields.

//QUESTION: What does "IPFIX PEN zero" mean? Is it a typo?

[WARNING]
Overriding standard field names and/or types might prevent ECS field mappings
from functioning properly.

// end::custom_definitions-setting[]

// =============================================================================

|===


[[input-netflow-performance-tuning-settings]]
=== Performance tuning settings

Settings that affect performance.

[cols="2*<a"]
|===
| Settings | Description

// =============================================================================

// tag::expiration_timeout-setting[]
|
[id="input-{input-type}-expiration_timeout-setting"]
`expiration_timeout`

| (string) The time before an idle session or unused template is expired. Only
applicable to v9 and IPFIX protocols. A value of zero disables expiration.

*Default:* `????`

//QUESTION: What is the default? Should the above say 0 rather than zero?

// end::expiration_timeout-setting[]

// =============================================================================

include::input-shared-settings.asciidoc[tag=udp-read_buffer-setting]

include::input-shared-settings.asciidoc[tag=udp-timeout-setting]

// =============================================================================

|===

[[input-netflow-data-parsing-settings]]
=== Data parsing, filtering, and manipulation settings

Settings used to parse, filter, and transform data. These settings are
valid for all input types.

[cols="2*<a"]
|===
| Settings | Description

include::input-shared-settings.asciidoc[tag=fields-setting]

include::input-shared-settings.asciidoc[tag=fields-under-root-setting]

include::input-shared-settings.asciidoc[tag=keep_null-setting]

include::input-shared-settings.asciidoc[tag=pipeline-setting]

include::input-shared-settings.asciidoc[tag=processors-setting]

include::input-shared-settings.asciidoc[tag=publisher_pipeline.disable_host-setting]

include::input-shared-settings.asciidoc[tag=tags-setting]

|===

:input-type!:
