[[kafka-input]]
= Kafka input

++++
<titleabbrev>Kafka</titleabbrev>
++++

Use the `kafka` input to read from topics in a Kafka cluster.

To configure this input, specify a list of one or more `hosts` in the cluster to
bootstrap the connection with, a list of `topics` to track, and a `group_id`
for the connection.

Example configuration:

[source,yaml]
----
inputs:
  - type: kafka
    hosts:
      - kafka-broker-1:9092
      - kafka-broker-2:9092
    topics: ["my-topic"]
    group_id: "agent"

----

The following example shows how to use the `kafka` input to ingest data from
Microsoft Azure Event Hubs that have Kafka compatibility enabled:

[source,yaml]
----
inputs:
  - type: kafka
    hosts: ["<your event hub namespace>.servicebus.windows.net:9093"]
    topics: ["<your event hub instance>"]
    group_id: "<your consumer group>"

    username: "$ConnectionString"
    password: "<your connection string>"
    ssl.enabled: true
----

For more details on the mapping between Kafka and Event Hubs configuration
parameters, see the
link:https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-for-kafka-ecosystem-overview[Azure documentation].

[[kafka-input-compatibility]]
== Compatibility

This input works with all Kafka versions in between 0.11 and 2.1.0. Older versions
might work as well, but are not supported.

[[input-kafka-configuration-settings]]
== Configuration settings

The `kafka` input supports the following settings. Most of these settings have
sensible defaults that allow you to run {agent} with minimal configuration.

{also-see-common-input-settings}

[[input-kafka-client_id-setting]]
`client_id`::
(string) The Kafka client id (optional).

[[input-kafka-connect_backoff-setting]]
`connect_backoff`::
(string) How long to wait before trying to reconnect to the Kafka cluster
after a fatal error.
+
Default: `30s`

[[input-kafka-consume_backoff-setting]]
`consume_backoff`::
(string) How long to wait before retrying a failed read.
+
Default: `2s`

[id="input-kafka-enabled-setting"]
`enabled`::
(boolean) Enable or disable the `kafka` input.
+
Default: `true`

[[input-kafka-expand_event_list_from_field-setting]]
`expand_event_list_from_field`::
(string) The name of a field that bundles multiple messages. Use this setting
for filesets that receive multiple messages bundled under a specific field.
For example, in Azure filesets, the events are found under the JSON object
`"records"`.
+
["source","json"]
----
{
"records": [ {event1}, {event2}]
}
----
+
This setting splits the messages under the group value (`"records"`) into
separate events.

[[input-kafka-fetch-setting]]
`fetch`::
(string) Kafka fetch settings:
+
`min`::: The minimum number of bytes to wait for. Default: 1.
`default`::: The default number of bytes to read per request. Default: 1 MB.
`max`::: The maximum number of bytes to read per request. Default: 0 (no limit).

[[input-kafka-group_id-setting]]
`group_id`::
(string) The Kafka consumer group id.

[[input-kafka-hosts-setting]]
`hosts`::
(list) A list of Kafka bootstrapping hosts (brokers) for this cluster.

[[input-kafka-initial_offset-setting]]
`initial_offset`::
(string) The initial offset to start reading, either `"oldest"` or `"newest"`.
+
Default: `"oldest"`

[[input-kafka-isolation_level-setting]]
`isolation_level`::
(string) Configures the Kafka group isolation level:
+
--
- `"read_uncommitted"` returns _all_ messages in the message channel.
- `"read_committed"` hides messages that are part of an aborted transaction.
--
+
Default: `"read_uncommitted"`

[[input-kafka-kerberos-setting]]
`kerberos`::
Configuration options for Kerberos authentication.

// See <<configuration-kerberos>> for more information..

[[input-kafka-max_wait_time-setting]]
`max_wait_time`::
(string) How long to wait for the minimum number of input bytes while reading.
+
Default: `250ms`

[[input-kafka-rebalance-setting]]
`rebalance`::
Kafka rebalance settings:
+
`strategy`::: Either `"range"` or `"roundrobin"`. Default: `"range"`.
`timeout`::: How long to wait for an attempted rebalance. Default: 60s.
`max_retries`::: How many times to retry if rebalancing fails. Default: 4.
`retry_backoff`::: How long to wait after an unsuccessful rebalance attempt.
Default: 2s.

// I can't find the syntax for these in the reference yaml. would they be
// written as rebalance.strategy: "range"?

[[input-kafka-topics-setting]]
`topics`::
(list) A list of topics to read from.

[[input-kafka-version-setting]]
`version`::
(string) The version of the Kafka protocol to use.
+
Default: `"1.0.0"`

[[input-kafka-wait_close-setting]]
`wait_close`::
(????) When shutting down, how long to wait for in-flight messages to be
delivered and acknowledged.
+
Default: `????`
