:input-type: activemq-metrics

[[activemq-metrics-input]]
== ActiveMQ metrics input

Use the `activemq/metrics` input to fetch JMX metrics from Apache ActiveMQ. To
configure this input, specify one or more metricsets. To use this input, you
must also configure the Jolokia input.

//TODO: Add link to Jolokia docs when they are available.

To collect data, {agent} communicates with a Jolokia HTTP/REST endpoint
that exposes the JMX metrics over HTTP/REST/JSON (JMX key:
`org.apache.activemq:brokerName=localhost,destinationName=sample_queue,destinationType=Queue,type=Broker`).


*Compatibility:* This input has been tested with ActiveMQ 5.13.0 and 5.15.9.
Other versions are expected to work.

Example configuration:

//TODO: Convert this config to correct format for agent.

[source,yaml]
----
  [source,yaml]
  ----
  - module: activemq
    metricsets: ['broker', 'queue', 'topic']
    period: 10s
    hosts: ['localhost:8161']
    path: '/api/jolokia/?ignoreErrors=true&canonicalNaming=false'
    username: admin # default username
    password: admin # default password
  ----
----


The `activemq/metrics` input supports the following settings, grouped by category.
Many of these settings have sensible defaults that allow you to run {agent}
with minimal configuration.

<<input-activemq-metrics-metricset-settings>>::
Available metricsets and their settings.

<<input-activemq-metrics-standard-settings>>::
Standard settings available to any metrics input.

<<input-activemq-metrics-standard-http-settings>>::
Standard settings for inputs or metricsets that define the host as an HTTP URL.

//TODO: Add missing agent-related settings.

[[input-activemq-metrics-metricset-settings]]
=== Metricsets

{agent} provides the following metricsets for fetching JMX metrics from Apache
ActiveMQ. Some metricsets have additional settings that you can specify to alter
their behavior.

NOTE: FORMATTED USING SECTIONS (INSTEAD OF TABLES) AS A TEST CASE.

[[broker-metricset]]
==== `broker` metricset

This metricset provides metrics describing the monitored ActiveMQ broker,
including connected consumers, producers, memory usage, active connections,
and exchanged messages.

[[queue-metricset]]
==== `queue` metricset

This metricset provides metrics describing the available ActiveMQ queues,
including exchanged messages (enqueued, dequeued, expired, in-flight),
connected consumers, producers, and its current length.

[[topic-metricset]]
==== `topic` metricset

This metricset provides metrics describing the available ActiveMQ topics,
including exchanged messages (enqueued, dequeued, expired, in-flight),
connected consumers, and producers.

[[input-activemq-metrics-standard-settings]]
=== Standard config settings

Standard config settings available to any metrics input.

[cols="2*<a"]
|===
| Settings | Description

include::input-shared-metrics-settings.asciidoc[tag=enabled-setting]

include::input-shared-metrics-settings.asciidoc[tag=fields-setting]

include::input-shared-metrics-settings.asciidoc[tag=hosts-setting]

//QUESTION: Remove this?
include::input-shared-metrics-settings.asciidoc[tag=index-setting]

include::input-shared-metrics-settings.asciidoc[tag=keep_null-setting]

include::input-shared-metrics-settings.asciidoc[tag=metricsets-setting]

include::input-shared-metrics-settings.asciidoc[tag=period-setting]

include::input-shared-metrics-settings.asciidoc[tag=processors-setting]

include::input-shared-metrics-settings.asciidoc[tag=service.name-setting]

include::input-shared-metrics-settings.asciidoc[tag=tags-setting]

|===

[[input-activemq-metrics-standard-http-settings]]
=== Standard HTTP settings

Standard settings for inputs or metricsets that define the host as an HTTP URL.

[NOTE]
====
Metricsets that define the host as an HTTP URL can use the standard
schemes for HTTP (`http://` and `https://`) and the following schemes to connect
to local pipes:

* `http+unix://` to connect to UNIX sockets.
* `http+npipe://` to connect to Windows named pipes.
====

[cols="2*<a"]
|===
| Settings | Description

include::input-shared-metrics-settings.asciidoc[tag=basepath-setting]

include::input-shared-metrics-settings.asciidoc[tag=bearer_token_file-setting]

include::input-shared-metrics-settings.asciidoc[tag=connect_timeout-setting]

include::input-shared-metrics-settings.asciidoc[tag=headers-setting]

include::input-shared-metrics-settings.asciidoc[tag=password-setting]

include::input-shared-metrics-settings.asciidoc[tag=query-setting]

include::input-shared-metrics-settings.asciidoc[tag=ssl-setting]

include::input-shared-metrics-settings.asciidoc[tag=timeout-setting]

include::input-shared-metrics-settings.asciidoc[tag=username-setting]

|===

:input-type!: