:input-type: unix

[[unix-input]]
= Unix input

beta[]

++++
<titleabbrev>Unix</titleabbrev>
++++

Use the `unix` input to read events over a stream-oriented Unix domain socket.

Example configuration:

[source,yaml]
----
inputs:
  - type: unix
    max_message_size: 10MiB
    path: "/var/run/filebeat.sock"
----

[[input-unix-configuration-settings]]
== Configuration settings

The `unix` input supports the following settings. Many of these settings have
sensible defaults that allow you to run {agent} with minimal configuration.

{also-see-common-input-settings}

// tag::unix-settings[]

[id="input-{input-type}-unix-framing-setting"]
`framing`::
(string) The framing used to split incoming events.  Can be one of
`delimiter` or `rfc6587`. `delimiter` uses the characters specified
in `line_delimiter` to split the incoming events. `rfc6587` supports
octet counting and non-transparent framing as described in
https://tools.ietf.org/html/rfc6587[RFC6587]. `line_delimiter` is
used to split the events in non-transparent framing.
+
Default: `delimiter`

[id="input-{input-type}-unix-group-setting"]
`group`::
(string) The group ownership of the Unix socket that will be created by
{agent}.
+
Default: the primary group name for the user {agent} is running
 +
This option is ignored on Windows.

[id="input-{input-type}-unix-line_delimiter-setting"]
`line_delimiter`::
(string) The characters used to split the incoming events.
+
Default: `'\n'`

[id="input-{input-type}-unix-max_connections-setting"]
`max_connections`::
(int) The maximum number of connections to accept at any time.
+
Default: `????`

//QUESTION: What is the default?

[id="input-{input-type}-unix-max_message_size-setting"]
`max_message_size`::
(string) The maximum size of the message received over the socket. 
+
Default: `20MiB`

[id="input-{input-type}-unix-mode-setting"]
`mode`::
(string) The file mode of the Unix socket that will be created by {agent}.
This is expected to be a file mode as an octal string.
+
Default: system default (usually `0755`)

[id="input-{input-type}-unix-path-setting"]
`path`::
(string) The path to the Unix socket that will receive events.

[id="input-{input-type}-unix-socket_type-setting"]
`socket_type`::
(string) The type to of the Unix socket that will receive events. Valid values
are `stream` and `datagram`.
+
Default: `stream`

[id="input-{input-type}-unix-timeout-setting"]
`timeout`::
(duration) The number of seconds of inactivity before a connection is closed. The default
is `300s`.

// end::unix-settings[]

:input-type!:
