[[elastic-agent-input-configuration]]
= Configure inputs for standalone {agent}s

++++
<titleabbrev>Inputs</titleabbrev>
++++

include::{fleet-repo-dir}/standalone-note.asciidoc[]

The `inputs` section of the `elastic-agent.yml` file specifies how {agent}
locates and processes input data.

By default {agent} collects system metrics, such as CPU, memory, network, and
file system metrics, and sends them to the default output. For example, to define the datastream for `cpu` metrics, this is the configuration:


[source,yaml]
-----------------------------------------------------------------------
- name: system-metrics
  type: system/metrics
  use_output: default
  meta:
    package:
      name: system
      version: 0.10.9
  data_stream:
    namespace: default
  streams:
    - data_stream:
        dataset: system.cpu
        type: metrics
      metricsets:
        - cpu
      period: 10s
      cpu.metrics:
        - percentages
        - normalized_percentages
-----------------------------------------------------------------------

Each input can have several fields:

[horizontal]
`name`:: User defined name for the input.

`type`:: A generic type describing the data.

`use_output`::
The name of the `output` to use. If not specified, `default` will be used.

`meta.package`:: Package specification.

`data_stream`::

`namespace`:::
A user defined namespace.
`dataset`:::
A user defined dataset. It can contain anything that makes sense to signify the source of the data.
`type`:::
The type of the data stream.

`metricsets`::
Enabled module metricsets.
+
In the {metricbeat-ref}/metricbeat-module-system.html[System module] there are several options. The `cpu` is just one of them. Its fields can be configured.




