[[redis-input]]
= Redis input

++++
<titleabbrev>Redis</titleabbrev>
++++

experimental[]

Use the `redis` input to read entries from Redis slowlogs.

Example configuration:

[source,yaml]
----
inputs:
  - type: redis
    hosts: ["localhost:6379"]
    password: "${redis_pwd}"
----

[[input-redis-configuration-settings]]
== Configuration settings

The `redis` input supports the following settings. Many of these settings have
sensible defaults that allow you to run {agent} with minimal configuration.

{also-see-common-input-settings}

[[input-redis-hosts-setting]]
`hosts`::
(list) The list of Redis hosts to connect to.

[[input-redis-maxconn-setting]]
`maxconn`::
(int) The maximum number of concurrent connections.
+
Default: `10`

[[input-redis-network-setting]]
`network`::
(string) The network type to use for the Redis connection. Valid settings
include: `tcp`, `tcp4`, `tcp6`, and `unix`.
+
Default: `tcp`

[[input-redis-password-setting]]
`password`::
(string) The password to use when connecting to Redis.

[[input-redis-scan_frequency-setting]]
`scan_frequency`::
(string) How often {agent} reads entries from Redis slowlogs.
+
Default: `10s`
+
Specify `1s` to scan Redis as frequently as possible without causing {agent} to
scan too frequently. Do not set this value to less than `1s`.
+
IMPORTANT: Redis slowlogs are not permanent. To ensure that all slowlog entries
are collected, set `scan_frequency` to a value that allows {agent} sufficient
time to connect to Redis, query the logs, and buffer them to the output within
the specified interval.

[[input-redis-timeout-setting]]
`timeout`::
(string) How long to wait for a response from Redis before the input returns
an error.
+
Default: `1s`
