[[cloudfoundry-input]]
= Cloud Foundry input

++++
<titleabbrev>Cloud Foundry</titleabbrev>
++++

Use the `cloudfoundry` input to get http access logs, container logs, and error
logs from Cloud Foundry. Connects to the Cloud Foundry Loggregator to receive
events.

Example configurations:

[source,yaml]
----
inputs:
  - type: cloudfoundry
    api_address: https://api.dev.cfdev.sh
    client_id: uaa-elastic-agent
    client_secret: verysecret
    shard_id: filebeat
    ssl:
      verification_mode: none
----

[source,yaml]
----
inputs:
  - type: cloudfoundry
    api_address: https://api.dev.cfdev.sh
    client_id: uaa-filebeat
    client_secret: verysecret
    shard_id: elastic-agent
    ssl.certificate_authorities: ["/etc/pki/cf/ca.pem"]
    ssl.certificate: "/etc/pki/cf/cert.pem"
    ssl.key: "/etc/pki/cf/cert.key"

----

[[input-cloudfoundry-configuration-settings]]
== Configuration settings

The `cloudfoundry` input supports the following settings. Many of these settings
have sensible defaults that allow you to run {agent} with minimal configuration.

{also-see-common-input-settings}

[id="input-cloudfoundry-api_address-setting"]
`api_address`::
(string) The URL of the Cloud Foundry API. .
+
Default: `"http://api.bosh-lite.com"`

[id="input-cloudfoundry-client_id-setting"]
`client_id`::
(string) Client ID to authenticate with Cloud Foundry.
+
Default: `""`

[id="input-cloudfoundry-client_secret-setting"]
`client_secret`::
(string) Client Secret to authenticate with Cloud Foundry.
+
Default: `""`

[id="input-cloudfoundry-doppler_address-setting"]
`doppler_address`::
(string) The URL of the Cloud Foundry Doppler Websocket.
+
Default: "(value from ${api_address}/v2/info)"

[id="input-cloudfoundry-rlp_address-setting"]
`rlp_address`::
(string) The URL of the Cloud Foundry RLP Gateway.
+
Default: "(`log-stream` subdomain under the same domain as `api_server`)"

//QUESTION: What do the defaults actually look like ^^? Is this meant to be
//descriptive If so, why is it quoted?

[id="input-cloudfoundry-shard_id-setting"]
`shard_id`::
(string) Shard ID for the connection with Cloud Foundry. Use the same ID
across multiple {agent}s to shard the load of events.
+
Default: "(generated UUID)"

[id="input-cloudfoundry-ssl-setting"]
`ssl`::
This specifies SSL/TLS common config.

//QUESTION: Are these the common ssl options described elsewhere? I think this
//section needs more detail.

[id="input-cloudfoundry-uaa_address-setting"]
`uaa_address`::
(string) The URL of the Cloud Foundry UAA API.
+
Default: "(value from ${api_address}/v2/info)"

[id="input-cloudfoundry-version-setting"]
`version`::
(string) Consumer API version to connect with Cloud Foundry to collect events.
Use `v1` to collect events using Doppler/Traffic Control. Use `v2` to collect
events from the RLP Gateway.
+
Default: `"v1"`
