:input-type: azure-metrics

[[azure-metrics-input]]
== Azure metrics input

Use the `azure/metrics` input to periodically retrieve Azure monitor metrics
using the Azure REST APIs.

Azure monitor metrics are numerical values that describe some aspect of a system
at a particular point in time. They are collected at regular intervals and are
identified with a timestamp, a name, a value, and one or more defining labels.

Additional Azure API calls are made to retrieve information about resources
targeted by the user.

IMPORTANT: Extra Azure charges on metric queries may be generated by if you
use this input. See <<azure-api-cost,additional notes about metrics and costs>>
for more details.

//TODO: Add info about required credentials. We need to decide how much info
//to duplicate in the settings reference.

//*Compatibility:* 

Example:

//TODO: convert to correct config syntax for agent. 

[source,yaml]
----
  [source,yaml]
  ----
  metricbeat.modules:
  - module: azure
    metricsets:
    - monitor
    enabled: true
    period: 300s
    client_id: '${AZURE_CLIENT_ID:""}'
    client_secret: '${AZURE_CLIENT_SECRET:""}'
    tenant_id: '${AZURE_TENANT_ID:""}'
    subscription_id: '${AZURE_SUBSCRIPTION_ID:""}'
    resources:
      - resource_query: "resourceType eq 'Microsoft.DocumentDb/databaseAccounts'"
        metrics:
        - name: ["DataUsage", "DocumentCount", "DocumentQuota"]
          namespace: "Microsoft.DocumentDb/databaseAccounts"

  - module: azure
    metricsets:
    - compute_vm
    enabled: true
    period: 300s
    client_id: '${AZURE_CLIENT_ID:""}'
    client_secret: '${AZURE_CLIENT_SECRET:""}'
    tenant_id: '${AZURE_TENANT_ID:""}'
    subscription_id: '${AZURE_SUBSCRIPTION_ID:""}'

  - module: azure
    metricsets:
    - compute_vm_scaleset
    enabled: true
    period: 300s
    client_id: '${AZURE_CLIENT_ID:""}'
    client_secret: '${AZURE_CLIENT_SECRET:""}'
    tenant_id: '${AZURE_TENANT_ID:""}'
    subscription_id: '${AZURE_SUBSCRIPTION_ID:""}'

  - module: azure
    metricsets:
    - storage
    enabled: true
    period: 300s
    client_id: '${AZURE_CLIENT_ID:""}'
    client_secret: '${AZURE_CLIENT_SECRET:""}'
    tenant_id: '${AZURE_TENANT_ID:""}'
    subscription_id: '${AZURE_SUBSCRIPTION_ID:""}'

  - module: azure
    metricsets:
    - container_instance
    enabled: true
    period: 300s
    client_id: '${AZURE_CLIENT_ID:""}'
    client_secret: '${AZURE_CLIENT_SECRET:""}'
    tenant_id: '${AZURE_TENANT_ID:""}'
    subscription_id: '${AZURE_SUBSCRIPTION_ID:""}'

  - module: azure
    metricsets:
    - container_service
    enabled: true
    period: 300s
    client_id: '${AZURE_CLIENT_ID:""}'
    client_secret: '${AZURE_CLIENT_SECRET:""}'
    tenant_id: '${AZURE_TENANT_ID:""}'
    subscription_id: '${AZURE_SUBSCRIPTION_ID:""}'

  - module: azure
    metricsets:
    - container_registry
    enabled: true
    period: 300s
    client_id: '${AZURE_CLIENT_ID:""}'
    client_secret: '${AZURE_CLIENT_SECRET:""}'
    tenant_id: '${AZURE_TENANT_ID:""}'
    subscription_id: '${AZURE_SUBSCRIPTION_ID:""}'

  - module: azure
    metricsets:
    - database_account
    enabled: true
    period: 300s
    client_id: '${AZURE_CLIENT_ID:""}'
    client_secret: '${AZURE_CLIENT_SECRET:""}'
    tenant_id: '${AZURE_TENANT_ID:""}'
    subscription_id: '${AZURE_SUBSCRIPTION_ID:""}'

  - module: azure
    metricsets:
      - billing
    enabled: true
    period: 24h
    client_id: '${AZURE_CLIENT_ID:""}'
    client_secret: '${AZURE_CLIENT_SECRET:""}'
    tenant_id: '${AZURE_TENANT_ID:""}'
    subscription_id: '${AZURE_SUBSCRIPTION_ID:""}'

  - module: azure
    metricsets:
      - app_insights
    enabled: true
    period: 300s
    application_id: ''
    api_key: ''
    metrics:
      - id: ["requests/count", "requests/duration"]

  - module: azure
    metricsets:
      - app_state
    enabled: true
    period: 300s
    application_id: ''
    api_key: ''
  ----

----

The `azure/metrics` input supports the following settings, grouped by category.
Many of these settings have sensible defaults that allow you to run {agent}
with minimal configuration.

<<input-azure-metrics-metricset-settings>>::
Available metricsets and their settings.

<<input-azure-metrics-standard-settings>>::
Standard settings available to any metrics input.

<<input-azure-metrics-standard-http-settings>>::
Standard settings for inputs or metricsets that define the host as an HTTP URL.

//TODO: Add missing agent-related settings.

[[input-azure-metrics-metricset-settings]]
=== Metricsets

Metricsets available to this input. Some metricsets have settings that alter
their behavior. 

//TODO: Add metricset info.

[[input-azure-metrics-standard-settings]]
=== General settings

General settings available to any metrics input.

[cols="2*<a"]
|===
| Settings | Description

include::input-shared-metrics-settings.asciidoc[tag=enabled-setting]

include::input-shared-metrics-settings.asciidoc[tag=fields-setting]

include::input-shared-metrics-settings.asciidoc[tag=hosts-setting]

//QUESTION: Remove this?
include::input-shared-metrics-settings.asciidoc[tag=index-setting]

include::input-shared-metrics-settings.asciidoc[tag=keep_null-setting]

include::input-shared-metrics-settings.asciidoc[tag=metricsets-setting]

include::input-shared-metrics-settings.asciidoc[tag=period-setting]

include::input-shared-metrics-settings.asciidoc[tag=processors-setting]

include::input-shared-metrics-settings.asciidoc[tag=service.name-setting]

include::input-shared-metrics-settings.asciidoc[tag=tags-setting]

|===

[[input-azure-metrics-standard-http-settings]]
=== HTTP settings

Standard settings for inputs or metricsets that define the host as an HTTP URL.

[NOTE]
====
Metricsets that define the host as an HTTP URL can use the standard
schemes for HTTP (`http://` and `https://`) and the following schemes to connect
to local pipes:

* `http+unix://` to connect to UNIX sockets.
* `http+npipe://` to connect to Windows named pipes.
====

[cols="2*<a"]
|===
| Settings | Description

include::input-shared-metrics-settings.asciidoc[tag=basepath-setting]

include::input-shared-metrics-settings.asciidoc[tag=bearer_token_file-setting]

include::input-shared-metrics-settings.asciidoc[tag=connect_timeout-setting]

include::input-shared-metrics-settings.asciidoc[tag=headers-setting]

include::input-shared-metrics-settings.asciidoc[tag=password-setting]

include::input-shared-metrics-settings.asciidoc[tag=query-setting]

include::input-shared-metrics-settings.asciidoc[tag=ssl-setting]

include::input-shared-metrics-settings.asciidoc[tag=timeout-setting]

include::input-shared-metrics-settings.asciidoc[tag=username-setting]

|===

:input-type!: