[[apm-apis]]
= APM APIs

There are three kinds of APIs related to Elastic APM:

// TO DO: add Managed intake service API page/link
[cols="1,1"]
|===
| https://www.elastic.co/docs/api/doc/observability-serverless[Managed intake service API] image:images/icons/popout.svg[]
a| status_badge::[serverless, ga] The managed intake service exposes an API endpoint to query general server information.
This lightweight endpoint is useful as a server up/down health check.

This API is exclusively for APM agent developers. The vast majority of users should have no reason to interact with this API.

| <<apm-app-api>>
|  status_badge::[stack, ga] {kib} APIs specific to working with the Applications UI including updating configuration options,
  uploading real user monitoring (RUM) source maps, adding annotations, and more.
| <<apm-api>>
| status_badge::[stack, ga] APIs for working with APM Server.
  These are mainly intake APIs that accept data from APM agents and are used primarily by APM agent developers.
|===

include::{observability-docs-root}/docs/en/observability/apm/api/api-ui.asciidoc[leveloffset=+1]
include::{observability-docs-root}/docs/en/observability/apm/api/apm-server/index.asciidoc[leveloffset=+1]
