[discrete]
[[monitor-kubernetes-overview]]
== Monitoring overview

[Author: DeDe]

TODO: Provide an introduction to Kubernetes monitoring. Some things we might
want to cover:

* Describe challenges of monitoring a complex, distributed, transient system -
monitoring multiple layers (host system, applications, container, orchestration
software itself). Containers are a moving target, etc. These blog posts have
some good introductory info:
https://www.elastic.co/blog/kubernetes-observability-tutorial-k8s-log-monitoring-and-analysis-elastic-stack[here]
and https://www.elastic.co/blog/monitoring-kubernetes-and-docker-containers-with-beats-logs-metrics-and-metadata[here].

* Provide an overview of monitoring capabilities, perhaps with a diagram. Might
want to show an example deployment that’s running a couple of applications, like
Nginx and MySQL. Describe the data to collect and the technology stack for
collecting the data. Probably best to keep this as a broad overview and explore
the finer details later, but should touch on these concepts:

** Deployment: What is a DaemonSet? Why deploy as a DaemonSet?

** Filebeat for log collection

** Metricbeat for metrics collection

** Metadata for correlating logs, metrics, and traces:
add_cloud_metada, add_docker_metada, add_kubernetes_metadata

** Autodiscovery for automatically detecting and monitoring services as they appear
dynamically. To avoid too much front loading, probably shouldn't talk about
details like hints-based autodiscovery, labels, and templates, but will need to
cover that some later.

TODO: Provide setup instructions for the Petclinic sample app.
