[discrete]
[[monitor-kubernetes-application-performance]]
== Part 5: Monitor application performance

[Author: Eyal]

TODO: Describe how to use APM to monitor applications.

[discrete]
=== Set up APM Server

TODO: Describe how to set up APM server.

[discrete]
==== Through ECK

Question: Are we sure we want to cover ECK here? Can we point to the ECK docs
instead? If we try to document all the ways in all the sections, I think users
might get confused.

[discrete]
==== On cloud

TODO: Describe how to set up APM server on cloud.

[discrete]
==== Download and install

TODO: Describe how to download and install APM server from archives.

[discrete]
=== Set up APM Agents

TODO: Describe how to set up the agents:

Question: Can we show the setup for one type of agent, then point to related
docs for other agents?

* Java agent (see https://www.elastic.co/blog/using-elastic-apm-java-agent-on-kubernetes-k8s)
* NodeJS Agent
* Python Agent
* ... and so forth


[discrete]
=== Configure

TODO: Describe how to add Kubernetes data to events by adding environment
variables to the K8s pod spec.

Question: Is there a more descriptive title that we can use for this section?
"Configure" seems a bit vague. By reading the docs, it sounds like you sometimes
need to add these variables, but it's not clear when/why you add them.
