[[monitor-kubernetes]]
= Monitor Kubernetes: Observe the health and performance of your Kubernetes deployments

TODO: Remove the following list along with all author names before publishing. 

*Assumptions made during content development:*

* Users are familiar with Kubernetes concepts.
* We will publish this content in phases. The first phase will include the
monitoring overview plus sections about monitoring K8s logs and metrics.
* We may provide a sample application to complement this guide.
* We will update this guide to use Elastic Agent + integrations when Fleet is
GA.

[discrete]
== What you’ll learn

[Author: DeDe]

In this guide, you’ll learn how to use the {stack} to collect, analyze, and
correlate logs and metrics from containers, applications, and services
running on top of Kubernetes.

This guide describes how to deploy Elastic monitoring agents as DaemonSets.
For other deployment options, see:

* {eck-ref}/index.html[{ecloud} on Kubernetes (ECK)]
* https://github.com/elastic/helm-charts/blob/master/README.md[Helm charts]

[discrete]
== Before you begin

[Author: DeDe]

TODO: List the prerequisites here. For example, {es} for storing and searching
your data, and {kib} for visualizing and managing it, Kubernetes config that's
required, like setting up Kubernetes to generate logs, enable
kube-state-metrics, etc.


include::monitor-k8s-overview.asciidoc[]

include::monitor-k8s-logs.asciidoc[]

include::monitor-k8s-metrics.asciidoc[]

include::monitor-k8s-uptime.asciidoc[]

include::monitor-k8s-network.asciidoc[]

include::monitor-k8s-application-performance.asciidoc[]

include::diagnose-k8s-bottlenecks.asciidoc[]

[discrete]
== What’s next

[Author: DeDe]

TODO: Add links to related topics that users might want to explore, such as
anomoly detection. 
