[[monitor-kubernetes]]
= Monitor Kubernetes: Observe the health and performance of your Kubernetes deployments
++++
<titleabbrev>Monitor Kubernetes</titleabbrev>
++++

Applications running in a containerized environment like Kubernetes pose a
unique monitoring challenge: how do you diagnose and resolve issues with
hundreds of microservices on thousands (or millions) of containers, running
in ephemeral and disposable pods?

A successful Kubernetes monitoring solution has a few requirements:

* Monitors all layers of your technology stack, including:
** The host systems where Kubernetes is running.
** Kubernetes core components, nodes, pods, and containers running within
the cluster.
** All of the applications and services are running in Kubernetes containers.

* Automatically detects and monitors services as they appear dynamically.

* Provides a way to correlate related data so that you can group and explore
related metrics, logs, and other observability data.

[discrete]
== What you’ll learn

This guide describes how to use Elastic {observability} to observe all layers of
your application, including the orchestration software itself:

* Collect logs and metrics from Kubernetes and your applications
* Collect trace data from applications deployed with Kubernetes
* Centralize the data in the {stack}
* Explore the data in real-time using tailored dashboards and {observability} UIs

This guide describes how to deploy Elastic monitoring agents as DaemonSets using
the {agent} manifest files. For other
deployment options, see the Kubernetes operator and custom resource definitions
from {eck-ref}/index.html[{ecloud} on Kubernetes (ECK)].

include::monitor-k8s-overview.asciidoc[]

include::monitor-k8s-add-integration.asciidoc[]

include::monitor-k8s-explore-logs-and-metrics.asciidoc[]

include::monitor-k8s-application-performance.asciidoc[]

[discrete]
== What’s next

* Want to protect your endpoints from security threats? Try
https://www.elastic.co/security[{elastic-sec}]. Adding endpoint protection is
just another integration that you add to the agent policy!

* Are your eyes bleary from staring at a wall of screens?
{observability-guide}/create-alerts.html[Create alerts] and find out about
problems while sipping your favorite beverage poolside.

* Want Elastic to do the heavy lifting? Use {ml} to
{observability-guide}/inspect-log-anomalies.html[detect anomalies].
