[discrete]
[[monitor-kubernetes-logs]]
== Part 1: Monitor logs

[Author: @ChrsMark]

TODO: Provide a brief intro. We'll need to decide how much to cover here vs
the monitoring overview. Again lots of good introductory info here:
https://www.elastic.co/blog/kubernetes-observability-tutorial-k8s-log-monitoring-and-analysis-elastic-stack)

[discrete]
=== Logs you should monitor

TODO: Discuss the various logs (Kubernetes cluster, nodes, host, container logs)
that users might want to collect. I'm not sure if this deserves a separate
section or should be part of the previous section.

[discrete]
=== Deploy {filebeat} to collect logs

TODO: Describe how to configure and deploy Filebeat as a daemonset. We should
walk users through the parts of the deployment YAMLs, explain what they do, and point
out the settings they might want to change or add. Rough list of what
we need to cover:

* Download the Filebeat deployment manifest

* Set the connection information for Elasticsearch (also describe how to create
secrets)

* Configure log collection:

** Collect Kubernetes logs (cluster, node)

** Collect host logs

** Collect container logs (use autodiscovery)
We should probably explain what the default config with the container input does
then focus on documenting how to use autodiscovery. 

* Add metadata to events. Enrich the event with metadata coming from Docker,
Kubernetes, host, and the cloud providers.

* (optional) Drop unwanted events

* Deploy Filebeat as a DaemonSet on Kubernetes

[discrete]
=== View logs in {kib}

TODO: Describe how to view logs in Kibana. Show how to use the Logs app and how to
set up and view pre-built dashboards and visualizations.
