[[monitor-kubernetes]]
= Monitor Kubernetes: Observe the health and performance of your Kubernetes deployments
++++
<titleabbrev>Monitor Kubernetes</titleabbrev>
++++

Applications running in a containerized environment like Kubernetes pose a
unique monitoring challenge: how do you diagnose and resolve issues with
hundreds of microservices on thousands (or millions) of containers, running
in ephemeral and disposable pods?

A successful Kubernetes monitoring solution has a few requirements:

* Monitors all layers of your technology stack, including:
** The host system where Kubernetes is running.
** Kubernetes core components, nodes, pods, and containers running within
the cluster.
** All the applications and services running in Kubernetes containers.

* Automatically detects and monitors services as they appear dynamically.

* Provides a way to correlate related data so that you can group and explore
related metrics, logs, and other observability data.

This guide describes how to use Elastic Observability to observe all layers of
your application, including the orchestration software itself.

[discrete]
== What you’ll learn

In this guide, you’ll learn how to:

* Collect logs and metrics from Kubernetes
* Centralize the data in the {stack}
* Explore the data in real-time using tailored dashboards and Observability UIs

//TODO: Add APM goals here

This guide describes how to deploy Elastic monitoring agents as DaemonSets.
For other deployment options, see {eck-ref}/index.html[{ecloud} on Kubernetes (ECK)]
and https://github.com/elastic/helm-charts/blob/master/README.md[Helm charts].

[discrete]
== Before you begin

To monitor Kubernetes, you need {es} for storing and searching your
observability data, and {kib} for visualizing and managing it. For more
information, see <<spin-up-stack>>.

include::monitor-k8s-overview.asciidoc[]

include::monitor-k8s-logs.asciidoc[]

include::monitor-k8s-metrics.asciidoc[]

//include::monitor-k8s-uptime.asciidoc[]

//include::monitor-k8s-network.asciidoc[]

include::monitor-k8s-application-performance.asciidoc[]

//include::diagnose-k8s-bottlenecks.asciidoc[]

[discrete]
== What’s next

[Author: DeDe]

//TODO: Add links to related topics that users might want to explore, such as
//anomoly detection. 
