[[observability-troubleshoot-logs]]
= Troubleshoot logs

// :description: Find solutions to errors you might encounter while onboarding your logs.
// :keywords: serverless, observability, troubleshooting

This section provides possible solutions for errors you might encounter while onboarding your logs.

[discrete]
[[observability-troubleshoot-logs-user-does-not-have-permissions-to-create-api-key]]
== User does not have permissions to create API key

When adding a new data using the guided instructions in your project (**Add data** → **Collect and analyze logs** → **Stream log files**),
if you don't have the required privileges to create an API key, you'll see the following error message:

[NOTE]
====
You need permission to manage API keys
====

[discrete]
[[observability-troubleshoot-logs-solution]]
=== Solution

You need to either:

* Ask an administrator to update your user role to at least **Deployment access** → **Admin**. Read more about user roles in <<general-assign-user-roles>>. After your use role is updated, restart the onboarding flow.
* Get an API key from an administrator and manually add the API to the {agent} configuration. See <<observability-stream-log-files-step-3-configure-the-agent,Configure the {agent}>> for more on manually updating the configuration and adding the API key.

// Not sure if these are different in serverless...

////
/* ## Failed to create API key

If you don't have the privileges to create `savedObjects` in a project, you'll see the following error message:

```plaintext
Failed to create API key

Something went wrong: Unable to create observability-onboarding-state
```

### Solution

You need an administrator to give you the `Saved Objects Management` {kib} privilege to generate the required `observability-onboarding-state` flow state.
Once you have the necessary privileges, restart the onboarding flow. */
////

[discrete]
[[observability-troubleshoot-logs-observability-project-not-accessible-from-host]]
== Observability project not accessible from host

If your Observability project is not accessible from the host, you'll see the following error message after pasting the **Install the {agent}** instructions into the host:

[source,plaintext]
----
Failed to connect to {host} port {port} after 0 ms: Connection refused
----

[discrete]
[[observability-troubleshoot-logs-solution-1]]
=== Solution

The host needs access to your project. Port `443` must be open and the project's {es} endpoint must be reachable. You can locate your project's endpoint by clicking the help icon (image:images/icons/help.svg[Help icon]) and selecting **Endpoints**. Run the following command, replacing the URL with your endpoint, and you should get an authentication error with more details on resolving your issue:

[source,shell]
----
curl https://your-endpoint.elastic.cloud
----

[discrete]
[[observability-troubleshoot-logs-download-agent-failed]]
== Download {agent} failed

If the host was able to download the installation script but cannot connect to the public artifact repository, you'll see the following error message:

[source,plaintext]
----
Download Elastic Agent

Failed to download Elastic Agent, see script for error.
----

[discrete]
[[observability-troubleshoot-logs-solutions]]
=== Solutions

* If the combination of the {agent} version and operating system architecture is not available, you'll see the following error message:
+
[source,plaintext]
----
The requested URL returned error: 404
----
+
To fix this, update the {agent} version in the installation instructions to a known version of the {agent}.
* If the {agent} was fully downloaded previously, you'll see the following error message:
+
[source,plaintext]
----
Error: cannot perform installation as Elastic Agent is already running from this directory
----
+
To fix this, delete previous downloads and restart the onboarding.
* You're an Elastic Cloud Enterprise user without access to the Elastic downloads page.

[discrete]
[[observability-troubleshoot-logs-install-agent-failed]]
== Install {agent} failed

If an {agent} already exists on your host, you'll see the following error message:

[source,plaintext]
----
Install Elastic Agent

Failed to install Elastic Agent, see script for error.
----

[discrete]
[[observability-troubleshoot-logs-solution-2]]
=== Solution

You can uninstall the current {agent} using the `elastic-agent uninstall` command, and run the script again.

[WARNING]
====
Uninstalling the current {agent} removes the entire current setup, including the existing configuration.
====

[discrete]
[[observability-troubleshoot-logs-waiting-for-logs-to-be-shipped-step-never-completes]]
== Waiting for Logs to be shipped... step never completes

If the **Waiting for Logs to be shipped...** step never completes, logs are not being shipped to your Observability project, and there is most likely an issue with your {agent} configuration.

[discrete]
[[observability-troubleshoot-logs-solution-3]]
=== Solution

Inspect the {agent} logs for errors. See the {fleet-guide}/debug-standalone-agents.html#inspect-standalone-agent-logs[Debug standalone {agent}s] documentation for more on finding errors in {agent} logs.
