[[xpack-apm]]
= Navigate the APM UI

TIP: For task-oriented guides, see the <<apm-how-to-guides>>.

The APM app in {kib} allows you to monitor your software services and applications in real-time;
visualize detailed performance information on your services,
identify and analyze errors,
and monitor host-level and APM agent-specific metrics like JVM and Go runtime metrics.

Having access to application-level insights with just a few clicks can drastically decrease the time you spend
debugging errors, slow response times, and crashes.

For example, you can see information about response times, requests per minute, and status codes per endpoint.
You can even dive into a specific request sample and get a complete waterfall view of what your application is spending its time on.
You might see that your bottlenecks are in database queries, cache calls, or external requests.
For each incoming request and each application error,
you can also see contextual information such as the request header, user information,
system values, or custom data that you manually attached to the request.

For a quick, high-level overview of the health and performance of your application,
start with:

* <<services>>
* <<traces>>
* <<dependencies>>
* <<service-maps>>

Notice something awry? Select a service or trace and dive deeper with:

* <<service-overview>>
* <<mobile-service-overview>>
* <<transactions>>
* <<spans>>
* <<errors>>
* <<metrics>>
* <<infrastructure>>
* <<logs>>

Configure and troubleshoot the APM UI:

* <<apm-app-users>>
* <<apm-settings-in-kibana>>
* <<troubleshooting-apm-app-overview>>

include::services.asciidoc[leveloffset=-1]

include::traces.asciidoc[leveloffset=-1]

include::dependencies.asciidoc[leveloffset=-1]

include::service-maps.asciidoc[leveloffset=-1]

include::service-overview.asciidoc[leveloffset=-1]

include::mobile-service.asciidoc[leveloffset=-1]

include::transactions.asciidoc[leveloffset=-1]

include::spans.asciidoc[leveloffset=-1]

include::errors.asciidoc[leveloffset=-1]

include::metrics.asciidoc[leveloffset=-1]

include::infrastructure.asciidoc[leveloffset=-1]

include::logs.asciidoc[leveloffset=-1]

include::apm-app-users.asciidoc[]

include::settings.asciidoc[]

include::troubleshooting.asciidoc[]
