[[apm-settings-in-kibana]]
== APM app settings

++++
<titleabbrev>Settings</titleabbrev>
++++

You do not need to configure any settings to use the APM app. It is enabled by default.
If you'd like to adjust the default settings, see {kibana-ref}/apm-settings-kb.html[APM Settings].

[float]
[[apm-indices-settings]]
=== APM Indices

The APM app uses data views to query APM indices.
To change the default APM indices that the APM app queries, open the APM app and select **Settings** > **Indices**.
Index settings in the APM app take precedence over those set in `kibana.yml`.

APM indices are {kib} Spaces-aware;
Changes to APM index settings will only apply to the currently enabled space.
See <<apm-spaces>> for more information.

[float]
[[apm-labs]]
=== APM Labs

**APM Labs** allows you to easily try out new features that are technical preview.

To enable APM labs, navigate to **APM** > **Settings** > **General settings** and toggle **Enable labs button in APM**.
Select **Save changes** and refresh the page.

After enabling **APM Labs** select **Labs** in the toolbar to see the technical preview features available to try out.
