[[observability-get-started-with-metrics]]
= Get started with system metrics

:description: Learn how to onboard your system metrics data quickly.
:keywords: serverless, observability, how-to

preview:[]

:role: Admin
:goal: onboard system metrics data
include::../partials/roles.asciidoc[]
:role!:

:goal!:

In this guide you'll learn how to onboard system metrics data from a machine or server,
then observe the data in {observability}.

To onboard system metrics data:

. <<observability-create-an-observability-project,Create a new {observability} project>>, or open an existing one.
. In your {observability} project, go to **Project Settings** → **Integrations**.
. Type **System** in the search bar, then select the integration to see more details about it.
. Click **Add System**.
. Follow the in-product steps to install the System integration and deploy an {agent}.
The sequence of steps varies depending on whether you have already installed an integration.
+
** When configuring the System integration, make sure that **Collect metrics from System instances** is turned on.
** Expand each configuration section to verify that the settings are correct for your host.
For example, you may want to turn on **System core metrics** to get a complete view of your infrastructure.

Notice that you can also configure the integration to collect logs.

.What if {agent} is already running on my host?
[NOTE]
====
Do not try to deploy a second {agent} to the same system.
You have a couple options:

* **Use the System integration to collect system logs and metrics.** To do this,
uninstall the standalone agent you deployed previously,
then follow the in-product steps to install the System integration and deploy an {agent}.
* **Configure your existing standalone agent to collect metrics.** To do this,
edit the deployed {agent}'s YAML file and add metric inputs to the configuration manually.
Manual configuration is a time-consuming process.
To save time, you can follow the in-product steps that describe how to deploy a standalone {agent},
and use the generated configuration as source for the input configurations that you need to add to your standalone config file.
====

After the agent is installed and successfully streaming metrics data,
go to **Infrastructure** → **Inventory** or **Hosts** to see a metrics-driven view of your infrastructure.
To learn more, refer to <<observability-view-infrastructure-metrics>> or <<observability-analyze-hosts>>.

[discrete]
[[observability-get-started-with-metrics-next-steps]]
== Next steps

Now that you've added metrics and explored your data,
learn how to onboard other types of data:

* <<observability-get-started-with-logs>>
* <<observability-stream-log-files>>
* <<observability-apm-get-started>>
