[[observability-infrastructure-monitoring-required-fields]]
= Required fields

// :description: Learn about the fields required to display data in the Infrastructure UI.
// :keywords: serverless, observability, reference

preview:[]

This section lists the fields the Infrastructure UI uses to display data.
Please note that some of the fields listed here are not {ecs-ref}/ecs-reference.html#_what_is_ecs[ECS fields].

[discrete]
[[observability-infrastructure-monitoring-required-fields-additional-field-details]]
== Additional field details

The `event.dataset` field is required to display data properly in some views. This field
is a combination of `metricset.module`, which is the {metricbeat} module name, and `metricset.name`,
which is the metricset name.

To determine each metric's optimal time interval, all charts use `metricset.period`.
If `metricset.period` is not available, then it falls back to 1 minute intervals.

[discrete]
[[base-fields]]
== Base fields

The `base` field set contains all fields which are on the top level. These fields are common across all types of events.

|===
| Field | Description | Type

| `@timestamp`
a| Date/time when the event originated.

This is the date/time extracted from the event, typically representing when the source generated the event.
If the event source has no original timestamp, this value is typically populated by the first time the pipeline received the event.
Required field for all events.

Example: `May 27, 2020 @ 15:22:27.982`
| date

| `message`
a| For log events the message field contains the log message, optimized for viewing in a log viewer.

For structured logs without an original message field, other fields can be concatenated to form a human-readable summary of the event.

If multiple messages exist, they can be combined into one message.

Example: `Hello World`
| text
|===

[discrete]
[[host-fields]]
== Hosts fields

These fields must be mapped to display host data in the {infrastructure-app}.

|===
| Field | Description | Type

| `host.name`
a| Name of the host.

It can contain what `hostname` returns on Unix systems, the fully qualified domain name, or a name specified by the user. The sender decides which value to use.

Example: `MacBook-Elastic.local`
| keyword

| `host.ip`
| IP of the host that records the event.
| ip
|===

[discrete]
[[docker-fields]]
== Docker container fields

These fields must be mapped to display Docker container data in the {infrastructure-app}.

|===
| Field | Description | Type

| `container.id`
a| Unique container id.

Example: `data`
| keyword

| `container.name`
| Container name.
| keyword

| `container.ip_address`
a| IP of the container.

_Not an ECS field_
| ip
|===

[discrete]
[[kubernetes-fields]]
== Kubernetes pod fields

These fields must be mapped to display Kubernetes pod data in the {infrastructure-app}.

|===
| Field | Description | Type

| `kubernetes.pod.uid`
a| Kubernetes Pod UID.

Example: `8454328b-673d-11ea-7d80-21010a840123`

_Not an ECS field_
| keyword

| `kubernetes.pod.name`
a| Kubernetes pod name.

Example: `nginx-demo`

_Not an ECS field_
| keyword

| `kubernetes.pod.ip`
a| IP of the Kubernetes pod.

_Not an ECS field_
| keyword
|===

[discrete]
[[aws-ec2-fields]]
== AWS EC2 instance fields

These fields must be mapped to display EC2 instance data in the {infrastructure-app}.

|===
| Field | Description | Type

| `cloud.instance.id`
a| Instance ID of the host machine.

Example: `i-1234567890abcdef0`
| keyword

| `cloud.instance.name`
| Instance name of the host machine.
| keyword

| `aws.ec2.instance.public.ip`
a| Instance public IP of the host machine.

_Not an ECS field_
| keyword
|===

[discrete]
[[aws-s3-fields]]
== AWS S3 bucket fields

These fields must be mapped to display S3 bucket data in the {infrastructure-app}.

|===
| Field | Description | Type

| `aws.s3.bucket.name`
a| The name or ID of the AWS S3 bucket.

_Not an ECS field_
| keyword
|===

[discrete]
[[aws-sqs-fields]]
== AWS SQS queue fields

These fields must be mapped to display SQS queue data in the {infrastructure-app}.

|===
| Field | Description | Type

| `aws.sqs.queue.name`
a| The name or ID of the AWS SQS queue.

_Not an ECS field_
| keyword
|===

[discrete]
[[aws-rds-fields]]
== AWS RDS database fields

These fields must be mapped to display RDS database data in the {infrastructure-app}.

|===
| Field | Description | Type

| `aws.rds.db_instance.arn`
a| Amazon Resource Name (ARN) for each RDS.

_Not an ECS field_
| keyword

| `aws.rds.db_instance.identifier`
a| Contains a user-supplied database identifier. This identifier is the unique key that identifies a DB instance.

_Not an ECS field_
| keyword
|===

[discrete]
[[group-inventory-fields]]
== Additional grouping fields

Depending on which entity you select in the **Inventory** view, these additional fields can be mapped to group entities by.

|===
| Field | Description | Type

| `cloud.availability_zone`
a| Availability zone in which this host is running.

Example: `us-east-1c`
| keyword

| `cloud.machine.type`
a| Machine type of the host machine.

Example: `t2.medium`
| keyword

| `cloud.region`
a| Region in which this host is running.

Example: `us-east-1`
| keyword

| `cloud.instance.id`
a| Instance ID of the host machine.

Example: `i-1234567890abcdef0`
| keyword

| `cloud.provider`
a| Name of the cloud provider. Example values are `aws`, `azure`, `gcp`, or `digitalocean`.

Example: `aws`
| keyword

| `cloud.instance.name`
| Instance name of the host machine.
| keyword

| `cloud.project.id`
a| Name of the project in Google Cloud.

_Not an ECS field_
| keyword

| `service.type`
a| The type of service data is collected from.

The type can be used to group and correlate logs and metrics from one service type.

For example, the service type for metrics collected from {es} is `elasticsearch`.

Example: `elasticsearch`

_Not an ECS field_
| keyword

| `host.hostname`
a| Name of the host. This field is required if you want to use {ml-features}

It normally contains what the `hostname` command returns on the host machine.

Example: `Elastic.local`
| keyword

| `host.os.name`
a| Operating system name, without the version.

Multi-fields:

os.name.text (type: text)

Example: `Mac OS X`
| keyword

| `host.os.kernel`
a| Operating system kernel version as a raw string.

Example: `4.4.0-112-generic`
| keyword
|===
