[[elastic-agent-configuration]]
= {agent} standalone configuration

include::{fleet-repo-dir}/standalone-note.asciidoc[]

Standalone {agent}s are manually configured and managed locally on the systems
where they are installed. To configure standalone {agent}s, specify settings
in the `elastic-agent.yml` file deployed with the agent. Prior to installation,
the file is located in the extracted {agent} package. After installation, the
file is copied to the directory described in <<installation-layout>>. To apply
changes after installation, you must modify the installed file.

For installatino details, refer to <<install-standalone-elastic-agent>>.

The following sections describe some settings you might need to configure to
run an {agent} standalone. For a full reference example, refer to the
<<elastic-agent-reference-yaml,elastic-agent.reference.yml>> file.

The settings described here are available for standalone {agent}s. Settings for
{fleet}-managed agents are specified through the UI. You do not set them
explicitly in a configuration file.

TIP: To get started quickly, use {kib} to generate a standalone
configuration. You'll still need to deploy and manage the file, though. For more
information, refer to <<generate-standalone-agent-config>>.

//TODO: Explain the structure of the file, how it's used, etc.
