[[elastic-agent-configuration]]
[role="xpack"]
= {agent} standalone configuration

include::{fleet-repo-dir}/standalone-note.asciidoc[]

Standalone {agent}s are manually configured and managed locally on the systems
where they are installed. To configure standalone {agent}s, specify settings
in the `elastic-agent.yml` file deployed with the agent. Prior to installation,
the file is located in the extracted {agent} package. After installation, the
file is copied to the directory described in <<installation-layout>>. To apply
changes after installation, you must modify the installed file.

The following sections describe some settings you might need to configure to
run an {agent} standalone. For a full reference example, refer to the
<<elastic-agent-reference-yaml,elastic-agent.reference.yml>> file.

The settings described here are available for standalone {agent}s. Settings for
{fleet}-managed agents are specified through the UI. You do not set them
explicitly in a configuration file.

TIP: To get started quickly, you can use {fleet} to generate a standalone
configuration. You'll still need to deploy and manage the file, though. For more
information, see <<run-elastic-agent-standalone>>.

//TODO: Explain the structure of the file, how it's used, etc.

include::inputs/input-configuration.asciidoc[leveloffset=+1]

include::outputs/output-configuration.asciidoc[leveloffset=+1]

include::elastic-agent-standalone-logging.asciidoc[leveloffset=+1]

include::elastic-agent-monitoring.asciidoc[leveloffset=+1]

include::yaml/elastic-agent-reference-yaml.asciidoc[leveloffset=+1]
