[[apm-app-annotation-user-create]]
= Applications UI annotation user

status_badge::[cloud_serverless, unavailable]

++++
<titleabbrev>Create an annotation user</titleabbrev>
++++

NOTE: By default, the `viewer` and `editor` built-in roles provide read access to Observability annotations.
You only need to create an annotation user to write to the annotations index
({kibana-ref}/apm-settings-kb.html[`xpack.observability.annotations.index`]).

[float]
[[apm-app-annotation-user]]
== Annotation user

View deployment annotations in the Applications UI.

. Create a new role, named something like `annotation_user`,
and assign the following privileges:
+
[options="header"]
|====
|Type | Privilege | Purpose

|Index
|`read` on +\{ANNOTATION_INDEX\}+^1^
|Read-only access to the observability annotation index

|Index
|`view_index_metadata` on +\{ANNOTATION_INDEX\}+^1^
|Read-only access to observability annotation index metadata
|====
+
^1^ +\{ANNOTATION_INDEX\}+ should be the index name you've defined in
{kibana-ref}/apm-settings-kb.html[`xpack.observability.annotations.index`].

. Assign the `annotation_user` created previously, and the roles and privileges necessary to create
a <<apm-app-reader-full,full>> or <<apm-app-reader-partial,partial>> APM reader to any users that need to view annotations in the Applications UI

[float]
[[apm-app-annotation-api]]
== Annotation API

See <<apm-app-api-user>>.