[[apm-app-central-config-user]]
= Applications UI central config user

++++
<titleabbrev>Create a central config user</titleabbrev>
++++

[float]
[[apm-app-central-config-manager]]
== Central configuration manager

Central configuration users need to be able to view, create, update, and delete APM agent configurations.

. Create a new role, named something like `central-config-manager`, and assign the following privileges:
+
--
include::{observability-docs-root}/docs/en/observability/apm/tab-widgets/central-config-users/widget.asciidoc[]
--
+
TIP: Using the deprecated APM Server binaries?
Add the privileges under the **Classic APM indices** tab above.

. Assign the `central-config-manager` role created in the previous step,
and the following Kibana feature privileges to anyone who needs to manage central configurations:
+
[options="header"]
|====
|Type | Privilege | Purpose

| Kibana
|`All` on the APM and User Experience feature
|Allow full use of the Applications and User Experience UIs
|====

[float]
[[apm-app-central-config-reader]]
== Central configuration reader

In some instances, you may wish to create a user that can only read central configurations,
but not create, update, or delete them.

. Create a new role, named something like `central-config-reader`, and assign the following privileges:
+
--
include::{observability-docs-root}/docs/en/observability/apm/tab-widgets/central-config-users/widget.asciidoc[]
--
+
TIP: Using the deprecated APM Server binaries?
Add the privileges under the **Classic APM indices** tab above.

. Assign the `central-config-reader` role created in the previous step,
and the following Kibana feature privileges to anyone who needs to read central configurations:
+
[options="header"]
|====
|Type | Privilege | Purpose

| Kibana
|`read` on the APM and User Experience feature
|Allow read access to the Applications and User Experience UIs
|====

[float]
[[apm-app-central-config-api]]
== Central configuration API

See <<apm-app-api-user>>.