[[apm-app-users]]
= Secure access to the APM UI

:beat_default_index_prefix: apm
:annotation_index: observability-annotations

++++
<titleabbrev>Secure access to the APM UI</titleabbrev>
++++

Use role-based access control to grant users access to secured
resources. The roles that you set up depend on your organization's security
requirements and the minimum privileges required to use specific features.

{es-security-features} provides {ref}/built-in-roles.html[built-in roles] that grant a
subset of the privileges needed by APM users.
When possible, assign users the built-in roles to minimize the affect of future changes on your security strategy.
If no built-in role is available, you can assign users the privileges needed to accomplish a specific task.
In general, there are three types of privileges you'll work with:

* **Elasticsearch cluster privileges**: Manage the actions a user can perform against your cluster.
* **Elasticsearch index privileges**: Control access to the data in specific indices your cluster.
* **Kibana feature privileges**: Grant users write or read access to features and apps within Kibana.

Select your use-case to get started:

* <<apm-app-reader>>
* <<apm-app-annotation-user-create>>
* <<apm-app-central-config-user>>
* <<apm-app-storage-explorer-user-create>>
* <<apm-app-api-user>>

include::{observability-docs-root}/docs/en/observability/apm/security/user-access/reader.asciidoc[leveloffset=+1]
include::{observability-docs-root}/docs/en/observability/apm/security/user-access/annotation.asciidoc[leveloffset=+1]
include::{observability-docs-root}/docs/en/observability/apm/security/user-access/api-ui.asciidoc[leveloffset=+1]
include::{observability-docs-root}/docs/en/observability/apm/security/user-access/central-config.asciidoc[leveloffset=+1]
include::{observability-docs-root}/docs/en/observability/apm/security/user-access/storage-explorer.asciidoc[leveloffset=+1]
