[[apm-app-reader]]
= APM reader user

status_badge::[cloud_serverless, unavailable]

++++
<titleabbrev>Create an APM reader user</titleabbrev>
++++

APM reader users typically need to view the Applications UI and dashboards and visualizations that use APM data.
These users might also need to create and edit dashboards, visualizations, and machine learning jobs.

[float]
[[apm-app-reader-full]]
== APM reader

To create an APM reader user:

. Create a new role, named something like `read-apm`, and assign the following privileges:
+
--
:apm-read-view:
:apm-monitor:
include::{observability-docs-root}/docs/en/observability/apm/tab-widgets/apm-app-reader/widget.asciidoc[]
:!apm-read-view:
:!apm-monitor:
--

. Assign the `read-apm` role created in the previous step, and the following built-in roles to
any APM reader users:
+
[options="header"]
|====
|Role | Purpose

|`kibana_admin`
|Grants access to all features in Kibana.

|`machine_learning_admin`
|Grants the privileges required to create, update, and view machine learning jobs
|====

[float]
[[apm-app-reader-partial]]
== Partial APM reader

In some instances, you may wish to restrict certain Kibana apps that a user has access to.

. Create a new role, named something like `read-apm-partial`, and assign the following privileges:
+
--
include::{observability-docs-root}/docs/en/observability/apm/tab-widgets/apm-app-reader/widget.asciidoc[]
--

. Assign feature privileges to any Kibana feature that the user needs access to.
Here are two examples:
+
[options="header"]
|====
|Type | Privilege | Purpose

| Kibana
| `Read` or `All` on the APM and User Experience feature
| Allow the use of the the Applications and User Experience UIs

| Kibana
| `Read` or `All` on Dashboards and Discover
| Allow the user to view, edit, and create dashboards, as well as browse data.
|====

. Finally, assign the following role if a user needs to enable and edit machine learning features:
+
[options="header"]
|====
|Role | Purpose

|`machine_learning_admin`
|Grants the privileges required to create, update, and view machine learning jobs
|====
