If you <<synthetics-get-started-project,set up the monitor using a Synthetics project>>,
you'll update the monitor in the Synthetics project and then `push` changes to your Observability project.

For lightweight monitors, make changes to the YAML file.

For browser monitors, you can update the configuration of one or more monitors:

* To update the configuration of an individual monitor, edit the journey directly in
the JavaScript or TypeScript files, specifically the options in `monitor.use`.
* To update the configuration of _all_ monitors in a Synthetics project, edit the
<<synthetics-configuration-monitor,global synthetics configuration file>>.

To update the journey that a browser monitor runs, edit the journey code directly and
<<synthetics-test-locally,test the updated journey locally>> to make sure it's valid.

After making changes to the monitors, run the <<elastic-synthetics-push-command,`push` command>>
to replace the existing monitors with new monitors using the updated
configuration or journey code.

[NOTE]
====
Updates are linked to a monitor's `id`. To update a monitor you must keep its `id` the same.
====
