

This section describes common problems you might encounter.

////
### I/O Timeout

I/O Timeouts can occur when your timeout settings across the stack are not configured correctly,
especially when using a load balancer.

You may see an error like the one below in the {apm-agent} logs, and/or a similar error on the intake side:

```logs
[ElasticAPM] APM Server responded with an error:
"read tcp 123.34.22.313:8200->123.34.22.40:41602: i/o timeout"
```

To fix this error, ensure timeouts are incrementing from the {apm-agent},
through your load balancer, to the Elastic APM intake.

By default, Elastic APM agent timeouts are set at 10 seconds, and the Elastic intake timeout is set at 60 seconds.
Your load balancer should be set somewhere between these numbers.

For example:

```txt
APM agent --> Load Balancer  --> Elastic APM intake
 10s            15s                 60s
``` */
////

[discrete]
[[field-limit-exceeded-legacy]]
=== Field limit exceeded

When adding too many distinct tag keys on a transaction or span,
you risk creating a {ref}/mapping.html#mapping-limit-settings[mapping explosion].

For example, you should avoid that user-specified data,
like URL parameters, is used as a tag key.
Likewise, using the current timestamp or a user ID as a tag key is not a good idea.
However, tag **values** with a high cardinality are not a problem.
Just try to keep the number of distinct tag keys at a minimum.

The symptom of a mapping explosion is that transactions and spans are not indexed anymore after a certain time. Usually, on the next day,
the spans and transactions will be indexed again because a new index is created each day.
But as soon as the field limit is reached, indexing stops again.
