[[docker-provider]]
= Docker Provider

Provides inventory information from Docker.

Docker provider ensures, that each docker container event is enriched with
the container's metadata, namely: `container.id`, `container.name`, `container.image.name`
and `container.labels`.

{agent} automatically prefixes the container's metadata fields with `docker.`, which is the name of the provider.

The available keys are:

// lint disable arg
|===
|Key |Type |Description

|`docker.container.id`
|`string`
|ID of the container

|`docker.container.name`
|`string`
|Name of the container

|`docker.container.image.name`
|`string`
|Image of the container

|`docker.container.labels`
|`object`
|Labels of the container
|===
// lint enable arg

To set the container ID dynamically in the configuration, use a variable in the
{agent} policy to return container ID information from the provider:

[source,yaml]
----
inputs:
  - id: 'docker-container-logs-${docker.container.id}'
    type: filestream
    paths:
      - '/var/lib/docker/containers/${docker.container.id}/*-json.log'
----

Sample of the policy generated by this configuration will look like:

[source,yaml]
----
inputs:
  - id: docker-container-logs-b9b898d9c2a1126384d38e9f857b3985480cd05c8e74ffc8b628d92245f5a103
    paths:
    - /var/lib/docker/containers/b9b898d9c2a1126384d38e9f857b3985480cd05c8e74ffc8b628d92245f5a103/*-json.log
  - id: docker-container-596bbd114498253985e6a5c4f0f7bf2d9eb8fcd4fe3e6cb53bdfba0cdc7036c8
    type: filestream
    paths:
    - /var/lib/docker/containers/596bbd114498253985e6a5c4f0f7bf2d9eb8fcd4fe3e6cb53bdfba0cdc7036c8/*-json.log
----
