name: Add to dev board
on:
  pull_request_target:
    types:
      - labeled
permissions:
  contents: read

jobs:
  add_to_data_plane-project:
    runs-on: ubuntu-latest
    if: |
      github.event.label.name == 'Team:Elastic-Agent-Data-Plane'
    steps:
      - name: Get token
        id: get_token
        uses: elastic/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.OBS_DOCS_AUTOMATION_PRIVATE_KEY }}
          APP_ID: 203735
      - name: Add to EA Data Plane board
        uses: octokit/graphql-action@v2.x
        id: add_to_project
        with:
          headers: '{"GraphQL-Features": "projects_next_graphql"}'
          query: |
            mutation add_to_project($projectid:[ID!]!,$contentid:ID!) {
              updatePullRequest(input: {pullRequestId:$contentid, projectIds:$projectid}) {
               clientMutationId
              }
            }
          projectid: "PRO_kwDOAGc3Zs4AzG8z"
          contentid: ${{ github.event.pull_request.node_id }}
          GITHUB_TOKEN: ${{ steps.get_token.outputs.app_token }}
  add_to_control_plane-project:
    runs-on: ubuntu-latest
    if: |
      github.event.label.name == 'Team:Elastic-Agent-Control-Plane'
    steps:
      - name: Get token
        id: get_token
        uses: elastic/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.OBS_DOCS_AUTOMATION_PRIVATE_KEY }}
          APP_ID: 203735
      - name: Add to EA Control Plane board
        uses: octokit/graphql-action@v2.x
        id: add_to_project
        with:
          headers: '{"GraphQL-Features": "projects_next_graphql"}'
          query: |
            mutation add_to_project($projectid:[ID!]!,$contentid:ID!) {
              updatePullRequest(input: {pullRequestId:$contentid, projectIds:$projectid}) {
               clientMutationId
              }
            }
          projectid: "PRO_kwDOAGc3Zs4AzG9E"
          contentid: ${{ github.event.pull_request.node_id }}
          GITHUB_TOKEN: ${{ steps.get_token.outputs.app_token }}
  add_to_fleet_ui-project:
    runs-on: ubuntu-latest
    if: |
      github.event.label.name == 'Team:Fleet'
    steps:
      - name: Get token
        id: get_token
        uses: elastic/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.OBS_DOCS_AUTOMATION_PRIVATE_KEY }}
          APP_ID: 203735
      - name: Add to Fleet board
        uses: octokit/graphql-action@v2.x
        id: add_to_project
        with:
          headers: '{"GraphQL-Features": "projects_next_graphql"}'
          query: |
            mutation add_to_project($projectid: ID!, $contentid: ID!) {
              addProjectNextItem(input:{projectId:$projectid contentId:$contentid}) {
                projectNextItem {
                  id
                }
              }
            }
          projectid: "PN_kwDOAGc3Zs4AAsH6"
          contentid: ${{ github.event.pull_request.node_id }}
          GITHUB_TOKEN: ${{ steps.get_token.outputs.app_token }}
