on:
  pull_request_target:
    types: [opened]
    paths:
      - '**.asciidoc'
      - '**.jpg'
      - '**.png'
      - '**.gif'

jobs:
  doc-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        name: Add doc preview links
        with:
          script: |
            const pr = context.payload.pull_request;
            const comment = `A documentation preview will be available soon:
              - 📚 [HTML diff](https://${context.repo.repo}_${pr.number}.docs-preview.app.elstc.co/diff)
              - 📙 [Observability Guide](https://${context.repo.repo}_${pr.number}.docs-preview.app.elstc.co/guide/en/observability/master/index.html)`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment,
            });
